### ISSUE TITLE
AMD APU (780M iGPU) glitches/freezes with Preview enabled

### ISSUE THREAD

**Issue by AaronZ101** [obsproject/obs-studio#10071]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/xBvh34pNmbNyWB22

### Expected Behavior

A normal working preview.

### Current Behavior

I just about a week ago got this new Mini PC containing one of the latest AMD mobile APUs (7940HS), I have ran several benchmarks and other applications/games with no issues, definitely no throttling on thermals or power, its running very well. Depending on sources, different problems with this iGPU (named 780M) have been happening. To keep things as simple as possible I'm using a 1280X720 canvas running at 60.00FPS and no scaling, the only plugin being CoreAudio AAC, however, encoding has no relation to the problem. I get different errors popping up, the most frequent one being:

`Device Remove/Reset!  Rebuilding all assets...`

This can repeatedly popup whether using game capture, capture card or even just a simple media file. Another one I have seen is:

`device_vertexbuffer_create (D3D11): Failed to create buffer (887A0005)
Device Removed Reason: 887A0006
device_draw (D3D11): No vertex buffer specified
Device Remove/Reset!  Rebuilding all assets...`

Both of these (from googling) appear to be GPU related. Eventually what happens is, my preview becomes frozen, I am still able to move things around - clicking and dragging will not appear to do anything, but closing and reopening OBS shows that they have indeed moved, I have made a video showing this (I had to wait an hour for it to finally happen this time, it seems it can happen at any moment, the audio is still coming through the capture card too), the strange thing is, nothing appears in the log at all on this occasion:

https://youtu.be/80Rr2DBaLTw
(skip to 2:53 for the above error appearing in the log)

Dragging the source or even deleting it will still show it in the preview until the program is rebooted. All of these issues stem from having the preview enabled, basically I can only use OBS with the preview disabled, even bringing up individual source previews (properties) will glitch out and OBS will need rebooting.

I also was testing the old OEM driver last night (I have reinstalled Windows again since, all of the above testing is using the current device drivers, absolutely no conflicts, I haven't even ran Windows Update), and it was performing much worse, after about a minute it was just lagging constantly until the preview was turned off, watch at 1:04 where I turn on/off the preview and the skipping stops/starts:
https://youtu.be/oRCope8HRew

So definitely want to stick with the latest driver from AMD at least with this system. One last thing I noticed from my log, not sure if its significant:
"D3D11 GPU priority setup failed (not admin?)"

### Steps to Reproduce

1. Enable Preview
2. Add a source (source depending, maybe you don't even need one, I could test maybe leaving OBS running with no sources for an hour and then try adding something, see if the preview has already frozen)
3. Eventually preview becomes frozen

### Anything else we should know?

I have tested this with both Windows 10 (Home) and Windows 11 (Education, Home and Pro), happens on all.

AMD Adrenaline Driver used: 23.12.1 - https://www.amd.com/en/support/apu/amd-ryzen-processors/amd-ryzen-9-processors-radeon-graphics/amd-ryzen-9-7940hs (the OEM driver for this mini PC is dated June 2023, it has even worse problems however, so I'm just using the official driver). Problems don't seem to happen until the driver is installed, the only thing I have not tried is installing driver versions "inbetween" the OEM one from June and the latest official one from December 2023.

I have tested 2 capture cards and both result in the same thing, but its definitely neither of the capture cards causing this since it also happens in a scene only involving a Game Capture or Media File.

I have the latest Bios version installed for this PC (1.09), 64GB 5600mhz DDR5 Sodimm RAM, 4GB allocated to the iGPU graphics.

HWInfo showed perfectly fine temps for both SSD and RAM (around 40C or less).

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Device reset messages in the log files most commonly means your GPU driver is crashing.

Thank you!

**Comment by AaronZ101** [comment]
If you read through the post it most definitely is an OBS bug and not a "request for support", unless OBS being the only program in existence having problems with this iGPU is down to the driver and definitely not the program itself. The iGPU/driver is working perfectly with pretty much everything else...

**Comment by Fenrirthviti** [comment]
Unfortunately, your assessment isn't accurate. OBS runs in user space, and cannot directly cause a GPU driver to crash like that. Something else is going on, which someone more familiar with AMD systems should be able to take a look through our normal support channels. The assumption that the issue is only between OBS and the driver is also incorrect, as plenty of external factors could be contributing to this. OBS also accesses and uses you system in ways that most applications don't, so while it might be correct to say the act of using OBS is triggering a GPU crash, it cannot, by nature of how OBS works and operates in user space, be a root cause. The GPU driver crashing is not an OBS bug, so there is nothing for us to fix.

**Comment by hdosys** [comment]
I had the exact same issue. However, since updating to 30.1.2 yesterday, it appears to be gone. Earlier, I disabled Multi-Plane Overlay and updated to AMD GPU driver version 24.4.1. Neither of those changes made a difference. It is somewhat strange that updating OBS seems to have silently fixed the issue for me.
