### ISSUE TITLE
[WASAPISource::ProcessCaptureData] Timestamp error!

### ISSUE THREAD

**Issue by matixal** [obsproject/obs-studio#10143]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/iz4FX1AA1Wcivcdk

### Expected Behavior

Disconnecting all devices through processor.

### Current Behavior

I stream normally, I use Elgato wave link (wave xlr) randomly during stream, my OBS freezes my mouse all cables are getting disconnected camera, keyboard, mouse, internet everything goes fully off except monitors, it lasts for 1-2 minutes maximum, after 2 minutes everything reconnects, I can't stream because of that issue, my mic is getting turned off, audio goes through speakers not through headphones anymore, I use nvidia broadcast ( after 2 minutes of freeze I need to open broadcast to set up from beginning Camera settings) I have to open wave link to set up audio settings, it's really frustrating and can't do anything about it, please help.

### Steps to Reproduce

1.go live stream
2.can have 4 hour session when everything goes smoothly but rarely.
3.when I am on stream, mouse freezes and everything getting disconnected, after 2 min everything is normal, and again same stuff happens.
...

### Anything else we should know?

I have fast internet, and I have been facing this issue, last 1 month before that everything was normal.

**Comment by Fenrirthviti** [comment]
Given the high number of resolution failures in your log: 

```
00:06:42.395: RTMP_Connect, failed to connect socket: No such host is known. (11001)
```

Looks to be some sort of DNS issue on either your hardware or with your ISP.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by alinsavix** [comment]
Just a quick note, in case the poster hasn't solved this one yet -- based on the description of their symptoms, and the log, I think they're actually having their USB bus crash -- they're using a USB network adapter, so when the bus goes down so does the network, which is why the DNS failures and such. So that's the problem OP will ultimately need to solve.

(still, not really a problem OBS has any influence over and definitely not a bug)
