### ISSUE TITLE
obs_source_media_play_pause() not working in python script

### ISSUE THREAD

**Issue by Kevin-Kevin** [obsproject/obs-studio#10172]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/5hyQlCjjyzoSN6LL

### Expected Behavior

media source should be paused or resumed as i want
but it is not working

### Current Behavior

media source still playing the video
`obs_source_media_stop() `or `obs_source_media_play_restar()` work well

### Steps to Reproduce

```python
def script_load(a):
    global c_settings
    media_source_name = obs.obs_data_get_string(c_settings, "media_source_name")
    scene = obs.obs_frontend_get_current_scene()
    media_source = obs.obs_get_source_by_name(media_source_name)
    
    if media_source:
        state = obs.obs_source_media_get_state(media_source)
        obs.obs_source_media_started(media_source)
        if state == obs.OBS_MEDIA_STATE_PLAYING:
            print("Media source is playing")
            obs.obs_source_media_play_pause(media_source, False)
```

**Comment by gxalpha** [comment]
On OBS startup, scripts are loaded in OBS before sources are loaded. In your script, your logic is in `script_load`, which means that it tries to find the source before it exists.
Try moving it to a frontend event like `OBS_FRONTEND_EVENT_FINISHED_LOADING` to make sure the source exists. Otherwise, please ask in the `#scripting` channel of the OBS [Discord server](https://discord.gg/obsproject), you're likely to get faster responses there.
