### ISSUE TITLE
[reproducible freeze] on stop recording with `obs-ffmpeg-output`

### ISSUE THREAD

**Issue by CaptainTeemo** [obsproject/obs-studio#10178]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

no log

### Expected Behavior

not freeze

### Current Behavior

freeze

### Steps to Reproduce

1. output select custom encoder
2. select mp4 container
3. select VP9 or video toolbox
4. start recording and wait for seconds then stop, repeat several times.
5. make sure there is a video playing to be recording (camera or media file).

### Anything else we should know?

looks like the main thread is freeing the `ffmpeg_data`.

<img width="1116" alt="Screenshot 2024-02-01 at 4 06 28 PM" src="https://github.com/obsproject/obs-studio/assets/4487505/6ef657ab-5ad5-4d1d-8811-56a4f4a1f5c2">

and the video thread is accessing the `ffmpeg_data`

<img width="1130" alt="Screenshot 2024-02-01 at 4 06 45 PM" src="https://github.com/obsproject/obs-studio/assets/4487505/14be5c02-7396-4eb1-80d4-bfbc296b06a2">

**Comment by CaptainTeemo** [comment]
sometimes it crashes.
here is the crash log on macOS:
[OBS-2024-02-01-143120.ips.zip](https://github.com/obsproject/obs-studio/files/14123421/OBS-2024-02-01-143120.ips.zip)

**Comment by alinsavix** [comment]
I can't reproduce the hang, after a few dozen tries. No clue how close my configuration is to OP's, since they didn't include a log, but I configured the couple of things they mentioned in their report.

I **can** reproduce the crash, though, although only with the libvpx-vp9 encoder -- with h264_videotoolbox, no issues. Was able to reproduce the crash multiple times in rapid succession, I don't think it ever took more than two start/stop cycles to do so. Not sure why anyone would want to record directly to VP9, but there ya go.

OBS log and crash log included. I'm on M1 hardware, but I can try to reproduce on x86 hardware if a dev thinks that would be at all helpful.

[2024-02-01 08-15-38.txt](https://github.com/obsproject/obs-studio/files/14127974/2024-02-01.08-15-38.txt)

[OBS-2024-02-01-081557.ips.txt](https://github.com/obsproject/obs-studio/files/14127995/OBS-2024-02-01-081557.ips.txt)

**Comment by RytoEX** [comment]
For what it's worth, VP9 in Custom FFmpeg Output is known to be finicky at best. Sometimes it works. Sometimes it doesn't. This has been true for as long as I can remember. It, and Custom FFmpeg Output (referred to in-program as "Custom Output (FFmpeg)") are both provided more or less "at your own risk".

**Comment by gxalpha** [comment]
As mentioned above, we consider Custom FFmpeg Output to be mostly unsupported. If you find that the problem is indeed on our side and find a fix, feel free to open a Pull Request.
