### ISSUE TITLE
OBS Virtual Camera Aspect Ratio Handling Issue in macOS (Version 30)

### ISSUE THREAD

**Issue by cyberpapiii** [obsproject/obs-studio#10263]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/pK3ymIU4rBHTVnzr

### Expected Behavior

The expected behavior would be for OBS to dynamically adapt the virtual camera's output resolution to match the canvas setting within OBS, regardless of orientation or aspect ratio. Specifically, when the canvas is set (9:16 aspect ratio), the virtual camera should output the full canvas without cropping, zooming, or altering the aspect ratio, just as it did in previous versions like 29.1.

### Current Behavior

The OBS virtual camera feature in version 30 is presenting a cropping issue when outputting a vertical canvas (9:16 aspect ratio) on macOS. The virtual camera is outputting at 1920x1080 resolution, leading to a cropped image in any video conferencing or video output destination, despite the canvas being set to vertical mode.

**Here are supporting logs:**
[Dec 12 10-37-32.txt](https://github.com/obsproject/obs-studio/files/14336668/Dec.12.10-37-32.txt)
[Feb 8 12:44.txt](https://github.com/obsproject/obs-studio/files/14336670/Feb.8.12.44.txt)

**Here are screenshots of the current behavior.**
![Discord MacOS Support Feb 8](https://github.com/obsproject/obs-studio/assets/103138198/e8810cf4-f3b4-42fb-895b-cada9e4c49ad)
![Feb 8 at](https://github.com/obsproject/obs-studio/assets/103138198/9233b25c-fe44-4b5b-86ab-2609fbd994d7)
![image](https://github.com/obsproject/obs-studio/assets/103138198/b71675cc-500c-4edb-82c4-347f7231c673)

### Steps to Reproduce

1. Set OBS canvas to 9:16 aspect ratio (or any non-standard aspect ratio other than 16:9).
2. Start virtual camera
3. Add virtual camera as camera source in any output destination (such as webcam test site, zoom, VDO ninja, google meet, etc.)
4. Notice that the output is cropped at the top and bottom, showing a zoomed-in 16:9 aspect ratio instead of the full 9:16 canvas.
...

### Request for Assistance
Given the major daily impact on live production workflows, I am seeking a quick resolution to this regression. Collaboration with the OBS team would be greatly appreciated to resolve this issue. 

I stream vertically every day and rely solely on the vertical virtual camera output. I imagine there's many more people experiencing the same issue. I've had to completely switch back to OBS 29 to use the virtual camera which breaks my projects due to plugin updates etc.

I am ready to provide further details, participate in debugging sessions, and assist with testing solutions.

### Supporting Information
[Link to original discord conversation](https://discord.com/channels/348973006581923840/636682784156549152/1184171869587378360) with @PatTheMav + @ yam + @ penwywern

[Link to OBS Camera Device Source](https://github.com/obsproject/obs-studio/blob/4b28631a957765528c51f3bdcc54e554357514af/plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift) on GitHub

### Core Issue Context
The core of the problem seems to be the interaction between OBS's hardcoded resolution and macOS's handling of non-standard camera resolutions, particularly for vertical orientations. macOS may be performing a crop to fit the vertical video into a widescreen format. It appears that the virtual camera extension on macOS always creates a 1920x1080 device, which is not adapting to the vertical orientation set in OBS.

PatTheMav, one of the developers, mentioned that it's hardcoded because they couldn't figure out how to expose different possible resolutions to the subsystem. The new version of the virtual camera introduced in OBS version 30 seems to have changed how resolutions are managed, resulting in this issue.

>[PatTheMav — 12/12/2023 11:52 AM](https://discord.com/channels/348973006581923840/636682784156549152/1184175848992018532)
in theory something could be exposed via providerProperties in the provider source, but as I said I couldn't figure it out
you'd also have to add all the plumbing to rescale the sample buffers and react to config changes and all
usually a device uses the "best" resolution internally and macOS then rescales/resizes implicitly

The issue is not with macOS's capabilities, as other applications correctly handle vertical video; the problem lies with how OBS interacts with macOS's camera system.

The solution may involve modifying the virtual camera extension to allow for different output formats or investigating further into macOS's capabilities to see if it can accept dynamic resolution changes from OBS.

### Conclusion
This cropping issue is critical, as it prevents the proper use of vertical video formats for live streaming. The expected behavior is a seamless match of the virtual camera's output to the OBS canvas settings, which was the standard functionality prior to version 30. The ability to adapt to both standard (16:9) and non-standard aspect ratios (9:16 for vertical video) is essential for a broad range of content creators who rely on OBS for media production.

**Comment by Fenrirthviti** [comment]
With respect, this might be critical to your specific workflow, but this is not a critical issue. Please allow the project to assign priority and severity when making reports.

**Comment by PatTheMav** [comment]
The issue is not necessarily with OBS or our virtual camera implementation but with other applications - when using a vertical resolution, the virtual camera will correctly switch its sample buffer resolution precisely to the resolution and aspect ratio provided by OBS.

This can be confirmed by using QuickTime, Cameo, and even in OBS itself (if you add the virtual camera as a source) - each app changes the resolution and aspect ratio dynamically depending on the content you send out.

The issue only occurs when the target application forces a specific device resolution, which is wrong (by default applications need to use the "High" preset and not force a resolution specific preset), which means that whichever application used to test the virtual camera needs to change the way it handles the camera input.

**Comment by tanrenye** [comment]
same issue, did you fixed yet?

**Comment by PatTheMav** [comment]
There is nothing for us to fix:

* Virtual cameras have no physical sensor, so they have no ‘resolution’ that could be changed (the API provides no methods for it, because it’s not necessary) - it has a ‘default resolution’ we use for the placeholder, but once it receives actual frames from OBS, their resolution takes over
* CMIO changes its sample output resolution dynamically and expects applications to look at _that_ and not the device resolution
* The virtual camera’s sample output resolution follows the input provided by OBS: If you send a 16:9 stream, it will be 16:9, if you send 4:3, it will be 4:3
* If an application requests an explicit resolution from CMIO, the sample output will be scaled and cropped to fit that resolution

If you add the virtual camera in OBS and don’t use a resolution-specific preset, you will see that the source resolution follows the input. The same happens in QuickTime, which will adjust the window size accordingly.

We cannot change the WebRTC stack in browsers (or wrapped web applications), nor can we change other applications. The rules (‘look at output buffer resolution, do not look at device resolution’) haven’t changed, so this is on those other parties to fix/implement correctly.

**Comment by mwawrusch** [comment]
How can we make this work in google chrome then? We are trying to display video from obs in a google chrome web app in 720x1280 and get a distorted, unusable output. Advice is very much appreciated

**Comment by PatTheMav** [comment]
> How can we make this work in google chrome then? We are trying to display video from obs in a google chrome web app in 720x1280 and get a distorted, unusable output. Advice is very much appreciated

Your only course of action would be to report this defect to the Google Chrome developers and ask them to use the resolution of the actual frames provided by a camera device instead of the device' resolution property in their implementation on macOS.

It's a defect in Chrome that it ignores the sample buffer resolution, which is the actual source of truth for it and not the device properties. This might work differently on other operating systems, but as far as macOS is concerned, that seems like the intended workflow.

**Comment by martinfavorited** [comment]
Thanks Pat

**Comment by Tackoil** [comment]
As far as I know, all browser mainly following this [W3C TR](https://www.w3.org/TR/mediacapture-streams/) about media capturing. In particular, browsers capture the video stream by offering [`getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) API. Web developers may claim their constraints about the video stream, and browser should enumerate all capabilities of devices and match the settings most fit to constraints.

*Looking at the output buffer resolution* seems to be reasonable in most cases. However, if web developers just need a video stream with a specific resolution, browsers will be hard to select a correct device.

As the definition in the spec, if a device reports a wrong capability, browser may select this devices incorrectly and web developer will not get the stream they desired. For example, web developers will claim they need a 1920x1080 video stream by following code.

```JavaScript
// It means I need a video stream with 1920x1080, no matter which device.
const stream = await navigator.mediaDevices.getUserMedia({
    video: {width: 1920, height: 1080},
})
```

And unfortunately, browser select the OBS virtual camera because it maybe the best one matching the constraints. As a result, web developer will get a 1080x1920 stream as the OBS settings, which is not they want.

Therefore, it's actually an issue should be fixed I think. If the OSs are without a capability for solving this issue, would it be better to send a feedback towards Apple or Microsoft?

BTW, I try my best to debugging the Chromium, and it'll be so difficult to add a workaround for OBS. So I also file an [issue](https://issues.chromium.org/issues/389023398) to Chromium. Maybe it'll be helpful.

**Comment by evolvingsushi** [comment]
As a data point, I am not able to output in a vertical resolution using macOS, but can do it in Windows 11 via Chrome or Opera, but not Edge.

Would much prefer the speed and reliability of my MacBook!
