### ISSUE TITLE
obs doesnt show hardware encoding option (nvenc)

### ISSUE THREAD

**Issue by maliknajjar** [obsproject/obs-studio#10284]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/RZqnXyI22wwxOOhC

### Expected Behavior

to show me the hardware (nvenc) encoding option

### Current Behavior

it doesnt show me the hardware (nvenc) encoding option.

### Steps to Reproduce

1. open obs
2. go to the settings
3. go to output
4. in streaming area click on video encoder
5. you will find only one option which is "Software (x264)"

### Anything else we should know?

I have a nvidia GeForce GTX 1650 that has nvenc encoding support.
when I run ffmpeg with the nvenc encoding option it creates the video successfully
but when I open the obs I cant find the hardware (nvenc) option

**Comment by tytan652** [comment]
Please install Nvidia driver Flatpak by running `flatpak update`.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.  

Thank you!
