### ISSUE TITLE
occasionally, OBS prevents a normal windows shutdown while replay buffer is active. "OBS is currently active. All streams and recordings will be ended. Do you really want to close OBS?"

### ISSUE THREAD

**Issue by D4n2021** [obsproject/obs-studio#10306]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/O9tGyLjGPlKTR2Wr

### Expected Behavior

A running replay buffer should never ever prevent a fully normal user-triggered Windows shutdown.

### Current Behavior

Only occasionally, OBS prevents a normal shutdown if replay buffer is running.

### Steps to Reproduce

1. activate replay buffer
2. shut down Windows

**Comment by RytoEX** [comment]
Replay Buffer is an output. If an output (NDI, Replay Buffer, etc.) is active, and you try to exit OBS, OBS will emit this warning. This is working as intended.

**Comment by Fenrirthviti** [comment]
I tested on my test machine and 20/20 times it held up shutdown as expected. If Windows is forcequitting in some cases (which it will do if you wait long enough), that's beyond what we have the ability to control.

**Comment by Fenrirthviti** [comment]
As mentioned, this is not a bug, nor is it unexpected behavior at all. We recommend closing OBS before initiating a shutdown. If you don't want the prompt to ever show, feel free to disable the shutdown check: https://obsproject.com/kb/launch-parameters

**Comment by RytoEX** [comment]
As [I said before](https://github.com/obsproject/obs-studio/issues/10306#issuecomment-1970357144):
> Replay Buffer is an output. If an output (NDI, Replay Buffer, etc.) is active, and you try to exit OBS, OBS will emit this warning. This is working as intended.

The warning you are getting has nothing to do with the check disabled by `--disable-shutdown-check`. The `--disable-shutdown-check` only disables the check that would trigger Safe Mode. It does not disable any checks that occur _during OBS shutdown_.

The_ warning you are getting is a warning that _some_ output, _any_ output, is still active when you try to exit OBS. This is intentional. Stop any outputs before trying to shutdown OBS.

---------------------------
Exit OBS?
---------------------------
OBS is currently active. All streams/recordings will be shut down. Are you sure you wish to exit?
---------------------------
Yes   No   
---------------------------

![image](https://github.com/obsproject/obs-studio/assets/624931/d9d56d17-5ed1-465d-a411-9489b0866a2c)
