### ISSUE TITLE
Edit transform dialog does not open and is unuseable when the source is locked

### ISSUE THREAD

**Issue by 31JSON** [obsproject/obs-studio#10424]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/uLW49OrIaBuyldPm

### Expected Behavior

In previous versions, one could still use the Edit Transform dialog to make changes to sources even if it was locked in the Sources list. This had the advantage of turning off the bounding box for precision placement of sources, or for cropping sources.

### Current Behavior

Turning on the lock in the Sources list disables the Edit Transform item in the contextual menu, and disables the Ctrl+E shortcut. If the dialog is already open upon locking, it becomes disabled.

### Steps to Reproduce

1. Lock a source
2. Right click on source, select Transform, Edit Transform... is greyed out; attempt Ctrl+E

### Anything else we should know?

It would be nice if the previous behavior was restored, or at least to have the option to restore the previous behavior. If not that, then an option to turn off bounding boxes so the edges of sources can be easily visualized.

**Comment by Fenrirthviti** [comment]
This was an intentional change, so this is not a bug.

I would recommend using the alignment guides (Settings -> General -> `Show pixel alignment guides` under the Preview section) to get precise alignment.

A request to disable the bounding box would be feature request, best suited for the [ideas page](https://ideas.obsproject.com/)

**Comment by 31JSON** [comment]
@Fenrirthviti Can you a least give a reason why this change was made? It's worked like that since I started using OBS back at version 25. A bug that's a feature is not a bug.

**Comment by Fenrirthviti** [comment]
The [change was made](https://github.com/obsproject/obs-studio/pull/9575) to bring OBS in line with how other tools of a similar nature function, where locking an object prevents *all* input from being changed. Having a locked item that can still be changed defeats the purpose of locking the item.

You were using an unintended side effect of what ultimate amounted to a design oversight to enable a workflow, but your real problem is not that you can no longer edit when the source is locked, but that you want to hide the bounding box while editing.

This would be a feature request, which would be posted to our ideas page, and is effectively the same as this here: https://ideas.obsproject.com/posts/1008/option-to-make-the-red-borders-when-editing-source-be-around-the-source-not-hiding-edge-pixels

**Comment by jp-d-cruz** [comment]
Cropping a "fit to screen" source is difficult because the red selection covers the boundaries so it's hard to make sure the source covers the whole screen without setting it to "stretch to screen" instead with this change but it will skew the source.
With the ability to at least crop the source while locked will ensure that edges are seen to accurately crop it.

**Comment by cireCloud** [comment]
Please make it togglable, really annoying feature when requires align overlays to have no gaps.
