### ISSUE TITLE
obs-studio-30.1.1-macos-intel sha256 hash value doesn't match with the one listed on the github release page

### ISSUE THREAD

**Issue by tiansworld** [obsproject/obs-studio#10447]
### Operating System Info

macOS 11

### OBS Studio Version

30.1.1

### OBS Studio Log URL

sorry, no log available now

### Expected Behavior

The hash value of the downloaded file should be the same as the value listed on the project's github release page.

### Current Behavior

They are different.
Downloaed: d37a2f968e19473c05d3a0e173c04e278e7ca8fc52019550765b63c8ba6d44d3
Listed: 67d48d59dab15a4ff62b777649cf06d43f06e619c881010abed1a76d238da7c0

### Steps to Reproduce

1. Click the macOS(Intel) button at the top of https://obsproject.com/
2. Use 'sha256sum' to check the hash value of the downloaded file
3. Compare the value with the one on https://github.com/obsproject/obs-studio/releases

### Anything else we should know?

I've downloaded the obs-studio-30.1.1-macos-intel.dmg installation file from https://cdn-fastly.obsproject.com/downloads/obs-studio-30.1.1-macos-intel.dmg twice. Then I used sha256sum to check the hash value, two downloaded files have the same value: d37a2f968e19473c05d3a0e173c04e278e7ca8fc52019550765b63c8ba6d44d3 .

**Comment by derrod** [comment]
It seems the workflow that creates the draft release and uploads artifacts was re-ran multiple times due to issues with the Sparkle appcast creation. In the process it would've produced new DMG files that don't match the hash for various reasons (codesigning timestamps, etc.), but not updated the draft release notes.

I have updated the release notes to reflect the actual hashes of the files that were last uploaded by the workflow run, the artifacts of which are still available here: https://github.com/obsproject/obs-studio/actions/runs/8403913167
