### ISSUE TITLE
Crashing my system

### ISSUE THREAD

**Issue by JohannT1111** [obsproject/obs-studio#10519]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Log URL

i did not get one

### Expected Behavior

im not sure

### Current Behavior

im not sure

### Steps to Reproduce

im not sure

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Additionally, this issue is beyond unactionable. If you're looking for support in the future, please try not to actually provide the bare minimum information that we request as part of the issue template.

Thank you!
