### ISSUE TITLE
Global shortcut doesn't work on Wayland

### ISSUE THREAD

**Issue by mdsmendes94** [obsproject/obs-studio#10538]
### Operating System Info

Other

### Other OS

Arch Linux 6.8.6-2

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.1-1.1

### OBS Studio Log URL

https://obsproject.com/logs/BA0sxugLZ2o19vlL

### Expected Behavior

Global shortcut working when OBS is not in focus

### Current Behavior

Global shortcut only works when OBS is in focus

### Steps to Reproduce

1.Wayland Session
2.Open OBS
3.Set a global shortcut for recoding, save and apply
4. Unfocus OBS and press the global shortcut you set
...

**Comment by kkartaltepe** [comment]
And we do not support global shortcuts on wayland, since wayland does not support global shortcuts. See earlier reports for more information https://github.com/obsproject/obs-studio/issues/10348#issuecomment-1985565023

**Comment by mdsmendes94** [comment]
> since wayland does not support global shortcuts. See earlier reports for more information [#10348 (comment)](https://github.com/obsproject/obs-studio/issues/10348#issuecomment-1985565023)

How come Spectacle have functioning global shortcuts then?

**Comment by tiberium-v** [comment]
> > since wayland does not support global shortcuts. See earlier reports for more information [#10348 (comment)](https://github.com/obsproject/obs-studio/issues/10348#issuecomment-1985565023)
> 
> How come Spectacle have functioning global shortcuts then?

KDE as a Desktop Environment monitored the screenshot hotkey and run the command to Spectacle/Screenshot Program of your choice. 

You can archive similar with the websocket protocol of obs. https://github.com/pschmitt/obs-cli with this tool, you can set up a hotkey in KDE and let run the `obs-cli scene switch "Scene2"` (as a example) command.

A new "Hotkey" Portal is on way for Wayland, but it is not wide adapted and obs hotkey logic has to be re-written for that.

**Comment by neurekadev** [comment]
If OBS isn't interested in making hotkeys work in Wayland, then people will simply find an alternative.

Most users just want software to work and don't want to have to deal with websockets, cli, and scripts. The added complexity is not worth it when there are alternatives that work just fine in Wayland.

**Comment by Fenrirthviti** [comment]
We are interested in supporting this, but it's a complicated feature to implement and nobody who has the requisite knowledge or skill to do so has had the time or motivation to work on it. If you're looking to get involved and see how you can assist, making vaguely threatening comments on a closed issue isn't a great way to do that. I'd suggest joining our Discord or Forums and getting involved with the community instead.

PRs, as always, are welcome.

**Comment by neurekadev** [comment]
> making vaguely threatening comments on a closed issue isn't a great way to do that.

Nobody is making vaguely threatening comments. OBS is free to do as they please and so are end users. I was simply pointing out a pain point.

**Comment by leia-uwu** [comment]
I made a plugin to integrate with the [global shortcuts portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GlobalShortcuts.html)

https://github.com/leia-uwu/obs-wayland-hotkeys

if anyone wants to use it as a reference to implement the portal upstream on OBS feel free, i just couldn't find my way around the codebase so decided to make a plugin

**Comment by Suor** [comment]
@leia-uwu why not contribute it to the OBS itself?

**Comment by prsm3** [comment]
> I made a plugin to integrate with the [global shortcuts portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GlobalShortcuts.html)
> 
> https://github.com/leia-uwu/obs-wayland-hotkeys
> 
> if anyone wants to use it as a reference to implement the portal upstream on OBS feel free, i just couldn't find my way around the codebase so decided to make a plugin

Thank you so much for this! I just installed the plugin on CachyOS and it works flawlessly! <3

**Comment by Hi-Angel** [comment]
@leia-uwu thanks, I just tried it and I'm a bit confused how it's supposed to work.

On the first start of `obs`  I got a new window that enlists shortcuts, and each of them was empty. I just assumed it's a bug that they empty and the window just asks for permissions, so I pressed `Ok` to agree.

However, when I press <kbd>F1</kbd> afterwards *(a shortcut for "start/stop recording")*, it only starts if obs is focused, i.e. it's *still* not considered global.

Maybe I should've explicitly re-assigned shortcuts in that initial pop-up…? Either way, the window no longer appears on start, and ultimately the portal just doesn't work.

**Comment by prsm3** [comment]
@Hi-Angel Yes you have to specifically reassign the key bind in that initial pop up window.

**Comment by Hi-Angel** [comment]
I see. Weird, the README says on KDE I should be now able to find shortcuts in Keyboard → Shortcuts under "OBS Studio", but there's no such item.

<img width="931" height="427" alt="Image" src="https://github.com/user-attachments/assets/e6dad969-3967-4d14-a4d0-fd326739316c" />

Oh, well…

**Comment by Hi-Angel** [comment]
> We are interested in supporting this, but it's a complicated feature to implement and nobody who has the requisite knowledge or skill to do so has had the time or motivation to work on it. If you're looking to get involved and see how you can assist, making vaguely threatening comments on a closed issue isn't a great way to do that. I'd suggest joining our Discord or Forums and getting involved with the community instead.
> 
> PRs, as always, are welcome.

@Fenrirthviti thank you for reply! I think this issue was closed by mistake, can you please reopen it to make it visible to contributors that the feature is wanted and contributions are welcome 😊

**Comment by Slavomir9** [comment]
I am not a professional programmer myself, but I used AI to perform a real-time search of the OBS Studio GitHub repository regarding global hotkey implementation. The AI confirmed that they are indeed implemented via the XDG Desktop Portal.

The possibility that the issue lies within the Wayland implementation (Mutter, KWin) might be more likely than it appears at first glance. 

However, bugs within the OBS Studio codebase related to global hotkeys also cannot be ruled out as a potential source of the problem.

In an age where AI helps programmers, it shouldn't be much work for a developer to fix this. Probably few minutes
https://www.youtube.com/watch?v=1AF5pFGwRTM&list=PL4cUxeGkcC9h-AKdBSCRpqjD3y6T7Xgrb


With a solution to temporarily, provisionally solve it
https://github.com/obsproject/obs-studio/issues/13169

**Comment by leia-uwu** [comment]
average AI nonsense... everything you just posted is wrong :)

currently obs studio implements global shortcuts by effectively keylogging global keypress events, which is not possible on wayland by design

the global shortcuts portal which unlike what the misinformation-making-machine you used said, is not implemented by obs, and is a completely different approach to global shortcuts

**Comment by Slavomir9** [comment]
<p data-path-to-node="2">&nbsp;<strong data-path-to-node="2" data-index-in-node="0">Apologies regarding AI hallucinations and update on Wayland global hotkeys</strong></p>
<p data-path-to-node="3">Dear developer,</p>
<p data-path-to-node="4">My apologies. It seems you were right, and I was misled by AI hallucinations. After verifying the data, I was unable to find any official information confirming that OBS Studio currently supports global hotkeys on Wayland. This was my first experience with such extensive AI hallucinations.</p>
<p data-path-to-node="5">However, during my verification process, I found some interesting links:</p>
<ul data-path-to-node="6">
<li>
<p data-path-to-node="6,0,0"><strong data-path-to-node="6,0,0" data-index-in-node="0">A critique of Wayland's current state:</strong> <a class="ng-star-inserted" href="https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277?permalink_comment_id=4604853" target="_blank" rel="noopener" data-hveid="0" data-ved="0CAAQ_4QMahcKEwjpwYPfsZCTAxUAAAAAHQAAAAAQIg">https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277?permalink_comment_id=4604853</a></p>
</li>
<li>
<p data-path-to-node="6,1,0"><strong data-path-to-node="6,1,0" data-index-in-node="0">A potential workaround mentioned by a user (a specific plugin):</strong> <a class="ng-star-inserted" href="https://flathub.org/en/apps/com.obsproject.Studio.Plugin.WaylandHotkeys" target="_blank" rel="noopener" data-hveid="0" data-ved="0CAAQ_4QMahcKEwjpwYPfsZCTAxUAAAAAHQAAAAAQIw">https://flathub.org/en/apps/com.obsproject.Studio.Plugin.WaylandHotkeys</a></p>
</li>
<li>
<p data-path-to-node="6,2,0"><strong data-path-to-node="6,2,0" data-index-in-node="0">The official feature request for implementing the GlobalShortcuts portal:</strong> <a class="ng-star-inserted" href="https://ideas.obsproject.com/posts/2066/implement-globalshortcuts-portal" target="_blank" rel="noopener" data-hveid="0" data-ved="0CAAQ_4QMahcKEwjpwYPfsZCTAxUAAAAAHQAAAAAQJA">https://ideas.obsproject.com/posts/2066/implement-globalshortcuts-portal</a></p>
</li>
</ul>
<p>&nbsp;</p>
<p data-path-to-node="4"><s>To provide more context, OBS Studio has implemented support for the </s><code data-path-to-node="4" data-index-in-node="68"><s>org.freedesktop.portal.GlobalShortcuts</s></code><s> portal.</s></p>
<p data-path-to-node="5"><s>Key technical details:</s></p>
<ul data-path-to-node="6">
<li>
<p data-path-to-node="6,0,0"><strong data-path-to-node="6,0,0" data-index-in-node="0"><s>Version:</s></strong><s> This feature was introduced in version 30.0.</s></p>
</li>
<li>
<p data-path-to-node="6,1,0"><strong data-path-to-node="6,1,0" data-index-in-node="0"><s>Code Location:</s></strong><s> The implementation can be found in </s><code data-path-to-node="6,1,0" data-index-in-node="50"><s>plugins/linux-wayland/wayland-shortcuts.c</s></code><s> (or integrated within Wayland backend services in more recent versions).</s></p>
</li>
<li>
<p data-path-to-node="6,2,0"><strong data-path-to-node="6,2,0" data-index-in-node="0"><s>Technical Principle:</s></strong><s> Upon startup (or when a shortcut is configured), OBS sends a request via DBus to the compositor (KWin/Mutter) to establish a Session.</s></p>
</li>
<li>
<p data-path-to-node="6,3,0"><strong data-path-to-node="6,3,0" data-index-in-node="0"><s>Portal Calls:</s></strong><s> The codebase specifically utilizes the following method calls:</s></p>
<ul data-path-to-node="6,3,1">
<li>
<p data-path-to-node="6,3,1,0,0"><code data-path-to-node="6,3,1,0,0" data-index-in-node="0"><s>CreateSession</s></code><s> &ndash; to establish a secure connection with the system.</s></p>
</li>
<li>
<p data-path-to-node="6,3,1,1,0"><code data-path-to-node="6,3,1,1,0" data-index-in-node="0"><s>BindShortcuts</s></code><s> &ndash; to register specific keys (e.g., F10 for pausing).</s></p>
</li>
</ul>
</li>
</ul>
<p data-path-to-node="7"><s>As mentioned previously, since the issue is present on both Ubuntu (Mutter) and Kubuntu (KWin), it is worth investigating if there is a common bug in how these compositors handle these specific portal requests.</s></p>

**Comment by leia-uwu** [comment]
sure love when people reply to someone calling them out about AI slop with even more AI slop...

**Comment by Fenrirthviti** [comment]
@Slavomir9 Please do not post AI output on our repo. Consider this your only warning.

**Comment by C0rn3j** [comment]
Could this issue be reopened, since Wayland protocols now supports global hotkeys (which is the original reason why this issue was closed)?

Or is there another issue that tracks this that I missed?

**Comment by Fenrirthviti** [comment]
This is a feature request, not a bug, which we don't track on Github.

**Comment by Hi-Angel** [comment]
> This is a feature request, not a bug, which we don't track on Github.

Are they tracked elsewhere?

Also, I don't really understand how non-working functional isn't a bug. And neither global shortcuts are a rarely used corner-case — you don't typically want recording to show you clicking start/stop/pause…

**Comment by Fenrirthviti** [comment]
We track feature requests on our [Ideas Page](https://ideas.obsproject.com/).

A bug would be if we had support for Wayland global shortcuts, and something wasn't working properly. There just simply isn't any implementation, so this isn't a bug. You can't have a bug in nonexistent code :)

Thank you!

**Comment by Hi-Angel** [comment]
> There just simply isn't any implementation, so this isn't a bug. 

Well, fair enough… I just opened the "Hotkeys" settings, and it indeed nowhere says the the hotkeys are "global", so… The fact that it works globally in different settings can be considered an undocumented quirk, I see where you're getting… Fair.
