### ISSUE TITLE
OBS-NVENC OpenSharedResource failed

### ISSUE THREAD

**Issue by ValentinVV1** [obsproject/obs-studio#10620]
### Operating System Info

Other

### Other OS

Windows Server 2022

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/kQaNOL9K0gt118Bn

### Expected Behavior

Stream should restart normally after Internet loss.

### Current Behavior

If the network is unavailable, it retries to reconnect as normal until it does - then it throws this error in the console "[obs-nvenc: 'advanced_video_stream'] get_tex_from_handle: OpenSharedResource failed: 0x80070057" and stops streaming until manual intervention (pressing Start streaming again does not work, OBS must be relaunched). OBS also shows a window with a generic encoding error message.

### Steps to Reproduce

1. Set encoding to NVENC H264 (quality settings as bitrate, preset etc. does not seem to matter)
2. Start streaming
3. Disconnect from the Internet at any time (e.g. restart the router)
4. When the Internet connection is back, the error occurs.

### Anything else we should know?

The graphics card that I use is a Quadro K620.
Tested with software H264 encoding, it has no such errors.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a note, we don't support running OBS on Windows Server versions. Looks to be a driver bug/crash from a quick glance at the error/log.

Thank you!
