### ISSUE TITLE
PPA does not contain packages for Ubuntu 24.04

### ISSUE THREAD

**Issue by qwertychouskie** [obsproject/obs-studio#10861]
### Operating System Info

Other

### Other OS

Ubuntu 24.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

N/A

### OBS Studio Log URL

N/A

### Expected Behavior

Adding PPA works

### Current Behavior

```
Err:8 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce

1. Try to add PPA

### Anything else we should know?

An issue was opened previously (https://github.com/obsproject/obs-studio/issues/10609) but was closed at the time because 24.04 hadn't yet officially released.

**Comment by tiberium-v** [comment]
There was no release of an obs version yet since the release of ubuntu 24.04. You have to wait for the obs release of 30.2. What is currently in beta. 

When you want, you can install the beta package via the release section here on GitHub: `https://github.com/obsproject/obs-studio/releases/tag/30.2.0-beta3` click down on assets and choose the package ` obs-studio_30.2.0.beta3-0obsproject1.noble_amd64.deb` (the one with noble in the name).

**Comment by tytan652** [comment]
30.2 once releases (not as a beta/rc) it be available on the stable PPA.
