### ISSUE TITLE
nvenc main10 vbr mode and nvidia driver problem

### ISSUE THREAD

**Issue by L4cache** [obsproject/obs-studio#10891]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

I'll upload it if it's necessary

### Expected Behavior

Do VBR like before.

### Current Behavior

VBR target bitrate setting is not behaving like it used to be.

### Steps to Reproduce

1. Set VBR bitrate to something high.
2. Record.

### Anything else we should know?

https://github.com/rigaya/NVEnc/issues/590

**Comment by Fenrirthviti** [comment]
This issues doesn't properly explain what the problem is, and contains no log files.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by L4cache** [comment]
I thought the problem was explained in linked issue...
Basically the problem is something in nvidia's newer driver prevents the QP to go below some unknown threshold in VBR mode, manually set the lower bound fixes it. Well, **probably**.

**Comment by L4cache** [comment]
You can even reproduce it in ffmpeg.
Try something like `ffmpeg -i input.mkv -c:v hevc_nvenc -pix_fmt p010le -rc vbr -b:v 200M [-qmin 0] output.mkv`, compare the result with and without `-qmin 0`.

**Comment by Fenrirthviti** [comment]
If this is happening because of a driver issue, I'm not sure what we can do.

In the future, if you're opening an issue against a project, putting as much clear and concise context in to the issue is prudent. Linking an external resource is fine for additional context, but just linking an external issue with no explanation is typically bad etiquette.
