### ISSUE TITLE
Crash on launch on Fedora 40

### ISSUE THREAD

**Issue by CorneliusCornbread** [obsproject/obs-studio#10938]
### Operating System Info

Other

### Other OS

Fedora 40

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.1

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

https://pastebin.com/JUw1uGqA

### Expected Behavior

It does not crash on launch

### Current Behavior

It crashes on launch

### Steps to Reproduce

1. Install the latest F40 updates
2. Install the _native_ F40 version of 
3. Open
4. Crash

### Anything else we should know?

This is likely an issue caused by a change in Fedora's upstream, unfortunately, Discover unhelpfully links _here_ for the native Fedora package, instead to a Fedora package maintainer. I'm sorry if this is the wrong place for this, if so, feel free to close this issue. Seems to be an issue related to LLVM

**Comment by tytan652** [comment]
Report to Fedora bugzilla.

**Comment by mihawk90** [comment]
> Discover unhelpfully links _here_ for the native Fedora package

Which is correct, because Discover links to the project's website.

Regardless, packaging bugs are to be reported to the distribution.
The link to the RedHat Bugzilla can be found on the package details page:
https://packages.fedoraproject.org/pkgs/obs-studio/obs-studio/

RPM Fusion packages are separate of course but that's not relevant in this case.
