### ISSUE TITLE
libobs symbol visibility is different on Windows and linux

### ISSUE THREAD

**Issue by ludolpif** [obsproject/obs-studio#10973]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

(this is a CMake configuration topic for libobs rather an OBS UI execution bug)

### Expected Behavior

All symbols exported in libobs.so on linux should be found on obs.dll too. (or the other way around if hidding is intentional ?). 

For instance, with libobs.so.30 taken from : https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/obs-studio_30.1.2-0obsproject1~mantic_amd64.deb
I see : 
```
ludolpif@lud-5490:/tmp$ objdump -T libobs.so.30 | grep ep_parse
00000000000ab580 g    DF .text  0000000000002ede  Base        ep_parse
```
This function is declared in obs/graphics/effect-parser.h, implemented in obs/graphics/effect-parser.c.

### Current Behavior

Under Windows, with latest OBS 30.1.2 obs.dll file, this symbol ep_parse is not exported, but the code is shipped because in use by the exported gs_effect_create() function.

### Steps to Reproduce

1. Create the simplest standalone program with #include <obs/graphics/effect-parser.h>
2. Call ep_parse();  
3. build (with success windows and linux)
4. link (with failure under windows !)

### Anything else we should know?

I expect the difference came from not using `-fvisibility=hidden` CFLAGS on linux builds (default GCC behavior = all symbol exported), using weird (to me) trick in effect-parser.h with "extern" keyword in front of declared functions (but define them normally in the corresponding .c file) and no macro to explicitly export symbols in DLLs.

"extern" for ep_parse is there since 2013 in git. Exported symbol ep_parse is there in most recent stable builds of OBS under linux and also present in libobs.29.so in debian 12, which is built with the old CMake files so I think that new CMake config does not create this discrepancy, it may be there since ages.

Why I get there and call ep_parse() : 

I contribute to an OBS plugin, https://github.com/xurei/obs-shadertastic, which aim to help non-technical users to cherry pick filters and transitions from an online collection and get them in OBS with only one plugin installed once.

We are hitting walls (limitations and segfaults) with libobs/graphics/effect-parser. I built a simple standalone program against libobs to output extra informations in case of parsing problems like lexical errors.

I use only functions in /usr/include/obs/*/*.h, my program just works under linux. It notably calls directly `ep_parse()` and uses it's state to print out more details that the output argument error_string gives using gs_effect_create().

A typical segfault is easy to trigger leave an unbalanced count of `{` and `}` like adding in a valid shader the following line : 
```
if (false) {
```
and I want to trace it without the burden of the full OBS UI/threads/obs-browser footprint and so and fix the parser bug or at least provide a standalone "syntax checker" for OBS effects for effects writers (that could be live streamers).

**Comment by kkartaltepe** [comment]
Linux has historically leaked a fair amount of private headers and symbols, if the symbol doesnt begin with `obs_` you probably shouldnt use it. In this case it looks like it is [marked public](https://github.com/obsproject/obs-studio/blob/master/libobs/CMakeLists.txt#L290) so maybe its intentional to be shared.

The multiplatform way to mark symbols for windows is to use the `EXPORT` macro if you want to send a PR.

**Comment by RytoEX** [comment]
I was pretty sure that we changed the visibility of symbols in the CMake rewrite which is now available on all platforms. @PatTheMav may recall.

**Comment by ludolpif** [comment]
Thanks for the quick reply !

I will be happy to try to help sending a PR but as a newcomer on this project, it seems that it will touch many files at once if I try to be exhaustive around all leaked symbols.

Did you meant a PR only around `effect_parser.h/c` ?

And comes with the question around the shipped headers themselves : why `effect_parser.h` is deployed in `/usr/include/obs/` on all `.deb` packages I've ever watched if it was never desirable some one build a program using it ? (this whole header file seems useless if the if you don't export `ep_free()` for instance).

It didn't really see how you want to work around the public/private headers. I imagine that you want (or have and I don't see it) a mechanism to ensure :

- While compiling libobs, every functions needs to be available from other compilation units of libobs via header files
- While shipping header files for end-users, plugins, etc, it may only define functions that are indeed exported in the lib

Should I PR a way to not publish headers files without any matching exported symbols in the PR too ? 

I am unsure about where the public/private limits are behind obs_* functions because of structs, darray, and header inter-dependencies. It there an up-to-date source of trust that is exhaustive already done somewhere ? If not, I can try graph it, or try to diff with documented API in https://docs.obsproject.com/backend-design but it will probably open many new questions.

Best regards,
Ludovic

**Comment by PatTheMav** [comment]
Only symbols explicitly marked as `EXPORT` are considered public and should be used by third party code. If anything breaks after this change, that breakage is intentional because a private symbol is used that was never part of the API (which _already_ exposes far too many internals and will be reduced/cleaned up in the future).

The only exception to this is if a function logically needs to be exported for the (current) API to work but has not been correctly marked as such.

> And comes with the question around the shipped headers themselves : why effect_parser.h is deployed in /usr/include/obs/ on all .deb packages I've ever watched if it was never desirable some one build a program using it ? (this whole header file seems useless if the if you don't export ep_free() for instance).

Because - quite frankly - our code base and packaging was a bit of a mess in this regard and not enough attention was placed on using good practices around symbol visibility. In the past simply _all_ header files were made part of the exported library because no time or effort was pu in to check which symbols are actually supposed to be exposed and which associated header files are needed in the first place.

_If_ something used those private functions, it needs to either change its code to use the actual public API or request the functionality as a new feature or open a feature PR adding it to the code base (though there is the chance that we might not accept it as we might not want to open up even more internals to plugins).

**Comment by RytoEX** [comment]
Closing this per above. As far as I'm aware, these changes were intentional.
