### ISSUE TITLE
OBS lowers game performance too much since release 30.0

### ISSUE THREAD

**Issue by Hydrough2k2k** [obsproject/obs-studio#10987]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/OiWHStf0zp7j4pxQ

### Expected Behavior

I have Satisfactory running on my PC, running at 140 FPS

### Current Behavior

The instant I launch up OBS it drops down to 80-100 FPS. Replay buffer, recording, streaming are all off, it is just sitting there. This performance hit is way too high!

My output settings are 1920x1080 no downscaling, using nvenc H264

### Steps to Reproduce

1. Launch up any heavy application, note the framerate and hardware usage when uncapped
2. Launch up OBS
3. Take note of the performance hit

### Anything else we should know?

I have a moderately powerful PC, Ryzen 7 5700X, 32GB DDR4 RAM, RTX 3060ti. It seems like OBS using way too much of my PC while doing nothing. The performance hit prior to 30.0 was not significant, I will be downgrading my OBS version.

**Comment by izyspania** [comment]
Same here , what i noticed that even without starting to stream or record anything the GPU usage spikes to about 50%, 25% the OBS and 25% NVIDIA Container and also OBS is using ~3-5% CPU while doing nothing, when i start streaming with NVENC even games with low GPU usage (like WoW) i see a noticeable FPS drop.

![image](https://github.com/user-attachments/assets/ec7ad77e-6bc2-4abb-aac4-b9fdc4828d5a)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

There is unfortunately nothing actionable here, and all of this sounds perfectly normal if you're running a game at max settings with uncapped framerates. The support channels can take a closer look and provide suggetsions.

Thank you!

**Comment by Hydrough2k2k** [comment]
Appreciate the reply, though I disagree, this is not normal. Like I said, this was not a thing before 30.0, I am running the game at a mix of low, medium, high. Regardless of the settings though the performance drop should not be this significant when no encoding is taking place.

Also reply to you, izyspania: It sounds like your performance hit is because of CPU, mine is from the GPU side. I really wonder what's going on with both cases... You could try to change the thread affinity in Task manager and see if that makes a difference

**Comment by Fenrirthviti** [comment]
Without further information, a bisection, a commit that caused the problem, a specific source type, etc., this report is not really actionable. General performance issues have been reported since the very first version of OBS Classic, and every single update someone claims things run worse. I can count on a single hand the number of times it's been something that was actually our fault, and I don't want to turn GitHub in to a support back and forth, as it clutters the report, and we don't do general troubleshooting and support on GitHub. If the support channels determine that there is an actual problem here, and identify what that is, it will be a verified report that can be submitted, or this issue can be re-opened with details.

**Comment by izyspania** [comment]
With older versions it was working OK but with this new version it does not, i dont understand why OBS is using 25-40% of the GPU  when is not doing anything, i did a fresh install of latest version too, you can see in pictures , that GPU usage is happening without enconding or recording anything, i only open OBS, im also using 5700x and a 2060 Super.

**Comment by Fenrirthviti** [comment]
Because your CPU/GPU are likely downclocking. Task manager is an awful metric for measuring actual usage, because at lower power modes it can appear to be using more.

Again, please use the support channels, as this is a common misconception that could be explained there.

**Comment by izyspania** [comment]
I am not a noob with computers but i might be wrong the idea is that i dont think is anything wrong with my computer , my other system with 5800x3d and a 3060 has the same behavior,  with the older OBS the GPU is not used unless im starting to stream, it just looks like this version is doing some extra work on the GPU.
Anyway i am just going to use the older one , i just wanted to report this as i think its a bug in OBS and im not looking for support.

Best Regards

On idle only OBS started.
![image](https://github.com/user-attachments/assets/77aa9d33-0551-46a5-8d6a-e900779dde31)
