### ISSUE TITLE
OBS is not working anymore with new version, Vcredist microsoft C++ bug (2015-2022)

### ISSUE THREAD

**Issue by wblanc77** [obsproject/obs-studio#10988]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0

### OBS Studio Log URL

Can't launch OBS...

### Expected Behavior

Worked as usual...

### Current Behavior

Not working, Crash at beginning because of the new version, telling me that my vcredist is not updated (this is wrong). I can't repair vcredit, i can't reinstall, many people have the same problem, what can i do ?

### Steps to Reproduce

1. Launching OBS
2. Accepting to reinstall Vcredist
3. Not Working
4. Reboot and try to repair or anything
5. Not Working
6. Ask to you what can i do ?

### Anything else we should know?

This only happened because of the new version, i've never have this BUG from all this time. 

Look at this screen, thank you.
![OBS bug vcredist](https://github.com/user-attachments/assets/52de5a30-d06f-44d8-a58a-4de49f25d957)

**Comment by notr1ch** [comment]
You will need to resolve whatever issue prevents you from installing / repairing the updated Visual Studio runtimes, this is outside the scope of OBS.

**Comment by ceruleanight** [comment]
I'm facing the same problem on win10. Both versions have been downloaded and installed from the obs website, and it still gives that error. I ended up just downgrading to [30.1.2](https://github.com/obsproject/obs-studio/releases/tag/30.1.2) without issue.

**Comment by tripathi-abhishek** [comment]
Click Ok -> Goto download page -> then download the "Vcredist microsoft C++ bug (2015-2022)" and try installing it. It will show repair button if already installed. Click on repair. then restart PC.

This worked for me.

**Comment by wblanc77** [comment]
> I'm facing the same problem on win10. Both versions have been downloaded and installed from the obs website, and it still gives that error. I ended up just downgrading to [30.1.2](https://github.com/obsproject/obs-studio/releases/tag/30.1.2) without issue.

This is what i did.

**Comment by wblanc77** [comment]
> Click Ok -> Goto download page -> then download the "Vcredist microsoft C++ bug (2015-2022)" and try installing it. It will show repair button if already installed. Click on repair. then restart PC.
> 
> This worked for me.

It was impossible for me, i will try something with this => https://answers.microsoft.com/en-us/windows/forum/all/unable-to-delete-microsoft-visual-c-2015-2019/73bd3a00-228d-4670-b3b5-f7ed1f62f70e

**Comment by derrod** [comment]
> I'm facing the same problem on win10. Both versions have been downloaded and installed from the obs website, and it still gives that error. I ended up just downgrading to [30.1.2](https://github.com/obsproject/obs-studio/releases/tag/30.1.2) without issue.

If running the installer worked, please let us know the following:

1. If there are any files called `msvcp140.dll` in the OBS installation directory

2. The version of `msvcp140.dll` in `C:\Windows\System32` (right click -> properties -> details)
![DLL proerties](https://github.com/user-attachments/assets/5cf0f741-33a9-47fa-b899-8d3794cacd31)

3. Which `msvcp140.dll` is loaded by the OBS process (you can see this in [process explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer))
![process explorer](https://github.com/user-attachments/assets/f5aeada2-1b1d-44d6-8a95-62f960f3e534)

**Comment by hgouveia** [comment]
i am facing the same issue, i downloaded both x64/x86 version from the OBS provided urls, click repair, restarted, nothing, tried once again after restart and restarted again, same issue 

![image](https://github.com/user-attachments/assets/9c9cf8a5-a6f0-4631-8d50-11a8c83bdcc2)

**Comment by hgouveia** [comment]
> Please provide the information I asked for in the above comment [#10988 (comment)](https://github.com/obsproject/obs-studio/issues/10988#issuecomment-2229727390)

hey sure

`C:\Windows\System32\msvcp140.dll`
![image](https://github.com/user-attachments/assets/435d13f6-b457-439a-b1c4-6969d7d719ee)

`obs64.exe`
![image](https://github.com/user-attachments/assets/829d5a18-ed8a-4b30-8b13-47f7f688797a)

**Comment by derrod** [comment]
Yeah that DLL should not be there. And we don't put it there either. Can you provide us with a log from the last time you successfully launched OBS (in `%APPDATA%\obs-studio\logs`)? Afterwards try to uninstall and reinstall OBS.

**Comment by hgouveia** [comment]
> Yeah that DLL should not be there (the OBS install folder). And we don't put it there either. Can you provide us with a log from the last time you successfully launched OBS (in `%APPDATA%\obs-studio\logs`)? Afterwards try to uninstall and reinstall OBS.

Yeap, after removing `msvcp140.dll` from the `bin` folder in my obs installation, solved the issue i didnt need to uninstall/reinstall, not sure why those dll were there ,i guess was an addon, but at this point i can't be sure which one tbh

logs
[2024-07-16 16-46-02.txt](https://github.com/user-attachments/files/16265393/2024-07-16.16-46-02.txt)

**Comment by ddescham74** [comment]
I have the exact same issue, msvcp140.dll is not in the obs folder, I have it in System32 and the version is 14.29.30133.0.
Everything is installed correctly, I tried repairing vcredist, didn't do nothing.
It worked twice with the new version, then it stopped working and had to downgrade. I didn't change anything on my system between the time it worked and the time the error appeared.
Here are the logs of when it worked. 
[2024-07-14 11-43-36.txt](https://github.com/user-attachments/files/16270610/2024-07-14.11-43-36.txt)
[2024-07-15 10-53-56.txt](https://github.com/user-attachments/files/16270664/2024-07-15.10-53-56.txt)

**Comment by RytoEX** [comment]
Version 14.29.30133.0 is outdated. The current version is 14.40.33810.0.

**Comment by ddescham74** [comment]
Well, I don't know what to do, I installed the version of vcredit that is on the OBS wensite, it says it is already installed and repairing didn't do anything. 
Well, I am gonna investigate then

**Comment by RytoEX** [comment]
If Repair does not work, then you need to uninstall and reinstall it. This is outside the scope of this Issue though. Please visit our support channels if you require further assistance with that.

If you still have issues _after_ confirming that the version in System32 is the latest version, then please provide the info requested in the comment above: https://github.com/obsproject/obs-studio/issues/10988#issuecomment-2229727390

**Comment by hgouveia** [comment]
> I have the exact same issue, msvcp140.dll is not in the obs folder, I have it in System32 and the version is 14.29.30133.0. Everything is installed correctly, I tried repairing vcredist, didn't do nothing. It worked twice with the new version, then it stopped working and had to downgrade. I didn't change anything on my system between the time it worked and the time the error appeared. Here are the logs of when it worked. [2024-07-14 11-43-36.txt](https://github.com/user-attachments/files/16270610/2024-07-14.11-43-36.txt) [2024-07-15 10-53-56.txt](https://github.com/user-attachments/files/16270664/2024-07-15.10-53-56.txt)


in my case, in the bin folder i had 3 `msvcp140.dll`. i removed all of them

```
msvcp140.dll
msvcp140-1.dll
msvcp140-2.dll
```

**Comment by Fenrirthviti** [comment]
> > I have the exact same issue, msvcp140.dll is not in the obs folder, I have it in System32 and the version is 14.29.30133.0. Everything is installed correctly, I tried repairing vcredist, didn't do nothing. It worked twice with the new version, then it stopped working and had to downgrade. I didn't change anything on my system between the time it worked and the time the error appeared. Here are the logs of when it worked. [2024-07-14 11-43-36.txt](https://github.com/user-attachments/files/16270610/2024-07-14.11-43-36.txt) [2024-07-15 10-53-56.txt](https://github.com/user-attachments/files/16270664/2024-07-15.10-53-56.txt)
> 
> in my case, in the bin folder i had 3 `msvcp140.dll`. i removed all of them
> 
> ```
> msvcp140.dll
> msvcp140-1.dll
> msvcp140-2.dll
> ```

We need the full details requested in https://github.com/obsproject/obs-studio/issues/10988#issuecomment-2229727390

**Comment by ddescham74** [comment]
Yeah no I had no msvcp140 dlls in the obs folder whatsoever
I fixed the issue tho, I had to repair the vcredist 3 times and then upgrade OBS which installed the vcredist again as well and it finally worked.
The joys of windows
Thanks for your help everyone!

**Comment by IanJSaul** [comment]
I ran into this same issue after using OBS without a problem yesterday.  The only change was that I updated Davinci Resolve to the 19 Beta 5 release, restarted - and OBS stopped working.

A quick REPAIR to both of the 2015-2022 C++ Redistributable for x86/x64 - and OBS now opens.

**Comment by yunytuny** [comment]
Agree with @IanJSaul. I also update Davinci Resolve to 19 public beta 5 release an OBS stiooed working. I wonder what this is related to

**Comment by RytoEX** [comment]
If you're having issues running OBS Studio after installing DaVinci Resolve, please report that to their developers.

**Comment by kikosgc** [comment]
> If you're having issues running OBS Studio after installing DaVinci Resolve, please report that to their developers.

@RytoEX I have that exact same situation!

**Comment by RytoEX** [comment]
@kikosgc Please report the issue to the DaVinci Resolve team.

**Comment by RytoEX** [comment]
> I wonder what integrity/version check is occurring that prevents runnning OBS. I wonder if it could have run without having to re-do VC redist.

No. Without the correctly updated VC redist, OBS Studio will crash.

**Comment by hannahbellelee** [comment]
I installed the update, but it immediately threw an exception when i tried to launch it. I'm a Sr. Software Eng. (for goin on 2 decades) and already have that vcredist version TRUST ME.... And I update my OS, Visual Studio 2022, and all dev tools regularly. And not only that, but I'm really confused as to why your software would require both x86 and 64bit versions.  This is not a requirement of the OS nor of the Redistributable... So that leaves your software or 3rd party libraries. Either way, I will not overwrite my working version of a 2yr/old C++ redist unless Visual Studio prompts me to, and I'm guessing if I try to uninstall the OBS version and reinstall the last version I had that was working, It's probably already too late. So I guess I won't be using it anymore with a requirement like that, anyway. Hope you figure it out soon.

**Comment by RytoEX** [comment]
> I installed the update, but it immediately threw an exception when i tried to launch it. I'm a Sr. Software Eng. (for goin on 2 decades) and already have that vcredist version TRUST ME.... And I update my OS, Visual Studio 2022, and all dev tools regularly. And not only that, but I'm really confused as to why your software would require both x86 and 64bit versions. This is not a requirement of the OS nor of the Redistributable... So that leaves your software or 3rd party libraries. Either way, I will not overwrite my working version of a 2yr/old C++ redist unless Visual Studio prompts me to, and I'm guessing if I try to uninstall the OBS version and reinstall the last version I had that was working, It's probably already too late. So I guess I won't be using it anymore with a requirement like that, anyway. Hope you figure it out soon.

The requirement for a newer VC++ Redistributable is due to a change in the Microsoft STL shipped with Visual Studio 2022 17.10, which is then used in any software built with VS 2022 17.10 or newer. Microsoft considers this change by design. See:
* https://github.com/microsoft/STL/releases/tag/vs-2022-17.10
* https://developercommunity.visualstudio.com/t/Visual-Studio-17100-Update-leads-to-Pr/10669759

As noted earlier in this thread, some installers will overwrite existing newer/current vcredist installs with _older_ versions (Blackmagic's DaVinci Resolve does this). Unfortunately, that is outside of our control. Some installers targeting the OBS Studio directory may install their own versions into OBS Studio's directory. Unfortunately, that is also outside of our control.

OBS Studio requires both x86 and x64 versions because it has both x86 and x64 components for Game Capture and Virtual Camera. This is so that those components can work with x86 software instead of just working with x64 software.

Installers for older versions of OBS Studio are available on the [Releases Page](https://github.com/obsproject/obs-studio/releases). Older versions of OBS Studio should work with newer versions of the VC++ Redistributable.

This GitHub Issue remains open [due to cases where some other installer ships its own copy of msvcp140.dll](https://github.com/obsproject/obs-studio/issues/10988#issuecomment-2233083140) as a reminder that we would like to find a way to detect such rogue DLLs. We suspect that these cases are due to some OBS Studio plugin installers, but we have been unable to confirm. Thank you for your understanding.

**Comment by hannahbellelee** [comment]
I am running VS2022 17.11.2. Still no other apps are crashing Maybe I read that differently than you did. My runtimes/redists are installed when I select them in Visual Studio Installer, not "independently".  And I have customers using the older Redists. I can't just go and change the redistributable prereqs that get published to my customers.  If I did, then all my devs that build and/or publish those apps would have to do the same...then every user of every computer that runs our software will also have to update. And some companies don't allow that at all. This would be the equivalent of me changing one of my apps from >net Framework 4.72 to .NET8 without planning it with my customers.
 
 Sorry, I can't install those redists. I can't do that to my customers.  And really, I can't understand why you'd push such a change to all your users, because let's be honest here, the latest redist that uses the latest c++ features, is a breaking change for many of your users, and now you've locked them in to either using older versions of OBSStudio or updating their own redists. 
 
 And again, maybe I'm reading the devcommunity response incorrectly or understanding it differently, but the post seems to focus on the way the mutex is implemented, and that is the root cause of the app crashing. I took it to mean either you are deploying an app with newer headers than EVERYONES INSTALLED REDIST VERSIONS, and all of our versions must be updated to meet a minimum requirement based on YOUR headers, or "When you mix binaries built by different supported versions of the toolset, the Redistributable version must be at least as new as the latest toolset used by any app component." And whether it was your code or a 3rd party vendors code, it doesn't matter. You pushed a breaking change to your customers and now they can choose to remain on your now-frozen-in-time legacy builds, or they unnecessarily update. Either way, this wasnt "by Microsoft's Design".... good luck

**Comment by RytoEX** [comment]
> Sorry, I can't install those redists. I can't do that to my customers. And really, I can't understand why you'd push such a change to all your users, because let's be honest here, the latest redist that uses the latest c++ features, is a breaking change for many of your users, and now you've locked them in to either using older versions of OBSStudio or updating their own redists.

My understanding is that any application built with VS 17.10+ (which shipped the updated Microsoft STL headers) that uses mutexes would be affected. The root cause is a change in the mutex constructor in the Microsoft STL at that time, which is mentioned in the linked release notes as a "bug fix" ("Fixed `mutex`'s constructor to be `constexpr`"). As soon as GitHub Actions updated Visual Studio to 17.10, our CI builds were affected.

Per the Microsoft Resolution on the devcommunity thread:
> You can define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR as an escape hatch.
That is, if you’re seeing crashes due to null dereferences in mutex locking machinery, you’re deploying a program built with new STL headers, but without a sufficiently new msvcp140.dll, which is unsupported. You need to be (re)distributing a new STL DLL too. (If a VS 2022 17.10 VCRedist has been independently installed on the machine - then everything will happen to work.)

We elected not to use the escape hatch, because there's no guarantee that that will work forever, and instead advise users to update the VC++ Redistributable if they wanted to update OBS. If a user does not want to, or is not able to, update the VC++ Redistributable on their system, then they do not have to update OBS.

We are aware that it is frustrating, as it was frustrating to us at the time to have it become something we had to address. However, it was a change in the Microsoft STL to the `mutex` constructor.

I would prefer that this GitHub Issue would remain focused on discussion about rogue/unexpected msvcp140.dll files inside the OBS Studio directory and possibly finding a root cause or a solution for that.

**Comment by natereprogle** [comment]
> > Sorry, I can't install those redists. I can't do that to my customers. And really, I can't understand why you'd push such a change to all your users, because let's be honest here, the latest redist that uses the latest c++ features, is a breaking change for many of your users, and now you've locked them in to either using older versions of OBSStudio or updating their own redists.
> 
> My understanding is that any application built with VS 17.10+ (which shipped the updated Microsoft STL headers) that uses mutexes would be affected. The root cause is a change in the mutex constructor in the Microsoft STL at that time, which is mentioned in the linked release notes as a "bug fix" ("Fixed `mutex`'s constructor to be `constexpr`"). As soon as GitHub Actions updated Visual Studio to 17.10, our CI builds were affected.
> 
> Per the Microsoft Resolution on the devcommunity thread:
> 
> > You can define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR as an escape hatch.
> > That is, if you’re seeing crashes due to null dereferences in mutex locking machinery, you’re deploying a program built with new STL headers, but without a sufficiently new msvcp140.dll, which is unsupported. You need to be (re)distributing a new STL DLL too. (If a VS 2022 17.10 VCRedist has been independently installed on the machine - then everything will happen to work.)
> 
> We elected not to use the escape hatch, because there's no guarantee that that will work forever, and instead advise users to update the VC++ Redistributable if they wanted to update OBS. If a user does not want to, or is not able to, update the VC++ Redistributable on their system, then they do not have to update OBS.
> 
> We are aware that it is frustrating, as it was frustrating to us at the time to have it become something we had to address. However, it was a change in the Microsoft STL to the `mutex` constructor.
> 
> I would prefer that this GitHub Issue would remain focused on discussion about rogue/unexpected msvcp140.dll files inside the OBS Studio directory and possibly finding a root cause or a solution for that.

To add my $0.02, I just updated OBS on my PC and I did _not_ have that rogue `msvcp140.dll` in my OBS install folder, however it was still prompting me to install a newer version of the redist. I had both the x32 and x64 versions of the specific redist on your website already installed. What did work was [this suggestion](https://github.com/obsproject/obs-studio/issues/10988#issuecomment-2292333473) above. So, I can't say that it was the msvcp140.dll file that caused the issue since it never existed in the first place. I, too, did not have to restart my PC after repairing the redist for OBS to launch (Even though the repair claims it's necessary). Not sure if that's any assistance or not.

**Comment by SBarkovskiy** [comment]
A solution which helped me:
1. Go to installed `Apps` on within your Windows `Settings` app
2. Search for `C++`
3. Search for `Microsoft C++ 2015-2022 Redistributable (x64) - 14.40.33810`
4. Hit `...` => `Modify` => `Repair`
5. Allow to restart your machine at the end
6. After the restart - lunch OBS

**Comment by kfrncs** [comment]
This was happening for me, also after installing Da Vinci. Repairing both x64 and x86 did not work, even with a restart. I uninstalled both msvcpp's and obs, then installed the latest msvcpp (mentioned above) and obs and the problem is fixed. Just in case that info is useful or relevant. Would have to check what's up with the Da Vinci installer messing around with system dll's, because I did not have that .dll file in my install folder or in /bin

I don't know now if the linked version in the error message is the latest, or whether just updating *may* have solved. Could be unrelated. Thanks

**Comment by soundattacker13** [comment]
> This was happening for me, also after installing Da Vinci. Repairing both x64 and x86 did not work, even with a restart. I uninstalled both msvcpp's and obs, then installed the latest msvcpp's (mentioned above) and OBS and the problem is fixed. Just in case that info is useful or relevant. Would have to check what's up with the Da Vinci installer messing around with system dll's, because I did not have that .dll file in my install folder or in /bin
> 
> I don't know now if the linked version in the error message is the latest, or whether just updating _may_ have solved. Could be unrelated. Thanks. I'll email this thread to Blackmagic support

Where du you install the new msvcp?

**Comment by gubbsg2** [comment]
> This was happening for me, also after installing Da Vinci. Repairing both x64 and x86 did not work, even with a restart. I uninstalled both msvcpp's and obs, then installed the latest msvcpp's (mentioned above) and OBS and the problem is fixed. Just in case that info is useful or relevant. Would have to check what's up with the Da Vinci installer messing around with system dll's, because I did not have that .dll file in my install folder or in /bin

how the fuck did you uninstall it if the uninstall button doesn't work?

**Comment by Edvando** [comment]
> > Estou enfrentando o mesmo problema no win10. Ambas as versões foram baixadas e instaladas do site obs, e ainda dá esse erro. Acabei fazendo downgrade para [30.1.2](https://github.com/obsproject/obs-studio/releases/tag/30.1.2) sem problemas.
> 
> Se a execução do instalador funcionou, informe-nos o seguinte:
> 
> 1. Se houver algum arquivo chamado `msvcp140.dll`no diretório de instalação do OBS
> 2. A versão de `msvcp140.dll`em `C:\Windows\System32`(clique com o botão direito -> propriedades -> detalhes)
>    ![Propriedades DLL](https://private-user-images.githubusercontent.com/3123295/348895190-5cf0f741-33a9-47fa-b899-8d3794cacd31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTcwMDksIm5iZiI6MTcyODIxNjcwOSwicGF0aCI6Ii8zMTIzMjk1LzM0ODg5NTE5MC01Y2YwZjc0MS0zM2E5LTQ3ZmEtYjg5OS04ZDM3OTRjYWNkMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDZUMTIxMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFmOTJmODQ1NGVhZTFlMWJiMzdhMDdlNWFhZDI3Nzg3MWMyZjVkMjFhZDhiYjQ1ZDc0MWQzZTgxNTYwMGY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WIF4TsxhnhR6eaEpr-0IAGuyL3sChxVkurUbYtjk_6E)
> 3. Que `msvcp140.dll`é carregado pelo processo OBS (você pode ver isso no [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) )
>    ![explorador de processos](https://private-user-images.githubusercontent.com/3123295/348895296-f5aeada2-1b1d-44d6-8a95-62f960f3e534.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTcwMDksIm5iZiI6MTcyODIxNjcwOSwicGF0aCI6Ii8zMTIzMjk1LzM0ODg5NTI5Ni1mNWFlYWRhMi0xYjFkLTQ0ZDYtOGE5NS02MmY5NjBmM2U1MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDZUMTIxMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFlMWQ0Y2EwYmUyYTljNTA1OWQ0MTRjNDY5ZDQyZmJlM2E2NzlmZTllZjk5OWRlOTRkNTUxMjJhMmM5Yjc0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UIuo_NollZkhmUBrjMmhx6BDE09eh0o16C-q5exxj9s)

It's simple to solve: just take the msvcp140.dll from windows in C:\Windows\System32 and transfer it to obs and restart the PC and mine came back, and delete all versions of msvcp140.dll that are in the folder

**Comment by Fenrirthviti** [comment]
As this issue is caused by third party applications and other unrecommended practices by applications outside OBS, this issue is now considered closed. If you are experiencing issues launching OBS and getting a similar error message, make sure to check that all VC Redist packages are up to date, and there are no improperly installed libraries in the OBS program directory.

If this does not resolve the issue, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
