### ISSUE TITLE
massive performance regression with version 30.2.0

### ISSUE THREAD

**Issue by kakra** [obsproject/obs-studio#11009]
### Operating System Info

Other

### Other OS

Gentoo Linux

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/jLSFpzI5UbhVOtAc

### Expected Behavior

Running on X11...

With OBS 30.1.2 I could stream to Twitch and record to harddisk at the same time without any problem and with steady 60fps.

This changed with OBS 30.2.0, and I'm not sure if this related to switching from ffmpeg nvenc to native nvenc.

### Current Behavior

Compared to OBS 30.1.2, with OBS 30.2.0 I can no longer record and stream a video at the same time, I'm seeing massive performance drops. Previously, I could record with steady 60fps, now, either the game drops below 10fps, especially if the game streams new textures, or the recording drops below 10fps, sometimes both drop down to 3fps for multiple seconds. If I encode only just one video, the same behavior can be observed but the performance drop eventually recovers after 20-30s can goes back up to 60fps. In the extreme case, even audio playback from the game stutters. This looks a lot like bus bandwidth usage due to VRAM pressure, and by looking at `nvidia-smi`, I can confirm that OBS probably leaks VRAM somewhere (it used 1.8 GB at which point I had to stop the game and OBS, and restart the stream). OBS usually hovers at around 600-800 MB VRAM.

After some more testing, I've switched from Xcomposite window capture to using the linux-vkcapture plugin to record the game window. This improved things a lot: While I still see performance drops that recover after a few seconds, at least OBS settles at around 800 MB VRAM usage. However, I still cannot properly record and stream at the same time: OBS struggles to go over 40 fps, and this also causes a lot of heavy performance drops.

I also tried using wayland natively and switching to pipewire recording sources: This is unusable, after a short time windows start to flicker or go black. Even the game window itself may become black while I can still see the contents properly recorded in the stream.

This happens with both the flatpak version and the native Gentoo version, but I prefer the native Gentoo version because it has lower CPU usage (0.5% idle vs 3% idle, similar but closer while recording/streaming). I think this is due to flatpak sandboxing.

Since this worked just fine with OBS 30.1, I doubt my system would be underpowered for this setup.

According to `nvidia-smi`, around 1 GB of VRAM remains free all the time, so this isn't actually VRAM pressure. Maybe render surfaces are allocated from non-device memory sometimes?

### Steps to Reproduce

1. Install and configure OBS 30.1.2
2. Record and stream at the same time with 60fps, play with 60fps at 4k (locked via mangohud)
3. Upgrade to OBS 30.2
4. Record and stream at the same time
5. Notice immediate worse performance, OBS struggles to stream/record more than 40fps, game runs at 60fps
6. Play a little longer, change game scenes, go through loading screens: whole setup drops below 10fps

### Anything else we should know?

I'm not sure if Gentoo disabled ffmpeg nvenc in 30.2 so I cannot test but I realize that the log says "FFmpeg VAAPI H264 encoding not supported" - but this is probably just non non-NVIDIA anyways.

Here's another log from a streaming session:
https://obsproject.com/logs/WmWANmjJzU9ujc9r

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by kakra** [comment]
Well then be it, although a performance regression is a bug in my opinion. But that's fine, I'll go to the forums then.

**Comment by Fenrirthviti** [comment]
Understand that every single update we get hundreds of "performance is worse" without any actual reduced test case or steps to replicate from a clean setup. You're also using several third party plugins, which may be resulting in issues. As it stands, this issue report is "something went wrong" and will take hundreds, if not more, replies and back and forth to try and isolate, which should be done well in advance of submitting an issue report. We reserve issues for verified, reproducible issues. Until a very specific cause, commit, or other targeted reason for a performance loss is determined to be something we did, the support channels is the right place to go. If something is identified, then we can consider reopening this with the new information.

I am not closing this because I'm stating there isn't an issue, I have no idea if there is or not. I am closing this because there's not enough information to be actionable, and the discussion to get to that point is not something we want to have on GitHub.

**Comment by kakra** [comment]
> As it stands, this issue report is "something went wrong" and will take hundreds, if not more, replies and back and forth to try and isolate, which should be done well in advance of submitting an issue report.

This makes sense, thanks for explaining. I can perfectly follow your reasoning, I'm running a Github project myself and long discussions are actually reducing visibility of the underlying core problems.

Reposted here if someone wants to join the discussion, no further reply needed here unless the source of the issue has been identified: https://obsproject.com/forum/threads/performance-regression-with-obs-30-2-gentoo-linux.176932/

**Comment by Chiitoo** [comment]
As the Gentoo Linux maintainer for OBS Studio, I will mention here that nothing was intentionally disabled on that side with regards to nvenc.  It is entirely possible that I have missed some changes related to that, however, especially since I don't use nvidia any longer myself.

In a situation like this, I might recommend 'git bisecting' to find when exactly the regression starts.  Could make use of the '9999' version, setting a commit SHA between the releases to test and build next (make note of browser and websocket commits as well, as they may have changed).

Can reach me via IRC on libera.chat or via e-mail (`chiitoo@gentoo.org`) for any further discussion on that.  :]
