### ISSUE TITLE
Live Streaming Keeps Stopping

### ISSUE THREAD

**Issue by PCC-Linda** [obsproject/obs-studio#11016]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/Now5YKJn9B9Dm66J

### Expected Behavior

I normally just hit the start streaming and we have no issues.

### Current Behavior

So we were streaming. Then all of a sudden the stream stops there is no indication on OBS that this is occuring. The onyl way to know is to monitor the live stream simultaneously. It is not our bandwidth as we are doing a upload of over 200. The system is showing no dropped scenes. It occured over 5 times within one hour this morning. In order to correct it you need to hit the stop streaming then go back in and hit the start streaming.

### Steps to Reproduce

1.We hit the start streaming button, 
2. After a few minutes it stops streaming but shows no indication of it on the program only when you are monitoring the youtube channel
3.
...

### Anything else we should know?

no

**Comment by Fenrirthviti** [comment]
There is no indication of anything wrong in OBS in the log files. It's likely this is an issue with the restreaming service you are using. I suggest you contact them first.

**Comment by PCC-Linda** [comment]
Could I have downloaded the wrong log?

**Comment by Fenrirthviti** [comment]
Doubtful, the log has plenty of streaming attempts in it, but they are all manually stopped, as you stated in your description, and none of them contain any errors or issues that would result in the stream stopping. Restream has had issues like this in the past, either they were having a partial outage of some kind, or there is some other issue on their end. As it stands, we can't determine what the issue is, as OBS is reporting everything is fine, so Restream will need to investigate on their end. If they determine there was an issue with the stream being sent from OBS, we can open with those details.
