### ISSUE TITLE
OBS Being Laggy When FPS Is Set To Lower Than 1

### ISSUE THREAD

**Issue by Yqloss** [obsproject/obs-studio#11048]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://file.io/GwKnEfFNFFas

### Expected Behavior

OBS behaves normally, being as responsive as 60 FPS.

### Current Behavior

OBS will lag after doing almost every operation like startup, exit, modify settings and so on. If I set the framerate to 1/10 FPS then OBS will lag about 10 seconds. 1/3600 FPS will cause 1-hour lag and just like this.

### Steps to Reproduce

1. Settings -> Video
2. Select "Fractional FPS Value"
3. Set Numerator to 1, Denominator to 10
4. Restart your OBS
5. Now you can notice that there is a huge lag

### Anything else we should know?

I searched for keywords like "low FPS", "low framerate", "lag" in issues and got no result.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a note, we don't typically support framerates that low, and recommend using a different method for "timelapse" style recordings.

Thank you!

**Comment by matoi974** [comment]
This is normal / by design, I'd advise not going below 0.25 FPS. Use external software to further reduce the frame rate of your recordings, if necessary.
