### ISSUE TITLE
OBS is "mostly" white

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#11068]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/Bgy0RUDHoYbIkCEo

### Expected Behavior

I expect most of the application to not appear white rendering OBS unusable.

### Current Behavior

![image](https://github.com/user-attachments/assets/87766e91-4903-4efa-abff-7b4fe02bcfa0)

### Steps to Reproduce

I have no idea. I just started OBS up one day and it looks like this.

### Anything else we should know?

The previous day it worked fine. Didn't break between OBS updates, no hardware changes to my system, no Windows updates caused this, etc, etc..

**Comment by Fenrirthviti** [comment]
This is typically caused by third-party display drivers, such as ones that ship with mobile device emulators, screen sharing applications, drawing tablets, etc. https://obsproject.com/kb/known-conflicts

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by jadenquinn** [comment]
> This is typically caused by third-party display drivers, such as ones that ship with mobile device emulators, screen sharing applications, drawing tablets, etc. https://obsproject.com/kb/known-conflicts
> 
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

I have the official NVIDIA drivers, and they are up to date.
