### ISSUE TITLE
When you add the source as a browser, the browser title changes all the time, but you can't match the title with a regular expression

### ISSUE THREAD

**Issue by ahoujanai** [obsproject/obs-studio#11093]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/4iOTbmeIzhNLuN8F

### Expected Behavior

Expect to support regular match titles
![屏幕截图 2024-08-08 183528](https://github.com/user-attachments/assets/60b374ea-79f8-42e6-b0bd-270e157af929)

### Current Behavior

When you add the source as a browser, the browser title changes all the time, but you can't match the title with a regular expression, and you have to reopen the browser to change the browser back to the default title if you want to display the browser

### Steps to Reproduce

1.all the time
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

At best, this is a feature request, which should be submitted to our ideas page: https://ideas.obsproject.com/

Thank you!
