### ISSUE TITLE
Virtual Audio Cables no longer working in latest version

### ISSUE THREAD

**Issue by InanimateCrbnRod** [obsproject/obs-studio#11175]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/QzfGAYSWGKCpUEug

### Expected Behavior

I choose "audio output source" and set it to listen to a virtual audio cable or the "default" windows audio and it captures the sound from the virtual cable.

### Current Behavior

I don't remember which version I had before this, I think 29 or 30. At any rate, I always use Vb-Matrix Coconut to create virtual audio cables, then route those into OBS. Since the new update no sound comes through virtual cables in OBS. I can route those cables other places and they work, just not in OBS. Also using the "Default" output as a source doesn't work either. The only sources that work are manually specified legitimate windows audio devices. 

### Steps to Reproduce

1. add an audio output source
2. change it to a virtual audio cable. In my case I'm using VB-Matrix Coconut, which worked previously.
3. See if you receive sound in OBS from that cable

### Anything else we should know?

that's it. Thank you

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

However, as a note I would recommend reaching out to VB-Matrix Coconut support first.

Thank you!

**Comment by InanimateCrbnRod** [comment]
You can close this issue a complete reinstall of both program fixed it.
