### ISSUE TITLE
connecting and disconnecting

### ISSUE THREAD

**Issue by At-barbara** [obsproject/obs-studio#11245]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

I don't know

### OBS Studio Crash Log URL

I don't know

### Expected Behavior

From the beginning the live

### Current Behavior

Obs studio keeps connecting and disconnecting

### Steps to Reproduce

1.I don't know
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

In the future, when submitting an issue report, please properly fill out the template, and at the absolute minimum, provide a log. This is not actionable as presented.

Thank you!
