### ISSUE TITLE
Flickering in a video recorded via OBS (Game Capture) while Reshade enabled

### ISSUE THREAD

**Issue by Sopheus** [obsproject/obs-studio#11250]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://youtu.be/TMAFGtVURq8

### Expected Behavior

Game Capture recording is normal, without any flickering.

### Current Behavior

There is a flickering on recorded video that makes the whole recording hard to watch. I think it has something to do with the fact that OBS and ReShade both using hooks, hence leading to a conflict?

Here is an example of what I am talking about: https://youtu.be/TMAFGtVURq8

I have checked everywhere, it seems there was an option called "Attempt to fix synchronization for Direct3D 12", but it is not available in current version of the OBS.

So currently the only workaround is "Display Capture" instead of "Game Capture" mode.

### Steps to Reproduce

1. Record video via "Game Capture" with ReShade enabled.
2. Observe the issue in recorded video.

**Comment by Fenrirthviti** [comment]
ReShade is very likely incompatible with OBS due to the abusive way they inject themselves in to applications and replace directx functions with their own. If everything works fine without ReShade installed, please reach out to them for more assistance.

Additionally, no log file was provided so this is unactionable on our end anyway.
