### ISSUE TITLE
OBS Studio prints errors about the HD Pro Webcam C920: v4l2-input: /dev/video0: select timed out; /dev/video0: failed to log stat

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#11295]
### Operating System Info

Other

### Other OS

FreeBSD 14.1

### OBS Studio Version

30.2.3

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

OBS plays the webcam video but it prints these errors:
```
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 1920x1080
info: v4l2-input: Pixelformat: H264
info: v4l2-input: Linesize: 3840 Bytes
info: v4l2-input: Framerate: 30.00 fps
info: v4l2-input: /dev/video0: select timeout set to 166666 (5x frame periods)
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: ------------------------------------------------
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
```

### Steps to Reproduce

run-time

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Additionally, no log file or expected outcome was provided, so this is entirely unactionable.

Thank you!

**Comment by yurivict** [comment]
@Fenrirthviti 

How do I collect more log?

These are the only errors that I see:
```
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
```

Expected outcome is obviously "NO SUCH ERROR MESSAGES". Do I really have to type this in?

**Comment by Fenrirthviti** [comment]
Providing a link to a log file is a requirement of the template, as denoted by the red * and the fact it doesn't let you submit without entering something. Consciously choosing to ignore that an put `n/a` instead hinders a report as there is often important information in the log files, including system hardware setup, additional plugins that might be installed, etc.

And yes, when you are submitting a report to a project, ignoring the requested template responses sends a message, intentional or not, that "your process isn't worth my time, but look at this bug anyway." It's bad etiquette to submit a bug report with such limited information, and nothing actionable.

As you stated in the report, the camera is working fine, so what exactly is the problem here? Does the camera fail after a certain time? Is there a message expected from v4l2 that isn't printed here that is useful for some reason? As far as I can tell, something on v4l2's side failed to respond, so there's likely not going to be much here for us to fix in the first place, especially if it's just a failed log line as the error indicates rather than anything functional.

**Comment by kkartaltepe** [comment]
This is intentional. You are dropping frames and you the user should take action to increase the timeout in the source settings or accept the dropped frames. Since this is freebsd and these settings are tuned to c920's on linux, maybe you can improve the freebsd side to deliver frames in a timely manner like linux instead.
