### ISSUE TITLE
Browser source stops updating after a random amount of time

### ISSUE THREAD

**Issue by DidierMalenfant** [obsproject/obs-studio#11327]
### Operating System Info

Other

### Other OS

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/B3VBYQE3BCWjNCuR

### Expected Behavior

When using a browser source for a chatbot and comparing it to a Firefox window using the same URL, the chat messages should match in both windows.

### Current Behavior

They match up until a point where it looks like OBS stops updating the browser source, even though I can see the chat still updating in the Firefox window.

### Steps to Reproduce

1. Obtain a chat box URL from Streamlabs
2. Add a browser source to your scene with that URL
3. Open a Firefox window with the same URL
4. Compare both outputs as you type things in the chat.

**Comment by Fenrirthviti** [comment]
We do not maintain Streamlabs' products, please reach out to them for further assistance.

**Comment by Fenrirthviti** [comment]
Not necessarily, Firefox isn't really close to a comparison to the browser source in OBS. Chrome would be a better test, but even that isn't the same as the browser source in OBS itself. Streamlabs is better positioned to identify what is going on with their products, and why they are having issues in OBS. If they determine there to be an actual bug, they have lines of contact where they can inform us. It's extremely unlikely that there is a bug on our end that would need to be addressed, however.

If you are able to provide a reduced test case in a sample web page that can be shared to run locally. Otherwise there is too much of Streamlabs' service that will be effectively black box and impossible for us to determine what's going on.

They can.

**Comment by DidierMalenfant** [comment]
I open a ticket with stream labs and will report back.

**Comment by DidierMalenfant** [comment]
Further info, I seem to be able to repro the issue with Twitch alerts too. Those URLs don't come from StreamLabs but directly from Twitch.

Same symptoms. Browser source works, eventually stops updating correctly (sometimes after just a few seconds, sometimes more, can't figure out the rational there) until you refresh the cache on the browser source. Then OBS picks up the updates again until it doesn't.

So it could be an issue with my setup, a user error on my end or something to do with the way OBS deals with URL that update but I don't think it's limited to just StreamLabs.

Just trying to figure this out.

**Comment by Fenrirthviti** [comment]
I'd recommend using our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance. We don't use GitHub for troubleshooting, issues should be verified and reproducible before being submitted.

**Comment by DidierMalenfant** [comment]
https://obsproject.com/forum/threads/browser-source-stops-updating-after-a-while.180554/
