### ISSUE TITLE
Bring back system theme

### ISSUE THREAD

**Issue by MorsMortium** [obsproject/obs-studio#11342]
### Operating System Info

Other

### Other OS

Artix linux (based on Arch linux)

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.1

### OBS Studio Log URL

https://obsproject.com/logs/MGx3TBYb0Kf3Bksn

### Expected Behavior

That there is an option for system theme, like there was previously

### Current Behavior

The option for system theme got removed

### Steps to Reproduce

1. Open OBS
2. Click File
3. Click Settings
4. Click Appearance

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by MorsMortium** [comment]
I use foss, which discord isn't.
But anyway, this was not a support question but a bug report, as currently it's broken on linux (not following system theme)
Thank you!

**Comment by Fenrirthviti** [comment]
Discord is not the only option, you can use our forums as well if you want. This would also be a suggestion, which is not something we use GitHub issues for. We have an [ideas page](https://obsproject.com/) for suggestions.

In any event, this is intentional, and not a bug. You are welcome to make local changes and compile from source if you do not agree with the decision, but the tradeoffs for allowing it from a support and stability standpoint were not worth it for us.

Further context on the decision can be found here:  https://github.com/obsproject/obs-studio/pull/10719

**Comment by MorsMortium** [comment]
I know the bug was introduced intentionally.

**Comment by derrod** [comment]
This is not a bug but an intentional change, duplicate of #11342

**Comment by MorsMortium** [comment]
To the devs: Thank you!
