### ISSUE TITLE
pipewire-screen-capture-sources are not saved after restart

### ISSUE THREAD

**Issue by Daholli** [obsproject/obs-studio#11425]
### Operating System Info

Other

### Other OS

NixOs

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/OXzcS0N3Roicmndw

### Expected Behavior

When closing Obs and restarting it again, I expect my sources to be saved upon returning, but instead I have to reselect the sources from pipewire (without knowing which source I currently have to reselect)

### Current Behavior

Obs asks for monitor/window for each previously configured scene

### Steps to Reproduce

1. Open Obs in Hyprland
2. Configure Sources using the pipewire-screen-capture-source
3. Close Obs
4. Reopen Obs
5. -> Be asked to reselect the sources
...

**Comment by tytan652** [comment]
This is an issue on the portal implementation side if persistence not enabled by the user, OBS Studio always tries to restore the given token if available.

**Comment by Daholli** [comment]
Oh thanks! that is already very helpful, I will try to fix it then, I just found no information regarding that

**Comment by tiberium-v** [comment]
The portal is what give OBS the permission and information what to capture. Since you are on hyperland, you are using the wlr-portal who doesn't have the option to save the permission/session I think?  I recommend ask this in the hyperland community. IIRC, they are developing they own portal implementation. So support for that function has to come from there.

OBS self has no control over it.

**Comment by Daholli** [comment]
No I was just plain stupid, there is a little check mark that I had to click which would then make it work.... Feel so dumb for not seeing that even after multiple tries
