### ISSUE TITLE
macOS: Crash when selecting source associated with disconnected audio device

### ISSUE THREAD

**Issue by jcm93** [obsproject/obs-studio#11432]
### Operating System Info

macOS 14

### OBS Studio Version

31.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/8mw70o6ZVONr7cEf

### Expected Behavior

OBS on macOS should not crash just because an audio device was disconnected and a source existed for it.

### Current Behavior

OBS on macOS can and will crash if there is any source lurking that is associated with a disconnected audio device.

### Steps to Reproduce

1. Create an Audio Input Capture source associated with an audio device
2. Disconnect that device or otherwise render it unavailable to macOS
3. Select the source in OBS

### Anything else we should know?

* This issue has a "tell"; logs are spammed with a message similar to `[coreaudio_get_device_name] failed to get name: 560947818` repeatedly if there a source associated with a disconnected device
* Not specific to the OBS 31 beta. Probably has been an issue for a prolonged period
* Log is via a user in support channels

**Comment by jcm93** [comment]
Specific crash area (pardon IDE screenshot):

<img width="1840" alt="Screenshot 2024-10-21 at 9 30 08 PM" src="https://github.com/user-attachments/assets/0edbb631-3a78-421b-b9eb-d3b7ee3eb16a">

**Comment by PatTheMav** [comment]
Changing this line

https://github.com/obsproject/obs-studio/blob/e8968ba7152120129eddb8f78850819a01530a1b/plugins/mac-capture/mac-audio.c#L1010

into `if (ca != NULL && ca->au_initialized)` should fix the issue, as that boolean is set to `false` whenever we "uninitialise" a device because it's not available or was disconnected.

It would also be beneficial to remove the half-measure of only listening for a "device is not alive" event (and then desperately polling for it to be available again _somehow_) by adding a proper event handler for any device list changes, which would then iterate over the list of reported devices and thus can detect if the current device (identified by its `device_uid`) is available or not and initialise/unintialise the audio unit based on that.

I have a POC for that in a branch somewhere that I should finalise.. 😅

**Comment by RytoEX** [comment]
Is this crash new to 31?

**Comment by jcm93** [comment]
It's present in 30.2.3 (though not 30.0 in my testing).
