### ISSUE TITLE
"Whoops! OBS has crashed!"

### ISSUE THREAD

**Issue by Verity-Freedom** [obsproject/obs-studio#11455]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/qlVbdeCHPhbknJC5

### Expected Behavior

I want it to allow reboot PC normally without crash message.

### Current Behavior

So every time as I reboot the PC when OBS is running, it is saying it is crashed and doesn't allow me to reboot the PC, I need to close the message about crash manually. This is kinda frustrating and can cause bugs while something like driver installation is happening, when the PC should be rebooted instantly.

### Steps to Reproduce

1. Reboot the PC while OBS is running

### Anything else we should know?

Nothing, really.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

In the future, if you are reporting a crash it helps to include the crash report.

Thank you!
