### ISSUE TITLE
[Flatpak] Runtime org.kde.Platform branch 6.6 is end-of-life

### ISSUE THREAD

**Issue by Tiagoquix** [obsproject/obs-studio#11478]
### Operating System Info

Other

### Other OS

Linux

### OBS Studio Version

30.2.3

### OBS Studio Version (Other)

N/A

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

Use a more recent runtime.

### Current Behavior

Uses an old runtime.

### Steps to Reproduce

Type `flatpak update` in terminal.

Get the following message:
```
$ flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.obsproject.Studio

Nothing to do.
```

### Anything else we should know?

On [Flathub](https://flathub.org/apps/com.obsproject.Studio) details, it also says:
![image](https://github.com/user-attachments/assets/8d0c5163-0f38-4fdd-8eb1-0403b884faf4)

**Comment by derrod** [comment]
The runtime will be updated when we switch to a new Qt version.

**Comment by DarkSpir** [comment]
@derrod Excuse me but when will that be? I checked the discussion, the issue tickets and all ressources I could find to get a roadmap or anything that indicates that this is already in the pipeline. Your reply feels like "It will be when it will be, don't ask. <ticketclose>" and I hope I'm wrong with that.

**Comment by derrod** [comment]
Probably with the next release, but it could be postponed if there are more regressions in the new Qt version. There is no real timeline, but we generally try to update dependencies with each new (minor/major) release.

**Comment by zevlee** [comment]
Given that OBS 31.0.0 released On December 6, am I correct to assume that there are complications which prevent the flatpak version from being updated?

**Comment by secretmango** [comment]
Wait, OBS Flatpak is that outdated?

**Comment by derrod** [comment]
> Given that OBS 31.0.0 released on December 6, am I correct to assume that there are complications which prevent the flatpak version from being updated?

"Next Release" here is referering to the release after 31.0, which was already in beta/feature frozen at the time. But I'm not sure where we're at for 31.1, I don't believe we've tested Qt 6.8 yet.

**Comment by DarkSpir** [comment]
Then you should probably skip Qt 6.8 entirely and head straight over to 6.9, which is scheduled to be released on March 2025. Unless you have a commercial license (which none of us has), the community support ends with the next minor version and that is released every 6 months (see [here](https://wiki.qt.io/QtReleasing)).

I know this support and release cycle is far from ideal for an open source project to handle. But otherwise there will be tickets identical to this one in about 4 months from now saying that flatpak put Qt 6.8 is EoL and the maintainer should upgrade asap.

**Comment by Croydon** [comment]
Is there any non-closed issue that tracks progress on this topic, collects information about the problems why this hasn't happened yet etc?

**Comment by derrod** [comment]
> Is there any non-closed issue that tracks progress on this topic, collects information about the problems why this hasn't happened yet etc?

No, we usually don't have issues for dependency updates unless there is some critical reason it needs to be updated. This is just an overly dramatic warning in a package manager.

> It is somewhat confusing that this was closed, even more so, closed as "not planned" when it is apparently planned eventually.

Because GitHub only gives you "fixed" or "not planned" as options. This isn't a bug so it was closed, but closing it as "fixed" doesn't make sense, so the other option was used.

**Comment by DarkSpir** [comment]
Sorry, this is not "an overly dramatic warning in a package manager" but an issue, possibly an security issue. I just scrolled through the [release notes](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.7.0/release-note.md) of Qt 6.7.0 and saw at least two fixed memory leaks while scrolling by. There could be even more, I have not read through the 6.8 release notes yet. And to be honest: There should be no reason to do this, because you absolutely should keep your dependencies up to date.

Or would be using an out of support OpenSSL version for example also an overly dramatic warning in a package manager?

**Comment by Fenrirthviti** [comment]
We will update when we've verified the packages don't cause regressions.

Thank you.
