### ISSUE TITLE
Problem of blurred projection after using full screen

### ISSUE THREAD

**Issue by JMM935** [obsproject/obs-studio#11476]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

Slightly blurred image quality when projecting full screen to another computer's OBS client.

### OBS Studio Crash Log URL

Slightly blurred image quality when projecting full screen to another computer's OBS client.

### Expected Behavior

Slightly blurred image quality when projecting full screen to another computer's OBS client.

### Current Behavior

Slightly blurred image quality when projecting full screen to another computer's OBS client.

### Steps to Reproduce

1.Slightly blurred image quality when projecting full screen to another computer's OBS client.
2.
3.
...

### Anything else we should know?

Slightly blurred image quality when projecting full screen to another computer's OBS client.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

For future reference, ignoring the issue template will result in issues being closed anyway.

Thank you!
