### ISSUE TITLE
OBS crashing AMD driver

### ISSUE THREAD

**Issue by UnrealKaraulov** [obsproject/obs-studio#11536]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

steam obs default current version (I can't open OBS because it crash my hardware)

### OBS Studio Log URL

I can't run OBS it crash at load

### OBS Studio Crash Log URL

https://pastebin.com/KeCkFspH

### Expected Behavior

Start without crash AMD drivers

### Current Behavior

Crash AMD drivers (sometime even with PC poweroff)

### Steps to Reproduce

1. Download Steam
2. Install Steam
3. Login Steam
4. Install OBS
5. Run OBS
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

OBS runs in user space, and cannot be a direct cause of a driver or system-wide crash. Sounds like your PC is experiencing instability which should be addressed first.

Thank you!

**Comment by UnrealKaraulov** [comment]
@Fenrirthviti какие стркои нужно изменить что бы это являлось баг репортом? вроде бы похоже на https://github.com/obsproject/obs-studio/issues/11524 , почему там является баг репорт а мой запрос не является багрепортом?

**Comment by UnrealKaraulov** [comment]
После установки в настройках Steam, night builds, краши прекратились.
