### ISSUE TITLE
Game Capture Black Screen with Ubisoft Connect game: Tom Clancy's the Division 2

### ISSUE THREAD

**Issue by DADSBURNINONE** [obsproject/obs-studio#11662]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/releases/tag/31.0.0

### Expected Behavior

Game Capture to display game.

### Current Behavior

Game capture produces black screen when trying to capture Ubisoft Connect game: Tom Clancy's the Division 2.  I did try previous obs studio version 30.2.3 and it works fine. 

### Steps to Reproduce

1. Add game capture and try to capture specific window "Division 2". 
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

In the future, when reporting an issue log files are required for a reason.

Thank you!

**Comment by MattyFresh68** [comment]
Division 2 devs need to use an updated EAC module to be compatible with obs game capture hook signature in v31

**Comment by DADSBURNINONE** [comment]
Joel,

Yeah I'm not sure how to provide log files.

**Comment by GenesisFR** [comment]
It was fixed on the game side about 2-3 weeks ago.
