### ISSUE TITLE
Include luasocket with standard installation

### ISSUE THREAD

**Issue by tobi** [obsproject/obs-studio#2281]
It's fantastic that OBS ships with LuaJIT out of the box. 

Although I think its fair to say that its currently underutilized. I think the reason is pretty simple: the lua environment ships without support for IO and especially network sockets. It's possible to add this manually through FFI or through manually compiling luasocket (which is a pain on 64bit windows). The potential of LUA scripts is limited right now. 

Because of this, a lot of script authors try python, but that comes with its own installation complexity. 

## Expected Behavior
Include luasocket with the standard distribution of obs studio so that lua script authors can rely on its presence. 

I expect that this will shift more and more plugin dev towards lua because it works out of the box and now can acquire additional data from web and local services.

## Current Behavior
* Either hook through ffi into socket.dlls which is error prone
* Or hope that a python installation is present and working

## Additional information
http://w3.impa.br/~diego/software/luasocket/home.html

**Comment by DDRBoxman** [comment]
I'll leave some thoughts here from when I was looking into this a while back.

Scripts are executed on the OBS main thread. This means that say a network request will block OBS. Looking into Lua threading solutions ended up as a dead end because they try to hook in and control lua execution, while OBS is doing the same.

A few things that might work:
*  Build a threading solution into the OBS scripting system that can run tasks and then callback. 
*  I believe that we would have to write a version of luasockets ourself that understands the OBS execution model. I remember running into some issues with the native code in luasockets too.
*  Figure out how to make OBS play nice with how people expect Lua to work out of the box.

Like you said earlier I did some experiments with ffi and loading a custom native lua module that  used c++ thread to handle network tasks, probably not what most people want. This worked but was pretty terrible.

**Comment by tobi** [comment]
ok that's a good reason for why this isn't there. I think it would be fine to simply expose the async IO to lua in that case. Async code in lua is pretty straightforward because we have coroutines. 

It seems that this is the route that Robox went as well.

**Comment by Fenrirthviti** [comment]
Going to close this for now, as it's not exactly a bug and we are trying to keep the issues dedicated to repeatable bugs.

Discussed with the team, and we are open to the idea, but this will [need an rfc](https://github.com/obsproject/rfcs) for more discussion and to hash out the specifics.
