### ISSUE TITLE
Bug: Test (GDI+) Outline not applied to Innter 

### ISSUE THREAD

**Issue by zinthose** [obsproject/obs-studio#2415]
## Expected Behavior

The ID of fonts should also have the outline effect applied.
This typically only effect letters that are enclosed like 8, B etc.. 
While some others are not effected. Like: D, 0, Q
This appears to be an issue with smaller ID's?

## Current Behavior

The outline should also be applied inside the fonts.

## Steps to Reproduce

The Font used is the Rubik Black Regular font by google available at:
* [https://fonts.google.com/download?family=Rubik](https://fonts.google.com/download?family=Rubik)
* Outline is set to 20
Screen shot at: [https://imgur.com/a/AGjlgmp](https://imgur.com/a/AGjlgmp)

**Comment by Fenrirthviti** [comment]
Can you please fill out the template to provide more information on this, most importantly with replication steps and an explanation of the issue?

**Comment by zinthose** [comment]
Sorry I fat fingered the enter key when typing the title and immediately went back in to edit it.  I just wasn't fast enough to get it done before you seen it.

**Comment by kkartaltepe** [comment]
This is a bug in GDI+'s outlining/path generation so there is nothing we can do to fix it. There are a number of outline artifacts/glitches like this related to dots and overlapped characters in the GDI's outline drawing.

**Comment by kkartaltepe** [comment]
Actually reopening this. Its possible this might be solved by setting round endcaps depending on how GDI renders. It seems we dont set any which may lead to flat endcaps.

**Comment by onefreetv** [comment]
can some one help me , 'how to install PBS in google cloud vps'   
because these code does not work...
docker run -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc
sudo add-anstall ffmpeg
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt-get upgrade
sudo apt-get update
sudo apt-get install obs-studiopt-repository ppa:kirillshkrogalev/ffmpeg-next
sudo apt-get update && sudo apt-get install ffmpeg
sudo apt-get install ffmpeg
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt-get upgrade
sudo apt-get update
sudo apt-get install obs-studio

**Comment by nitinPaulGupta** [comment]
@zinthose Is this fixed?

**Comment by OldBaldGeek** [comment]
I just tried this with OBS 27.2.3 on Windows 10, using the variable font version of Rubik Black, and other fonts, and it seems to be fixed.

Here is with an Outline Size of 20 (the max). I don't get a choice of Rubik Black Regular, so I used Rubik Black Black.
![image](https://user-images.githubusercontent.com/31324355/136614955-0270e701-3c39-4d58-895c-e2ff6812e5b6.png)

Here is with an Outline Size of 4
![image](https://user-images.githubusercontent.com/31324355/136615082-8d62134a-8017-4261-822e-6c0da1e7d891.png)

**Comment by kkartaltepe** [comment]
Your top post shows the artifact in question. In the 8 9 0 the eyes should be fully red but due to the overlapping of the outlines they end up being unfilled to varying degrees. I actually dont think this is solvable with endcaps at least for this particular artifact, but if anyone wants to try and let us know.

**Comment by RytoEX** [comment]
The default font size of 256 with an outline size 20 works fine, and we generally recommend the default font size of 256 because it works best in the vast majority of cases. For us, this is a won't fix. If someone does figure out how to fix it, PRs are welcome.
