### ISSUE TITLE
rtmp: Build failure on Linux with older mbedtls

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-studio#2426]
## Expected Behavior
Build succeeds, or alternatively, fails at the configure stage (if mbedtls is a hard dependency now)

## Current Behavior
Piles of errors regarding MD5_Init and friends

## Steps to Reproduce
1. Update to the latest master branch
2. Ensure that mbedtls is not installed
3. Build
4. Install mbedtls from Debian Stable
5. Build

Steps 3 and 5 will both fail, but differently. If no mbedtls is installed, the errors relate to MD5_Init not being defined; if it's an older version, MD5_Init is okay, but expands to call on mbedtls_md5_starts_ret which does not exist.

## Additional information
When using mbedtls 2.4.2 from Debian Stretch (current oldstable and still supported), failures happen.

When using mbedtls 2.16.4 from Debian Unstable, all is well.

Not tested against 2.16.0 from Debian Buster (current stable) but will most likely work.

**Comment by RytoEX** [comment]
As far as I know, the mbedTLS version requirement is 2.7, per PR #1477:
> On Ubuntu 16.04 (Xenial), we have to build mbedTLS from source because
the version available from apt, mbedTLS 2.2.1, does not work with the
RTMPS implementation in OBS, which requires mbedTLS 2.7 at minimum. This
is due to the use of the function mbedtls_ssl_conf_dh_param_bin, which
was introduced in mbedTLS 2.7.

PR #2304 surmised that `mbedtls_md5_starts_ret` was introduced in mbedTLS 2.7 as well.

The Step 5 failure is expected, because Debian Stretch's version of mbedTLS still does not meet the necessary version requirement when building with mbedTLS.  I _think_ the consensus at the time was if older *nix distros did not have an up-to-date mbedTLS package available, they would have to build it from source, which was also the only way for us to build OBS with RTMPS/mbedTLS on AppVeyor CI on Ubuntu 16.04 at the time.

When PR #1360 added mbedTLS support, it was not added as a hard dependency.  However, after asking about this, it appears that SRT requires some kind of TLS/SSL (mbedTLS/OpenSSL/GnuTLS), so if you're building against FFmpeg libraries that have SRT support, you might also need one of those TLS/SSL libraries.  Hopefully @pkviet or @kkartaltepe can provide insight here.

You _can_ disable RTMPS support in the build with the WITH_RTMPS CMake flag.  Have you tried explicitly setting "WITH_RTMPS" to OFF?  Does the OBS build still fail with this set to OFF?  The default setting "AUTO" should still build OBS without RTMPS if mbedTLS cannot be found, but I don't think it accounts for finding an mbedTLS below the necessary version.

**Comment by kkartaltepe** [comment]
My personal opinion follows.

I dont think we should support any debian targets (except SID). They are too ancient and carry too much baggage and supporting them in upstream doesnt even make sense from a debian perspective. My recommendation has been to track the current ubuntu LTS (meaning once 20.04 is out 18.04 will be desupported). Which is purely out of pragmatism as we need a fairly up to date release to build automation on and we maintain supported packages for ubuntu.

If you are using debian stable/oldstable/anything that isnt SID you should stick with the packaged version of software to ensure a stable system. If you desire updates beyond backpatching security fixes to your software its likely that using debian stable was the wrong choice for your use case. Forcing compatibility on upstream with deprecated software makes everyone's life harder for the benefit of a tiny fraction of users who are using their system in a way that was unintended by the distributors.

And unless you can get debian obs-studio package maintainers to update obs packages in stable/oldstable/whatever I see no reason for us to maintain backwards compatibility. Because no one but a tiny fraction of debian's fraction of users will benefit from it, but our minimal linux support team will have to bear the load of supporting it.

**Comment by RytoEX** [comment]
@kkartaltepe 
I agree with almost everything you said above, though I have mixed feelings on dropping Ubuntu 18.04 immediately.  Personally, I think it'd be fine for us to support 18.04 for a little while after 20.04 releases (at least 6 months, at most 1 year after), though you and @Gol-D-Ace probably have better insight on that than I do.

I agree with everything else said with respect to Debian and its package maintenance, and that asking us to work around the packages doesn't make sense.  If you want to compile OBS git master HEAD, then you'll also have to compile some of the dependencies rather than relying on system packages, and that's out of scope for the support we can provide.

All of that being the case, I'm in favor of closing this issue unless there is a significant reason not to.

**Comment by Ndugutse** [comment]
Ok

**Comment by Rosuav** [comment]
I'm okay with the build failing, if this is a firm dependency. But dependencies should be checked for at the configure stage, rather than bombing out hard at a later stage. Can a check be added?

**Comment by Chiitoo** [comment]
The build is indeed broken also when building with '-DWITH_RTMPS="off"' (Mbed TLS 2.17.0).

**Comment by Chiitoo** [comment]
Bisecting was quicker than I thought: commit 86d3eb30 [1] is the first bad commit.

1. https://github.com/obsproject/obs-studio/commit/86d3eb30

**Comment by kkartaltepe** [comment]
Thanks for bisecting!

**Comment by notr1ch** [comment]
Please try changing https://github.com/obsproject/obs-studio/commit/baa559813c46df666f0208668ea63aa597f516e5#diff-1116df941969e1d5576d4771cff96507R2715

to `#if MBEDTLS_VERSION_NUMBER >= 0x02070000`

**Comment by notr1ch** [comment]
For building without mbedTLS, please try https://github.com/notr1ch/obs-studio/commit/5e866744e9d599cd84d092f161e51595ed5a5a11

**Comment by Chiitoo** [comment]
> For building without mbedTLS, please try [notr1ch@5e86674](https://github.com/notr1ch/obs-studio/commit/5e866744e9d599cd84d092f161e51595ed5a5a11)

Seems to work here.

Thanks!

**Comment by Rosuav** [comment]
Perfect! Confirming that this works (a) with no mbedtls, and (b) with an old mbedtls. So even though you're not supporting Debian Stable, it still works :) Thank you!

**Comment by notr1ch** [comment]
Thanks for the feedback!
