### ISSUE TITLE
projectobs.com vs obsproject.com VERY confusing

### ISSUE THREAD

**Issue by clemens-tolboom** [obsproject/obs-studio#2565]
Advising people to use OBS make them google and find two websites.

There are no crossreferences validating or disqualifying the other website.

## Expected Behavior

As https://obsproject.com is the real deal either redirect or takedown https://projectobs.com to make it a way better and less stressful start for new users.

## Steps to Reproduce

1. Visit https://obsproject.com
2. Compare with https://projectobs.com
3. Feel puzzled

**Comment by ElectronicWar** [comment]
projectobs.com is not affiliated with us in any way.

**Comment by clemens-tolboom** [comment]
Why are you closing this without replying to my concerns?

We should try to take that site down don't we?

**Comment by dodgepong** [comment]
Thanks for making us aware of the site. We will take it from here. In the meantime, this should not be on the Github, so we're keeping the issue closed.

**Comment by clemens-tolboom** [comment]
@dodgepong thanks for this better answer 👍

**Comment by OBSPlus** [comment]
Hello.

I'm the owner of the [ProjectOBS.com](https://ProjectOBS.com) website, and it's currently in the early stage of development.

I'm making it because the official website does not good enough for a lot of users who do not know English.
Also, the official website sometimes is not accessible in some countries because of their censorship laws and bugs in traffic filtering.

I have extensive experience in developing projects aimed at audiences with different languages and living in this kind of country, so I know how to make it good.

Also, I do have some ideas on how to improve the OBS itself, and I do plan to implement it in my fork.

If I will make a fork, I'm also will make a change to the name of the program to avoid confusion. Currently, I distribute official binaries.
Since OBS Studio is open source and licensed under the GNU General Public License v2, there is no reason for concern. Anyone can do whatever they want if it complies with the license.

I appreciate and respect the work of the team working on OBS Studio and will do my best to make good docs, taking into account the specifics of the different regions and distribute of OBS Studio for those who have difficulties with the official site.

**Comment by clemens-tolboom** [comment]
@OBSPlus thanks for your reply. Now we have a discussion :-)

It would be great to have a banner on your site making clear and linking to the official site.

IMHO the url is confusing (as I explained above). Maybe donate this URL to the official project?

> I'm making it because the official website is not good enough for a lot of users who do not know English.
Also, the official website sometimes is not accessible in some countries because of their censorship laws and bugs in traffic filtering.

I understand and feel sorry for those parts of the world being cut off from the rest :-(

Hope you succeed in these goals :-)

**Comment by notr1ch** [comment]
@OBSPlus The official website is translated into several languages already, eg the German and Russian options you list on your homepage are available at https://obsproject.com/de and https://obsproject.com/ru. If you want to help the project, please consider contributing updated translations to our Crowdin project so they can be used on the official site - creating a separate website for this seems very unnecessary.

Also as far as I can tell, our site does not appear to be blocked or censored in any countries, it even works from behind the Chinese firewall.

**Comment by SillyFreak** [comment]
@OBSPlus I was just told about OBS and found both websites. As you said, license-wise you're doing nothing wrong, trademark-wise it might be a different thing but IANAL and I have no stake so it's not something I care too much about.

However, one thing you should be aware of should be security concerns. A software such as OBS needs access to a lot of relatively low-level parts of a system and would be a good vehicle for malware. Even granting that both sites only distribute legitimate software, OBS users are trained to trust a less-than-unambiguously-official source for this software, which might make them susceptible to downloading malware in the future.

Linking to a GitHub repo that is external to your own efforts without a disclaimer of any kind makes your site look fishy. It reminds me of video streaming platforms that want to sell your their ads before forwarding you to content from a different source.

I'm not trying to allege any malicious intention from your part, but please be aware of the unintended consequences your choice of website and content can have. I understand that it's probably in your community-building interest to not link to the official site, but it definitely would be in the _community's_ interest to clarify your (non)relationship with OBS. I personally would be comforted by a note such as "this is a separately maintained presentation of OBS software; downloads point to the official repositories."

**Comment by clemens-tolboom** [comment]
@SillyFreak visiting both sites it is difficult to see the differences as the theming is same color (which it wasn't before). Seeing adds on the imposter site makes it even harder to believe good intent :-/

**Comment by dubstard** [comment]
Having two locations to download from is an un necessary attack vector.
The unofficial site could be used to build trust and SEO, and then theoretically the unofficial site could switch the links to laced binaries (it may never happen), but is unnecesarry risk.

And the monetarization part via ads is pretty dubious.

If you did the same to CocaCola for example, they would DMCA you immediately, just my 2c.

**Comment by alorimer** [comment]
@OBSPlus, this is a very confusing situation for new/potential users, and even long-time users like myself. I agree with @dubstard that there are a number of security and IP implications. These are not necessarily strict violations of any rules, but this type of naive replication of documentation and binaries is not considered good practice in the open source community. I don't mean to dismiss your concerns about the official documentation and the considerable effort you've put into your own site, but visitors to your site need to be aware that it is not the official site and doesn't necessarily provide accurate or up-to-date information.

Could you add a banner to the site explaining the situation and referring to the official site? Or rename the site to something like "OBS Studio Unofficial Documentation"? Even just an "about" page explaining the purpose of the site would be useful. At the moment, there is no way of knowing that it is unofficial, and it almost seems like you are trying to divert people away from the official site by imitating it.

**Comment by pakunjr** [comment]
It's now 2023 and...

Still named projectobs (no difference from obsproject which is the official one).
No link(s) to the official website at the landing page.

**Comment by dubstard** [comment]
`I appreciate and respect the work of the team working on OBS Studio and will do my best to make good docs, taking into account the specifics of the different regions and distribute of OBS Studio for those who have difficulties with the official site.`

To me it looks like that in the age where google translate can be used for localization that such a "service" is just a façade to have a redundant parasite location which nobody actually needs, under the presence of potential improvements, which never got delivered.

`Also, the official website sometimes is not accessible in some countries because of their censorship laws and bugs in traffic filtering.`
The website is accessible worldwide, including OFAC sanctioned countries, China, North Korean, ex Russian republics, tested with both automated tools and real world users.


`I'm making it because the official website is not good enough for a lot of users who do not know English.
Also, the official website sometimes is not accessible in some countries because of their censorship laws and bugs in traffic filtering.`

There are no issues with the official website whatsoever. This statement `the official website is not good enough for a lot of users` is flawed.

Seems like the extra copy is not malicious as in terms of malware or laced binaries, but serves as a method just to get revenue from advertisements, aka cyber squatting. Cyber squatting is so 1998 and should not be tolerated.

**Comment by Fenrirthviti** [comment]
As a note, we don't tolerate this, and have attempted to contact the owner to take down the website in the past, to which they have refused. 

We have other options we are pursuing, but they take time.

**Comment by OBSPlus** [comment]
Hello.

> As a note, we don't tolerate this, and have attempted to contact the owner to take down the website in the past, to which they have refused.

@Fenrirthviti, This is strange because no one has contacted me, and I haven't refused anyone. On the contrary, I'm open to dialogue and ready to discuss your position with you so that we can find common ground and resolve this question. Please provide detailed information about what exactly happened at hi@projectobs.com.

As I mentioned earlier, my intentions are purely constructive, and I adhere to the GNU General Public License v2.0, which allows for the distribution of this software. I have lived in countries where there are often serious issues with access to different websites, and I know firsthand how the existence of alternative sources can help people.

Thanks to everyone who has expressed their thoughts on this. I will change the domain to avoid any confusion because I want the site to be clearly perceived as a fan-made product and not to mislead anyone.

Hope you have a good day!

**Comment by Fenrirthviti** [comment]
The issue is not the GPL, but rather the blatant violation of our trademark. We have sent several notices to the contact form associated with the domain whois, and have never received a reply.

We would prefer you take down the site entirely, as none of the listed issues appear to be actually relevant any more, but at the very least using our trademarked name is not permitted.

**Comment by dubstard** [comment]
@Fenrirthviti you could try your luck with a trial with "brand protection" companies, such as PhishFort, WMC PhishFeed, NetCraft, Doppel or another similar company. They could and would likely assist with URDP / DMCA / Brand related takedown, even if there is no phishing or malware, given that the necessary documentation is provisioned.

**Comment by OBSPlus** [comment]
@Fenrirthviti Thank you very much for the information. I want to let you know that your messages weren't refused. Unfortunately, I never received these emails for some reason. I'm here, and I'm open to the discussion. I hope we'll find the best way to cooperate, and if there are indeed any trademark issues (which were never intended), then I'll fix them.

I'm waiting for more detailed information about it at hi@projectobs.com. Let's see what we can do together. My main priority is to be helpful to software users in accordance with open-source principles and the software's license.
