### ISSUE TITLE
[BUG] Hotkeys don't work when using Modifier Keys that have been remapped

### ISSUE THREAD

**Issue by jsit** [obsproject/obs-studio#2597]
Hotkeys don't work when using Modifier Keys that have been remapped

## Platform
Operating system and version: macOS 10.15.4
OBS Studio version: 24.0.6

## Expected Behavior
Hotkeys should work even if they include remapped Modifier Keys

## Current Behavior
Hotkeys don't work if they include remapped Modifier Keys

## Steps to Reproduce
1. Change the behavior of some Modifier Keys in the Keyboard section of System Preferences:
<img width="780" alt="Screen Shot 2020-03-29 at 3 11 35 PM" src="https://user-images.githubusercontent.com/643417/77858345-f1acee80-71d0-11ea-96e4-a9f8ee943b0c.png"> 

2. Create a hotkey using one or more of the remapped Modifier Keys

3. See that the hotkey doesn't work

**Comment by PatTheMav** [comment]
If I'm not mistaken, this could be due to the hotkey code querying the device (see `obs_hotkeys_platform_is_pressed` in `obs-cocoa.m`), whereas QT probably uses `NSKeyEvent` to get the key information from the OBS which is properly translated.

Might be fixed with a new iteration of the macOS hotkey code.

**Comment by gxalpha** [comment]
@jsit does this issue refer to hotkeys while OBS is in focus or out of focus?

**Comment by RytoEX** [comment]
Please confirm if this is still an issue with OBS Studio 28.0.2.

**Comment by PatTheMav** [comment]
Seems to have been fixed by the hotkey changes we merged in 28 - I switched ALT and CTRL and set CTRL+A as the recording hotkey (recognised as ALT+A). It was correctly set in the app and triggered with OBS in focus and without.

Switching the input setting back dutifully recognised the hotkey as ALT+A.
