### ISSUE TITLE
[BUG] Scene duplication is shallow ; this causes problems with groups

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#2600]
## Platform

Operating system and version: Lunux KUBuntu 18.04
OBS Studio version: 25.0.3 from ubuntu repo (obs-studio/bionic,now 25.0.3-0obsproject0~bionic amd64)

## Steps to Reproduce

1. Create a scene (say S) with a group (say G) containing a source (eg. a color source, say C).
2. Duplicate scene S into new scene S'.
3. In S', delete C.

## Expected Behavior

S should remain unchanged.

## Current Behavior

C is removed from S as well as from S'.

**Comment by WizardCM** [comment]
This is expected behaviour. Scene, Source and Group names are unique, and by default all copy functions (including "Duplicate scene") is purely shallow. That is, nothing within the group is duplicated. If two groups have the exact same name, they are references of each other, and modifying one group will modify them all.
