### ISSUE TITLE
[Crash] OBS will crash while renaming scene source whose related scene has been deleted.

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2602]
WIN-10 64
OBS.25.0.1
**100% reproduced**

**Steps:**
1. add scene1 and scene2
2. switch to scene2
3. add scene source into scene2 depond on scene1
4. delete scene1 from scene list
5. click F2 for entering renaming scene source
6. click enter to exit renaming
7. crashed 100%

In step (4), there are two ways to delete scene: del hotkey and menu.
Crash always reproduce by the first way. 

## Additional information
none

**Comment by wangshaohui1314** [comment]
![2020-03-30 22;13;33](https://user-images.githubusercontent.com/18413354/77922556-c8c15200-72d3-11ea-8716-b12dbcac16bd.gif)

**Comment by tielqt** [comment]
I've successfully duplicated this issue on my machine. 

The trick here seems to be using the context menu to remove the scene in question instead of the Delete key. Using the delete key removes the referenced scene, but right clicking and choosing "Remove" does not, allowing for the scene to be renamed and thus crash OBS.

Thanks for the report!

**Comment by Xaymar** [comment]
This crash happens with any action taken on the now deleted scene. Moving, properties, filters, etc will all freeze and then crash. Below is a crash log from a successful repro - the steps are the same except for the final step where I simply dragged the scene item down, which somehow added it to a nonexistent group.

[Crash 2020-04-01 11-53-22.txt](https://github.com/obsproject/obs-studio/files/4414306/Crash.2020-04-01.11-53-22.txt)

**Comment by skeletonbow** [comment]
I can repro this also.
