### ISSUE TITLE
[BUG] V4L2 capture does not list all known modes, fails to see MJPEG, H264

### ISSUE THREAD

**Issue by indrora** [obsproject/obs-studio#2608]
## Platform

Operating system and version: Fedora 31 KDE Neon
OBS Studio version: OBS Studio - 25.0.1 (linux)

## Expected Behavior

V4L2 capture should show all modes the V4L2 device has.

## Current Behavior

V4L2 capture only shows YUV and emulated modes.

## Steps to Reproduce

1. Have a camera that supports H264/MJPEG video modes
2. Add a V4L2 capture to a scene
3. Attempt to set MJPEG or H264 video mode

## Additional information

```
$ uname -a
Linux ganymede.atdot.xyz 5.5.11-200.fc31.x86_64 #1 SMP Mon Mar 23 17:32:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ v4l2-ctl --list-formats-ext -d /dev/video1
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'MJPG' (Motion-JPEG, compressed)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 1920x1080
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 1280x720
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x360
                        Interval: Discrete 0.033s (30.000 fps)
        [1]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x360
                        Interval: Discrete 0.033s (30.000 fps)
        [2]: 'H264' (H.264, compressed)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.042s (24.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                Size: Discrete 1920x1080
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.042s (24.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                Size: Discrete 1280x720
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.042s (24.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                Size: Discrete 640x360
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.042s (24.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)

```

V4L2 testbench says MJPEG 1920x1080

![image](https://user-images.githubusercontent.com/470584/78091333-5c9d2780-7381-11ea-9e62-16256a5fb0ee.png)

Log: https://obsproject.com/logs/PsCky8zuLxKwt4TC

**Comment by kkartaltepe** [comment]
Not a bug, compressed formats are unsupported at this time.

**Comment by emaste** [comment]
Related issue in old bug tracker: https://obsproject.com/mantis/view.php?id=321

Note that formats listed as (Emulated) are converted by libv4l2 from some other format which could be mjpeg or h.264.

**Comment by kkartaltepe** [comment]
Well Checking with usbtop it appears that is the case. Thanks for following up.

**Comment by indrora** [comment]
I don't care that it's not being decoded by OBS. I care for a higher video resolution and better framerate. 

Interestingly, it works Just Fine :tm: on my Windows machine: I pick MJPEG (which for my device has no perceptible lag, unlike H264) and I continue happily. 

I care that I can figure out what input is what. Multiple other V4L frontends, including the "test if V4L2 can shove you pixels" demos will happily display the decoded pixel stream that V4L2 produces called "H264" or "Motion-JPEG" and they aren't loading libx264 to decode the stream.

**Comment by emaste** [comment]
@indrora you should have some (Emulated) formats that will give you high resolution and framerate.

A Logitech C920 attached to my FreeBSD system gives me a choice of:
YUYV 4:2:2
BGR3 (Emulated)
YU12 (Emulated)
YV12 (Emulated)

YUYV 4:2:2 is native uncompressed video from the webcam and when I chose that format I can do 1920x1080 at 5 fps through 800x448 at 30 fps and various combinations in between. Choosing BGR3 (Emulated) lets me do 1920x1080 at 30 fps, and is converted from the webcam's MJPEG by libv4l2 before data gets to obs.

It is unfortunate that libv4l2 is unable to report the original format (so that obs could report "BGR3 (Emulated from MJPEG)" for example). It also does not provide a way (as far as I know) to select which source format is used, e.g., to allow obs to present a choice of "BGR3 (Emulated from MJPEG)" and "BGR3 (Emulated from h.264)". There's no ambiguity for me though because I have only one compressed format (MJPEG) available from my webcam.

**Comment by indrora** [comment]
The issue is that OBS doesn't expose what the V4L2 API says. Even if it's
getting an "emulated" colorspace, you can't say the V4L2 API doesn't have
the information since it does.

**Comment by emaste** [comment]
It's not just an emulated colorspace, it's the entire data stream that's emulated.

In the drop-down OBS is listing all of the v4l sources it can consume; since it can't sink MJPEG data it's not listed as an option. If you look at the log you'll see that it detected the additional formats but does not make them available (because it cannot handle them) - on my machine I see:

```
15:20:01.033: v4l2-input: Pixelformat: YUYV 4:2:2 (available)
15:20:01.033: v4l2-input: Pixelformat: H.264 (unavailable)
15:20:01.033: v4l2-input: Pixelformat: Motion-JPEG (unavailable)
15:20:01.033: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)
15:20:01.033: v4l2-input: Pixelformat: BGR3 (Emulated) (available)
15:20:01.033: v4l2-input: Pixelformat: YU12 (Emulated) (available)
15:20:01.033: v4l2-input: Pixelformat: YV12 (Emulated) (available)
```

The missing information is not a v4l2 issue it's libv4l2; the "Emulated" entries are synthesized by libv4l2 but it has no way to indicate what the original source was and just returns the emulated format with a `V4L2_FMT_FLAG_EMULATED` flag set.

**Comment by dendy** [comment]
> Not a bug, compressed formats are unsupported at this time.

Reply above confirms that this is known issue and need to be eventually supported. But then issue is closed. I am confused. You might have no time to work on it at the moment, but that does not mean that it should not be fixed.

I am trying to use HDMI capture device on Linux with OBS via Emulated formats and they are unstable. Framerate is uneven, lot of frame drops, picture with tearing. On Windows/Mac with MJPEG format picture is solid and framerate is stable 60.

As far as I understand from this thread is a lack of implementation in OBS itself so support MJPEG/H.264 streams. Why Windows/Mac supports MJPEG, when Linux does not? Is that because of the missing packages in the OS, like ffmpeg or gstreamer?

**Comment by altsalt** [comment]
Perhaps it is due to the title indicator as a bug. Any reason not to re-open and change the title/framing to a feature request? Or would opening a separate issue make sense?

**Comment by dendy** [comment]
I would vote for reopening this issue. I am new to OBS, but so far this looks to me like a critical missing feature.

Lets discuss the plan how this could be implemented. I saw a thread in Internet that somebody did attempt to fix this, will be no surprise if people made it work already. Could OBS contributors explain what exactly is blocking this?

**Comment by RytoEX** [comment]
> 
> 
> Perhaps it is due to the title indicator as a bug. Any reason not to re-open and change the title/framing to a feature request? Or would opening a separate issue make sense?

> I would vote for reopening this issue.

We do not track feature requests on GitHub.  Any feature requests submitted as a GitHub Issue will be closed.  Feature Requests can be submitted here:  https://ideas.obsproject.com/

Pull requests to add functionality or features are welcome.

This will remain closed per @kkartaltepe 's [comment above](https://github.com/obsproject/obs-studio/issues/2608#issuecomment-606988089), unless they revise their conclusion.

**Comment by dendy** [comment]
Well, this looks like a bug to me, or a known issue if you want. This is not a new idea to discuss and speculate about, because it is already implemented and works fine on other platforms. I believe there are no objections to make these formats work on Linux. As for the suggestion... My only suggestion is to fix this "not a bug" (-:

Per my understanding the problem is in technical limitation, would be good to get input from code authors what are our options to proceed. I don't even mind to dive into the code and do it myself if needed. As long as this effort will not be wasted.

**Comment by indrora** [comment]
This isn't a feature request, unless the definition of "feature request" is now "work the same between two OSs". 

It works on windows. I see all the streams, even badly behaved ones. 


When **other** tools that use v4l that do not necessarily themselves do the decoding of pixels handle it fine, that's a bug. V4L happily handles the data flow and other tools deal with it fine. OBS, by contrast, doesn't even show the existence of these streams.

**Comment by dendy** [comment]
I see @ggodlewski already added MJPEG format some time ago: https://github.com/ggodlewski/obs-studio/commits?author=ggodlewski

**Comment by kkartaltepe** [comment]
https://github.com/obsproject/obs-studio/pull/1835 was proposed and retracted because, perhaps unsurprisingly, emulated formats worked well enough.

> This isn't a feature request, unless the definition of "feature request" is now "work the same between two OSs".

Yes adding functionality is a feature request. Our goal is to have the same functionality across all platforms, that does not make it a bug for there to be differing functionality between platforms depending on platform features and available developers.

> As far as I understand from this thread is a lack of implementation in OBS itself so support MJPEG/H.264 streams. Why Windows/Mac supports MJPEG, when Linux does not? Is that because of the missing packages in the OS, like ffmpeg or gstreamer?

Id recommending reading the code you if you are not sure how this works on all platforms. Perhaps it will inspire you to make a PR with the functionality you find critical to your workflows.

**Comment by dendy** [comment]
> #1835 was proposed and retracted because, perhaps unsurprisingly, emulated formats worked well enough.

Except that they do not work well enough.

The only discussion I see by that link is the comment of the patch author itself:

> Damn, after few hours of coding I discovered that emulated formats have fps that I need.
> Well, maybe I'll use this fork to handle h264 and get better quality.

He got his 30 FPS with emulated formats, then happily closed the ticket. In my case I am periodically getting 60 FPS with tearing and constant frame drops. While with MJPEG on Windows and Mac I have no performance nor image quality issues.

> Id recommending reading the code you if you are not sure how this works on all platforms. Perhaps it will inspire you to make a PR with the functionality you find critical to your workflows.

My workflows is not any different to other people: capture HDMI input on Linux in 1080@60 without frame drops and image artifacts.

You would save everyone's time in this chat be quickly explaining why implementation varies on different platforms. I assume because on Windows/Mac OBS is using some platform dependent libraries to process MJPEG. In patch proposed by @ggodlewski he implemented decoding with avcodec. Since OBS is already using ffmpeg I see no obstacles to have that implementation merged in some form.

Btw, what PR means?

**Comment by altsalt** [comment]
PR is Pull Request. The suggestion is to read the code and either 1) implement it yourself, in such a way that it won't get rejected, or 2) realize that Linux implements things in such a way that attempting to bring in this functionality will just lead to madness.

**Comment by RytoEX** [comment]
> This isn't a feature request, unless the definition of "feature request" is now "work the same between two OSs".
> 
> It works on windows. I see all the streams, even badly behaved ones.

I would consider a request for feature parity to be a feature request.  Windows, macOS, and Linux all use completely different plugins and backends for video capture devices.  While we strive for as much feature parity as possible, a missing feature/functionality on one OS in a completely separate plugin that provides the same utility (capturing video data from device) is not a bug.  For example, we had feature requests for browser source functionality on macOS and Linux to attain feature parity with Windows (see https://ideas.obsproject.com/posts/913/add-support-for-linux-in-obs-browser and https://ideas.obsproject.com/posts/979/linux-browser-support).

On the subject of the different implementations of ingesting video capture devices, on Windows, we use [win-dshow](https://github.com/obsproject/obs-studio/tree/master/plugins/win-dshow), which in turn [uses FFmpeg for MJPEG](https://github.com/obsproject/obs-studio/pull/1930) or DirectShow for anything else.  On macOS, we use [mac-avcapture](https://github.com/obsproject/obs-studio/tree/master/plugins/mac-avcapture).  On Linux, we use [linux-v4l2](https://github.com/obsproject/obs-studio/tree/master/plugins/linux-v4l2).  I am not familiar enough with the macOS or Linux device capture plugins to describe their internals.

> Btw, what PR means?
PR is Pull Request.
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

Pull Requests (PRs) are welcome to address this lack of feature parity between platforms.  Debating on this GitHub Issue about how we manage our Issue tracker is not productive.  If you have questions about how one might implement these changes, you are welcome to ask in our #development channel on our Discord.

**Comment by dendy** [comment]
Thanks, I am familiar with pull requests, just don't use such abbreviations on a daily basis.

> implement it yourself, in such a way that it won't get rejected

I see that original patch was not rejected, instead author just wanted 30 FPS here and now, so he closed the ticket as soon as found out about emulated formats. The patch still worth to be ported, it was 2 years ago after all, could require some cleanup and refactoring.

> on Windows, we use win-dshow, which in turn uses FFmpeg for MJPEG or DirectShow for anything else. On macOS, we use mac-avcapture

Thanks for explanation, so it is platform dependent implementation for capturing/decoding the stream. So the issue is in missing decoder and reading the proposed patch I see two implementations: imagemagick and avcodec, mutually exclusive and selected and build time. Didn't try it myself, but it looks straightforward, also with ffmpeg it does not add new dependencies to the OBS.

I wonder why this was not implemented from the very beginning. If there are no objections then lets proceed with porting. Probably ffmpeg should be picked as an only solution. This should also work for decoding h264 streams as is since implementation is using avformat for demuxing stream and resolving codec.

**Comment by RytoEX** [comment]
> I wonder why this was not implemented from the very beginning.

Jim, the project's lead developer and maintainer, primarily develops on Windows.  By my last recollection, most of our regular contributors run Windows, followed by macOS, and then Linux.  We as a project largely rely on Linux users to submit patches in the form of Pull Requests (PRs) to add functionality that they would like to see added to the project.  Of course, Jim still has the final call on what gets merged into the project, but a Pull Request is a place to start.

**Comment by dendy** [comment]
I don't mind to update the patch and create pull request, have plenty experience with ffmpeg coding. My concern about why this code is not in the mainline for so long is because maybe there is a major objection to not proceed with proposed solution. And if so I would want to hear about that in advance to avoid wasting time.

How could we summon this Jim guy into the chat to give us green light to proceed?

**Comment by RytoEX** [comment]
> 
> 
> I don't mind to update the patch and create pull request, have plenty experience with ffmpeg coding. My concern about why this code is not in the mainline for so long is because maybe there is a major objection to not proceed with proposed solution. And if so I would want to hear about that in advance to avoid wasting time.
> 
> How could we summon this Jim guy into the chat to give us green light to proceed?

A PR was submitted and then closed by the author.  We don't typically go through closed PRs to see if they should have been merged.  As I previously explained most of our regular contributors don't operate on Linux, and presumably the ones who do haven't needed this feature themselves.  That's about it as to "why".  It has nothing to do with any supposed objection to the previously mentioned PR.

We're in the middle of a Release Candidate (RC) phase right now for OBS Studio 27.  Jim has plenty on his plate as it is, and we wouldn't get around to reviewing or merging a PR any time soon as all of our attention is focused on fixing regressions and bugs introduced in code changes tagged for OBS Studio 27.

I think it's better if you just proceed to work on submitting a PR, and we can discuss the merits of the code there rather than here.  If this were a major feature change, I'd suggest going through the RFC process, but that's really for significant changes, additions, or removals.

**Comment by dendy** [comment]
That is a good input, thanks! That is all I need to know at this point. I will edit the proposed patch then to leave only ffmpeg implementation, ensure it follows OBS coding guidelines, etc. Then create separate PR to discuss.

**Comment by altsalt** [comment]
Thanks @dendy ! Please leave a message here when there is something to review.

**Comment by dendy** [comment]
Will do my best (-;

**Comment by RytoEX** [comment]
> 
> 
> Thanks @dendy ! Please leave a message here when there is something to review.

I would prefer if they just tag you by username in the PR message.  Posting here also notifies all project members, so we're just creating more notifications at this point.

**Comment by ggodlewski** [comment]
Honestly I don't remember why this PR was closed. Probably I thought it was redundant and equivalent to emulated mode (which I discovered afterwards). My changes was pretty trivial so you can go ahead and port them easily.

**Comment by dendy** [comment]
Already did, there were few conflicts, but MJPEG via ffmpeg works as expected, performance is great. Some optimizations would be good to implement though, like avoid recreating AVFormatContext and looking for codec at each frame. Just jump straight to send_packet/receive_frame. I will spend some time on the code to optimize it and will notify everyone involved.

Good job btw!

**Comment by altsalt** [comment]
@RytoEX I understand and appreciate that, though there are a number of folks who have been watching this issue for a year hoping for movement, and they may not all be participating in the conversation. Figured it is worth the extra ping on an already noisy to the project members closed issue hehe.
