### ISSUE TITLE
[BUG] Show/hide behaviour in studio mode inconsistent re groups

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#2626]
## Platform

Operating system and version: KUbuntu 18.04
OBS Studio version: 25.0.3 from ubuntu repo

## Steps to Reproduce

1. Create a scene S. Within it, create a color source C1 and a group G. Within G, create a color source (different color) C2.
2. Activate Studio mode
3. Switch visibility of C1 and C2 alternatively.

## Expected Behavior

I would expect visibility changes to be reflected in the program in a consistent manner.
## Current Behavior

Visibility changes of C1 are reflected in the programme only when a transition is made.
Visibility changes of C2 are reflected immediately.

## Additional information
Maybe, like #2600, this is intended by the authors of OBS, but then, like #2600, it is undocumented ; in fact the Quickstart Guide, the Overview Guide and the Sources Guide do not contain a single instance of the word "Group".

**Comment by WizardCM** [comment]
This is not a bug per-se, just a side effect of how Studio Mode is configured by default, and how it wasn't originally designed with groups in mind.

![image](https://user-images.githubusercontent.com/941350/78338405-78e9d000-75de-11ea-967f-6488b4973ddf.png)

If you click the gear icon in the middle, you'll notice "Duplicate Scene" is enabled, but "Duplicate Sources" is not. This means that things like transformation of sources in the scene happen independently from Studio mode (as you're configuring the scene, not the source), but as Sources aren't duplicated (a group is also considered a source), modifying the contents of the group/source are done directly on the group/source, rather than as part of the scene. The same would happen if you modified a URL of a browser source, for example.

To solve this, simply enable "Duplicate Sources". You can hover over the two options to learn more about what they do.

**Comment by ysalmon** [comment]
It is also strange that these parameters do not appear in the main Parameters dialog, under General > Studio mode or in Advanced.

Introducing an option to duplicate Groups only would be interesting, since if I understand correctly duplicating all sources has drawbacks and may even not completely work.
