### ISSUE TITLE
[WEBSITE SUGGESTION] Please add FreeBSD to the list of platforms where OBS is available

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2629]
## Platform
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.3

## Expected Behavior
Please add FreeBSD (https://www.freebsd.org/) to the list of platforms where OBS Studio runs: https://obsproject.com/

The FreeBSD port has been available from ```2015-05-03``` and is currently at the version ```25.0.3```: https://www.freshports.org/multimedia/obs-studio/

It runs well on FreeBSD, and I've periodically heard from users who reported that they use ```OBS Studio``` on ```FreeBSD``` and it works fine for them.

You can use one of these icons: https://imgbin.com/png/MjHiA0AZ/computer-icons-freebsd-portable-network-graphics-scalable-graphics-png , https://www.hiclipart.com/free-transparent-background-png-clipart-mwwsa

## Installation instructions on FreeBSD
The recommended way: Install from a package:
> pkg install obs-studio

Users can also build and install OBS Studio from a port (this is much slower):
> cd /usr/ports/multimedia/obs-studio && make install clean

Thank you!

Yuri (maintainer of the port ```multimedia/obs-studio```)

**Comment by Fenrirthviti** [comment]
I've edited the post, I misspoke. It's just the install page, not the Linux install page.

Either way, it's not a supported platform as none of the development team uses or has any interest in using FreeBSD.

**Comment by yurivict** [comment]
> Either way, it's not a supported platform as none of the development team uses or has any interest in using FreeBSD.

Ok. I should probably lose interest in OBS Studio too then.

**Comment by kkartaltepe** [comment]
Please dont take it the wrong way. We have no active contributors from the BSD community, so it would be disingenuous of us to claim we supported any BSD. We are always happy to review patches for compatibility and so far that is enough that OBS appears to mostly work on BSD.

Not being a BSD user I imagine most would assume much of the software on linux will run on bsd via packaging and porting efforts, and they would likely check that instead of assuming it being missing from our website means its completely unavailable to them.

So while I understand the concern to advertise its availability on the website, if a user were to search "obs-studio bsd" in linux they are helpfully directed to the install instructions for FreeBSD already. And since we dont have anyone able to provide timely testing and bugfixing on BSD platforms, i don't think this is really a big discoverability concern.
