### ISSUE TITLE
[BUG] Sound Multiplication on Several Scenes with the Same Sound within One Scene

### ISSUE THREAD

**Issue by DarkR** [obsproject/obs-studio#2871]
## Platform

Operating system and version: Win 10 Pro
OBS Studio version: 25.0.8

## Expected Behavior

Both stream sound and same monitoring sound should be the same.
1. Same Audio Sources should be enumerated in Audio Mixer for proper monitor controll.
OR
2. Same Audio Sources shouldn't be mixed and multiplied with each other.

## Current Behavior

The sound of the stream become much louder and can clip in a scene with several scene sources with the same Audio Input Capture Source in them. So these same audio sources just miltiplies by the factor of scenes count. However main monitoring doesn't show any problems. Is it norm behavior?

## Steps to Reproduce

1. Create the first scene with Audio Input Capture.
2. Create the second scene with the same Audio Input Capture (Reference).
3. Put these scenes in one main scene.
4. Record and switch between scenes.
Here is an example: https://youtu.be/dJ9-JXN945s

## Additional information

Please fix this issue. I'll make a donation for that =)

**Comment by WizardCM** [comment]
Do you have monitoring enabled for all of the scene items, or just for one of them?

I would say in terms of actual output, this is by design.

**Comment by rjhelms** [comment]
Am experiencing this same issue.

Part of the issue here is that the audio source goes to the stream multiple times, but only shows up in the mixer once. This is confusing as it seems like there's a volume change between scenes that isn't reflected in the UI.

This behaviour can make setting up a scene hierarchy difficult. Consider a case with a "display" scene, a "camera" scene, and a "picture-in-picture" scene, and want the same audio capture device desired in all three.

The obvious way to set this up is with the audio capture device in both the "display" and "camera" scenes, with the "picture-in-picture" scene just being a combination of those two. However, with the current behaviour that will result in a significant volume difference between the PIP scene and the other two.

**Comment by RytoEX** [comment]
As [mentioned above](https://github.com/obsproject/obs-studio/issues/2871#issuecomment-680406891), this is working as designed. That is not to say that we would not consider patches/PRs to change the behavior to something possibly more intuitive, but this is working as designed.

**Comment by datamattsson** [comment]
This has nothing to do with nesting scenes. If you add multiple crops on the same AV device in the same scene the exact same issue crops up.
