### ISSUE TITLE
[BUG] Last frame of media source flashes before starting video playback

### ISSUE THREAD

**Issue by guusguusguus** [obsproject/obs-studio#2906]
### Platform

Operating system and version: Windows 10, Pro 64-bit 
OBS Studio version: 25.0.8

### Expected Behavior

Play video starting with first frame

### Current Behavior

First plays last frame and then starts playing from first frame

### Steps to Reproduce

    Add 'Media source'
    Select a local video file (tested with quicktime and transparency and also h264 mp4) 
    Configure playback with the following settings:
     [ ] loop
     [x]  restart playback when source becomes active
     [x] or [ ] use hardware enc..
     [ ] show noth...
     [x] or [ ] close file when in...
    
     Switch between scenes and the problem appears most of the time, problem is most consistent around lower framerates (25 fps) bu still noticeable around higher framerates (50 fps)

### Additional information

I have a media source with a quicktime video with alpha enabled. When i start the scene with this media source it first shows the last frame of the video and then starts playing the video from the first frame. I have tested it with exporting the video with the last frame fully transparent and this solves the issue but it makes it impossible to end the video on the last frame.

i have also tested it without using transparency (a h264 mp4 file) and it has the same problem 

problem persists on older versions (have tested it al the way back to version 16)

I have also been testing with framerates and the problem was most persistent with lower framerates (around 25 fps) and less persistent with higher framerates (around 50 fps) but the problem never really disappeared. the source material for the test was 25 fps

i started a post on the forum:
https://obsproject.com/forum/threads/last-frame-of-media-source-flashes-before-starting-video-playback.121882/

somebody confirms that the problem is also on the linux versions

i have been using the windows version (32 and 64 bit versions)

this is the output of the log file:

[2020-05-10 00-55-14.txt](https://github.com/obsproject/obs-studio/files/4605414/2020-05-10.00-55-14.txt)

**Comment by RytoEX** [comment]
Please don't delete the issue template.  Please edit your issue to use the template.

**Comment by therentabrain** [comment]
Workaround fwiw:  I had this problem when going from one video file scene to another.  I was able to avoid the flash by adding a full black screen jpg source under the first video.  I also changed the first video from internal player to VLC.   The second one is the internal player.  I don't even remember what inspired this idea, or which one worked, but I hope something here helps.

**Comment by chamberlago** [comment]
I seem to be having this issue again with 26.1.1

**Comment by tdp4** [comment]
I can confirm this is also happening to me on 26.1.1.

**Comment by SimonGZ** [comment]
Noting that this continues to be a problem in OBS 27.2.1 on Mac. This old forum post does a really nice job of visualizing the issue: https://obsproject.com/forum/threads/media-source-rendering-the-last-frame-at-the-beginning.110180/

**Comment by therentabrain** [comment]
I don't even understand my own workaround above.
The one I use now is to put a very short black screen video file as the top item in the scene.  When I switch to the scene, it plays the black frames on top and then that video stops, letting the thing underneath show through.

**Comment by DrewSunn** [comment]
Problem persists on 28.0.1

**Comment by tomica00** [comment]
Problem persists on 29.1.3
It's really annoying.

**Comment by 1030** [comment]
Problem still persists in 2025. I have many projects halted due to this, any help would be appreciated. How do we escalate?

**Comment by therentabrain** [comment]
If I were still dealing with this, here's what I'd try as workaround now:
use the Advanced Scene Switcher extension plugin
Things I'd try...
Macro 1:
On scene change, reset all media players to no media (empty)

Macro 2:
On scene change, if the new scene is the one that should be playing media, then set up the media and begin playing

If that doesn't work, then you could also put a cover image, or even a text box with a solid background, over the video and use Advanced Scene Switcher to turn it visible in macro 1, and hide it after 100 milliseconds or something in macro 2.

And a third idea:
Would it hide the trouble frame if you set up a 500ms fade-in as the "Show" transition for the video control?  Then instead of having a cover-up object, you could tell Macro 2 to make the video itself appear, and perhaps the fade-in would hide the problem.

Oh here's a variation:
Do #3 using a very short blank solid video as a stinger.  The advantage here is that it can pop in, rather than fade in, and the audio won't be affected.  I think #3 might cause the audio to fade in.

I haven't had to deal with this issue in a while but I thought these might be good ideas. :)

**Comment by tomica00** [comment]
I'm still using 29.1.3 but now the problem seems to have resolved itself. :S Maybe the problem was with Windows, and after an update it started working normally. I don't know.

On the stinger idea, I don't know if that would work, since a stinger is also just a cut with an overlay.
If that doesn't work, maybe try a custom Luma Wipe (there's a way to add custom wipe PNGs, see [here](https://www.reddit.com/r/Twitch/comments/6842z3/guide_how_to_add_custom_luma_wipes_in_obs_studio/)), but use a blank grey image. That will look like a cut with a small delay, but it should trigger the playout at the very beginning.

**Comment by SimonGZ** [comment]
I'm on macOS with OBS 31.0.1 and the problem remains.

I just tried some of @therentabrain's proposed workarounds (thank you for typing them out). Using Advanced Scene Switcher and setting it to blank out the file path and hide the scene item visibility, then restoring the scene item visibility and source settings does help but it's not a great solution for me. It removes the most obvious part of the painful flicker where you see the last frame of the media, but there's still a flicker as the video is now loaded in after a slightly longer delay. And of course there's now a lot of setup required in advanced scene switcher. 

Thinking through this problem, I think what's really desired here is that when returning to a scene with a media source set to restart after played (but not set to loop), OBS should have the first frame of the media source preloaded and ready to go, rather than the last frame or no frames.

**Comment by Poodmund** [comment]
I've had a bash at resolving this and it seems to be working in my debug build. I have absolutely no idea on the ramifications of what I've done however, so anyone who could review would be greatly appreciated: https://github.com/Poodmund/obs-studio/commit/4986749ff5b693fc21d24d504b4ec2c6cf109750.

**Comment by tomica00** [comment]
Hi! I'm having trouble building this. I followed the build instructions on
obsproject git, but after cmake --preset windows-x64 I get this:

Preset CMake variables:

  ENABLE_BROWSER:BOOL="TRUE"
  GPU_PRIORITY_VAL:STRING=""
  RESTREAM_CLIENTID:STRING=""
  RESTREAM_HASH:STRING=""
  TWITCH_CLIENTID:STRING=""
  TWITCH_HASH:STRING=""
  VIRTUALCAM_GUID:STRING="A3FCE0F5-3493-419F-958A-ABA1250EC20B"
  YOUTUBE_CLIENTID:STRING=""
  YOUTUBE_CLIENTID_HASH:STRING=""
  YOUTUBE_SECRET:STRING=""
  YOUTUBE_SECRET_HASH:STRING=""

CMake Error at cmake/common/versionconfig.cmake:49 (list):
  list index: 1 out of range (-1, 0)
Call Stack (most recent call first):
  cmake/common/bootstrap.cmake:60 (include)
  CMakeLists.txt:3 (include)


CMake Error at cmake/common/versionconfig.cmake:50 (list):
  list index: 2 out of range (-1, 0)
Call Stack (most recent call first):
  cmake/common/bootstrap.cmake:60 (include)
  CMakeLists.txt:3 (include)


CMake Error at CMakeLists.txt:5 (project):
  VERSION "bf92f0aea" format invalid.


-- Configuring incomplete, errors occurred!

What am I doing wrong? :( Pls advise.

Tomi Tukša

**Comment by Poodmund** [comment]
In the pull request, it builds OBS with the changes. You can see the artifacts for all the different platforms in the Action checks; presuming you're using Windows, here is the link to the Windows one: https://github.com/obsproject/obs-studio/actions/runs/13485351192/artifacts/2637617428

**Comment by tomica00** [comment]
I'm getting error 404 on that URL :(

Tomi

**Comment by Fenrirthviti** [comment]
You need to be signed in to download artifacts.

However, this issue is from 5 years ago and while there might be a similar problem, is likely something else since we already fixed the issue as presented in this case.

Please keep discussion on the linked open issue https://github.com/obsproject/obs-studio/issues/4667

**Comment by tomica00** [comment]
> You need to be signed in to download artifacts.
> 
> However, this issue is from 5 years ago and while there might be a similar problem, is likely something else since we already fixed the issue as presented in this case.
> 
> Please keep discussion on the linked open issue [#4667](https://github.com/obsproject/obs-studio/issues/4667)

Thank you! Silly me. I managed to download and install it. I'll post in the discussion you mentioned above if I find any problems.
