### ISSUE TITLE
[UX bug] Filename should not contain % by default

### ISSUE THREAD

**Issue by innerop** [obsproject/obs-studio#2994]
## Platform

Operating system and version: all platforms and OS versions
OBS Studio version: all versions

## Expected Behavior
In Advanced settings, the file name should not contain "%" by default. This assumes that the filename will have a time component, but that is not always desired. 

## Current Behavior
Per the guide for HLS output, it states:

"In the settings dialog go to Advanced and set the recording filename. The default includes the current time; which would mean you wouldn't know where to point the HLS player JavaScript before you start streaming. Choose something without any special % time values. You may also like to enable Overwrite if file exists."

## Steps to Reproduce
In the settings dialog go to Advanced and notice the recording filename. It contains % by default.

**Comment by Fenrirthviti** [comment]
When you say %, you're talking about the variables? This is not a bug, this is intentional. OBS doesn't even support HLS output, so I'm unclear why the HLS standard matters for local file recordings in OBS.

**Comment by skeletonbow** [comment]
Not to mention that having the current time in the filename guarantees that the user is not going to overwrite a previous recording unintentionally by default.  Programs should IMHO always default to non-destructive behaviour unless the user has overridden a default with a setting that is intentionally destructive.

Otherwise the bug report then just turns into angry reports from battalions of users who have suffered permanent data loss: "OBS overwrote my last recording when I made a new one!"

Defaults should always be both safe, and for the general purpose use case.  People who have special circumstances should intentionally have to change things from default to more special case and/or destructive behaviour on purpose IMHO.

**Comment by innerop** [comment]
Fair enough guys. I feel like Custom Output should be its own separate flow and should allow taking the raw media and applying any processing pipeline that’s specified by the user.

Having it as a special case seems confusing and limiting, IMO.

Thanks
