### ISSUE TITLE
References to non-existent network resource cause 3-second hang, even when not visible

### ISSUE THREAD

**Issue by bradtem** [obsproject/obs-studio#3007]
## Platform

Operating system and version:  Windows 10
OBS Studio version: 25.0.8

## Expected Behavior
Smooth operation 

## Current Behavior

I had a scene with an Image source which referenced a file on a network drive.  ie; "\\system\pathname"    However, the "system" was no longer present having been renamed.   As a result, it meant that about every 30 seconds, OBS would go into a hiccup, where video would freeze and CPU would drop and then spike high for programs taking output from OBS via Virtualcam.  (however, problem occurs with no output turned on, but with only a tiny CPU spike.)

Note that this happens even though the Scene with the source is not currently active, and the source is currently inactive (eye icon grayed out) and the image source is marked to unload the image when inactive.   In other words, something is making it attempt to open the non-existent source about every 30 seconds anyway -- this made the problem hard to diagnose.    No matter what, the problem would recur until the offending source was deleted.

I believe the problem is well described and easy to reproduce, contact me if you need a log.
## Steps to Reproduce

1. Create a scene with an Image source on a network drive.  Disable that network drive so it can no longer be accessed.    Use OBS for approximately 30-40 seconds and video will freeze for a few seconds.    If feeding out to virtualcam to zoom, camera input will go gray.

**Comment by notr1ch** [comment]
While I've fixed the issue with hidden sources triggering this, the behavior will still occur with visible sources as the update checks are done in the graphics thread during source tick. I see a couple of possible options here:

- Move the file update checks to their own threads to avoid blocking the graphics thread. This would require mutexes being added for source updates and calling stat once a second is still not so great, but this is the easiest to implement

- Move the whole file update notification system to some kind of module / service that sources can utilize, making use of native file change notification APIs. This would require OS-specific code to be written and is a large and complex undertaking, but would be the "ideal" fix.

I'm tempted to go with the first option purely due to the complexity of the second one. There's a good chance it could introduce subtle bugs due to various inconsistencies in the different native OS APIs, eg in how they handle missing files, unreachable files, symbolic links, etc.

**Comment by bradtem** [comment]
I don't believe it's necessary to do a lot of work to make it super graceful in handling of this.   The thing that made this a more severe bug was that it breaks the cardinal rule of something going wrong without a diagnostic.    While resources do disappear, when they do what matters is that a warning be issued -- ideally visibly, but at the very least in log files.     Clearly vital threads should not block without an explanation of what is causing the blockage.

This bug became insidious because it appeared in a disused source which was disabled, but affected all operation.  There was no way to find the cause of the trouble other than deleting sources and scenes one by one until the problem went away, a very time consuming process.

The simplest fix would be to log the failure to log files.   Better would be to do so and to visibly display that this level of failure has taken place and blocked the graphics thread.

However, now that it requires the source be visible it does make it more likely users will detect when they have got a missing file.    In particular the source could, unable to open its resource, return an image with the error message, or a pointer to the log file.

**Comment by notr1ch** [comment]
All sources which do file I/O on the graphics thread would be affected to some extent. While this change does make it easier for the user to discover the problem (the failing to load of a visible source would make it into the log file), a separate RFC to bring about per-source diagnostics / logging in the UI itself is also in the works, see https://github.com/obsproject/rfcs/pull/19

**Comment by bradtem** [comment]
Yes, any file i/o can block, a network open just can block for the longest time.   A local open on a spun-down disk could go longer.  As can reads.  So over long term all blocking actions should end up in their own threads, but that's a bunch more work.   Thanks for the fix -- while this one won't burn me again, I suspect others would have run into it, or may have already.

**Comment by Fenrirthviti** [comment]
This is more or less expected, unfortunately. Windows itself will even stumble when there is a missing network resource, as does almost any application. I often will open Windows Explorer and have it hang and not actually load any content because a network drive has been disconnected. There isn't a whole lot we can do about this, but it's definitely something we're aware of, and keep in mind when providing support. It does come up occasionally in our support channels, but it's a hell of a problem to properly fix, and likely isn't worth the effort on our end as not even Windows themselves have fixed it.

**Comment by bradtem** [comment]
Yes, if you actually use the unavailable resource, it is not unusual for programs to hang.  That is not the reported bug.   The issue is that it hangs even when the resource is not in any visible source or scene.     This creates a difficult to diagnose situation, where the program is hanging and it is not apparent why.     Recommended fixes include not attempting to open resources from invisible scenes, or having a diagnostic when a resource fails to open telling the user that a file in a given scene and source could not be opened.   Failure with no diagnostic is never a good idea.
