### ISSUE TITLE
JACK Input Client doesn't record any sound

### ISSUE THREAD

**Issue by OnkelTem** [obsproject/obs-studio#3021]
## Platform
Operating system and version: Kubuntu 18.04
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior
Sound is recorded.

## Current Behavior
Sound is not recorded.

## Steps to Reproduce
1. Disable all the devices (obviously PulseAudio ones)
2. Add Jack inputs.
3. Ensure they're receiving data (Audio Mixer).
4. Record video and check if the sound were recorded.

### Output settings

![](https://i.gyazo.com/ed0410e0b8e36bdd0cc696833d5b793c.png)

### Audio settings

![](https://i.gyazo.com/509132d31200796bd9a1092f1bb2f16d.png)

### Connections

![](https://obsproject.com/forum/attachments/66807f591125bd17a1ae1e5e1d594e62-png.56941/)

### Log

https://obsproject.com/logs/B29FaiKv_plzCLwy

Video example: https://www.youtube.com/watch?v=mggeOs3lkbg

Forum thread: https://obsproject.com/forum/threads/jack-obs-no-sound.123527/

**Comment by Fenrirthviti** [comment]
Tested and working fine on my end, I will reply to the forum thread. Support requests should not be submitted to Github,

**Comment by OnkelTem** [comment]
Sorry, looked like a bug for me.
Thanks for quick reply and help, Joel

**Comment by LGCW** [comment]
I had a little spare time this morning to record OBS misbehaving with Jack2 using netone, most of my audiochain is IP based. I make extensive use of Jack in the studio and OBS is the only application not to record audio with Jack1 or 2. I should say reliably since it occasionally works.

For this example I have a single stereo pair and one mono channel. Audacity is recording the stereo pair from the same Jack source as OBS.

https://www.youtube.com/watch?v=GUR83nCuh60

This can be reproduced with any interface in my rack. (pictured)
![1obs](https://user-images.githubusercontent.com/3475462/89218895-d26a0780-d59c-11ea-948f-6fb40fa40c39.jpg)

I would like to see this bug reopened because people can and have lost data to it. Myself included.

**Log**
[OBSJack.txt](https://github.com/obsproject/obs-studio/files/5018020/OBSJack.txt)

**Comment by kkartaltepe** [comment]
Your log shows that you reached max audio buffering, which means your source was muted since it could no longer be kept in sync. Please use Discord for support before opening a bug.
