### ISSUE TITLE
Misleading "PAL" and "NTSC" in "Common FPS Values"

### ISSUE THREAD

**Issue by mivk** [obsproject/obs-studio#3039]
Under Settings > Video > "Common FPS Values", there is a handy list of the (well, as it says) common FPS values.

However, the additional mentions of "PAL" for 25 and 50, and of "NTSC" for 24 are very misleading.

PAL is a very specific denomination which doesn't really mean 25 frames per second. PAL is:
* 50 half-frames per second (25 interlaced)
* 720 x 576 non-square (!) pixels
* etc.

I would suggest removing the "PAL" and "NTSC" qualifiers which are irrelevant here, and which are only used for DVDs now.

It may also be useful to add a 23.976 (or "23.97") framerate, which was inherited from NTSC, but is still used in the US (and is often confused with true 24 which is the film standard).

The definitions seem to be in the [UI/forms/OBSBasicSettings.ui](https://github.com/obsproject/obs-studio/blob/master/UI/forms/OBSBasicSettings.ui) XML file. Let me know if you would like me to submit a patch or pull request.

OBS Studio version: 25.0.8

**Comment by Fenrirthviti** [comment]
This is not really a bug report, and you have deleted the template. This should probably be submitted as an [RFC](https://github.com/obsproject/rfcs) or discussed in our [Discord](https://obsproject.com/discord).

**Comment by mufunyo** [comment]
> PAL is a very specific denomination which doesn't really mean 25 frames per second.

In the context of frame rate, 25 and 50 are universally understood to belong to PAL regions, while 23.976, 29.970 and 59.940 are understood to belong to NTSC regions, regardless of whether the resolution is CIF, D1, HD, or full HD. If anything, your extreme pedantry reveals a lack of knowledge of video standards.
 
> I would suggest removing the "PAL" and "NTSC" qualifiers which are irrelevant here, and which are only used for DVDs now.

A significant percentage of OBS users use OBS in a professional studio setting, and having easy shorthand settings to correct broadcast frame rates is useful to them, and far from irrelevant.

> It may also be useful to add a 23.976 (or "23.97") framerate, which was inherited from NTSC, but is still used in the US (and is often confused with true 24 which is the film standard).

If you had spent 5 seconds verifying what the settings actually do, you would have discovered that the "common FPS values" are shorthand for the right numerator/denominators for NTSC: 24000/1001, 30000/1001, and 60000/1001.

The only valid complaint here, is that the terms are mixed up in the common FPS values dropdown, because "24 NTSC" refers to 24000/1001, while "29.97" refers to 30000/1001. It should either be "24 NTSC" and "30 NTSC", or "23.97" and "29.97". You seem to have been too busy being outraged at a complete non-issue to discover what's *actually* wrong with the UI.

**Comment by marshalleq** [comment]
There is no need to be so horrible to someone trying to help.

I have found this to be the most informative text on this issue so far.  As you can see, most of the standards have gotten this completely wrong.  Analogue SD video in PAL and NTSC is a bit tricky and not so straight forward.

https://lurkertech.com/lg/video-systems/#sqnonsq
https://lurkertech.com/lg/pixelaspect/

**Comment by BlueTrinity1** [comment]
I have zero idea what ANY of this means...so like when I stream to twitch and use those ntsc or PAL prefixed settings does it really make any difference to the stream?  I am still going to get the 24 or 25 fps right?  Because I find that 20 is sometimes just that TOUCH too slow IMO.  I think the human eye only detects around that that fps naturally correct?  Anything higher tends to just make it seem SMOOTHER to my undrestanding.  So I want to use the 24 or 25 bit settings, yet I am wondering if that PAL or ntsc stuff does anything "weird" to the video.  I guess my best bet for now is just to try em out and see what it looks like.  Lots of settings like that I have had to simple gain experience with to know if it will be good or otherwise.  Anyhews, thanks for the thread.  After all a newbie like me can use all the information on these settings that I can get!

**Comment by marshalleq** [comment]
You're on the right track @BlueTrinity1, for streaming don't worry about PAL or NTSC (essentially what the original poster was saying), just use the a frame rate (FPS) that is smooth enough for your needs (perceptual).  This becomes more complicated if using OBS for recording, but for streaming you're on the right track.
