### ISSUE TITLE
Dock icon is overriden on Mac by setWindowIcon

### ISSUE THREAD

**Issue by tbodt** [obsproject/obs-studio#3093]
## Platform

Operating system and version: macOS 10.15.6
OBS Studio version: 25.0.8-1-gc57481bcb-modified

## Expected Behavior
The icon used in the dock should be the obs.icns icon.

## Current Behavior

When OBS starts up it calls [setWindowIcon](https://github.com/obsproject/obs-studio/blob/5a6b417fcc9718573f6946c1a972cd02ddd04bf2/UI/obs-app.cpp#L1109) and this [also overrides the dock icon](https://doc.qt.io/qt-5/macos-issues.html#dock), leading to a noticeable "jump" in the dock icon because the two icons are not quite the same.

## Steps to Reproduce

1. Start OBS on Mac

**Comment by unknowndomain** [comment]
Great spot, personally I can't see any need for those calls on macOS due to how the OS works and presume the Windows bias of the development probably resulted in people not noticing as it also requires you to have the application saved in the dock or in recent applications on Catalina.

I've modified the code in my commit to just not change them as I presume the icons are different for visiblity reasons at small sizes on the Windows start bar and title bars.

**Comment by PatTheMav** [comment]
@unknowndomain Did you submit a PR for this? I've noticed the same "jumpy" behaviour but didn't have time to look into it.

**Comment by unknowndomain** [comment]
The issue was that the icon of the app bundle was different to the icon set at start up, the solution I proposed was the #ifdef for macOS all calls to set the icon however people complained this was break the ability for themes to set the icon, why you would do that this way on macOS is beyond me but that was why the PR was closed without merging it.

Someone else was going to replace all the icons to be consistent.

**Comment by PatTheMav** [comment]
I see - yeah in general I agree with you, there should be no themes on macOS IMO (instead there should be a bright and dark mode variant and support for upcoming custom highlights in macOS Big Sur), but that's non-essential.

Fixing the icons for the default skin(s) should be good enough.

**Comment by unknowndomain** [comment]
I don't really mind the themes, but changing the icon in the theme seems unnecessary and not normal of Mac applications, but to be honest I hadly ever use the Dock on my Mac so I don't really care about the issue either.

I mean I can't help but feel the future of OBS on macOS could be very limited anyway, there are a small number of features that don't work or exist, the UI is nothing like any other macOS app and Apple Silicon might be a nail in the coffin, that would be very sad because I love my Mac but to be honest OBS on Mac is not a great experience in my view.

**Comment by PatTheMav** [comment]
I think Steven Sinofsky's assessment on Twitter applies: 

https://twitter.com/stevesi/status/1275131954531192832

There is a lot of work to be done to be sure, but if people are willing to assist Jim with macOS support (and not just drop a PR and leave it), it can continue to support as much as possible.

**Comment by camayl** [comment]
Hi apologies if I sound dumb, but I wonder if my issue is related. On MacOS I changed the OBS dock icon to a custom image. For other apps this works fine, but whenever I open OBS, the icon reverts to its original state. I also tried to replace the AppIcon.icns file in Show Package Contents -> Contents -> Resources, but to no avail. Any fix?
