### ISSUE TITLE
Python [Unknown Script] w/ multiple scripts & script_tick() & imports

### ISSUE THREAD

**Issue by EstevanTH** [obsproject/obs-studio#3209]
Hi there!

## Platform

Operating system and version: Microsoft Windows 10 (10.0.17134) [x86-64]
OBS Studio version: official 25.0.8 [x86-64]
Python version: official 3.6.8 [x86-64]

## Expected Behavior

During the Python script initialization, all messages should have the script filename displayed as a prefix (such as `[live_mpegts_relay_emitter.py]`).

Remark: this does not work in threads created with the `threading` library, I perfectly understand that. I have overridden the `print()` function to have an extra prefix containing `__name__`. This is not the subject of this bug report. In my examples, there are only Python calls initiated by OBS Studio.

## Current Behavior

As the Python calls are initiated by OBS Studio with a known initiating thread, I should never get the prefix `[Unknown Script]` in place of the expected prefix. During the initialization process, the prefix can re-appear and disappear again on several times.

The bug applies at least when importing the script and when executing its `script_load()` function.

When the current script is not recognized, functions such as `obspython.obs_frontend_add_event_callback()` produce a crash.

Here is a preview of the script log after startup:

```
[gps_scene_auto_switch.py] Loading gps_scene_auto_switch...
[gps_scene_auto_switch.py] Python:  3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
[gps_scene_auto_switch.py] OBS Studio:  25.0.8
[gps_scene_auto_switch.py] Loaded live_mpegts_relay_emitter!
[live_mpegts_relay_emitter.py] Loading live_mpegts_relay_emitter...
[Unknown Script] Python:  3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
[Unknown Script] OBS Studio:  25.0.8
[Unknown Script] Loaded live_mpegts_relay_emitter!
[live_mpegts_relay_emitter.py] Initialized live_mpegts_relay_emitter!
```

## Steps to Reproduce

Please add scripts in the specified order to achieve the same behavior.

1. Remove all loaded scripts from the list.
2. Add the script `gps_scene_auto_switch.py`. The code is:

```py
print("Loading gps_scene_auto_switch...")

import obspython
import sys

print("Python: ", sys.version)
print("OBS Studio: ", obspython.obs_get_version_string())

def script_load(settings):
    print("Loaded gps_scene_auto_switch!")

def script_tick(seconds):
    """The [Unknown Script] in the other script disappears if this is undefined"""
    pass
```

3. Add the script `live_mpegts_relay_emitter.py`. The code is:

```py
print("Loading live_mpegts_relay_emitter...")

import obspython
import sys
# After that, importing any other module seems to mess up the script recognition!
import webbrowser  # problem when imported!

print("Python: ", sys.version)
print("OBS Studio: ", obspython.obs_get_version_string())

def _handler_frontend_event(event):
    pass

def _initialize():
    obspython.obs_frontend_add_event_callback(_handler_frontend_event)  # crash if unidentified script
    print("Initialized live_mpegts_relay_emitter!")

def script_load(settings):
    # _read_properties(settings)
    # Crash workaround: initialization is partially done in script_load(), due to bad script recognition ("[Unknown Script]" in console).
    # _initialize()
    print("Loaded live_mpegts_relay_emitter!")

initialized = False
def script_tick(seconds):
    global initialized
    if not initialized:
        initialized = True
        _initialize()

def script_unload():
    print("Unloaded live_mpegts_relay_emitter!")
```

4. Restart OBS Studio to have all scripts loaded together.
5. Pay attention to the comments in the scripts. As given, the scripts produce the bug as shown in the log. You can experiment to achieve other related behaviors.

## Additional information

Bonus:

```py
# Replacing the print() function to include the script name in extra threads:
_extra_threads = set()
def _():
    global print
    print_ = __builtins__["print"]
    script_name_prefix = "[%s]" % __name__
    def print(*args, **kargs):
        if threading.current_thread() in _extra_threads:
            return print_(script_name_prefix, *args, **kargs)
        else:
            return print_(*args, **kargs)
_(); del _
```

## Greetings

Thank you,

Momo :heart:

**Comment by RytoEX** [comment]
I can confirm the described behavior in OBS Studio 28.0.3 with Python 3.6.2 or Python 3.10. I do not know why it is happening though.

**Comment by PatTheMav** [comment]
What seems to happen is that the `tick` callback sets the state machine pointer for the "current" Python script to a null pointer right after the first `print` statement has executed, so any consecutive output done _while importing the module_ will have to work with a null pointer as the "current" script name.

Any other output at a later point does not happen at import time, but rather when specific callbacks are executed, and as such the state of the "current" script is established correctly before.

What seems to happen is that during import the GIL (Global Interpreter Lock) is released _after_ the first `print` statement, so the graphics thread can lock the GIL instead, execute the `tick` and unset the state variable.

That's also why the line `Initialized live_mpegts_relay_emitter` will have the correct script name associated with it, because that line is triggered by the graphics thread via the source tick, which sets (and resets) the `cur_python_script` state variable before execution.

One way to fix this would be to lock the `cur_python_script` state variable when a Python script is loaded but this would block the graphics thread's `tick` whenever a script is loaded/imported and I have a hunch that'd be undesirable.
