### ISSUE TITLE
Mission Control Breaks Cropped Dimension-Constrained Window Capture

### ISSUE THREAD

**Issue by MrDrProfK** [obsproject/obs-studio#3222]
## Platform

Operating system and version: MacOS 10.13.6
OBS Studio version: 25.0.8

## Expected Behavior

Mission control should not affect the video output and preview produced by a dimension constrained and cropped window capture.

## Current Behavior

Mission control adversely affects the video output and preview produced by a dimension constrained and cropped window capture. Output either disappears or shrinks as long as mission control is still active.

## Steps to Reproduce

1. Add window capture to scene.
2. Constrain window capture output dimensions. For example, select Transform -> Fit to screen.
3. Crop even a single bound inward.
4. Enter mission control and keep an eye on the OBS preview. FYI, the OBS preview seems to match results gleaned by recording the session.

**Comment by MrDrProfK** [comment]
@WizardCM Your timing is truly impeccable. I'm starting to think you actually are a wizard.

**Comment by WizardCM** [comment]
Only slightly. :P 


To those that may be confused, "Mission Control" is the name of the macOS [multitasking view](https://support.apple.com/en-au/HT204100). I honestly don't know if we have the ability to fix this issue. I can only assume the API we use to capture windows (which is just a cropped display capture on macOS afaik) behaves differently during mission control. Maybe there's some offset we can enable when mission control is active? Someone who actually knows macOS would have to dig into this, I'm afraid.

**Comment by MisutaaUrufu** [comment]
I don't know how to fix this, but **I can** both **confirm this issue** persists through both Catalina & Big Sur, and shed a bit of light on how OBS handles Window capture on macOS, which is a unique case.

******

macOS's integrated support for display capture supports 2 types of video capture, and ***3*** types of ***image*** capture. The two shared types are:
- Full Display Capture
- Display Selection ("Cropped Display") Capture

However, image capture offers a *third type* of ***Window Capture***. Looking briefly into OBS' macOS window capture bits (I get curious), it appears that, in order to capture *windows* rather than a portion of the display, OBS repeatedly calls the *image* capture api @ the specified framerate. So a 60fps capture is really just calling the window capture 60x a second. — This is also where it's option to capture the window's shadow comes from (the screenshot system for macOS can generate the window's shadow with transparency without capturing anything beneath)

Mission Control itself, though, counts as a "window" according to the system; furthermore, the window previews are live within Mission Control, suggesting that macOS shrinks the visual display of each window before presenting it within mission control.

This seems to suggest that a side effect of this is any application actively capturing an identified window will receive it "as is", including any adjustments made by the system. — Since the system is not actually resizing the window; instead visually shrinking the the window's visual appearance; the empty space left by the window is captured as a side effect.

I'm willing to admit I'm not 100% versed on how the API works, so it may be possible to mitigate, but from what I do know, this is "expected behavior" for window captures.

******

During streaming sessions I recommend just using the macOS Dock & ⌘+tab to switch between applications and their windows.

**Comment by dossy** [comment]
I'd like to dig in further to confirm this, but I have a hypothesis that the crop dimensions when windows are displayed under Mission Control/Exposé are getting amplified on HiDPI (e.g., Retina) displays.  I don't have a non-Retina Mac handy to test on to confirm, but if this is the case, it does kind of suggest what a suitable solution/fix might look like.

**Comment by MisutaaUrufu** [comment]
> I'd like to dig in further to confirm this, but I have a hypothesis that the crop dimensions when windows are displayed under Mission Control/Exposé are getting amplified on HiDPI (e.g., Retina) displays. I don't have a non-Retina Mac handy to test on to confirm, but if this is the case, it does kind of suggest what a suitable solution/fix might look like.

I'm not sure if this is correct. When "swiping" left to right between "Desktops", anything capture "by window" animates in OBS as well.

That is to say, the direction you swipe, the window "slides" in OBS past its bounds, before "snapping" back into place.

Even more so, when "reduce motion" is on, the "fading" animation from desktop switching is also captured. — So the application window will "fade out" in OBS, before "snapping back" to opaque, similar to the animated desktop switching animation's behavior.

Furthermore, a possibly related issue is that OBS cannot find windows that are not on the same "desktop" as it is. This is including windows on external (active) displays, and windows on other (inactive) desktops on the same display.

It would seem that the way OBS captures windows does not "keep up" with the operating system, and is not designed with the knowledge of other desktops in mind.

OBS can capture windows on other desktops, permitting they were on the _same_ desktop when launching, but OBS is blind to applications on other desktops, not yet captured, and captures desktop-animations to all programs on any desktop when capturing by window. Additionally, OBS cannot find windows if the capture is initiated whilst OBS is "full screen" (i.e. serving as its own single-application desktop).

I'm beginning to think this is related to how OBS captures windows in macOS (it captures by window using the same API the screenshot util uses, only at a high frame rate. macOS screen-recording APIs do not provide a capture by window option, including the built in system capture utility.)

Just speculating here, but if there was a way OBS could be made aware of desktop transition, it could possibly "freeze" the capture until transition takes place, and "cross-fade" the stale-frame with the latest capture, to provide a less "jarring" form of desktop transition handling.

This issue primarily effects multi-desktop workflows, so single-desktop users wouldn't notice issue. — I just happen to be a multi-desktop user who notices these things (I use OBS on one desktop, music on a second, games on a third, messengers on a fourth, etc., to provide easy, full screen switching.)

**Comment by gxalpha** [comment]
I can confirm that this happens, but as noted above there is likely nothing we can do about this behavior. Window Capture is using a now deprecated macOS API, so this behavior is unlikely to change.
Fortunately, the replacement API called ScreenCaptureKit (used by the `macOS Screen Capture` source available from OBS 28.0 on macOS 12.5 and higher) does not show this issue. The solution for this issue is to use the new source type.
