### ISSUE TITLE
Windows Security warns of Trojan:Win32/Wacatac.DD!ml in latest Azure Pipelines build 

### ISSUE THREAD

**Issue by ahmadnassri** [obsproject/obs-studio#3241]
## Platform

Operating system and version:
OBS Studio version: latest `master` commit `478f1de`: https://dev.azure.com/obsjim/obsjim/_build/results?buildId=4293&view=results

## Expected Behavior

Do not install Trojans! or, false positive with Windows Security

## Current Behavior

after downloading `winbuild` off the Azure pipeline, and attempting to extract and move into place, I get the following warning: 

![image](https://user-images.githubusercontent.com/183195/89135775-da269f00-d4fd-11ea-9579-78a9c93201a3.png)

## Steps to Reproduce

1. download latest Win 64 build artifact from https://dev.azure.com/obsjim/obsjim/_build/results?buildId=4293&view=artifacts&type=publishedArtifacts
2. extract

## Additional information

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.DD!ml&threatid=2147757792

**Comment by WizardCM** [comment]
This is a false positive. The injection code hasn't changed in a while.

**Comment by jp9000** [comment]
The CI builds aren't signed so it's probably going to trigger false positives on occasion.  There's nothing we can really do about it.  You can at the very least rest assured because the builds are automatically built from the repository source code, so if you're worried about it just take a look at the source code.  Or wait until an official release for digitally signed builds.

**Comment by ahmadnassri** [comment]
appreciate that fast response! curious why this is the first time windows threw this at me, been using pipeline builds for a few months now!
