### ISSUE TITLE
YouTube video lags

### ISSUE THREAD

**Issue by Roper89** [obsproject/obs-studio#3279]
When I play YouTube video in the media widget, the video lags.
Version 25.0.8 (x64)

**Comment by WizardCM** [comment]
GitHub issues shouldn't be used for support. Try our [Discord](https://obsproject.com/discord) instead. If actually reporting a bug, please fill in the issue template.

**Comment by Roper89** [comment]
@WizardCM This is an old bug, check it yourself.

**Comment by Roper89** [comment]
@WizardCM  Capture a video from YouTube through the OBS browser and see for yourself. This problem is faced by many people who use clip placement in their donations.  The problem is solved by installing version 24. People from other forums know about this, but only you thought that this is my personal problem. You should be ashamed of closing the topic. Search the internet for this problem.

**Comment by WizardCM** [comment]
So not the media widget, but the browser source? This is why a full issue report is required. "google it" is not a valid bug report. Please fill in the issue template if you would like us to look into this properly.

**Comment by mufunyo** [comment]
If the issue is widely reproducible, you should properly fill out the issue template with reproduction steps, and link to forum threads were other people are having the issue. "Search the internet" is not acceptable, OBS maintainers have better things to do.

**Comment by Roper89** [comment]
@mufunyo  @WizardCM 
Try it yourself to capture video from YouTube through the browser on the latest version of the OBS and make sure of the lags.
Is it difficult for you to make an action with two clicks? :)

English is hard for me, if it's not difficult for you. Create a problem request yourself.
This is a problem for everyone who uses embedding clips from YouTube in donations.

**Comment by Fenrirthviti** [comment]
When you submit a bug report, and spend more effort arguing with the maintainers of the project about filling out a bug report than it would take to actually fill out the bug report, it sets a bad tone. It sends the message that your time is more valuable than hours, and we should report this bug (which we have no details on because you have provided very little information) on your behalf. If you want this bug fixed, fill out the dang template. I've tested based on the extremely limited information you provided, and I cannot replicate the issue you describe.

This is why we request the template, so we can have *very clear replication steps* so we don't waste our time investigating something that is a misconfiguration or environment issue.

For the record, I've tested this on Windows as that is the platform I'm assuming you're on, seeing as you have, again, provided no details on this report. Without further information, this bug report is dead.
