### ISSUE TITLE
Pasting a source does not show up in the sources until switching from different scenes

### ISSUE THREAD

**Issue by flleeppyy** [obsproject/obs-studio#3387]
## Platform

Operating system and version: Windows 10 Build 18363
OBS Studio version: 25.08

## Expected Behavior

The source should paste in the same position it was in when copied, and should show up in the sources list
## Current Behavior

Pasting the copied source will reset its transform, and will not show up in the sources list until you switch to and from a different scene. There is also no menu options available for the newly pasted source.
After switching scenes, you have to copy and paste the transform.

## Steps to Reproduce

Create a new scene collection
1. Create a new source (Any type)
2. Put it into a group, and move it in and out of that group a couple times
3. Copy the source
4. Paste the copied source into a new scene
It will now have reset/screwed up its transform

## Additional information

I am not sure if this has been posted here before; I did a couple searches but I couldn't find anything related.

The "Does not show up in sources when pasting" part will only happen sometimes.

**Comment by RytoEX** [comment]
Please provide _written_ steps to reproduce.

**Comment by flleeppyy** [comment]
> 
> 
> Please provide _written_ steps to reproduce.

Just did

**Comment by flleeppyy** [comment]
I feel as if this is an issue with my OBS install specifically, cause NOBODY has reported this, and I'm pretty sure someone would have done so by now

**Comment by RytoEX** [comment]
I just tested on a color source in OBS 25.0.8 and could not reproduce with these steps.  What specific source type do you see this happen with?

**Comment by flleeppyy** [comment]
All source types. I believe its my issue

**Comment by flleeppyy** [comment]
> All source types. I believe its an issue on my install

Even though i JUST reinstalled OBS

**Comment by flleeppyy** [comment]
Yeah its an issue with my scene collection

**Comment by WizardCM** [comment]
Past reports in this area (I think @skeletonbow has run into this) essentially showed that moving stuff in and out of groups made this issue start to occur, and then would *always* occur in the scene collection, even after restarts. The issue is valid, but requires a fair bit of steps to repro for the first time.

**Comment by flleeppyy** [comment]
I went ahead and updated it, and reproduced it

**Comment by zoton2** [comment]
I experienced a similar issue the last couple of times I've done some events in the last few months (not on my own computer), although I thought it might be a PC issue or that install. I had been using groups so it would make sense if that was causing the issue. Next time I am able to access the computer it was being an issue on I could check that too.

**Comment by skeletonbow** [comment]
> Past reports in this area (I think @skeletonbow has run into this) essentially showed that moving stuff in and out of groups made this issue start to occur, and then would _always_ occur in the scene collection, even after restarts. The issue is valid, but requires a fair bit of steps to repro for the first time.

Yeah, I've encountered this problem before and one of my existing bug reports might be the same issue or a variant.  I was able to narrow these sort of bugs down to simple step by step 100% repro test cases here eventualy though without any complex OBS setup and free of plugins.   I'll test this issue specifically soon and report back my results also.

**Comment by zoton2** [comment]
I got remote access to the PC today but even on there couldn't make the bug happen again, maybe once you close/open it, it goes away? I have a copy of the scene collection I am pretty sure it was happening in if anything can be debugged from that.

**Comment by SPIKEYPUP** [comment]
> I went ahead and updated it, and reproduced it

I'm also experiencing this issue in RC1 and RC2, particularly when working in and out of groups then adding a source, it's like it never got added until you go in and out of the scene and then it appears...

**Comment by zoton2** [comment]
I actually got this issue again (and it may have been adding *anything* that caused it) on my local OBS which is still on the latest stable. Just the new source doesn't appear until I switch from and then back to the scene. I had a look at the logs but didn't see anything too interesting, besides that (I think) it was a Video Capture Device with logs like this...
```
19:06:08.014: Capture Card: DecodeDeviceId failed
19:06:08.014: Capture Card: Video configuration failed
19:06:08.015: User added source 'Capture Card' (dshow_input) to scene 'Game Scene'
```
...but this may be normal anyway.

**Comment by PatTheMav** [comment]
I haven't been able to reproduce this in OBS 28.0.3 so far - moving the source into and out of a group multiple times always applied/removed the appropriate transform and position.

What _is_ unexpected is that copying a source from within a group with no other sources present will copy it with the position/transform as it applies to within the group:

* When a group contains a single item, it represents a "scene" with a single scene-item (the source), positioned at (0,0), with the scene taking the size of the single source in it
* When the source is copied, it's _current_ position (0,0) is being copied with the item
* Pasting the source in a different scene will place it in the top left corner because of this

When you move the source out of the group, it's original "ungrouped" position is being restored (the transformation of the _group_ is being copied onto the source).

I also have not been able to reproduce the issue of pasted items not appearing, so if anyone has foolproof reproduction steps for this on 28.0.3, I'd be thankful to have them posted here.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

Since this is missing some key step or process to get to reliably occur, we are unable to take action.
