### ISSUE TITLE
[Linux] Preview remain disabled after maximized and difficult to re-enable

### ISSUE THREAD

**Issue by Aikatsui** [obsproject/obs-studio#3418]
**Steps to Reproduce**

1. Maximize OBS studio from tray. (Tested sources: screen capture and window capture)
2. [Test with screen capture] when maximize obs shows 'Preview is currently disabled'
3. 'Enable preview' button only helps seldom otherwise needs to click properties on screen capture source then click ok and click enable preview button again then works smooth.

It's good auto disable preview  when minimized (if not recording)

Screen capture:XSHM | Window capture:Xcomposite
PopOS 20.04.01 LTS | Gnome | 25.0.8 64bit (using apt)

**Comment by Fenrirthviti** [comment]
Please fully fill out the issue template.

**Comment by KizunaH** [comment]
@Fenrirthviti Above included all possible details able to provide and cover the issue template However let me know if that details insufficient to recognize the problem or required to add screenshots and other details

**Comment by WizardCM** [comment]
On Ubuntu 20.04 I can only reproduce this if "Always minimise to system tray instead of task bar" is enabled in Settings -> General.
1. After enabling the setting, press the "-" minimise button in the app titlebar
2. Pressing "Show" the first time in the tray icon after minimising will flash the window for a split-second but not display it properly
3. Pressing "Show" a second time will make it appear, with "Preview is currently disabled"
4. Pressing the "Enable Preview" button the first time will do nothing
5. Pressing it a second time will correctly enable the preview

Doesn't happen on Windows 10.

Tested with 0b163018b3f239e41cb5fa493a9904aec7c02404.
