### ISSUE TITLE
UX Bug: Stats Dialog acts differently

### ISSUE THREAD

**Issue by shleeable** [obsproject/obs-studio#3445]
this is just a small UX thing.  Might as well remove the undockable stats dialog if it has same result.

## Platform
Operating system and version: Windows 10 patched
OBS Studio version:v26-rc2

## Expected Behavior
Easily dock stats dialog.

## Current Behavior
Tried to dock the stats dialog and couldn't get it working.

## Steps to Reproduce
View -> Stats - Creates a stats dialog that cannot be docked.
View -> Docks -> Stats - Creates a stats dialog that can be docked.

**Comment by WizardCM** [comment]
This is not a bug but by design. The first is a dialog, that (as you state) cannot be docked. It has the benefit of sticking around when OBS is minimised. The second is a dockable window, which minimises when OBS is minimised, even if undocked. For now, we're keeping both until a better solution is available.
