### ISSUE TITLE
[BUG] macOS VLC Source won't play YouTube videos

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#3463]
## Platform
Operating system and version: macOS 10.15.6
OBS Studio version: OBS 25.0.8

## Expected Behavior
VLC on macOS and Windows, and OBS VLC Source in Windows will play a YouTube video by putting the URL of a YouTube video into the network open dialog or network link in the source properties.

## Current Behavior
On the macOS version of OBS VLC Source this doesn't work.

## Steps to Reproduce
1. Paste this URL into the VLC.app Network windows `https://www.youtube.com/watch?v=pTQJyZXBlkE`.
2. The video will play.
3. Add a VLC source.
4. In properties at a Path/URL type source.
5. Add the URL above again.
6. Video does not play on macOS but it will pay in Windows.

## Additional information
Reported by Discord user Jay_Keegan

**Comment by notr1ch** [comment]
Not sure this is really a bug, the VLC app uses [lua scripts](https://github.com/videolan/vlc/commits/e3378ac3a892728bb8775d1bd243b31fa721ba49/share/lua/playlist) for fetching the actual video file if the user enters a popular video site. This is not exposed when using libvlc (it's a frontend feature).

Download the video file directly instead (eg with youtube-dl) instead of entering a YouTube webpage and it should work.

**Comment by WizardCM** [comment]
I agree that this isn't within scope for the VLC Video Source. Another alternative would be a browser source.
