### ISSUE TITLE
Window min-width is not consistent across sources.

### ISSUE THREAD

**Issue by Momizer** [obsproject/obs-studio#3476]
## Platform

Operating system and version: Windows 10 1709 (Replicated on newest ver. too) 
OBS Studio version: 26.0.0-rc2 (64 bit)

## Expected Behavior

Window minimum width should stay consistent while the program is being used, as it did in previous versions.

## Current Behavior
Window minimum width changes depending on the source being selected. (Caused by the new UI below the previews)

## Steps to Reproduce

1. Select any scene.
2. Select a source that is not Text or an Image.
3. Resize the window to it's smallest width.
4. Select a source that is a Text or an Image, observe that the minimum width has increased.

Here is a .gif that shows the issue:
![.gif showing issue](https://user-images.githubusercontent.com/9637702/93283578-089ac980-f78e-11ea-85f4-37e5bc16c7ba.gif)

## Additional information

I like to use OBS vertically, towards the right side of the screen. When the minimum width changes, it makes OBS hang off the side of the screen, where I can't use it. It looks like there's a lot of room between the name of the currently selected source and the buttons used to interact with it, if that space was "collapsible" (shrinking in width as the width of the program was reduced) everything could still fit. 

This is just my own opinion, but what is the point of the new "bar"? To me it seems redundant considering you can already access its functionality in other ways. The name of the source is already visible because you've just selected it in the sources panel... and the Filter and Properties are available through the context menu. I was rebuilding my stream layout all afternoon and didn't touch the new interface at all.

Thank you for your time.

**Comment by VodBox** [comment]
The bar can be disabled by unchecking View > Source Toolbar, if you feel it is unnecessary. The point of it is to make it so the properties for sources that are most likely to be changed often are more readily available to the user, and to also make things more discoverable. Right clicking a source isn't necessarily something that people are going to think to do without prompting (part of why we'd like to move things out of only being in context menus if it makes sense), and the gear in the bottom of the sources dock lacks text that would make it obvious what it is for. Having the Properties and Filters be up front buttons in the middle of the UI helps to expose those options to users quicker, saves on number of clicks, and it also can teach them about the existence of filters, since the UI previously didn't make it clear that was a thing.

As far as the actual issue being presented, I can imagine we might want to increase the minimum width of the bar as a whole to prevent it changing, but I'm also inclined to treat this as a "won't fix", because it only affects certain specific cases, and is easily worked around.

**Comment by Momizer** [comment]
That fixes my issue and explains the use of the bar. Thank you!!

**Comment by Fenrirthviti** [comment]
This shouldn't need to be fixed, there is a simple workaround for it, and it won't come up very often. If there is a strong argument for making a change, feel free to reply and we can reopen this for further discussion.
