### ISSUE TITLE
[bug] vlc and libvlc.dll

### ISSUE THREAD

**Issue by CanadianJeff** [obsproject/obs-studio#3589]
if I have a scene/source that uses VIDEOLANS VLC in OBS and OBS is running VLC will refuse to uninstall because the file libvlc.dll is in use by OBS

a possible workaround for this would be to just copy the dlls from VLC into a seperate folder that OBS uses so when someone goes to uninstall VLC it will actually uninstall itself

**Comment by kkartaltepe** [comment]
Do not delete the bug template. This is also not a bug.

**Comment by CanadianJeff** [comment]
how is this NOT a bug?

**Comment by UltimateByte** [comment]
Why would OBS use VLC DLL files? Sounds odd to me. I just came across not being able to upgrade VLC because OBS was opened. Lost 10 minutes figuring out the issue came from OBS. -_-

**Comment by WizardCM** [comment]
OBS uses VLC DLL files for the VLC Video Source.

**Comment by UltimateByte** [comment]
> OBS uses VLC DLL files for the VLC Video Source.

Good info. However I'm now using it. So how come OBS accesses third party software on my PC without me knowing?

**Comment by UltimateByte** [comment]
Well, it is precisely about the original topic. OBS uses third party files from VLC even when not using these features, and without users knowing. Therefore, you can't uninstall or update VLC while OBS is running.

That doesn't make any sense when encountered the first time and that made me lose precious time for obscure/invalid reasons. Thankfully I found this issue. And preventing this issue in the first place would be a must so that others don't have to.

Ultimately, that raises a trust issue: OK VLC is free and open source (so maybe use the source to build it inside OBS would make more sense...). But is there an actual way to know that OBS will use your installation of VLC in your back? Are there other things that OBS does in your back? Does it use Thunderbird files as well to read my mails? Does it read memory from my password manager as well? Will it interact weirdly with other software? See the doubts raised by this apparently benign, software intrusion that is actually important.

**Comment by Fenrirthviti** [comment]
You are welcome to read the source code and compile yourself if you have those concerns.
