### ISSUE TITLE
AMF H.265 "Deblocking Filter" toggle inverted

### ISSUE THREAD

**Issue by QuartzSTQ** [obsproject/obs-studio#3624]
The toggle for the deblocking filter when using the AMF H.265 encoder is inverted in the log versus the GUI.
I.e. Enabled in GUI means disabled in log and vice versa.

## Platform

Operating system and version: Windows 10 2004 64-bit
OBS Studio version: 26.0.2

## Expected Behavior

The option should show up the same in both the GUI as in the log.

## Current Behavior

The option is the opposite in the GUI as in the log.

[Disabled in log, enabled in GUI](https://github.com/obsproject/obs-studio/files/5396527/2020-10-17.23-29-07.txt)
[Changed the option](https://github.com/obsproject/obs-studio/files/5396528/2020-10-17.23-28-45.txt)
[Enabled in log, disabled in GUI](https://github.com/obsproject/obs-studio/files/5396529/2020-10-17.23-26-13.txt)

## Steps to Reproduce

1. Set the output mode to "Advanced".
2. Set OBS to use the AMF H.265 encoder.
3. Set the view mode to "Expert" or higher.
4. Check the "Deblocking Filter" option.
5. Record.
6. Check the log.

![Disabled in log, enabled in GUI](https://user-images.githubusercontent.com/44265435/96353169-634b7c00-10d2-11eb-842a-04458f4255e6.png)
![Enabled in log, disabled in GUI](https://user-images.githubusercontent.com/44265435/96353171-647ca900-10d2-11eb-99f0-71d68c0aa8e4.PNG)

## Additional information

This might be an issue specifically because of my 5700 XT. Then again, I'm submitting this issue first because it's, in my opinion, most likely an issue with OBS itself rather than the encoder.

**Comment by Fenrirthviti** [comment]
Expert output mode is effectively a "no warranty" mode. There is no validation of settings, and it is expected you understand exactly what options you should be selecting. I understand this isn't the best from an end-user standpoint, and I don't know that the AMF/VCE documentation is sufficient enough to be able to determine if this is a valid combination of settings.

Assuming the latter, where it's not valid, this is likely not something we will be fixing as validation of all the advanced settings is a monumental undertaking, and probably not something we could ever really get 100% accurate. That said, as I am not certain that's the issue here, I'll leave this open for others to take a look.

**Comment by QuartzSTQ** [comment]
Isn't Master supposed to be the "no waranty" mode? Either way the use for this option is debatable, unless you're recording losslessly and want to make sure, maybe.

**Comment by Xaymar** [comment]
Both Expert and Master modes are "no warranty" modes, as they have no real daily use. Master is a step above and even has the "no support" clause attached, which unfortunately deterred zero people from using it. I regret ever adding those two modes in the first place, and should have just listened to other people and made the options far less complex.

Anyway, back to the bug itself. The problem is that I forgot to invert `e` in [this code ](https://github.com/obsproject/obs-amd-encoder/blob/master/source/amf-encoder-h265.cpp#L898-L909), which actually also needs to be updated with the correct define, instead of a string. Currently it is:

```
bool Plugin::AMD::EncoderH265::IsDeblockingFilterEnabled()
{
	bool e;

	AMF_RESULT res = m_AMFEncoder->GetProperty(L"HevcDeBlockingFilter", &e);
	if (res != AMF_OK) {
		QUICK_FORMAT_MESSAGE(errMsg, "<Id: %lld> <%s> Failed to retrieve value, error %ls (code %d)", m_UniqueId,
							 __FUNCTION_NAME__, m_AMF->GetTrace()->GetResultText(res), res);
		throw std::exception(errMsg.c_str());
	}
	return e;
}
```

But it should actually be:

```
bool Plugin::AMD::EncoderH265::IsDeblockingFilterEnabled()
{
	bool e;

	AMF_RESULT res = m_AMFEncoder->GetProperty(AMF_VIDEO_ENCODER_HEVC_DE_BLOCKING_FILTER_DISABLE, &e);
	if (res != AMF_OK) {
		QUICK_FORMAT_MESSAGE(errMsg, "<Id: %lld> <%s> Failed to retrieve value, error %ls (code %d)", m_UniqueId,
							 __FUNCTION_NAME__, m_AMF->GetTrace()->GetResultText(res), res);
		throw std::exception(errMsg.c_str());
	}
	return !e;
}
```

**Comment by gxalpha** [comment]
This issue is about the old AMF encoder which as of OBS 28.0 we consider to be deprecated. Please use the new encoder implementation instead.
