### ISSUE TITLE
Windows list only updates when changing source

### ISSUE THREAD

**Issue by scls19fr** [obsproject/obs-studio#3710]
Hello,

Window (Fenêtre) list (combobox) doesn't update when a new application is opened (and so a new Window available).
![Capture d’écran 2020-11-08 à 21 15 51](https://user-images.githubusercontent.com/109167/98483359-ebbbc900-2207-11eb-97af-58b14ae5c3a8.png)

## Platform

Operating system and version: Mac 10.13.6
OBS Studio version: 26.0.2

## Expected Behavior

If user open a new window, then clicking on Window combolist in OBS should be updated correctly (showing with this new window)

## Current Behavior
Window combolist is not updated when required.

ie if you open a new window and try to see this window name in Window combo, it doesn't appear.

A workaround is to change source and go back to "Window grab" (Capture de fenêtre) and click now on Window combobox.

Maybe list of windows should be updated at each Window combobox click.

## Steps to Reproduce

1 Create a Scene with at least a "Window grab" (Capture de fenêtre) source
2 Click on Window combolist and see Windows names
3 Open with your OS a new application
4 Go back to OBS and click on Window combolist (nothing have been updated despite a new Window exists)

Kind regards

**Comment by dossy** [comment]
This bug will likely be fixed by #4863.

**Comment by RytoEX** [comment]
This is working as designed. The combobox contents are populated when the specific source's Toolbar is initialized, which happens when a source/sceneitem is selected. A change to this behavior would be a feature request rather than a bug. If you would like to submit a feature request, please submit one to [our Ideas site](https://ideas.obsproject.com/) or the #ideas-suggestions channel on [our Discord](https://obsproject.com/discord/).
