### ISSUE TITLE
Interact window not alt tabbing or showing up properly in the Task Manager

### ISSUE THREAD

**Issue by TreezyDoesIt** [obsproject/obs-studio#3749]
## Platform

Operating system and version: Windows 10 home, ver. 20H2, OS build 19042.630
OBS Studio version: ver. 26.0.2

## Expected Behavior
 A browser source opened using the interact menu via OBS has no maximize/minimize buttons, cannot be alt tabbed to and also doesn’t show up properly in the Task Manager

## Current Behavior
The window doesn’t appear as a proper window, not able to ALT tab to it, maximize or minimize it, also doesn’t appear on the Task Manager properly.

## Steps to Reproduce
Set up a local browser source, right click on it and select interact, no way to alt tab to it, maximize or minimize the window and it shows 4-5 instances of “OBS-browser-page.exe, with no indication that the window that was opened is one of these 

1. Set up a local browser source
2. Right click and select Interact
3. Window appears, but cannot be ALT tabbed to, minimized or maximized and doesn’t appear correctly labelled in the Task manager.

## Additional information
 I posted screenshots on Nov19th, 2020 in the windows help channel on the OBS discord server

**Comment by Fenrirthviti** [comment]
I'm confused what this report is intended for. The interact window is not intended to be used as an actual browser window, but as a workaround in cases where you absolutely need to interact with a browser page. All browser sources are sub-processes of the main OBS process, and show up as "obs-browser" in the task manager. I don't see any actual problem report here, can you please clarify what the issue is?

**Comment by thelifeofkb** [comment]
I have a widget I'm trying to interact with.  How can I distinguish which window is the interact window in task manager.  I'm trying to bring it to top to try and use a hot key with it.

**Comment by WizardCM** [comment]
This is not a bug, but intended behaviour. Interact is a child window.
