### ISSUE TITLE
Simplify UX - Scene Item transition - Use whole number for size, position and bounding box of a source

### ISSUE THREAD

**Issue by Trouffman** [obsproject/obs-studio#3830]
Simplify UI for Edit Transform Item window/dialog.

The Positions, size & Bounding box size show 4 digits past the comma, while this will always be Pixels based. And a thousands of does not make much sense.

These trailing values are also used in the config files.
ie.: 
`
"pos": {
                            "x": 2560.0,
                            "y": 1440.0
                        },
`

This is mostly graphical / UX improvment and not a functional bug.

## Platform
Operating system and version: Win 10 2H20
OBS Studio version: 26.0.2

## Expected Behavior
Size, Position and bounding boz settigns should use wholr number only.

## Current Behavior
The Transform Dialog box ( source ) show 4 trailing values that have no added-value.

![image](https://user-images.githubusercontent.com/2151317/101228247-ddc36180-3668-11eb-8b8d-68e1f8aa2588.png)

## Steps to Reproduce
1. right click on a source
2. select Transform > edit

Position, Size and Bounding box should be whole number only.

## Additional information
NB : this is normal, the size / positions infos are type vec2 which are float.

**Comment by skeletonbow** [comment]
I'm a little concerned if there are any cases where this could cause any problems on people's setups that are not obvious.  Some use cases for maintaining decimal pixel values are that it can be used for precise fractional division layout which does not work out to an integer multiple.  Such as 1/7th of the screen size or whatnot.  OBS handles these fractional values right now precicely and scale filtering will handle things just fine.

Animation/movement done by the move-transition filter or websockets or other plugins may be computing things at fractional pixel values as that is what the hardware actually uses internally.

Forcing everything to be on integer boundaries when the underlying hardware doesn't and it has permitted this configuration all along seems potentially shortsighted to me and not something that should be changed whimsically without fully exploring the ramifications to existing user's setups including the use of plugins, especially since it isn't fixing any actual bug or providing any huge benefit worth potential risk.

Definitely want to avoid a "oops, we didn't think about these usage cases, now we have to revert this and maybe break more stuff" situation IMHO.

**Comment by skeletonbow** [comment]
I'd like to add too that OBS already has a number of places in it's configuration of filters and other things where the precision of the user parameters does not expose the precision of the actual video hardware properly, leading to configuration that has visible jumps rather than smooth transitions.  The Luma Key filter is a prime example of this where it only provides 100 possible luma values in its property controls varying from 0.00 to 1.00, when the hardware can represent a lot more possible luma value steps with current usage in Truecolor, and much more so when HDR support is added later on.

Please don't artificially limit the precision of things without considering all usage cases.

**Comment by Trouffman** [comment]
@skeletonbow totally legit concerns. This should be for "display" and the value SHOULD NOT be converted to an integer (mostly because the whole logic use vec2 type which is float-based).

The decimals ARE needed from a programatic/rendering PoV IIRC (could not remenber which issues/discussion it was from).

The configurations / storage and underlying should KEEP the vec2/float, only the UI could diplay the whole number.

Hope this would not be too limiting, otherwise this is mostly a UI/UX thingy anyway.

**Comment by RytoEX** [comment]
This is a feature request in that it is asking us to change the current UI. The UI is currently working as designed. GitHub Issues are reserved for bug reports. If you would like to submit a feature request, please submit one to [our Ideas site](https://ideas.obsproject.com/) or the #ideas-suggestions channel on [our Discord](https://obsproject.com/discord/).
