### ISSUE TITLE
OBS Media Source RTMP hangs

### ISSUE THREAD

**Issue by sppmacd** [obsproject/obs-studio#3906]
When using OBS Media Source for RTMP sources, 

OBS

## Platform

Operating system and version: Linux 5.4.0-58-generic #64-Ubuntu x86_64
OBS Studio version: 26.1.0-2-g9201390a4

## Expected Behavior

OBS doesn't hang.

## Current Behavior

OBS stops refreshing preview. When you start stream, it hangs.

## Steps to Reproduce

1. Create a nginx rtmp server (https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/)
2. Start streaming on another computer: set address to rtmp://server-ip/live/aaa
3. Add Media Source: uncheck "Local File", set input to rtmp://server-ip/live/aaa, input format: rtmp, other options leave as is.
4. Click "Ok".

**Comment by TuxGamer** [comment]
Having the same issue :(

It seems to be slightly better with a VLC input source but it still freezes. Curiously it also frezees with just VLC without OBS, so not sure what the issue is.

When using the [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server), it yields a garbled image but no freezes (for me)
