### ISSUE TITLE
Missing libraries when linking libobs

### ISSUE THREAD

**Issue by darix** [obsproject/obs-studio#3924]
When building obs-studio 26.1.0 with `'-DCMAKE_SHARED_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now'` you run into the issue of some undefined symbols. The following patch fixes the issue for me:

```patch
Index: obs-studio-26.1.0/libobs/CMakeLists.txt
===================================================================
--- obs-studio-26.1.0.orig/libobs/CMakeLists.txt
+++ obs-studio-26.1.0/libobs/CMakeLists.txt
@@ -513,6 +513,9 @@ target_include_directories(libobs
 		"$<INSTALL_INTERFACE:${OBS_INCLUDE_DESTINATION}>")
 target_link_libraries(libobs
 	PRIVATE
+    m
+    dl
+    xcb
 		${libobs_PLATFORM_DEPS}
 		${libobs_image_loading_LIBRARIES}
 		${OBS_JANSSON_IMPORT}
```

would this be a patch to upstream or should we check for the libraries before linking?

I guess normally the libraries will be linked into the main binary and the symbols will be satisfied through that. but making the library self sufficient would be the correct way to go.

**Comment by computerquip** [comment]
At the least, that patch wouldn't work regardless since it's in a platform-agnostic section of the script. Windows won't have something like libxcb.

It seems like at least xcb should be included above where X11_XCB_LIBRARIES is added to libobs_PLATFORM_DEPS (via XCB_XCB_LIBRARY or XCB_LIBRARIES).

You might could add m and dl for systems under the UNIX condition.

That said, I'm not sure what's intended here so someone else will definitely have to chime in on that.

**Comment by darix** [comment]
yeah the patch was just a proof of concept. some more guidance is welcome.
