### ISSUE TITLE
Transitions not working when randomize playback is enabled in an image slide show

### ISSUE THREAD

**Issue by PRiMENON** [obsproject/obs-studio#3993]
## Platform

Operating system and version: Windows 10  Home 20H2 OSbuild 19042.685
OBS Studio version: 26.1.0(64-bit, windows)

## Expected Behavior

transition is working.

## Current Behavior

image is displayed without transition.
check off "Randomize playback", transition is working!

## Steps to Reproduce

1. create "Game" and "Image" scenes. 
2. click "Image" scene.
3. add "Image Slide Show" source.
4. setup following (X)
5. click to "OK"
6. switching "Game" scene.
7. switching "Image" scene.

(X) Image Slide Show settings.
* Visibility Behavior: Stop when not visible, restart when visible
* Slide Mode: Automatic
* Transition: Fade
* Time Between Slides: 8000 (default)
* Transition Speed: 700 (default)
* ✅ Loop
* ___ Hide when slideshow is done
* ✅ Randomize playback
* Bounding Size/Aspect Ratio: Automatic
* Image Files: select local directory(inlucde 3 jpg files).

## Additional information

![issue](https://user-images.githubusercontent.com/9590953/103392943-816a3980-4b63-11eb-9e82-b58c7c0a5349.png)

**Comment by RytoEX** [comment]
I see what's happening.

https://github.com/obsproject/obs-studio/blob/940a07e62f6acf1eeb36e6acea2374477abd45da/plugins/image-source/obs-slideshow.c#L945-L948
When the slideshow source is activated (becomes visible by switching back to its scene), `ss_activate` is called.  When "Visibility Behavior" is set to "Stop when not visible, restart when visible", this sets `restart_on_activate` and `use_cut` to true.

Then...
https://github.com/obsproject/obs-studio/blob/940a07e62f6acf1eeb36e6acea2374477abd45da/plugins/image-source/obs-slideshow.c#L702-L710
On the next video tick, this code does not run because "Randomize Playback" is enabled, so the conditions evaluate to `TRUE && !TRUE && TRUE` -> `TRUE && FALSE && TRUE` -> `FALSE`.  Thus, `use_cut` is never reset to `false` and the slideshow source keeps using cut as its transition when `do_transition` calls `obs_transition_set` here:
https://github.com/obsproject/obs-studio/blob/940a07e62f6acf1eeb36e6acea2374477abd45da/plugins/image-source/obs-slideshow.c#L259-L263


@cg2121, I see that you had initially introduced the `if (ss->restart_on_activate && !ss->randomize && ss->use_cut)` conditional in https://github.com/obsproject/obs-studio/commit/1666abe8e676da138fcae65aac02582b13b6383a.  Then, you changed this behavior in https://github.com/obsproject/obs-studio/commit/4c7e13bb8a527898f9ab96ebcad190d5da49b106, but that was later reverted in https://github.com/obsproject/obs-studio/commit/07c22cb885b08788b63ad023c1bdf3fe5d865a55.  Would it be sufficient to remove the `!ss->randomize` portion of the conditional to address this issue immediately?  Should we change the conditional and `ss_restart` like done in https://github.com/obsproject/obs-studio/commit/4c7e13bb8a527898f9ab96ebcad190d5da49b106?  I don't know if there was a particular reason the conditional was written that way in the first place or if the refactor in https://github.com/obsproject/obs-studio/commit/4c7e13bb8a527898f9ab96ebcad190d5da49b106 was to fix a bug or just to accommodate new functionality.

For what it's worth, I can confirm that removing `!ss->randomize` from the conditional fixes this specific issue.  That seems like the quickest and least invasive fix for now.  It does cause the slideshow to always reset to the same initial file, but that seems like less of an issue than not using the selected transition settings.
