### ISSUE TITLE
AttributeError: module 'obspython' has no attribute  error: 'obs_frontend_source_list_free'

### ISSUE THREAD

**Issue by MarioMey** [obsproject/obs-studio#4113]
## Platform

Operating system and version: Debian 10
OBS Studio version: 26.1.2-29-g84fb6fc74-modified (64 bits)

## Expected Behavior

`obspython` should have attribute `obs_frontend_source_list_free` to releases sources within a source list and to free the list (as says in [documentation](https://obsproject.com/docs/reference-frontend-api.html?highlight=obs_frontend_get_scenes#c.obs_frontend_source_list_free).

## Current Behavior

Error arrises:

```
error: [Python: test.py] ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
error: [Python: test.py] │ /home/mario/meytv/obs-scripts/test.py:4 in <module>                          │
error: [Python: test.py] │                                                                              │
error: [Python: test.py] │   1 import obspython as obs                                                  │
error: [Python: test.py] │   2 scenes = obs.obs_frontend_get_scenes()                                   │
error: [Python: test.py] │ ❱ 3 obs.obs_frontend_source_list_free(scenes)                                │
error: [Python: test.py] ╰──────────────────────────────────────────────────────────────────────────────╯
error: [Python: test.py] AttributeError: module 'obspython' has no attribute 
error: [Python: test.py] 'obs_frontend_source_list_free'
```
## Steps to Reproduce
1. Make a script with this code:
```
import obspython as obs
scenes = obs.obs_frontend_get_scenes()
obs.obs_frontend_source_list_free(scenes)
```
2. Run it as script.
3. Look at the log/console.
4. 
## Additional information
I'm coding a script that uses `obs_frontend_get_scenes` tons of times (it's inside a function). OBS UI starts to delay before I can do anything on it and its delay is incremental: it is getting worse. I just read that scene lists have to be released and I can't do it without that function.

**Comment by MarioMey** [comment]
I think issue is here, but I don't know C.... or H... or whatever language is.

https://github.com/obsproject/obs-studio/blob/master/UI/obs-frontend-api/obs-frontend-api.h#L67

**Comment by Scrxtchy** [comment]
As per the section of Scripting differences from the C API, it is instructed to use `source_list_release` instead of the function you use
https://obsproject.com/docs/scripting.html#source_list_release

In python, instead of returning a `obs_frontend_source_list` pointer, it actually returns a python list of sources
https://github.com/obsproject/obs-studio/blob/master/deps/obs-scripting/obs-scripting-python-frontend.c#L54-L76

The function suggested takes this list an releases all the sources from memory, however the list itself will not be cleared within the python script and still be populated with swig objects despite so
https://github.com/obsproject/obs-studio/blob/master/deps/obs-scripting/obs-scripting-python.c#L1111-L1129
