### ISSUE TITLE
Virtual Camera not working OBS 26.1.2 Mac OS 11.0.1

### ISSUE THREAD

**Issue by euoia** [obsproject/obs-studio#4242]
## Platform
OBS 26.1.2
Mac OS 11.0.1

## Expected Behavior
Clicking "Start Virtual Camera" causes an OBS camera to show up in other applications (e.g. FaceTime)

## Current Behavior
OBS Camera does not show up in any applications.

## Steps to Reproduce
1. Download OBS Studio
2. Install and run OBS Studio
3. Click Start Virtual Camera
4. Enter password when prompted
5. The button changes to "Stop Virtual Camera"
6. Open FaceTime
7. Click on the Video menu
8. Observe that there is no OBS Camera available

## Additional information
Checking available cameras with `system_profiler SPCameraDataType` shows an error with code signing on the plugin:

```
~|⇒ system_profiler SPCameraDataType
2021-02-15 13:00:23.044 system_profiler[5378:33864] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process: mapping process is a platform binary, but mapped file is not
Camera:

    FaceTime HD Camera:

      Model ID: Apple Camera VendorID_0x106B ProductID_0x1570
      Unique ID: <redacted>

    Microsoft® LifeCam Cinema(TM):

      Model ID: UVC Camera VendorID_1118 ProductID_1885
      Unique ID: <redacted>
```

**Comment by asher-the-thrasher** [comment]
Take a look at this guide, explains what apps it works with and how you could get around some restrictions. https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility

**Comment by PatTheMav** [comment]
Virtual Cameras (doesn't matter which one) won't work on macOS if the App you want to use it in has not whitelisted the provider in their app.

In the case of Facetime and (since Big Sur) QuickTime this means that only actual physical USB cameras can be used, because Apple doesn't allow these apps to load any third party libraries into their runtime (a Virtualcam is in essence a third party library loaded into an App to do "things") by default.

There might be ways around this by disabling macOS' now security measures, but that is territory where we cannot provide support.
