### ISSUE TITLE
mjpeg stream not played in its original framerate - media source plugin

### ISSUE THREAD

**Issue by ogmkp** [obsproject/obs-studio#4268]
## Platform

Operating system and version: Linux Debian 10
OBS Studio version: 26.1.1

## Expected Behavior

The media source plugin must read an mjpeg stream carried by UDP in its original framerate.

## Current Behavior

The media source plugin opens an mjpeg stream on udp://:port and slows down the images instantly until the stream is no longer playing.
Because raw MJPEG does not store any timing information, and I can't set the input framerate. If I could set the number of frames per second like on "ffplay udp://:4441 -f mjpeg -framerate 30" I wouldn't have problems.

## Steps to Reproduce

1. Create a new media source in a scene.
2. Uncheck local file
2. Set url: udp://:port or udp://localip:port
3. See first images coming and slowing down and stops playing

## Additional information

Log about this issue:
11:50:32.632: [Media Source 'Source média 3']: settings:
11:50:32.632: 	input:                   udp://:4441
11:50:32.632: 	input_format:            mjpeg
11:50:32.632: 	speed:                   100
11:50:32.632: 	is_looping:              no
11:50:32.632: 	is_hw_decoding:          yes
11:50:32.632: 	is_clear_on_media_end:   no
11:50:32.632: 	restart_on_activate:     no
11:50:32.632: 	close_when_inactive:     no
11:50:36.421: MP: av_read_frame failed: Erreur d'entrée/sortie (-5)

**Comment by maxdrfr** [comment]
No idea someone ?

**Comment by jp9000** [comment]
Apologies for the delay in response -- the reproduction steps should probably also contain server-side reproduction steps as well. For example, how we can create both a server and a client locally in order to properly reproduce the issue. Not all of us are too familiar with doing this sort of thing, so including as many steps possible to easily reproduce would help.

**Comment by maxdrfr** [comment]
Hi Jim.
You can stream your webcam's mjpeg to UDP without rencoding for example:
ffmpeg -f v4l2 -input_format mjpeg -framerate 50 -video_size 1280x720 -i /dev/video0 -c copy -f mjpeg udp://127.0.0.1:4441

If you play the feed with ffplay and set framerate, no problem:
ffplay udp://:4441 -f mjpeg -framerate 50

But if you add the feed to obs's media plugin, the video starts slow and get slowing down to stop:
![Capture du 2021-03-01 17-28-54](https://user-images.githubusercontent.com/17526713/109527345-d3700280-7ab3-11eb-86e0-a5d45b1dd05f.png)

Because mjpeg from a hardware device don't provide timing information for the framerate.

**Comment by maxdrfr** [comment]
Find this PR https://github.com/obsproject/obs-studio/pull/4967 , maye be a solution need to be tested.

**Comment by stopforumspam** [comment]
i'll try to replicate this for you with my local dev instance of that PR compiled

**Comment by stopforumspam** [comment]
I cant even manage to get ffplay to display a picture when configured to stream this way

**Comment by maxdrfr** [comment]
Do you know which parameter I can pass to require a framerate?
I've tried:
framerate=50
fps=50
fps=fps=50

**Comment by maxdrfr** [comment]
Found it, it's framerate=50
but the image was still slow.
I need to pass 1 MB or more of network buffer and everything is OK.
Your PR works great !

**Comment by stopforumspam** [comment]
Great to know. Let's hope they merge it
________________________________
