### ISSUE TITLE
obs-filters: NVAFX filter errors out when first added

### ISSUE THREAD

**Issue by derrod** [obsproject/obs-studio#4441]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/SuuBYH830bc3Tz0D

### Expected Behavior

Suppression intensity should be adjustable.

### Current Behavior

Intensity is not adjustable until OBS is restarted.

### Steps to Reproduce

1. Add filter
2. Try changing intensity
3. Notice no worky

### Anything else we should know?

Logs gets spammed with errors when trying to change intensity.

**Comment by pkviet** [comment]
thanks for the report @derrod .
The issue comes from this line: https://github.com/obsproject/obs-studio/blob/27.0.0-rc1/plugins/obs-filters/noise-suppress-filter.c#L344
When the noise suppression filter is first loaded it loads rnnoise which prevents allocation and initialization of nvafx (rtx denoiser).
I'll push the fix in a bit.

**Comment by pkviet** [comment]
Fixed in PR #4458 .
