### ISSUE TITLE
When switching audio monitor output device - monitor audio stops

### ISSUE THREAD

**Issue by Fred-DTV** [obsproject/obs-studio#4463]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/xCZi22mtkq1wYOpF

### Expected Behavior

Audio monitoring output continues on new device

### Current Behavior

Audio monitoring output stops

### Steps to Reproduce

1. open Settings - Audio
2. change Monitoring device

### Anything else we should know?

After a restart of OBS it will work again

**Comment by wangshaohui1314** [comment]
I can reproduce this issue by another steps:
1. open settings of OBS, choose monitor device with "default";
2. start monitoring a media source;
3. open Window settings, switching default output device, audio monitor never work normally;

As commit in https://github.com/obsproject/obs-studio/commit/74e64481951e9247a7dec0af6d3660027dd57fb4#diff-93b96c16580b270f3d204c4e59c972a9c361a5cc7ba6f21c7cfa964c5ae894ea, maybe we should also detect event for output device and reinitialize monitor module to apply latest default device.

**Comment by MPeti1** [comment]
I was searching if theer's an issue for my problem. This seems similar enogh, but please tell me if it needs a different one.

I've recently noticed that if I have monitoring enabled for an audio capture, and my audio device (wireless headphone) gets disconnected and then reconnected, OBS won't play the monitor of the audio capture to headphone until I open the "advanced audio properties" menu and switch off and on the monitoring on all of the monitored devices.

I also noticed that if for some reason I need to restart the Audiosrv of Windows, OBS won't recover the audio streams even after Audiosrv has restarted. In this case, I think only a reopen helps, but I think I had a solution without that, like the one for the previous problem.

I think these are suitable here because these seem to be related to the problems mentioned by others here: OBS (probably) not listening for audio device state changes.

**Comment by asher-the-thrasher** [comment]
can confirm this on macOS, 
repo steps:
0) have the audio monitoring working on one device/source
1) switch the monitoring device in settings > audio
2) observe how the audio isnt being sent to the monitor
3) change advanced audio properties > monitoring to something other than what it is on then change it back
4) it will start working

NOTE: if you change the device back to the original device in settings > audio then it will work without messing with advanced audio properties.
