### ISSUE TITLE
Exporting a profile shows up the "Open file" dialog instead of the "Save as" dialog

### ISSUE THREAD

**Issue by VosaXalo** [obsproject/obs-studio#4548]
### Operating System Info

Other

### Other OS

KDE Neon 20.04

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/5AL1cwilHnMxw9x_

### Expected Behavior

If I choose to export a profile (menu Profile/Export), I should be able to save a json file with the profle's details on my local disk.

### Current Behavior

When I choose to export a profle (menu Profile/Export), the dialog for "Open a file" shows up and I can't actually save the profile.

### Steps to Reproduce

1. Open the menu Profile / Export
2. the dialog for "Open a file" shows up
3. I can't save the profile
...

### Anything else we should know?

- I'm running OBS Studio through the flatpak package
- the "Scene collection" exporting  (menu Scene collection / Export) is working correctly (_this is the "same" functionality as the one for the profiles_).

**Comment by RytoEX** [comment]
This appears to work fine on Windows and also Ubuntu when installed via our PPA.  You select a directory to Export to (the dialog says "Open"), and then the existing Profile directory is copied to the selected destination directory.

@GeorgesStavracas If this is actually an issue, should this be on the Flathub repo instead of here?

**Comment by VosaXalo** [comment]
@RytoEX Yes, I can choose where I want to save the profle, but the dialog says "Open" instead of "Save", and I can't actually save it.
As I said above, this is not happening with the Scene Import/Export, where correctly "Import" shows up the Open dialog, and "Export" shows up the Save dialog.

**Comment by WizardCM** [comment]
As a side note, the reason the two Exports behave differently:

1. Export Scene Collection uses `QFileDialog::getSaveFileName()` to name a file to save
2. Export Profile uses `QFileDialog::getExistingDirectory()` to choose a directory to save to

This is on purpose on our side, and behaves correctly (as far as I know) on Windows, macOS & the Ubuntu PPA.

**Comment by VosaXalo** [comment]
@RytoEX @WizardCM Ah, ok, now I see :-). In fact clicking on the "Open" button with the path I want, actually it saves the profile. So, no issue after all. I'm sorry.
But I have to say that this behavior is a little bit "misleading". As a user I always expect to see "Save" if I want to save, and "Open" if I want to open. Just my opinion of course.

**Comment by RytoEX** [comment]
I don't consider this to be a bug.  This is a native dialog to choose a directory to save to, which is an intentional design decision because a Profile can contain many files, so we copy/save the entire existing Profile directory from the config directory.  The native dialog does not let us specify the text of the action buttons.
