### ISSUE TITLE
OBS click to Stop Streaming   will not stop 

### ISSUE THREAD

**Issue by OG-C** [obsproject/obs-studio#4602]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

21:39:30.139: CPU Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 21:39:30.139: CPU Speed: 2904MHz 21:39:30.139: Physical Cores: 6, Logical Cores: 6 21:39:30.139: Physical Memory: 16299MB Total, 5109MB Free 21:39:30.139: Windows Version: 10.0 Build 19042 (release: 2009; revision: 867; 64-bit) 21:39:30.139: Running as administrator: true 21:39:30.139: Aero is Enabled (Aero is always on for windows 8 and above) 21:39:30.139: Windows 10 Gaming Features: 21:39:30.140: 	Game DVR: On 21:39:30.224: Sec. Software Status: 21:39:30.229:  21:39:30.230:  21:39:30.231:  21:39:30.231:  21:39:30.241: Current Date/Time: 2021-04-12, 21:39:30 21:39:30.241: Browser Hardware Acceleration: true 21:39:30.241: Portable mode: false 21:39:30.708: OBS 26.1.1 (64-bit, windows) 21:39:30.708: --------------------------------- 21:39:30.709: --------------------------------- 21:39:30.709: audio settings reset: 21:39:30.709: 	samples per sec: 48000 21:39:30.709: 	speakers:        2 21:39:30.733: --------------------------------- 21:39:30.733

### Expected Behavior

When click the "Stop Streaming" button, the push stream will be stopped immediately.

### Current Behavior

Clicking the "Stop Streaming" button will change to "Stop Streaming**...**" and it will not stop immediately, and sometimes you need to click the Stop button again. This failure is easier to reproduce when the frame loss rate turns red.

### Steps to Reproduce

1.When the frame loss rate turns red
2.Click "Stop Streaming"

### Anything else we should know?

Translated by Google

**Comment by WizardCM** [comment]
It does not stop immediately because it's essentially "finishing" sending frames. Once all frames are sent, it'll stop automatically. Clicking it again will override this behaviour. This is by design.

Additionally, we do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by OG-C** [comment]
> It does not stop immediately because it's essentially "finishing" sending frames. Once all frames are sent, it'll stop automatically. Clicking it again will override this behaviour. This is by design.
> 
> Additionally, we do not use GitHub Issues for support questions.
> 
> Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

This is very inconvenient. Can you remove this mechanism or give users a choice? Let users mistakenly think that the live broadcast has been closed, resulting in some unsuitable content being broadcast live.

https://user-images.githubusercontent.com/82382147/116196971-b92a6c00-a766-11eb-839e-9a77e30c5b9a.mp4

**Comment by WizardCM** [comment]
The "catchup" frames are only up to the time when you clicked "Stop Streaming" the first time. Anything past that is not encoded, so there is nothing that will be sent accidentally.

**Comment by Fenrirthviti** [comment]
Also, to clarify, this only happens in situations where the encoder or output is lagged. I notice in your video that you're dropping a significant amount of frames due to network instability or lack of speed, so there is nothing we can do to fix that as the software is working correctly. Lower your bitrate or look in to correcting whatever network issues you are having preventing stable streaming.
