### ISSUE TITLE
OBS does not correctly label additional [Video Toolbox] GPUs in Encoder list (27.0.0 RC2 macOS)

### ISSUE THREAD

**Issue by MisutaaAsriel** [obsproject/obs-studio#4611]
### Operating System Info

macOS 11.2

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

N/A

### Expected Behavior

OBS should differentiate additional AppleVT Hardware encoders, if available **or** default to an external GPU encoder (if connected).

Previous versions of OBS hardcoded the internal GPU (Intel QuickSync) encoder using Apple Video Toolbox. **Release Candidate 2 for version 27.0.0 remedies this issue**. However...

### Current Behavior

Currently, the eGPU & iGPU encoders are listed identically within the encoder list.
![OBS Encoder Menu](https://user-images.githubusercontent.com/8140068/116339720-8d79a700-a7a3-11eb-8c22-9769df769f99.png)

### Steps to Reproduce

1. Install OBS 27.0.0 RC2 for Mac
2. Connect an external GPU with AppleVT support to the Mac.
3. Launch OBS
4. Open Settings and navigate to the encoding options under **Output**
5. Open the dropdown list — 2 Apple VT H.264 Hardware encoders will be listed

# Additional Information & Suggestions

When using **[VTCopyVideoEncoderList](https://developer.apple.com/documentation/videotoolbox/1522108-vtcopyvideoencoderlist)** in a simple test application, one can see that the eGPU encoder is additionally identified by both an identifer at the end of its **Encoder ID**, as well as a **GPURegistryID**, which is used when specifying external encoders.

![Test Application In Playgrounds](https://user-images.githubusercontent.com/8140068/116339956-f6f9b580-a7a3-11eb-80fb-9504e212e324.png)

Without obtaining the name of each GPU connected, it should at the very least identify each additional hardware encoder as "Apple VT H.264 Hardware Encoder (External)", identifying it as an external encoder by property of a GPU Registry ID (these are only listed with secondary/external GPUs).

Alternatively, using MetalKit, one can query the available GPUs using **[MTLCopyAllDevices](https://developer.apple.com/documentation/metal/1433367-mtlcopyalldevices)**, iterate through the list, and when GPURegistryID is present in a VTEncoder, search for its matching device by registryID in the list, and label it based on the device name.

**Here is an example program**, runnable via Swift Playgrounds, which will enumerate VTEncoder devices, identify any external hardware devices, and label them based on their Metal device name: **[Code (Gist)](https://gist.github.com/MisutaaUrufu/22206996d21182c8f431506bc0ed458b)**

![screenshot](https://user-images.githubusercontent.com/8140068/116344745-6a072a00-a7ac-11eb-9bb6-fd8e58275ca7.png)

**Comment by WizardCM** [comment]
For those looking into this issue, here's how we determine the text to show:

https://github.com/obsproject/obs-studio/blob/20bbc9794daf088ca6ea880a7c42c9c9424448a0/plugins/mac-vth264/encoder.c#L834-L844

This fetches the translated string. We store the following data about each encoder (because it's all we care about):

https://github.com/obsproject/obs-studio/blob/20bbc9794daf088ca6ea880a7c42c9c9424448a0/plugins/mac-vth264/encoder.c#L935-L948

**Comment by MisutaaUrufu** [comment]
Whilst I am not familiar with C/Objective-C, Swift can be converted into Obj-C, and vice versa, as well as do both use the same foundational classes and APIs\*; as such, I thought I'd offer an example Swift implementation for retrieving the name of additional GPUs on the system, along with an example script which demonstrates how it may be used.

### _[[Gist] vtencoders.swift](https://gist.github.com/MisutaaUrufu/148be2f4d978db54891693594eb683d9)_
_The most relevant snippet is as follows_:
```swift
import Foundation
import VideoToolbox
import MetalKit

// Enumerates Available GPU devices and saves them to an array
let gpuDeviceList = MTLCopyAllDevices()

// Computed variable takes the array of MTLDevice(s) and converts it into a dictionary, which can return the GPU name by ID if a registry is provided
var gpuList: Dictionary<AnyHashable, AnyHashable> {
    var gpuSet = Dictionary<AnyHashable, AnyHashable>()
    for device in gpuDeviceList {
        gpuSet[device.registryID] = device.name
    }
    return gpuSet
}

// Function checks if ID exists as a key in the dictionary, and returns the name if so
func getEncoderDeviceName(byId id: AnyHashable) -> String {
    if let deviceName = gpuList[id] {
        return deviceName as! String
    } else {
        return ""
    }
}
```

Hopefully it can provide a useful reference, to help with understanding how to convert a GPURegistryID into a device name, and in writing a C function of similar nature to affix the device name onto the display name when necessary.

\*_Most Swift foundation classes are either bridges-to, or reimplementations-of, their Obj-C equivalent. Likewise, APIs are accessible from both langauges._

**Comment by StefanRied** [comment]
I'd love to have this. OBS already works great with eGPUs on the Mac, but the better the settings work the more people will use it. For those that are not familiar with external GPU on the Mac, here is a page with tons of hints https://egpu.io/
Basically, an external GPU makes a current Macbook Pro nearly as powerful as a Mac Pro Desktop Computer. Even older Macbooks prior to the USB-C generation, can use Thunderbold 2 and boost the total performance. If you don't buy an real expensive GPU, simply by putting the GPU heat of of the Laptop, the CPU will not experience thermo throttling. Gaming or simply running Zoom or MS Teams in parallel to OBS recording or broadcasting becomes real joy even on older Macbooks.
Thanks to all supporters.

**Comment by MisutaaUrufu** [comment]
@StefanRied OBS actually doesn't play well with eGPUs currently. Currently the public release (26.1.2) hard codes the internal Intel GPU as the hardware encoder. OBS has also had numerous rendering issues with eGPUs in mine and others experiences (though most have recently been fixed).

Release Candidate 2 for 27.0.0 **does** play well with eGPUs in my experience, but it fails to properly label any additional GPUs beyond the default with unique identifiers.

This means the only way to know which GPU you selected is to start a recording or stream, then check the GPU tab of Activity Monitor for which GPU VTEncoderXPCService is assigned to.

Hence this bug report.

**Comment by StefanRied** [comment]
Thanks a lot. I was already referring to the 27 release candidate.
Although Apple is officially supporting eGPUs natively since a while (https://support.apple.com/en-us/HT208544) it's still somehow the company's best kept secret. Especially OBS 26 is on an older Mac Book basically unusable and OBS27 with eGPU support would run so easy on the six year old Macbooks. If I would be the OBS initiator, I would make much more communication around.
have a weekend.

**Comment by MisutaaUrufu** [comment]
> Although Apple is officially supporting eGPUs natively since a while … it's still somehow the company's best kept secret. Especially OBS 26 is on an older Mac Book basically unusable…

This is because Apple Video Toolbox and eGPU support has some long standing misconceptions.

The primary one being that Video Toolbox will "automatically" select the "best" GPU in any situation; in reality, it is up to the developer, and the "primary" encoder for any codec will be the primary GPU (which in most cases is the Intel iGPU). — AVT is designed for direct access to encoders on the system, so the behavior misattributed to it may in fact exist in higher-level encoding APIs.

OBS 26.1.2 ≥ fell into this misconception, **hard-coding the primary encoder** when Apple VT hardware encoding was specified. This meant it was impossible to use any additional GPUs on the system for video encoding.

Likewise, whilst Apple provided "Prefer external GPU" option for applications as of 10.14, this is designed as a stop-gap, and for backwards support with older applications, not as an actual developer function. Best practice is for applications to be GPU aware, & to either detect and offload Metal API calls to the additional GPUs, or to provide the user with the option to select which GPU is to be used for rendering. — This fact can be seen in OBS 26.1.2 ≥, as _even with "Prefer external GPU" marked, Video Toolbox calls still used the Intel GPU_ (as it was hard coded). — The option is not a catch all, and will still yield to the developer's code preference, even if that was not the intent.

*****

For those managing this issue, feel free to mark these messages as off-topic. Whilst i feel it is helpful in explaining how these issues may have came about, they add nothing to resolving the issue.

**Comment by gxalpha** [comment]
As presented, this report is a feature request, which doesn't belong on GitHub Issues.
Closing as we also don't believe we'll ever change this, as per https://github.com/obsproject/obs-studio/pull/5424#issuecomment-1274926001.
