### ISSUE TITLE
linux: Window Capture fails with glXCreatePixmap failed: BadAlloc

### ISSUE THREAD

**Issue by rdgh8** [obsproject/obs-studio#4694]
### Operating System Info

Other

### Other OS

Pop!_OS 20.10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/sl6_0180LRyOqmkj

### Expected Behavior

OBS captures window of program (Microsoft Teams) using client side decorations

### Current Behavior

Black screen on preview window in OBS with the error `xcompcap: glXCreatePixmap failed: BadAlloc (insufficient resources for operation)`

### Steps to Reproduce

1. Open OBS
2. Under sources, add Window Capture (Xcomposite)
3. Change window to a program with CSD
4. Click ok
5. View preview window

### Anything else we should know?

Also, is there a way to add a pause recording button to the OBS system tray? I don't like to use shortcuts, and it's inconvenient to go into OBS to pause the recording every time.

**Comment by kkartaltepe** [comment]
Thanks I noticed we dont have an open issue for this so I have adjusted your title to reflect this and added the primary identifier of this issue to the OP.

This issue is not directly related to CSD (maybe they are a contributing factor?) as I am able to capture such windows and most users have successfully worked around this error by try different DEs (for example KDE is much less prone to the issue). To my knowledge this affects AMD and nvidia hardware and is most prominent on gnome DE but appears on less commonly on i3, kde, etc.

For now there is no real workaround sometimes resizing the window to a certain size will result in a successful capture but this may be too small to be usable. And not every user can/want change their DE to work around a failed capture.

**Comment by rdgh8** [comment]
Thank you, my mistake. I thought it was related to CSD as OBS can only record a Brave window when I have system titlebars turned on for it.

**Comment by OwczarekGit** [comment]
Have the same problem but in my case i try to capture spotify two times with different cropped parts of it, one capture works fine but when i create another xcomposite capture of the same window i'm getting "BadAlloc".

**Comment by kkartaltepe** [comment]
Attempting to open two captures will always fail with this error. This bug is for attempting to capture a window that is not already captured in obs or other software.

**Comment by awarus** [comment]
obs 27.0.0-rc1 works fine in Ubuntu 20.04.2 LTS(5.4.0-72 kernel) and Gnome 3.36.8 with different Xcomposite sources(MS Teams, VScode, multiple sources, etc.)

**Comment by thecoder08** [comment]
Similar issue on Debian unstable, using nvidia graphics card.

**Comment by RytoEX** [comment]
We have since dropped support for GLX (as of OBS Studio 28). If you experience a similar issue with EGL, please feel free to open a new Issue with new Steps To Reproduce.
