### ISSUE TITLE
Cannot click and drag images into window to create sources

### ISSUE THREAD

**Issue by Gamershy** [obsproject/obs-studio#4751]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc5

### OBS Studio Log URL

N/A

### Expected Behavior

In previous versions, I could click and drag an image onto the OBS window to create a scene

### Current Behavior

A black "no" symbol replaces my cursor when attempting.

### Steps to Reproduce

1. click and drag image onto OBS Window
2. Doesn't work

**Comment by WizardCM** [comment]
This happens if OBS is running as administrator. This is an operating system limitation, and as you have not provided a log we cannot confirm for sure.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
