### ISSUE TITLE
Advanced audio properties balance slider does not update after undo / redo

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#4763]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

N/A

### Expected Behavior

Balance slider updates after undo / redo.

### Current Behavior

Undo / redo of balance slider does not update.

### Steps to Reproduce

1. Open advanced audio properties
2. Move balance slider
3. Undo / redo the action

### Anything else we should know?

The value is actually saved, just the UI is not updated.

**Comment by RytoEX** [comment]
Isn't this what #4760 originally reported?  Though it looks like it was edited instead to report a crash.

**Comment by notr1ch** [comment]
Yes, the original title described this behavior but the content of the report was about the undo / redo of the sync offset values causing a crash. I created this issue to address it and renamed #4760 for clarity.

**Comment by RytoEX** [comment]
For the record, the original title of 4760 was "The Balance slider bar of Advanced Audio Properties can't change by undo/redo in OBS RC6" and the original issue description was:
> The Balance slider bar of Advanced Audio Properties can't change by undo/redo in OBS RC6

It's fine if it has instead become a crash report bug.  I was just confused because the initial email notifications did not match the issue, and then this popped up.
