### ISSUE TITLE
16 Bit Images Displaying Incorrectly

### ISSUE THREAD

**Issue by abney317** [obsproject/obs-studio#4787]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/MZFvICXTwJsCHptK

### Expected Behavior

![image](https://user-images.githubusercontent.com/15952844/120400915-75e29080-c304-11eb-85b5-b8e9d7f83288.png)

### Current Behavior

A few images from my stream layout became lighter colored than they were before after upgrading to 27.0.0. Found that it was because they were saved through Photoshop as 16 Bit/Channel. Opening and changing the files to 8 Bit/Channel fixed the images to display as expected.

### Steps to Reproduce

Here are copies of the 2 images test with:

![16bit](https://user-images.githubusercontent.com/15952844/120401122-e689ad00-c304-11eb-98d3-7210400589c2.png)
![8bit](https://user-images.githubusercontent.com/15952844/120401125-e7224380-c304-11eb-9f82-9f975afae386.png)

**Comment by YorVeX** [comment]
Just made the switch from 26.1.1 to 27.0.1 today (I always leave out the X.X.0 versions) and immediately noticed several scenes are brighter than before. At least it's consistent through different ways of creating opacity.

In some scenes a pre-rendered video loop is used which has an alpha channel integrated that creates a 90% opacity effect, leaving some visibility on another background video loop. In another scene, however, an image is used that doesn't have any alpha channel integrated, although it's of the same design. Instead, a Color Correction filter is applied to it with Opacity set to 90%. In all of these scenes the background video loop that is covered has the same brightness.

However, in 27.0.1 the video loop is brighter in total than in 26.1.1 in all of the scenes.

OBS 26.1.1:
![image](https://user-images.githubusercontent.com/528974/123565583-b4615300-d7bd-11eb-9812-0dc54d13760d.png)

OBS 27.0.1:
![image](https://user-images.githubusercontent.com/528974/123565591-bcb98e00-d7bd-11eb-9a29-a46cc6016eab.png)

I guess to achieve the same brightness I had before I need to apply an additional Color Correction filter to the overlapping video loop now.

I don't even know whether this is wrong or it has been wrong for all previous OBS versions and is now finally fixed, because when I manually put one image in a layer above the other in gimp and set the top layer to 90% opacity I get the same brightness that OBS 27.0.1 has. The only thing that confused me is that this issue says "it's brighter than before and this is wrong" and that this is supposed to be fixed in 27.0.1, which reads like this version should no longer make my scenes look brighter than they looked in 26.1.1. Thankful for anything that clears up my confusion.

**Comment by jpark37** [comment]
This is a separate issue. We did make fairly large changes to make alpha handling "correct" in OBS 27, which you can learn more about here: https://github.com/obsproject/obs-studio/wiki/Linear-Color-Blending

If you need additional help, please use Discord or forums.

**Comment by YorVeX** [comment]
Thanks, I totally missed this!
