### ISSUE TITLE
the menus of copy filters are different in OBS 27.0

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#4789]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/FwgKMul7uc0gd_sr

### Expected Behavior

Uniform

### Current Behavior

Non-Uniform
![obs27](https://user-images.githubusercontent.com/16969250/120410238-298b6500-c385-11eb-9a23-d5a745987472.jpg)

### Steps to Reproduce

1. add a audio input capture
2. This "copy filters" option is not available in the right-click menu
3. but there be available the right-click menu of the audio fixer.
...

**Comment by WizardCM** [comment]
Please fill in the issue template. A screenshot is not enough.

**Comment by Fenrirthviti** [comment]
Not enough information to be actionable. Please use the support channels on our Discord or the forums for further assistance.

**Comment by RytoEX** [comment]
After some time contemplating this Issue, I understand what this is describing.  When you right-click on a source in the Sources list that does not have any filters, the "Copy Filters" item is disabled.  When you right-click on an audio source in the Audio Mixer that does not have any filters, the "Copy Filters" item is enabled.  This is the inconsistency that was described.  I'll reopen this Issue and open a PR shortly.

@iesvme In the future, please fill out the issue report completely from the start.  The "Current Behavior", "Expected Behavior", "Steps to Reproduce", and "Anything else we should know?" fields all support image and file uploads (and drag-and-drop).  When the Issue Form is only partially filled out, we get the incomplete report emailed to us, and it can result in an incomplete understanding of what you're trying to report.

**Comment by RytoEX** [comment]
Sorry, I just saw #4790, so I'll close this and target that.
