### ISSUE TITLE
"Encoder ID 'vt_h264_hw' not found" on macOS when upgrading from OBS Studio 26.1.2 or earlier to OBS Studio 27.0.0

### ISSUE THREAD

**Issue by ACB-prgm** [obsproject/obs-studio#4799]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.0.0

### OBS Studio Version (Other)

26.1.2 (Works)

### OBS Studio Log URL

X

### Expected Behavior

Record when clicking reocrd

### Current Behavior

Was given the following error when trying to record.:

> Starting the output failed. Please check the log for details. Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date

Drivers are up to date. Here are my system specs:
<img width="234" alt="Screen Shot 2021-06-02 at 12 13 15 PM" src="https://user-images.githubusercontent.com/63984796/120523632-1d62d000-c3a4-11eb-9eca-b189955e5b0c.png">

Already downgraded back to 26.1.2 so I can't grab the log.  Everything works as it should on 26.1.2.

### Steps to Reproduce

1. Open OBS
2. Click "Start Recording"
3. Error
...

**Comment by dodgepong** [comment]
This report is not actionable without a log.

**Comment by danikino** [comment]
Same error here on Ubuntu 20.04 . previous version worked all right.

**Comment by WizardCM** [comment]
Without a session log, we cannot look into this issue. Please provide a session log (Help -> Log Files -> Upload Current Log)

**Comment by danikino** [comment]
Thank you for your prompt response . this is the log :https://obsproject.com/logs/zlggnAkVG0zUS84o

**Comment by WizardCM** [comment]
@danikino In your case, disable Psycho Visual Tuning in Settings -> Output for the NVENC encoder, as the 600/700-series don't support it.

**Comment by bigpigger** [comment]
thanks

**Comment by Pittan** [comment]
Hello! I'm facing same issue here.
Here is my log, hope this will help 🙏
https://obsproject.com/logs/mazhF4kXXRd8wtyZ

**Comment by danikino** [comment]
Sorry, but i didn't find Psycho Visual Tuning in Settings -> Output.

**Comment by Gol-D-Ace** [comment]
@Pittan 
Try switching to x264, start a recording/ steeam, stop it and then switch back to the hardware encoder.

**Comment by Gol-D-Ace** [comment]
@WizardCM 
Don't think that's possible for the ffmpeg nvenc.
(Linux)

**Comment by RytoEX** [comment]
> 
> 
> @WizardCM
> Don't think that's possible for the ffmpeg nvenc.
> (Linux)

@Gol-D-Ace 
I thought users could disable Psycho Visual Tuning on Linux since #4477?  @danikino 's issue actually appears to be #4785, NVENC failing on a Kepler GPU if attempting to enable Psycho Visual Tuning.

The original issue here was about macOS, so let's focus on that here.

----

After some testing by others on the team, we believe we know what has happened.  This has to do with changes from #4105.  What appears to have happened is that the user had a previously configured "vt_h264_hw" encoder.  With the changes in #4105, that encoder ID no longer exists in OBS, because we now use Apple's encoder IDs instead of our own internal IDs.  The encoder IDs have changed like this:

* vt_h264_hw -> com.apple.videotoolbox.videoencoder.h264.gva
* vt_h264_sw -> com.apple.videotoolbox.videoencoder.h264

If you manually change the encoder to one of the options in the UI, it should work fine.  We'll look into if we're able to handle this more gracefully in a future update.

**Comment by Gol-D-Ace** [comment]
@RytoEX 
Looks like I missed that one.
Sorry

In that case yeah it should be possible.

**Comment by WizardCM** [comment]
> vt_h264_hw -> com.apple.videotoolbox.videoencoder.h264.gva
vt_h264_sw -> com.apple.videotoolbox.videoencoder.h264

@RytoEX I do wonder if we can set an alias of some kind so that Intel users automatically get pointed internally to the new encoder ID? Or if it's better to leave this one-time manual reconfiguration..

**Comment by RytoEX** [comment]
> 
> 
> > vt_h264_hw -> com.apple.videotoolbox.videoencoder.h264.gva
> > vt_h264_sw -> com.apple.videotoolbox.videoencoder.h264
> 
> @RytoEX I do wonder if we can set an alias of some kind so that Intel users automatically get pointed internally to the new encoder ID? Or if it's better to leave this one-time manual reconfiguration..

We can probably check if the encoder ID is an old value and swap it for the corresponding new value.  I don't know for sure.

**Comment by Pittan** [comment]
> @Pittan
> Try switching to x264, start a recording/ steeam, stop it and then switch back to the hardware encoder.

@Gol-D-Ace 
Thank you for your response! 
I was previously using x264, so I think that operation doesn't make sense to me. Also, I tried that and it won't work, so I downgraded my environment to v26.x and it started to work again! 

It seems there was a problem in the code, please mention me is there anything I can help with the test.

**Comment by WizardCM** [comment]
@Pittan Your log file confirms you were using the Apple VT hardware encoder.

**Comment by jmurphyau** [comment]
When trying to get OBS to work just now, the options to change the encoder were greyed out. I'm not sure if the dropdown to select between "Simple" and "Advanced" was selectable or not, and it's too late to check now that I've fixed it, but the dropdown to change encoders was not selectable.

I had to find this thread, discover what the issue was and then use terminal to grep for any instance of "vt_h264" so I knew where to update it.

For anyone else who finds themselves in this situation, you can run this command to discover which files you need to update:

```
find ~/Library/Application\ Support/obs-studio -type f -exec egrep -H 'Encoder=vt_h264' {} \; 
```

To the OBS team: it seems you do have a situation where this is an irrecoverable issue

I tested on another Mac running version 26 - made sure the hardware encoder was selected - and after the upgrade I was able to selecte between the different encoders.. So not sure how widespread or what conditions need to be met for it to be greyed out like it was.

**Comment by PatTheMav** [comment]
@jmurphyau Would you be able to find the `basic.ini` of your profile from before the change (TimeMachine should help, APFS has local snapshots and if you browser to a snapshot from yesterday you should be able to recover that file).

FWIW I tested this situation on several Intel-based Macs as well as an M1-based Mac and in all cases OBS fell back to the first encoder in the list when a now non-existing encoder ID was found (which means VT hardware for streaming and "Use Stream encoder" for recording) and had no issue selecting another encoder - so for now I'm unable to reproduce the "greyed out selection box" issue.
