### ISSUE TITLE
Sliders get blocked if the modified_callback returns true

### ISSUE THREAD

**Issue by bfxdev** [obsproject/obs-studio#4817]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/DQc-eTZ8RAE1f192

### Expected Behavior

As usual, it should be possible to move back and forth any property slider when the mouse button is kept clicked, whatever the additional settings.

### Current Behavior

When the slider has a callback function set with obs_property_set_modified_callback, and the callback function returns true (to trigger a refresh of the GUI), then the slider remains blocked after the very first movement. After releasing the mouse button it is possible to drag the slider again, but again it gets blocked after the first movement.

### Steps to Reproduce

1. Use the Lua or Python script
2. Menu -> Tools -> Scripts
3. Try to move the slider
[test-slider.zip](https://github.com/obsproject/obs-studio/files/6603229/test-slider.zip)

**Comment by kkartaltepe** [comment]
The refresh of GUI is key here as the slider you are dragging may be removed. In fact the cause of this issue is indeed that it is deleted and then recreated based on the modified properties set.

Generally you should avoid using sliders if that setting may cause the set of properties to be modified. If it's not the case that modifying the slider causes the set of properties to be modified then you shouldn't be returning true.

**Comment by WizardCM** [comment]
In that case, this sounds like expected behaviour?

**Comment by kkartaltepe** [comment]
Im not sure if there is a decided behaviour, but it would be nice to support this as it would make v4l2 much nicer to work with as well.

**Comment by bfxdev** [comment]
I think I understand the issue, so it is a side effect of re-creating the slider widget, part of the complete properties widget refreshed by returning true. There is no link between the QT object that just disappeared and the newly created object.

I don't know for v4l2, but my use case would be to adjust some parameters of a curve (e.g. RGB color correction) and display a picture of the curve, generated on-the-fly as data URI, as part of the HTML description of another property. A bit like this [example of a property description with an image](https://obsproject.com/forum/threads/tips-and-tricks-for-lua-scripts.132256/#post-487565), but with a live changing picture.

**Comment by gxalpha** [comment]
As noted above, this is a direct result of refreshing the properties. We consider this expected behavior, and would recommend looking for another way to achieve your result, in case you haven't found one already (sorry for the super long delay here).
If you still need help with that, I'd recommend joining our Discord server at https://obsproject.com/discord and asking in the #development or #plugins-and-tools channel.
