### ISSUE TITLE
Some files are missing since you last used OBS. 

### ISSUE THREAD

**Issue by sjssoft** [obsproject/obs-studio#4822]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/cCRgy7ZsiT1MZJrb

### Expected Behavior

No such message should appear again and again, once discarded.

### Current Behavior

After update to 27.0.0 version, it is showing a message each time I start OBS and message is "Some files are missing since you last used OBS." -Screenshot attached.
This message is about a missing recorded file some few months ago using OBS. I use to place recorded files from my SSD to HDD after its use for backup purpose. So, I did it intentionally and moved that file. 
It is very annoying to see this message again and again.

![obs error](https://user-images.githubusercontent.com/5841879/120914646-295cd380-c6bd-11eb-8b8c-faefaabf3bab.PNG)

### Steps to Reproduce

1.  Just open OBS and this message pops up.

**Comment by WizardCM** [comment]
This is expected behaviour. You can click the 'x' button within the 'New File' field to clear the selected file within the source to eliminate the warning.

The main reason we do this is because if a file doesn't exist, OBS will (behind the scenes) keep trying to read the file, which can trigger rendering lag and other issues.

**Comment by DoctorMG** [comment]
I have the same issue. Since some day the behaviour is there. It is very annoying that this dialog box is shown **everytime** when OBS is started. From UX perspective it is a useless click to conduct for the user. 
The solution should not be to click an 'x' button **always**. 
The approach should be to explain the user how he can prevent the tool to search for this file. In my case "TheFrame". I cannot remember, if it is a graphic I used for something or if it is some OBS internal thing. 

Improvement strategies:
- Tell the user in which settings this file is saved as being wanted
- If it is a OBS must have and not a user made thing: where can I get it if it was removed accidentally?
- If it is not a must have and OBS will work after this "X" click: add another "Don't ask again" box and remove this requesting line "under the hood" 
 
From my opinion a lifelong "click-away" is insufficient from UX perspective.

**Comment by Warchamp7** [comment]
> I have the same issue. Since some day the behaviour is there. It is very annoying that this dialog box is shown **everytime** when OBS is started. From UX perspective it is a useless click to conduct for the user.
> The solution should not be to click an 'x' button **always**.
> The approach should be to explain the user how he can prevent the tool to search for this file. In my case "TheFrame". I cannot remember, if it is a graphic I used for something or if it is some OBS internal thing.
> 
> Improvement strategies:
> 
> * Tell the user in which settings this file is saved as being wanted
> * If it is a OBS must have and not a user made thing: where can I get it if it was removed accidentally?
> * If it is not a must have and OBS will work after this "X" click: add another "Don't ask again" box and remove this requesting line "under the hood"
> 
> From my opinion a lifelong "click-away" is insufficient from UX perspective.

As Matt noted above, you can make the dialog go away by either fixing the missing files or removing them from OBS (via the dialog itself or manually)

**Comment by DoctorMG** [comment]
Oh - now I got it! I mismatched the wanted 'x' with the 'x' on the titlebar corner on the right hand side of the dialog box. 
After applying the click on the correct place the box doesn't occur anymore after restarting.
Thank you!
