### ISSUE TITLE
No Screen Capture Option

### ISSUE THREAD

**Issue by GuptaAnant** [obsproject/obs-studio#4823]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/oGRNLrMV8IusaFzL

### OBS Studio Crash Log URL

NA

### Expected Behavior

If I click on the **+** icon on Sources then I will receive an option of **Screen Capture** there

### Current Behavior

If I click on the **+** icon on Sources then I do not get an option of Screen Capture. Even though I am running Xorg, not Wayland... I get an option for a webcam, & it works perfectly fine. The microphone & the speaker are also working fine. Just no Screen Capture option

### Steps to Reproduce

1. I installed OBS, from an AUR helper yay, (yay -S obs-studio)
2. Went through the setup wizard (Choose to record the only mode)
3. No option to set screen record
...

### Anything else we should know?

Distribution: Arch Linux
Kernel: 5.12.9-arch-1-1
Window Manager: bspwm
OBS Version: 27.0.0-1

**Comment by WizardCM** [comment]
We do not maintain the AUR packages. You'll want to contact the AUR package maintainer.

**Comment by tytan652** [comment]
It's an issue with an ArchLinux package, please report it to ArchLinux.

**Comment by GuptaAnant** [comment]
Ok, then I removed the package (yay -Rs obs-studio)
Then removed the config dir (rm -rf .config/obs-studio)
Installed from pacman (sudo pacman -S obs-studio)

But still having problems, also reporting the issue to the ArchLinux

**Comment by mtoohey31** [comment]
Hi @GuptaAnant , I ran into the same issue as you this morning, also on Arch and BSPWM with the same OBS version. A temporary solution that worked for me is to install [obs-studio-git](https://aur.archlinux.org/packages/obs-studio-git) from the AUR.

Just checking though, have you reported the bug to the package maintainer yet, because I don't see it under the [package tasks](https://bugs.archlinux.org/index.php?string=obs-studio&project=5&type%5B%5D=&sev%5B%5D=&pri%5B%5D=&due%5B%5D=&reported%5B%5D=&cat%5B%5D=&status%5B%5D=open&percent%5B%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=&do=index)? No worries if you haven't gotten to it yet, let me know if you have though, or if I should let them know.

**Comment by tytan652** [comment]
I hope it will be the last message:
The ArchLinux package has mess up his dependencies, you can try `obs-studio-tytan652` AUR package or still use `obs-studio` package or `obs-studio-browser` AUR package but you will need to install `pipewire` manually.

https://bugs.archlinux.org/task/71156
