### ISSUE TITLE
Fraud site and Google ADS campaign from site soft-obs.com

### ISSUE THREAD

**Issue by FC2469** [obsproject/obs-studio#4906]
### Operating System Info

Other

### Other OS

people think they install obs but install a virus

### OBS Studio Version

Other

### OBS Studio Version (Other)

fraud virus alert use OBS name for phishing

### OBS Studio Log URL

http://soft-obs.com

### Expected Behavior

provide to action for block fraud site.
![2021-06-15](https://user-images.githubusercontent.com/16600519/122111610-3cd80f00-ce20-11eb-9ce2-955139863dd7.png)

### Current Behavior

Hello. I want to inform you that the site https://soft-obs.com/ distributes obs studio. It looks like the obs software but I think it has something strange. My google account was hacked and ads campaigns were activated on that account for € 375.00 per day on this account connected to my credit card on which I was charged € 1200 I filed a complaint with the bank and I hope to get my money back but I wonder if by any chance the software development community wanted to take action against these scammers. Thanks for your kind attention.

### Steps to Reproduce

1. Go to https://soft-obs.com
2. Download malware, seem to install OBS but infect computer

### Anything else we should know?

 I hope my bank go back fund used by pirates for fraud ADS campaign.

**Comment by notr1ch** [comment]
Thanks for the report. How did you encounter this site?

**Comment by SoftwareMagicIT** [comment]
Because I received a notice from the bank to charge an ADS campaign for € 1200 on that site, which I have never done. My account Google has been hacked, now I have taken steps to protect this changing my password and enabling 2 factor auth and pausing the campaigns but not deleting them. Google support says me not delete campaign because needed to trace fraud actions. I hope they get my money back. Tomorrow I report this on police department and contact again Google ADS Support for this

**Comment by SoftwareMagicIT** [comment]
Please note: I also reported the problem to the provider on which that site is registered and asked for the registrant's details. I asked not to delete it for now because I need it as proof of the fraud to get my money back from Google.

**Comment by skeletonbow** [comment]
I think what notr1ch was asking above is more along the lines of:  Where did you find this site and what led you to go to this site for OBS instead of to the official OBS website?  Did you find them with a search engine, or a link on some other website, word of mouth or something else?

By understanding what led you to go to this fraudulent site in the first place, can help to understand how they are luring people in and potentially on how to better combat the problem.

**Comment by FC2469** [comment]
no, i discovered this site because i discovered the fraud. What brought me to this site? Fraudulent campaigns purchased on ADS created with my hacked google account. How did I discover the fraud? I have received the debit notifications. In practice, things went like this: yesterday at 17:00 UTC + 2 I receive notifications from Google that have withdrawn my money. I go to the Gmail account and following the bank report data I discover that I have a Google ADS account that I have never created. I look at which site the campaign refers to and see soft--obs.com for a total of € 1200. Is it clear enough? What is not understood?

**Comment by FC2469** [comment]
Sorry if I may sound rude, but they also stole money from me with this system, as Google actually charged me a lot of money for something fraudulent. I landed on that site only because I was looking for exactly what the advertising campaigns bought were about, the "AD" that appears in the Google search engine, so to speak.

**Comment by notr1ch** [comment]
It sounds like you were compromised outside of this site and they're using stolen adsense accounts to promote their scam further. You should be able to issue a chargeback through your bank. Going to close this issue now as we've reported as much we can and not much more can be done.

If anyone reading this wants to help out, please also report the site at https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en

**Comment by FC2469** [comment]
sure, only on the official obs site I would write something that warns people that the official site is the only one that distributes the guaranteed version and be wary of third party sites. The purpose of my report was this. Then I was asked how I learned about it and I described what happened. Thank you. I really like OBS and wouldn't want it to get a bad name for this. Ok? Regards ant thank you very much
