### ISSUE TITLE
Replay Buffer Missing in Advanced Mode

### ISSUE THREAD

**Issue by ulises-c** [obsproject/obs-studio#4948]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/gTndw0cnxWUXq2FT

### Expected Behavior

Enable replay buffer

### Current Behavior

Replay Buffer is missing completely when in Advanced Mode
![image](https://user-images.githubusercontent.com/13595269/123528633-b46a3180-d69d-11eb-87c9-2d4a25f538a3.png)

### Steps to Reproduce

1. Switch from simple to advanced mode
2. Enable Replay Buffer
3. Nothing happens
...

### Anything else we should know?

Replay buffer works in simple mode

**Comment by WizardCM** [comment]
That is a.. strangely empty log. If you create a new Profile, does the issue go away?

**Comment by ulises-c** [comment]
I'll create a new profile and see what happens.
I only use OBS to record so I'm guessing that's why it's fairly empty.

**Comment by Fenrirthviti** [comment]
This seems to only happen with Custom FFmpeg output mode selected. I don't recall if this is intentional or not, as Custom FFmpeg mode has a fair amount of limitations and "hands off" things about it.

**Comment by flaeri** [comment]
Its definitely intentional. There is code say no replay buffer when in custom ffmpeg.
https://github.com/obsproject/obs-studio/blob/8f97e32227083da457d158f126de61e37730bcfd/UI/window-basic-main-outputs.cpp#L425

Dont think it was ever intended to work. Sounds like a giant pain, and it seems to me like it would be incredibly difficult to make sure the configuration is valid, and you wouldnt get much feedback (currently).

**Comment by Fenrirthviti** [comment]
We should probably just hide that tab entirely (or grey it out) when custom ffmpeg mode is selected. Seems like UI/UX concern, so pinging @Warchamp7 for comment.

**Comment by Warchamp7** [comment]
The real issue here is that disabled checkboxes are not very clear on the Dark theme

There should probably be a warning in the Replay Buffer tab noting why it's disabled

**Comment by RubenHetKonijn** [comment]
How about you allow users to experiment with the settings but add a warning first. At least giving users the option to experiment with it would be useful

**Comment by EmmaKnijn** [comment]
Any luck on implementing it?
Replay buffer now does not appear blank and is checkable, but doesnt do anything. Probably since 28.0.0

![image](https://user-images.githubusercontent.com/64010592/188071222-9de96f40-1a5a-436c-ac5f-f281e2781097.png)
![image](https://user-images.githubusercontent.com/64010592/188071290-eeb5e288-42f0-4a6c-844b-853b1bb85704.png)
![image](https://user-images.githubusercontent.com/64010592/188071380-fc72484f-66c8-48cd-a13d-f510b4268c3f.png)

**Comment by EmmaKnijn** [comment]
@Warchamp7 could you have another look perhaps?
