### ISSUE TITLE
Loss of performance from 26.1.1 to 27.0.1 under same hardware and settings

### ISSUE THREAD

**Issue by Dancovich** [obsproject/obs-studio#4953]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/forum/attachments/obs_27_0_1-txt.72643/

### Expected Behavior

After upgrading from 26.1.1 to 27.0.1, I expected performance on the same hardware and settings would be about the same or have some improvement.

### Current Behavior

After upgrading to 27.0.1 and doing repeated tests, I can confirm OBS can no longer keep a steady 60fps stream or recording (same encoding settings), instead keeping on average 55fps, with lots of frame drops due to rendering lag.

### Steps to Reproduce

1. Install 26.1.1 on a low end computer, preferably one that has a monitor below 1080p.
2. Enable preview and set it to scale to window. Remove panels from the side of the preview window and reduce the size of bottom panels to make as room as possible for the preview.
3. Fine tune settings to have around 10ms to render frames, enough to keep steady 60fps.
4. Upgrade to 27.0.1
5. Same exact settings no longer can keep a steady 60fps.
6. Reduce the size of the preview window by placing panels on each side and increasing their width. When the preview window gets smaller the performance improves
7. Revert to 26.1.1. Performance is back where it was. This loss of performance is exclusive to 27.0.1 (haven't tested 27.0.0)

### Anything else we should know?

My computer is an old laptop, but I managed to fine tune it to be able to stream at 1080p 60 fps. 

Here are the log files for a short recording session for version 26.1.1 and 27.0.1. The end of the log file shows 27.0.1 lost a good amount of frames while 26.1.1 kept a steady framerate.

[26.1.1 log](https://obsproject.com/forum/attachments/obs_26_1_1-txt.72642/)
[27.0.1 log](https://obsproject.com/forum/attachments/obs_27_0_1-txt.72643/)

Below is my configuration for reference.

Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz 2.20 GHz
RAM 8,00 GB
Windows 10 21H1
Dual GPU configuration with
   Intel HD 5500
   AMD Radeon 8500M

**Comment by jpark37** [comment]
It would be helpful if you could gather GPU performance metrics against both OBS versions using the frame capture feature of Intel GPA, which will still work even if OBS runs against your Radeon as primary. You can get the tool here: https://software.intel.com/content/www/us/en/develop/tools/graphics-performance-analyzers.html

I basically want to know which draws became slower. If you need some help creating and navigating frame captures, you can find me in the OBS discord: https://discord.com/invite/obsproject

**Comment by Dancovich** [comment]
I'll do that as soon as I'm able. Thanks.

**Comment by Dancovich** [comment]
@jpark37 I don't know if that's what you need, but I managed to record two metric files as CSV.

[obs64.exe_26_1_1.csv](https://github.com/obsproject/obs-studio/files/6729703/obs64.exe_26_1_1.csv)
[obs64.exe_27_1_1.csv](https://github.com/obsproject/obs-studio/files/6729704/obs64.exe_27_1_1.csv)

I started OBS through Graphics Monitor, attached the System Analyzer, started recording metrics and started a 20 second recording session. I did that for both 26.1.1 and 27.0.1.

Capturing metrics reduced the overall performance of the computer, so both of them failed to reach 60fps while capturing metrics. Even then, 27.0.1 still suffered the most, falling to around 53fps while 26.1.1 kept around 57fps.

I hope that's what you need. I couldn't find your name on Discord but feel free to comment here or PM me on Discord if you need additional information.

**Comment by jpark37** [comment]
The useful capture is the single frame capture: https://software.intel.com/content/www/us/en/develop/tools/graphics-performance-analyzers/graphics-frame-analyzer.html

To make a single frame capture, select "Frame" from the bottom dropdown in Graphics Monitor, launch OBS, start a recording, and then press Ctrl+Shift+C.

What I would need are the captures, so I can analyze the draws/textures/shaders, and the exported draw timings since I don't have your hardware setup.

**Comment by Dancovich** [comment]
Here they are. Let me know if you need anything else. Sorry for the Google Drive link, Github didn't accept my upload, giving a "is not included in the list" error.

[GPA Frames](https://drive.google.com/file/d/1cYpJGzIPv6z1Mymosd6sSdPZGfO1cnQv/view?usp=sharing)

**Comment by jpark37** [comment]
I have some recommendations. In the future, use this button to export your draw timings because my draw timings will be different than yours, but also still include the frame captures so I can examine the GPU frame.
![image](https://user-images.githubusercontent.com/10396506/123746114-0cec2b00-d866-11eb-849c-7218c1f00597.png)

OBS 27 added a "version 2" of the color correction filter, and you are using the older version for the `Full HD` and `No Spoiler` images. This has the side effect of preventing an optimization that we were doing on version 26 to skip a draw. These two extra draws are especially expensive for you because the source images are oversized and squished into a small area.

- One solution is to replace your deprecated color correction filters with new color correction filters. You can do this by simply deleting and recreating the filter from OBS 27. Note that 50% alpha in the old filter is not the same as 50% alpha in the new filter (nonlinear alpha vs linear alpha), so you'd need a lower alpha to achieve approximately the same effect. I do not recommend this solution, but you can use it to verify performance parity between 26 and 27.
- A better solution for performance is to prebake the image to the correct size and opacity, so you don't need to resize or use color correction filters. I have created them for you here:
![fullhd_108_108_halfalpha](https://user-images.githubusercontent.com/10396506/123746915-1c1fa880-d867-11eb-9cf6-6928584675e2.png)
![nospoiler_108_108_halfalpha](https://user-images.githubusercontent.com/10396506/123746916-1c1fa880-d867-11eb-8cc1-2e98c8c43a97.png)

As a general optimization, you can probably presize the PicPay image as well.

I don't see any other obvious regressions in the frame captures. Let me know how it goes; I can do another round if you want.

**Comment by Dancovich** [comment]
Hi. I have excellent news.

First of all, sorry for not sending draw timings with the frame captures, didn't realize the app "re-rendered" the frame to measure them. Here they are for the sake of comparison.

[obs64_26_1_1.csv](https://github.com/obsproject/obs-studio/files/6737332/obs64_26_1_1.csv)
[obs64_27_0_1.csv](https://github.com/obsproject/obs-studio/files/6737333/obs64_27_0_1.csv)

I then followed your advice and replaced the color correction video to measure against 26.0.1. That immediately did the trick! I could record in 27.0.1 with the same performance I did in 26.1.1 (as in, the frame times measured around 141fps just like 26.1.1). So as far as this bug report goes, I consider this one solved.

Here's the frame capture and frame times for this experiment: [obs64_27_0_1_new_color_correction.zip](https://github.com/obsproject/obs-studio/files/6737349/obs64_27_0_1_new_color_correction.zip)

Then I adjusted as many images as I could, reducing them to the larger size used (I use different sizes of the same image depending on the scene) instead of being ridiculously large as they were. Most importantly, I baked the opacity and removed the color correction filter.

That obviously gave me even more performance, which is important in this outdated computer. Here's the frame and timings for that as well: [obs64_27_0_1_baked_transp.zip](https://github.com/obsproject/obs-studio/files/6737354/obs64_27_0_1_baked_transp.zip)

So all I can say now is thank you very much for your help. I would probably never have figured this out by myself.

**Comment by jpark37** [comment]
And thanks for the captures. I wouldn't have realized this stuff without looking through the GPU frames.
