### ISSUE TITLE
Resizing a scene within a group no longer has the expected behaviour

### ISSUE THREAD

**Issue by necropsyuk** [obsproject/obs-studio#4965]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/qmfd9GLjMUYiSaD4

### Expected Behavior

An element is placed within a group (in my case a scene)
When resizing the scene it is possible to do so outside the bounding box of the group

### Current Behavior

An element is placed within a group (in my case a scene)
When resizing the scene it is no longer possible to have the scene go beyond the bounding box of the group.
The group is also resized in this attempt.
There is also so strange unexplainable behaviour that causes the scene to become lost or move erratically within the group.

A video of the behaviour can be seen here: https://youtu.be/P-AebfbqARM

### Steps to Reproduce

1. Create a group
2. Create another element (tested with referenced scene and image)
3. Place the element inside the group
3. Select the element
4. Use resizing handles to resize the element within the group
5. Note that resizing the element from the transform->edit transform menu yields the expected behaviour
...

**Comment by Pablomx2** [comment]
More proof:

OBS 26.1.1

https://user-images.githubusercontent.com/53283603/124178008-dc72df80-da65-11eb-9d9a-66c20eb1742a.mp4

OBS 27.0.1

https://user-images.githubusercontent.com/53283603/124178081-f8768100-da65-11eb-91cf-99333a62a509.mp4

**Comment by Fenrirthviti** [comment]
The group box should be dynamically resizing to the content inside of it. This is expected behavior, even if it behaved differently in previous versions. We fixed a bug, so I will go ahead and close this as there is nothing for us to fix.

The arguments for if this is desired behavior, or the use cases of each, should happen in the Ideas page or a forum thread in the suggestions section.
