### ISSUE TITLE
Themes are loading incorrectly

### ISSUE THREAD

**Issue by fatalgoth** [obsproject/obs-studio#5183]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/uCBjlGc-uDAWy0_I

### Expected Behavior

Themes should load correctly on launch

### Current Behavior

All themes are loaded incorrectly resulting in a botched color scheme. Normal behavior is restored when I revert commit 58caf406cd26613103ec0f4cfea52067a647d71e

### Steps to Reproduce

1. Load the latest git master version of OBS Studio on Linux
2. Scream in horror at now garbled color palette (see attached
![2021-08-24_05-53](https://user-images.githubusercontent.com/62416119/130598283-321ce973-2fc2-4d0f-ae2e-e9a261989292.png)
)

**Comment by WizardCM** [comment]
Are you using the built in theme or a third party theme? If it's a third party theme, could you post a link to it?

**Comment by WizardCM** [comment]
I have just tested all the built in themes on Ubuntu 20.04 and verified that they all work correctly in latest master.

**Comment by fatalgoth** [comment]
> I have just tested all the built in themes on Ubuntu 20.04 and verified that they all work correctly in latest master.

I'm using the built in default Dark theme. However any built in theme I select exhibits the same behavior. It only corrects itself if I select a different theme after launch.

**Comment by Jokler** [comment]
I bisected OBS and is the commit that broke it for me https://github.com/obsproject/obs-studio/commit/e03aeb9bfd17657250bf815617a73b51adafcdb5. Reverting this commit fixed the dark theme for me.

**Comment by WizardCM** [comment]
And the behaviour matches @fatalgoth's experience that switching themes after initial launch fixes it?

If that's the case, I'll look into why initial launch might behave differently.

**Comment by Jokler** [comment]
Yes, though selecting the theme that is already applied also fixes it (the moment it is clicked in the drop-down).

**Comment by Jokler** [comment]
If it helps, it seems to load colors from the system QT/GTK theme for me.

**Comment by WizardCM** [comment]
If either if you are able to build OBS, please try applying this patch.

```patch
diff --git a/UI/obs-app.cpp b/UI/obs-app.cpp
index 782ff4e38..8c9b18a24 100644
--- a/UI/obs-app.cpp
+++ b/UI/obs-app.cpp
@@ -1101,6 +1101,7 @@ void OBSApp::ParseExtraThemeData(const char *path)
 bool OBSApp::SetTheme(std::string name, std::string path)
 {
        theme = name;
+       setPalette(defaultPalette);

        /* Check user dir first, then preinstalled themes. */
        if (path == "") {
@@ -1117,9 +1118,8 @@ bool OBSApp::SetTheme(std::string name, std::string path)
                }
        }

-       QString mpath = QString("file:///") + path.c_str();
-       setPalette(defaultPalette);
        ParseExtraThemeData(path.c_str());
+       QString mpath = QString("file:///") + path.c_str();
        setStyleSheet(mpath);
        QColor color = palette().text().color();
        themeDarkMode = !(color.redF() < 0.5);
```

Essentially, it seems we clear the palette before styling it, and I'm assuming it's taking longer than expected.

**Comment by fatalgoth** [comment]
> If either if you are able to build OBS, please try applying this patch.

Just compiled with this patch applied against OBS 27.1.3 and I'm still getting the same buggy behavior. I'm also using an entirely different computer with a fresh Arch Linux installation and Qt 5.15.2.

As @Jokler mentioned, it seems that the system Qt theme is being used for everything but buttons and a couple other things unless I switch themes back and forth manually. As of right now, reverting 58caf406cd26613103ec0f4cfea52067a647d71e has still been working for me.

**Comment by WizardCM** [comment]
That's really strange. That particular function runs the exact same way whether it's initial load or on theme switch, so it *shouldn't* behave differently unless there's some race condition unique to startup. Thanks for confirming. I'll do more digging.

**Comment by G2G2G2G** [comment]
I've had this issue as well for months (probably since initially reported) 
it occurs on manjaro and arch..
The theme resets "half way" between light theme and dark theme, which OP showed in the picture

What isn't explained is, if you run the "system theme" this issue doesn't occur, because it's trying to load the system theme every time.. I assume this is some fallback or something. But it only half loads it so depending on the theme you choose (dark being default) it'll load that for all the buttons, but most of the other stuff it doesn't.
Also since then, it takes a few seconds to change themes, instead of usually instant.

During start it tries loading this:

```
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
```
which doesn't work, however if you click "settings" and click the same exact theme, it'll give the same exact output.. and then work fine.

See video:
https://user-images.githubusercontent.com/50514477/160246687-eeec085e-ca6b-4c8a-9505-8ca7544c771b.mp4
(changing themes is actually faster when I'm opening my second OBS.. but still kinda slow)

**Comment by kkartaltepe** [comment]
Is this the same as #5339 ?

**Comment by G2G2G2G** [comment]
I'd say it is, yes, you can see the similarities on my video above

**Comment by kkartaltepe** [comment]
Yes its an environment variable, if you run obs on the terminal you can use `env -u QT_QPA_PLATFORMTHEME obs` as recommended in the other issue to see if obs renders correctly.

**Comment by G2G2G2G** [comment]
Yea that fixes this issue also fixes my other issue. (as I said in the other thread)
My other issue may be only on my computer, but this issue is on every arch/manjaro I use. Is this how pacman does it or something?
How can I make the env variable startup every time with OBS, I have to make a bash script or is there some other way?
Thanks

**Comment by kkartaltepe** [comment]
Yes you could use it in a bash script. Probably you need to discover why `QT_QPA_PLATFORMTHEME` is set on your system at all, but thats outside the scope of what we can figure out for you.

**Comment by G2G2G2G** [comment]
(I'm not the OP btw)

**Comment by Jokler** [comment]
I don't have `QT_QPA_PLATFORM` set and I have this issue, though I do have `QT_STYLE_OVERRIDE` set and unsetting that fixes it.
