### ISSUE TITLE
High Bitrate YouTube Stream Repeatedly Disconnects (Mac)

### ISSUE THREAD

**Issue by jasonmvp** [obsproject/obs-studio#5230]
### Operating System Info

macOS 11.5

### OBS Studio Version

27.1.0-rc1

### OBS Studio Version (Other)

Also happens with 27.0.1, 26.x, etc

### OBS Studio Log URL

https://obsproject.com/logs/xL5kdAQ0VAieec-c

### Expected Behavior

The stream should stay connected to YouTube's ingest server without disconnecting.

### Current Behavior

The stream seems to hit some sort of limit and it disconnects from YouTube.  It immediately reconnects and continues the stream, but the end user sees a glitch or two, and YouTube's console shows:

NO DATA

then immediately after that

STREAM HEALTHY

### Steps to Reproduce

1. Set up 4K/60 50Mbit/sec RTMP(S) stream to YouTube using the VT hardware encoder
2. Start the stream
3. Watch the stats window for resets
...

### Anything else we should know?

This smells very much like a buffer issue, but I'm not certain:

- If I set the bit rate lower (eg: 35Mbit/sec), the stream takes longer before it resets, but it still does it.

- I can reproduce this using x264 until I set a massive buffer size (double the frame rate).  Once I do that, the x264 no longer resets/discos in the same manner.  I don't know if there's any option within Apple's VT to customize the buffer, but that may be the key.

**Comment by kkartaltepe** [comment]
Please use our discord or forum for support.

**Comment by jasonmvp** [comment]
I have used the Discord for support.  I opened this to track it as an issue because I'm 99% certain it's internal to OBS.

**Comment by kkartaltepe** [comment]
Reopening since some people in discord wanted it presumably.

The error here is that youtube has closed the connection to you. I dont find this very likely to be an issue on obs, though as mentioned it could be that you have misconfigured settings for youtube causing it to disconnect you.

**Comment by jasonmvp** [comment]
> The error here is that youtube has closed the connection to you.

YouTube is doing that because it's receiving no data for some reason.

> I dont find this very likely to be an issue on obs, though as mentioned it could be that you have misconfigured settings for youtube causing it to disconnect you.

I'm fairly certain there isn't a misconfiguration specific to YouTube that's causing the discos.  In fact I know there isn't because the same settings work on Windows.  This appears to be an interaction between OBS the encoders; either the VT or libx264, _on the Mac_ specifically.  The difference is that I have access to NVENC on Windows where I don't on the Mac.

Some buffer, somewhere, somehow, is getting filled up before the encoder can process the frame and OBS can kick it out to YouTube.  That's what this smells like.  And it smells even more like that because of how I prevent it from happening with x264: increasing the buffer.

**Comment by cooperaj** [comment]
Thought I'd try out the RC's new youtube stuff and am seeing this same issue on a Windows system. I'm attempted to stream at 10k with a 20k buffer as indicated might affect things above but it just endlessly connects/disconnects.

**Comment by jasonmvp** [comment]
> Thought I'd try out the RC's new youtube stuff and am seeing this same issue on a Windows system. I'm attempted to stream at 10k with a 20k buffer as indicated might affect things above but it just endlessly connects/disconnects.

I suspect your challenge might be a bit different than mine.  Advanced --> page down to Network section, uncheck "Network Optimizations" and see if that fixes it for you.

**Comment by jasonmvp** [comment]
More data:

It happens with:

- 4K/60 @ 50Mbit/sec
- 4K/60 @ 35Mbit/sec
- 1440p/60 @ 50Mbit/sec
- 1440p/60 @ 35Mbit/sec
- 1080p/60 @ 50Mbit/sec

It doesn't happen with:
- 1080p/60 @ 20Mbit/sec

**Comment by WizardCM** [comment]
To confirm, when creating the stream key on the YouTube side, you are specifically choosing "Manual" and "4K60" and not "Variable", correct?

**Comment by jasonmvp** [comment]
> To confirm, when creating the stream key on the YouTube side, you are specifically choosing "Manual" and "4K60" and not "Variable", correct?

Prior to your message: I was using Variable.  I did just test it "Manual" with "4K/60" and it still does the same thing.  It takes longer to do so, but it does still DISCO and Reconnect.  No dropped frames from encoding or rendering, either.

**Comment by jasonmvp** [comment]
The results in the VOD are exactly like we saw in Tim The Tatman's vid.  For instance (no audio, this was a test) check this:

https://youtu.be/Nnzmdtzdb5U?t=202

**Comment by jasonmvp** [comment]
Snippet of a tcpdump right as the problem happened.  Unfortunately all I cap'd were the headers, but you can see that OBS on the Mac still thinks the connection is open while YouTube is chucking RSTs back at me.

`
18:52:57.970756 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [.], seq 133178350:133181186, ack 28131, win 2048, options [nop,nop,TS val 2064285433 ecr 2867288886], length 2836
18:52:57.970758 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [P.], seq 133181186:133182468, ack 28131, win 2048, options [nop,nop,TS val 2064285433 ecr 2867288886], length 1282
18:52:57.970874 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [.], seq 133182468:133185304, ack 28131, win 2048, options [nop,nop,TS val 2064285433 ecr 2867288886], length 2836
18:52:57.970875 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [P.], seq 133185304:133186586, ack 28131, win 2048, options [nop,nop,TS val 2064285433 ecr 2867288886], length 1282
18:52:57.970992 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [.], seq 133186586:133189422, ack 28131, win 2048, options [nop,nop,TS val 2064285434 ecr 2867288886], length 2836
18:52:57.970995 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [P.], seq 133189422:133190704, ack 28131, win 2048, options [nop,nop,TS val 2064285434 ecr 2867288886], length 1282
18:52:57.971067 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [.], seq 133190704:133192122, ack 28131, win 2048, options [nop,nop,TS val 2064285434 ecr 2867288886], length 1418
18:52:57.971070 IP [FQDN_REDACTED].49640 > iad30s46-in-f12.1e100.net.https: Flags [P.], seq 133192122:133192981, ack 28131, win 2048, options [nop,nop,TS val 2064285434 ecr 2867288886], length 859
18:52:57.971652 IP iad30s46-in-f12.1e100.net.https > [FQDN_REDACTED].49640: Flags [R], seq 3933387558, win 0, length 0
18:52:57.971656 IP iad30s46-in-f12.1e100.net.https > [FQDN_REDACTED].49640: Flags [R], seq 3933387558, win 0, length 0
18:52:57.971657 IP iad30s46-in-f12.1e100.net.https > [FQDN_REDACTED].49640: Flags [R], seq 3933387558, win 0, length 0
18:52:57.971658 IP iad30s46-in-f12.1e100.net.https > [FQDN_REDACTED].49640: Flags [R], seq 3933387558, win 0, length 0
`

**Comment by jasonmvp** [comment]
Update:  Replaced the GCN5-era Vega II GPU with an RDNA2-era dual-W6800X card.  Should have provided an increase in h.264 hardware encoding performance.  The YouTube streams still get disconnected.

**Comment by RytoEX** [comment]
I apologize in advance for the lengthy reply here.

----

First things first, clarification questions:
1. Have you reproduced this with FFmpeg CLI with Video Toolbox H.264?
2. Is it reproducible in OBS with 4K60 and a low-end bitrate, such as 20,000 Kbps?
    I know you tested with 1080p60 at 20 Mbps.  I'd like this as an extra data point.

----

As far as we know, the Video Toolbox H.264 (vth264 or mac-vth264) encoder only supports VBR.  Video Toolbox does not support CBR, and no matter what limits you try to set, the output will have fluctuation in the bitrate and frame size.  The bitrate variability will be smaller with a lower bitrate target and larger with a higher bitrate target.

For example, a stream with a 10 Mbps target bitrate might fluctuate between 5 Mbps and 15 Mbps at moments.  A stream with a 51 Mbps target bitrate might fluctuate between 25.5 Mbps and 76.5 Mbps.  These are just example figures based on some reading and guesswork, but should illustrate the idea.

I have three theories here as to what's causing the disconnects:
1. The swings that go too high are causing YouTube's ingest server to close the connection.
2. The swings that go too low are being considered by YouTube's ingest to be a stream disconnect due to the bitrate dropping a certain amount suddenly.
3. The variations in a high bitrate stream due to the characteristics of VBR are simple too far apart for YouTube to consider the stream stable.

The first theory might fit with the fact that this only happens at high target bitrates (e.g., 35 Mbps possibly having a dip-to-spike range of 17.5 Mbps to 52.5 Mbps).  This roughly lines up with YouTube's specified 20,000-51,000 Kbps for "4K / 2160p @60 fps".  This would only be true if YouTube is actually capping ingest bandwidth, which I don't think is true.  I think in this scenario, YouTube would either warn about low bitrate for the resolution+FPS or warn about excessively high bitrate, but it shouldn't shut down the connection as far as I know.

The second and third theories are basically variations of "sudden drop in bitrate interpreted as stream disconnection".

Unfortunately, if this can only be reproduced, reliably or at all, with very high bitrates, that limits the number of people who can even attempt to reproduce this.  I only have 5 Mbps upload, so I cannot test this at all, even if I had a Mac.

----

> I can reproduce this using x264 until I set a massive buffer size (double the frame rate). Once I do that, the x264 no longer resets/discos in the same manner.

The recommendation for the buffer size for x264 seems to depend on the use case.  The default recommendation from some sources seems to be 2x the maximum bitrate.  Supposedly if you want more tightly constrained bitrate, you can try setting it to 0.5x.  I believe OBS uses 1x the bitrate by default for x264.

----

> I don't know if there's any option within Apple's VT to customize the buffer, but that may be the key.

Short answer:  no.

Long answer:
As for whether or not we can control the buffer size with the VTEncoder, I believe the answer is no.  Apple provides very little configurability with the encoder.  [What we currently do is this](https://github.com/obsproject/obs-studio/blob/8c9bb3a84b907a4792cb44c11a960256e8f6d0b9/plugins/mac-vth264/encoder.c#L156-L176):

We convert the user-specified bitrate (in Kbps) to bits-per-second and set the result to the [`kVTCompressionPropertyKey_AverageBitRate`](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_averagebitrate?language=objc) property.

If "limit bitrate" is enabled...
1. Convert the "Maximum bitrate" setting (in Kilobits-per-second) to bytes-per-second times the "Maximum bitrate window"
    `cpb_size = max_bitrate * 125 * max_bitrate_window`
2. Set the "Maximum bitrate window (seconds)" (max_bitrate_window) setting to cf_cpb_window_s
    `cf_cpb_window_s = max_bitrate_window`
3. Place the values from 1 and 2 above into an array
    `rate_control = [ cpb_size, cf_cpb_window_s ]`
4. Set [`kVTCompressionPropertyKey_DataRateLimits`](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_dataratelimits?language=objc) to `rate_control` to attempt to set a hard limit of cpb_size bytes per cf_cpb_window_s seconds.

So with your settings:
1. `cpb_size = 50000 * 125 * 1` = 6250000
2. `cf_cpb_window_s = max_bitrate_window` = 1
3. `rate_control = [ cpb_size, cf_cpb_window_s ]` = `[ 6250000, 1]`
4. Set [`kVTCompressionPropertyKey_DataRateLimits`](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_dataratelimits?language=objc) to `rate_control` to attempt to set a hard limit of 6250000 bytes per 1 second (50,000,000 bits-per-second).

There's a note in Apple's documentation for [`kVTCompressionPropertyKey_AverageBitRate`](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_averagebitrate?language=objc) that says:
> Note that bit rate settings only have an effect when timing information is provided for source frames, and that some codecs do not support limiting to specified bit rates.

and [`kVTCompressionPropertyKey_DataRateLimits`](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_dataratelimits?language=objc) says:
> Note that data rate settings only have an effect when timing information is provided for source frames, and that some codecs do not support limiting to specified data rates.

No additional details are provided in the documentation, so I don't know if there should be an error if either the timing information isn't provided or if H.264 does not support limiting.  Maybe someone more familiar with Video Toolbox can elaborate.


As an aside, kVTCompressionPropertyKey_DataRateLimits only presents a hard _upper_ limit for the _average_ bitrate within a set duration.  Per the documentation:
> Each hard limit is described by a data size in bytes and a duration in seconds, and requires that the total size of compressed data for any contiguous segment of that duration (in decode time) not exceed the data size.

This does not prevent momentary drops or spikes in bitrate and frame size within a sub-period of that duration, so long as the average bitrate for the period is capped.


Aside from monitoring network conditions to see if any specific conditions (e.g., large changes in bitrate) coincides with YouTube closing the connection, I'm not sure what else to suggest at the moment.  At least for those who can reproduce this, it takes less time than the other macOS YouTube issue.  If we can confirm there's something we can do to address this in OBS, we will work on it.  If we can narrow down the conditions that might reproduce this further, I apologize that I can't be more helpful here.


References:
1. https://slhck.info/video/2017/03/01/rate-control.html
2. https://nlab.engr.uconn.edu/papers/cava.pdf
3. https://blog.twitch.tv/en/2017/04/04/segment-based-rate-control-of-video-encoder-for-live-abr-streaming-1da5e60a2ec1/
4. https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_averagebitrate?language=objc
5. https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_dataratelimits?language=objc#discussion
6. https://developer.apple.com/documentation/videotoolbox
7. https://github.com/obsproject/obs-studio/blob/8c9bb3a84b907a4792cb44c11a960256e8f6d0b9/plugins/mac-vth264/encoder.c#L156-L176

**Comment by jasonmvp** [comment]
I appreciate the long write-up and explanation.

> 1. Have you reproduced this with FFmpeg CLI with Video Toolbox H.264?

I haven't been able to.  If I start a stream up via CLI and just goes and goes.  No problems at all.  Even at 50Mbit/sec.

> 2. Is it reproducible in OBS with 4K60 and a low-end bitrate, such as 20,000 Kbps?  I know you tested with 1080p60 at 20 Mbps. I'd like this as an extra data point.

No.  I tried 20Mbit/sec and then bumped to 32Mbit/sec as two different tests.  At 20, solid stream with no discos.  At 32, I had one single disco two minutes into the stream, and then it was fine thereafter.

> Unfortunately, if this can only be reproduced, reliably or at all, with very high bitrates, that limits the number of people who can even attempt to reproduce this. I only have 5 Mbps upload, so I cannot test this at all, even if I had a Mac.

I understand that challenge completely which is why I'm open to doing whatever is needed to provide you guys with an abundance of data to try and help.

**Comment by jasonmvp** [comment]
In an effort to gather more data:  is there some way to 'hack' up OBS such that it constantly logs its outgoing bitrate?  Perhaps to a different file than the standard log file.  The other thing that it could keep track of is exactly when it receives the RST from YouTube?  Goal here would be to see if there's some bitrate trigger that actually causes it?

I get that this would be a one-off and pointless, otherwise.

**Comment by jasonmvp** [comment]
I attempted to do a 1440p/60 30Mbit/sec stream this evening and it was going fairly well for the first 18 minutes or so.  Then I started getting the random "NO DATA", "STREAM HEALTHY" messages every so often.  I'll keep the VOD public, and one such timestamp:

https://youtu.be/VkjhxIE2kFg?t=1110

Lower your volume; the game's sound effects were being fed from the mixer at full blast, so it's a bit loud.

**Comment by jasonmvp** [comment]
I have a 3G pcap file which captures the event, but I'm afraid I'm a bit over my head trying to make sense of it.  I can make it public, but my system's public IP is in the dump and I'm less keen on posting *that* ;-).  If someone wants to try and claw through the dump file, let me know.

**Comment by jasonmvp** [comment]
http://misc.lateapex.net/obs.pcap

That's a ~230M PCAP file that shows the complete capture of the event.  The "fun" starts at packet 142503.  I wish I could grok packet dumps, but I just simply don't have the skill set for that.  If someone else does, feel free to pull that file from S3 and take a look in Wireshark, et al.

**Comment by kkartaltepe** [comment]
And what were your stream settings for this session?

**Comment by jasonmvp** [comment]
> And what were your stream settings for this session?

Oh crap, sorry I'd forgotten that bit:

- Hardware encoding
- 4K/60
- 50Mbit/sec
- limit enabled: 50Mbit/sec
- Window: 1.5 sec
- Keyframe Interval: 2
- B-Frames enabled

**Comment by RytoEX** [comment]
> > And what were your stream settings for this session?
> 
> Oh crap, sorry I'd forgotten that bit:
> 
>  * Hardware encoding
>  * 4K/60
>  * 50Mbit/sec
>  * limit enabled: 50Mbit/sec
>  * Window: 1.5 sec
>  * Keyframe Interval: 2
>  * B-Frames enabled

Just as a note:  setting the Bitrate to 50000 kbps, Maximum Bitrate to 50000 kbps, and the Maximum Bitrate Window to 1.5s means that the Video Toolbox encoder will require that "the total size of compressed data for any contiguous segment of that duration (in decode time) not exceed the data size."  That means that it enforces an Average Bitrate of 51000 kilobits (6375000 bytes) over every 1.5s segment, or roughly 34000 kbps if I've done the math right.

The OBS default value for Maximum Bitrate Window is 1.5s, so be sure to be mindful of this setting while testing.  If possible, please provide logs for each test so that we can catch these details while investigating.

As I've explained before though, that doesn't mean that the bitrate for any given sub-period must be under the specified Maximum Bitrate (when converted to the appropriate duration or time unit), just that the total data size for the specified Maximum Bitrate Window must not exceed (Maximum Bitrate * 125 * Maximum Bitrate Window) Bytes.

**Comment by jasonmvp** [comment]
> 
> Just as a note: setting the Bitrate to 50000 kbps, Maximum Bitrate to 50000 kbps, and the Maximum Bitrate Window to 1.5s means that the Video Toolbox encoder will require that "the total size of compressed data for any contiguous segment of that duration (in decode time) not exceed the data size." That means that it enforces an Average Bitrate of 51000 kilobits (6375000 bytes) over every 1.5s segment, or roughly 34000 kbps if I've done the math right.

Is it worth tightening that Window, perhaps?  The smallest it goes is .1s if I'm not mistaken.

> The OBS default value for Maximum Bitrate Window is 1.5s, so be sure to be mindful of this setting while testing. If possible, please provide logs for each test so that we can catch these details while investigating.

Attached.
[obs-log.txt](https://github.com/obsproject/obs-studio/files/7195652/obs-log.txt)

**Comment by alinsavix** [comment]
> That's a ~230M PCAP file that shows the complete capture of the event. The "fun" starts at packet 142503. I wish I could grok packet dumps, but I just simply don't have the skill set for that. If someone else does, feel free to pull that file from S3 and take a look in Wireshark, et al.

I only got a chance to look at this very briefly, but in that quick glance it looks like you were having network problems, in both directions -- things looked fine, and then there was a burst of activity where it looked like both sides had possibly lost packets (need to look more to verify completely), and then the disconnect.

It didn't look like the OBS side had suddenly stopped sending data, or that there was suddenly a huge swing in data rate or similar. So unless I'm missing something stupid (which is possible) there's not an obvious smoking gun. It's quite possible there's something going on here where something is tickling youtube in just the wrong way and there's not going to be a way to figure out what the something is without their help.

If you felt like posting another capture, I could at least look and see if the behavior at the network layer was consistent each time. (I'll try to spend more time with the existing capture, too, when I'm able)

When you get the disconnects, is it always at about the same amount of time into a stream (e.g. always after 2 hours 5 minutes), or is it more random?

**Comment by jasonmvp** [comment]
I sincerely appreciate you looking at the PCAP.  I'll try to generate another one when I get off work later.

That said, this is going to seem a bit argumentative, but bear with me:

> I only got a chance to look at this very briefly, but in that quick glance it looks like you were having network problems, in both directions -- things looked fine, and then there was a burst of activity where it looked like both sides had possibly lost packets (need to look more to verify completely), and then the disconnect.

Please do.  For reference, I have a 1G business class symmetrical fiber run by Verizon.  I'm also 15-20 minutes from, literally: the _single_ most inter-connected place on the entire planet (Ashburn, VA).  Every large and small company that uses data center space, including YouTube (Google) is there.  Meaning: there's nothing "network related" causing the issue.

Further, this only happens with RTMP(S).  When I run a high bitrate HLS stream, it says _rock solid_ for the hour I'm allowed before I trip over the confirmed 1-hour bug.

You're seeing OBS send _something_ to YouTube there, and YouTube is saying, in essence, "eff off, here's a FIN-ACK."  The connection is reset.

> When you get the disconnects, is it always at about the same amount of time into a stream (e.g. always after 2 hours 5 minutes), or is it more random?

It's random, unfortunately.  That PCAP was literally within 1 minute after starting the stream, if that.  Other times it takes longer.

**Comment by Fenrirthviti** [comment]
We've received confirmation from YouTube that the max bitrate was incorrectly set too low after a recent update on their end and causing disconnects well below the expected max, which would explain why we haven't seen this issue crop up until now.

I'm not going to claim that it's the silver bullet fix on their end, but it certainly lines up and would explain a lot. The max cutoff will be increased in the coming week, I will provide an update when we get confirmation, and tests can be run again.

**Comment by jasonmvp** [comment]
Joel -

> We've received confirmation from YouTube that the max bitrate was incorrectly set too low after a recent update on their end and causing disconnects well below the expected max, which would explain why we haven't seen this issue crop up until now.

That's good info; thanks for sharing.  Did they happen to mention when that change was made?

**Comment by RytoEX** [comment]
> 
> 
> Joel -
> 
> > We've received confirmation from YouTube that the max bitrate was incorrectly set too low after a recent update on their end and causing disconnects well below the expected max, which would explain why we haven't seen this issue crop up until now.
> 
> That's good info; thanks for sharing. Did they happen to mention when that change was made?

They did not provide that information.

**Comment by RytoEX** [comment]
> Is it worth tightening that Window, perhaps? The smallest it goes is .1s if I'm not mistaken.

You can experiment with setting the window lower and appropriately lowering the "max bitrate" value to match the specified window (e.g., 25000 for 0.5s, 5000 for 0.1s) to see if that helps maintain a more consistent bitrate.  I have no idea how that works in practice or if it introduces any extra overhead.  I can only explain what our code does and what Apple's documentation says on the subject.

**Comment by jasonmvp** [comment]
> You can experiment with setting the window lower and making sure the bitrate and max bitrate match

I think I'm going to park testing for now until the folks at YouTube have verified that they've restored the max bitrate, per Joel's earlier message.

**Comment by Fenrirthviti** [comment]
Posting here as well, YouTube has confirmed the fix is now live on their end. Please test and let us know if the issue has been resolved, or if there is further investigation required.

**Comment by jasonmvp** [comment]
Joel, et al -

> Posting here as well, YouTube has confirmed the fix is now live on their end. Please test and let us know if the issue has been resolved, or if there is further investigation required.

I just tested a 4K/60 50Mbit/sec hardware-encoded stream and let it go for ~48 minutes.  No drops, disconnects, RST packets, etc that I saw.  YouTube did bark a couple of times suggesting I lower the bitrate to under 40Mbit/sec, but that's safe to ignore.  Specially at 4K/60.

I'm cautiously optimistic this did the deed.  I'm going to close the issue for now; if this pops back up again for me I'll comment here and we can pursue further debugging.

Thanks!

**Comment by jasonmvp** [comment]
Final follow-up even though this is closed:

I've done a series of +3 hour streams at 4K/60, 50Mbit/sec, hardware encoded from my Mac over the past weekend.  No hiccups, drops, or any such issues.  YouTube does bark at me every so often about ridiculously high bitrates (150Mbit/sec?!) but that goes away quickly.
