### ISSUE TITLE
OBS not using the correct gtk theme when run with "-platform wayland" argument

### ISSUE THREAD

**Issue by saikat0511** [obsproject/obs-studio#5239]
### Operating System Info

Pop OS 21.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/AfCk27ErZ__2Du9c

### Expected Behavior

OBS should use the theme set by user for window decorations and cursor. 
Its working as expected if I just run `obs` without any arguments. But I dont get any pipewire capture options for wayland that way so its not a solution.
![image](https://user-images.githubusercontent.com/57610828/132025861-1ed22f92-5a02-482b-b99d-8795c41aca3e.png)

### Current Behavior

It doesn't use the current system theme when run with "-platform wayland" and instead uses some other theme.
The window decoration and the cursor theme is different, the cursor doesn't even change when hovering on window edges so resizing window elements and the OBS window itself is pain in the butt.
![image](https://user-images.githubusercontent.com/57610828/132026015-b9982fbe-c984-466e-adf4-68071613e20a.png)

### Steps to Reproduce

1. run `obs -platform wayland` or `QT_QPA_PLATFORM=wayland obs` in gnome
2. OBS doesn't use the system theme

**Comment by CobaltSpace** [comment]
In x11, the top bar is provided by GNOME.  GNOME decided that they will not provide a top bar in wayland, so QT is the one that provides it.  GNOME thinks it is better if the top bar matches the window it is for over matching the desktop environment.

https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#Theme_engines is a good starting point for looking at fixes.

Based on my rudimentary research on Ubuntu/Pop!_OS, you need to install `qtstyleplugins-src` and set `QT_QPA_PLATFORMTHEME=gtk2`.  You may need to set your gtk2 theme to match your gnome theme.  If you want more control over QT applications, also install `qt5ct` & set `QT_QPA_PLATFORMTHEME=qt5ct` instead.  You can also launch `obs` with `-style gtk2` or `-style qt5ct` instead of setting `QT_QPA_PLATFORMTHEME`.

**Comment by mufunyo** [comment]
Based on the above comment this sounds like an environment issue, and not an issue with OBS. Closing.

**Comment by 71GA** [comment]
You might reconsider reopening this one...
https://github.com/obsproject/obs-studio/issues/7689#issuecomment-1296625416
