### ISSUE TITLE
Virtual Camara doesn't show up in all programes

### ISSUE THREAD

**Issue by josh-65** [obsproject/obs-studio#5253]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/IWT-EZDdrxNo-8ox

### Expected Behavior

The virtual camera output should show as a camera in all programes

### Current Behavior

So far the output doesn't show in windows 10 camera app and snap camera.

### Steps to Reproduce

1) Install OBS virtual cam
2) Start it
3) Open the windows 10 or 11 camera app
4) See it cant find any cameras

**Comment by RytoEX** [comment]
The Windows 10 Camera App uses Media Foundation, while the OBS Virtual Camera is DirectShow, so the fact that it doesn't show up is perfectly normal.

Snap Camera only supports cameras with drivers.  The OBS Virtual Camera does not use a driver because it is implemented directly as a DirectShow device.
