### ISSUE TITLE
Obs doesn't show any encoder besides x264 (software) on MacOS Catalina

### ISSUE THREAD

**Issue by MrXD06** [obsproject/obs-studio#5543]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/vPJg9pdeOjpovY7a

### Expected Behavior

well, idk, it never showed any other encoder so, not much to an Mac Mini Late 2012

### Current Behavior

![Screen Shot 2021-11-18 at 21 59 28](https://user-images.githubusercontent.com/81484776/142520772-e90d9bd5-6f8c-4da7-a329-6156be6f91ef.png)
it never showed up any other encoder, and its performance is horrible

### Steps to Reproduce

1.idk
2.
3.
...

### Anything else we should know?

its a Mac Mini (Late 2012) with a I5 2520M (Ivy Bridge) - iGPU Intel HD Graphics 4000 - 8gb Ram DDR3

**Comment by dodgepong** [comment]
If you don't know what the expected behavior is, then how do you know this is a bug?

The only two encoders supported on Mac are x264 and Apple VT, but AppleVT only works when you have a computer with hardware encoding capability. It sounds like your computer does not have that capability, so it's only offering you software x264 encoding.

**Comment by MrXD06** [comment]
so you're saying to me that i can't use an other encoder, and quicktime does not work, welp, fair enough.
