### ISSUE TITLE
Changing Global Audio Devices settings can produce sources with duplicate names if manually added to scenes

### ISSUE THREAD

**Issue by VodBox** [obsproject/obs-studio#5621]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/9yxVGx_Ad0J6_SDa

### Expected Behavior

Changing the Global Audio Devices options in Settings shouldn't produce name conflicts.

### Current Behavior

Changing the Global Audio Devices options in Settings can produce name conflicts if the underlying source has been added to a scene using "Add Existing".

### Steps to Reproduce

1. Set a Global Audio Device to some valid device and hit OK/Apply.
2. Add an Audio Input/Output Capture source and use add existing to pick the Global Audio Device.
3. Go back to Global Audio Device settings, change the device to disabled, then hit Apply.
4. Set the Global Audio Device back to some valid device and hit OK/Apply.
5. Repeat.

### Anything else we should know?

![image](https://user-images.githubusercontent.com/16394849/144736456-823947cc-6632-4eac-aa36-e155fbe36912.png)

**Comment by sora-blue** [comment]
The root cause of name conflicts in the scene item list probably lies in the fact that scene item uses name of its source as its name while scene items are allowed to have the same source. It should be noted that sources themselves have checked unique names, but more than one scene items are using the name of one source. 

The simplest approach is to prevent scene items from using the same source, as it was in my last pr. But it is pointed out that users will not expect this, while you cannot duplicate sources directly sometimes, so the only approach is to add independent
name property for scene items. But this involves bunches of parts in, like releasing memory usage, which may cause further problems, and i'm confusing about it. 

In the current version, name of scene item is name of its source. So in most cases, when you get name of scene item, `obs_source_get_name(item->source)` is used. When you rename scene item, you rename the source, then other scene items using the same source. Adding independent name property for scene items means you leave name of sources away, which is nonsense.

**Comment by sora-blue** [comment]
I didn't expect that name conflicts in source list would be intentional, so i totally mistook the took last time. The problem is specific to global audio sources.

Now i suppose the point is, it is expected that if you disable the global audio source on settings windows, it should be removed on spot, while the fact is that, if you added a scene items using global audio source, you added **extra strong reference** to it thus leading to its not being removed. On the other hand, changing from "disabled" to some available source directly causes creation of new source, so there are name conflicts.

There are 2 main solutions for solving the problem. One is removing scene items using the global audio sources when disabling, the other is checking reference count to decide if permitting "disabled" or usage of other audio devices. For the moment i tend to the latter solution, and i have 3 plans for pushing it:

1. checking refs on `SaveAudioSettings`
2. checking refs on `AudioChanged`
3. checking refs on `LoadListValues`

All 3 plans requires a direct volatile value of refs of source. Currently i'm working on the third plan, and the effect probably goes like this:

![img0](https://i.ibb.co/Gp025XZ/1.png)
![img1](https://i.ibb.co/Q8NpL6d/2.png)

Occupied on one channel will not affect usage on other channels.

**Comment by WizardCM** [comment]
After thinking about this, my preference would be that changing the device in Settings would simply update the property for the global source, rather than destroying and recreating the source entirely. This would also fix other sections such as Hotkeys reloading 3 times when the audio device is changed.

**Comment by sora-blue** [comment]
I checked code related to the process and suppose it is `OBSBasic::ResetAudioDevice` at UI/window-basic-main.cpp.
Changing from one available audio source to another seems to just update settings for the source, while changing from one aviable audio source to "disabled" , then to another available one seems to destroy & recreate it. So perhaps preventing global audio source in use from being disabled will prevent the extra process in the same time.

**Comment by sora-blue** [comment]
@jp9000 Well, i could have drawn it from the fact that obs lib has no direct access to the reference number. It depends on whether you want to keep it 'global'. Btw, there's a similar function `get_new_source_name` in frontend/windows-basic-source-select.cpp, and i suppose it may cause some harmless duplication.
