### ISSUE TITLE
Custom RTMP service doesn't send username/password to server

### ISSUE THREAD

**Issue by z0rti** [obsproject/obs-studio#5639]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

n/a

### Expected Behavior

OBS should send pubUser and pubPasswd to the server.

### Current Behavior

No pubUser and pubPasswd is sent.

### Steps to Reproduce

(0. Set up nginx with RTMP mod)
1. Settings->Stream Enable `[x] Use authentication`
2. Settings->Stream Enter a username and password
3. Start the stream

### Anything else we should know?

Tested with "Settings->Stream Custom RTMP service"
Server: nginx + [https://github.com/arut/nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module)
Checked with wireshark + tcpdump
In the connect('foo') RTMP packet there is `app, type, flashVer, swfUrl, tcUrl` but no pubUser/pubPasswd

**Comment by xiaozhihong** [comment]
Any body knows what's the status of this issue?

**Comment by jandrourgh** [comment]
Having the same issue, I thought credentials would be available on request headers, request body or in the worst case url encoded but they don't appear anywhere. Missing something obvious here?

**Comment by bontibon** [comment]
I just noticed this today as well.

**Comment by tt2468** [comment]
This is expected behavior for user/pass authentication. OBS waits for the RTMP server to report via an initial connect() `NetConnection.Connect.Rejected` command reply status before passing authentication fields. This is how I understand most applications to behave. Since nginx-rtmp does not support user/password authentication, it will not deny unauthenticated connect() commands, so OBS does not pass the username and password fields in the second connect() command.

The process for user/pass authentication is:
- Open TCP socket with server
- Perform handshake
- Send `connect()` command with no credentials
- Server replies with `NetConnection.Connect.Rejected` status
- Re-perform handshake
- Send new `connect()` command, this time including authentication details (appears to be vendor specific)
- RTMP server accepts the connection

If you are trying to implement authentication using something like nginx-rtmp, use query parameters and an HTTP callback to authenticate.
