### ISSUE TITLE
LIBOBS : obs_add_raw_video_callback convertion affects main output

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#5658]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

when the video_scale_info argument is provided to  obs_add_raw_video_callback , the converted frame to the callback should be independent of the main output.  only the callback should be fed with the converted video frames and the main output should not be affected and should remain same as was set with obs_reset_video

### Current Behavior

upon calling obs_add_raw_video_callback  with a video_scale_info argument, the main ouput is also converted to match the video_scale_info argument.

### Steps to Reproduce

1.   initialize the output format with video_format::VIDEO_FORMAT_ARGB (obs_video_info.output_format=video_format::VIDEO_FORMAT_ARGB)
2.  call obs_add_raw_video_callback with a  video_scale_info with video_format::VIDEO_FORMAT_BGRA
3.  you will notice the main ouput is now changed to VIDEO_FORMAT_BGRA
...

**Comment by gxalpha** [comment]
I cannot reproduce this on 29.0.0. Please provide more detailed steps to reproduce the problem (where are you setting the output format in the first place? How do you notice the problem in the first place?).

I'm also a bit confused since `VIDEO_FORMAT_ARGB` doesn't exist. We have a lot of video formats, but `VIDEO_FORMAT_ARGB` isn't one of them.

**Comment by gxalpha** [comment]
No response since January. Please open a new issue with new, detailed steps to reproduce if you can still cause this to happen in 29.1.1 or newer.
