### ISSUE TITLE
Recording PipeWire Window has Black Border

### ISSUE THREAD

**Issue by kevincox** [obsproject/obs-studio#5796]
### Operating System Info

Other

### Other OS

NixOS Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

[2022-01-14 15-16-56.txt](https://github.com/obsproject/obs-studio/files/7873078/2022-01-14.15-16-56.txt)

### Expected Behavior

The window was captured with no border.

### Current Behavior

A thick black border surrounded the window.

https://user-images.githubusercontent.com/494012/149582671-c77cc687-3387-4db6-abb9-b6e1903daea2.mp4

### Steps to Reproduce

1. Add a "Window Capture (PipeWire)" source
2. Select a Wayland window.
3. Observe black border

Note that putting a "Colour Source" background may make it easier to see.

### Anything else we should know?

This doesn't occur when caputring X11 windows using "Window Capture (PipeWire)" sources. It also doesn't work for maximized (or fullscreen) windows.

If I had to guess this is related to the compositor adding a shadow to windows. Maybe this needs to be excluded from capture or the transparency needs to be preserved.

**Comment by kkartaltepe** [comment]
> It also doesn't work for maximized (or fullscreen) windows.

The windows available and any data from them is based on your compositors implementation. If your compositor chooses not to list or otherwise not send data for fullscreen windows you should file a bug against them to implement capture for them.

> Observe black border

I'm pretty sure this was fixed in the latest release, but you are way behind. Feel free to comment again if this happens on the latest version and we can consider reopening.

**Comment by GeorgesStavracas** [comment]
Allow me to give some more details to this situation. Closing this bug is correct because it is not an OBS Studio bug - our PipeWire code is able to draw transparency just fine.

What's wrong in this situation is the compositor itself. Mutter uses non-transparent frames both for window and monitor captures, and that's the problem. The black border around the window is its shadow, but because the buffer has no transparency, it becomes pure black.

**Comment by kevincox** [comment]
> It also doesn't work for maximized (or fullscreen) windows.

Sorry, This was a typo. It was supposed to say that the problem doesn't occur for these cases. Only non-maximized Wayland windows.

> this was fixed in the latest release, but you are way behind

Ah, I see that there was a problem building newer OBS for my distro, this should be fixed with the next release. I'll test again once I get an updated.|

> What's wrong in this situation is the compositor itself. 

Ok. I can file an upstream bug in that case however I am getting mixed messages. kkartaltepe said that this issue was fixed in OBS but you are claiming this is a Mutter bug. Is the true bug location known?

Testing with Firefox I see that there is actually a black border as well. (I though I had tested that, maybe my setup changed slightly?). So this probably is a Mutter bug.  I don't see anything in the GNOME GitLab, do you know if this is tracked already? Otherwise I will open a new issue.

**Comment by GeorgesStavracas** [comment]
The Wayland / PipeWire capture code in OBS Studio used to get a bit confused with transparency before, and that was fixed.

Now, Mutter needs to send images with transparency, which I'm afraid it doesn't do.

> Testing with Firefox I see that there is actually a black border as well. (I though I had tested that, maybe my setup changed slightly?). So this probably is a Mutter bug. I don't see anything in the GNOME GitLab, do you know if this is tracked already? Otherwise I will open a new issue.

[This was reported long ago](https://gitlab.gnome.org/GNOME/mutter/-/issues/1097), and I thought I fixed this with a merge request, but the black borders weren't actually fixed because [Mutter still hardcodes `RGBX`](https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/backends/native/meta-renderer-native.c#L918) as the image format, and RGBX doesn't have transparency.

I'd vote for opening a new issue in the [Mutter issue tracker](https://gitlab.gnome.org/GNOME/mutter/issues), could you please report it there?

**Comment by kevincox** [comment]
Reported to Mutter here. Thanks everyone for the help triaging. https://gitlab.gnome.org/GNOME/mutter/-/issues/2099

**Comment by shehackedyou** [comment]
I tried removing the shadows by setting the following setting in ~/.config/gtk-3.0/gtk.css 

And this worked to fix the black borders on `Chromium`, but oddly not `gnome-terminal`; so this may be a temporary fix until a more permanent solution is implemented. 

```
decoration {box-shadow: none;}
```
