### ISSUE TITLE
Two mutually exclusive hotkeys

### ISSUE THREAD

**Issue by YuriiBatkovych** [obsproject/obs-studio#5804]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/XWLDDHPML25b6DP7

### Expected Behavior

An error message should appear or the program must perform only one of the two mutually exclusive actions

### Current Behavior

The pause and stop buttons turned on at the same time, but the recording was not stopped.

### Steps to Reproduce

Open section Hotkeys
Click on "Stop Recording" field and enter a key "R"
Click on "Pause recording" field and enter a key "R"
Click Apply
Click on "Start recording" button
Click "R"

**Comment by RytoEX** [comment]
This should be fixed by #5297 in that it shows the user a warning if a duplicate hotkey is detected.  It does not prevent a user from assigning the same hotkey to multiple actions, because there are cases where the user expects a hotkey to trigger multiple actions or act as a toggle (for example, using the same hotkey for start/stop recording).  Please feel free to test the latest OBS Studio 27.2.0 beta or wait for the stable release of OBS Studio 27.2.0.
