### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [obsproject/obs-studio#5807]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

No response

### Expected Behavior

Hi, I can't install OBS on the standard user.
Please make an installation for the current user/all users.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

### Current Behavior

![image](https://user-images.githubusercontent.com/23485114/149641034-8c7eb214-4405-4a2f-8ce5-880f96e0f3ca.png)

### Steps to Reproduce

1. Download EXE installer from the OBS website.
2. Run it.

**Comment by feetstv** [comment]
Use the ZIP version instead.

Also, your "Expected Behaviour" screenshots are from an administrator account.

**Comment by xmha97** [comment]
> Use the ZIP version instead.

If you add this feature to the installer, users can install the app more easily.

> Also, your "Expected Behaviour" screenshots are from an administrator account.

No, my user is a standard user and I don't access to administrator account.

**Comment by Fenrirthviti** [comment]
The installer configures and installs certain functionality on windows (such as game capture components and permissions that OBS requires) that require administrator access to work properly. Due to this, we don't currently have any plans to support unelevated users with our installer process. Users who wish to use OBS in user-space only are free to extract the .zip file we provide.
