### ISSUE TITLE
Unable to connect to Twitch account

### ISSUE THREAD

**Issue by subokita** [obsproject/obs-studio#5928]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/jWZBx_FHjNXHyqCL

### Expected Behavior

It will connect to my twitch account after logging in from the pop up browser

### Current Behavior

It keeps showing this error / warning:
```
Failed to load channel information for Twitch
Failed to get text from remote: The requested URL returned error: 404
```

Note that it does log in to my twitch account, since Twitch sent me login confirmation thru email.

### Steps to Reproduce

1. Go to Settings > Stream
2. Choose Connect Account 
3. Login with your twitch credential and OTP
...

### Anything else we should know?

I can still stream with my stream key, but I lost my stream element docks that shows activities / chat / stream info.

**Comment by dodgepong** [comment]
This is a temporary issue due to Twitch performing a staged shutdown of the v5 API: https://twitter.com/OBSProject/status/1490771625398222851

OBS Studio 27.2 is updated to the new API and will be release before the full shutdown comes into effect.

For now, we recommend either using the 27.2 release candidate, using a stream key directly, or waiting for today's temporary outage to end.

**Comment by Gol-D-Ace** [comment]
Twitch is having a temporary V5 API shutdown.
You can either wait or try the 27.2 RC
