### ISSUE TITLE
Reload python script does not reload imported scripts

### ISSUE THREAD

**Issue by BryanCrotaz** [obsproject/obs-studio#5982]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/KEeSXG6x0gDEqiab

### Expected Behavior

When developing a script, you need to reload the new code frequently. The script reload button should cause OBS to use the updated code files.

### Current Behavior

The main.py that is loaded in the OBS script UI window is reloaded.

If the script imports other scripts (e.g. a main.py imports `./src/ui.py` and `./src/control.py`), these scripts are still cached from the previous run and are not reloaded.

### Steps to Reproduce

```python
# parent.py
from child import test

def script_load(settings):
    print('parent version 1')
    test()

# child.py
def test():
    print('child version 1')
```

Load `parent.py` in OBS

Logs show
```
parent version 1
child version 1
```

Change both files to log version 2

Reload in OBS

Logs show
```
parent version 1
child version 1
parent version 2
child version 1
```

**Comment by WizardCM** [comment]
As someone who doesn't fully understand how the scripting stuff works (SWIG is complex), I can't actually see how we trigger a script unload. It's almost like we trigger the OBS `script_unload` function and then just clear out the script? We don't seem to call a proper Python unload function, which would unload imports.

**Comment by serakeri** [comment]
I don't think there is a proper python unload function. The reference can be removed from sys.modules but this could cause some issues in other scripts since they are all running on the same interpreter. The same import cache issue can be seen with python's importlib.reload() which I assume is called when the script is reloaded with PyImport_ReloadModule.

There are code and libraries that will recursively reload imports but that is something a developer would have to use in their module after the imports. Another potential fix would be an additional button allowing the user to restart the python interpreter without restarting OBS although that would need to restart all of the scripts.

**Comment by PatTheMav** [comment]
This is neither an issue with OBS nor with SWIG, it's simply how Python works:

* When you add `parent.py` it is imported as a new module
* Modules are cached
* When you reload `parent.py`, Python will reload the module (thus update the byte code if the source file has changed)

Now here's the important bit:
* Any module imported by your script are _not_ reloaded, because they are imported globally by the interpreter
* When you reload `parent.py` and import the `test` function from `child.py`, you essentially tell the interpreter to load the module `child`, add the `test` function to the scope of the `parent` module and throw away the rest
* As the `child` module is neither removed or reloaded, reloading `parent.py` re-uses the cached `child` module to resolve the import of the `test` function

As I mentioned above this is not related to OBS or SWIG, but how Python works:

```
python3 -vv
>>> import sys
>>> import parent
# trying parent.cpython-310-darwin.so
# trying parent.abi3.so
# trying parent.so
# trying parent.py
# code object from parent.py
# created '__pycache__/parent.cpython-310.pyc'
# trying child.cpython-310-darwin.so
# trying child.abi3.so
# trying child.so
# trying child.py
# code object from child.py
# created 'child.cpython-310.pyc'
import 'child' # <_frozen_importlib_external.SourceFileLoader object at 0x1032d8310>
import 'parent' # <_frozen_importlib_external.SourceFileLoader object at 0x1032d90c0>
>>> del(parent)
>>> import parent
>>> 
```

As you can see, re-importing parent doesn't lead to the file actually being reloaded, as the module is still imported (you can check the contents of `sys.modules`). As OBS can only know about the script file's module itself, we can only reload that one.

What you _can_ do is something like this:

```
import sys
from importlib import reload
[...]

if child in sys.modules.keys():
    reload(sys.modules['child'])
```

The other common way to solve this would be to reload the entire interpreter, which is out of scope for how OBS has implemented scripting.
