### ISSUE TITLE
Toggling image source causes OBS 27.2.1 to crash to desktop without error

### ISSUE THREAD

**Issue by transcedence9** [obsproject/obs-studio#6013]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/wHOMTjqAFXivoR6G

### Expected Behavior

In version 27.1.3 whenever you toggle an image source, it just opens automatically without an issue. In 27.2.0, there was already a crash to desktop in a similar manner when toggling an image source.

### Current Behavior

Upon toggling an image source, the image loads then OBS quickly shuts down without a crash to desktop error.

### Steps to Reproduce

1. Start OBS 27.2.1
2. Have an image source that is not showing
3. Toggle said image source to showing.
...

### Anything else we should know?

This was performed both on a stream deck and through regularly clicking on the toggle for the image source. In both cases, there was a silent crash to desktop.

**Comment by WizardCM** [comment]
Which image source? Does it happen with all files? Does the image source have any additional filters or source transitions?

**Comment by Fenrirthviti** [comment]
I also cannot reproduce this on 27.2.0 or 27.2.1.

This sounds more likely to be a support request rather than a bug report, as it appears to be specific to your environment (i.e. third party plugins may be a factor) and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
