### ISSUE TITLE
Complete stream visual output freeze

### ISSUE THREAD

**Issue by dionisiusphocaea** [obsproject/obs-studio#6018]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://drive.google.com/file/d/1x8HEvpP-JZ9-VvFI7gnC1OwHFMPS2vkp/view?usp=sharing

### Expected Behavior

I expected to stream without issue - this is the first time I am having issue with OBS Studio.

I will be rolling back to the previous update.

### Current Behavior

Stream froze entirely visually and only outputted audio with a completely frozen visual output.
 Kept showing this message over and over in the log: 21:56:19.920: warning: Found EOI before any SOF, ignoring
21:56:19.920: fatal:   No JPEG data found in image

Wont allow me to upload the log as it is too large - I uploaded to google drive instead for you.

### Steps to Reproduce

1. Stream
2. After a little while this happened. Nothing in particular special otherwise.
3.
...

**Comment by WizardCM** [comment]
The following lines are likely from a video capture device source or something similar, not the output.

```
21:06:02.720: warning: Found EOI before any SOF, ignoring
21:06:02.720: fatal:   No JPEG data found in image
21:06:02.720: Error decoding video
```

How far into the stream did the video freeze occur?

**Comment by dionisiusphocaea** [comment]
I was live for around 2hrs before the initial freeze happened. I then stopped streaming and attempted to restart and even though it said streaming, connected etc on OBS, nothing happened on twitch, it never went live.

I then restarted OBS and went live again. It worked for around 45mins maybe then it happened again.

It isnt one particular capture device or source that is affected as it was the entire stream video that froze, nothing was happening at all - only audio was being fed through

**Comment by Fenrirthviti** [comment]
So, first this log is an absolute nightmare of errors and third party plugin debug/error messages.

Missing files:
```21:06:01.263: Failed to open file 'E:/Dionisius Assets/New overlays July 2021/cam mask-01.png': No such file or directory```

Audio device issues:
```21:06:12.116: WASAPI: Device '{0.0.1.00000000}.{e48c6522-6a31-49be-80e8-2c1f78284a61}' failed to start```

Media file issues:
```21:07:45.830: warning: Could not update timestamps for discarded samples.```

and finally in the stream results:
```21:54:02.627: Output 'adv_stream': Number of lagged frames due to rendering lag/stalls: 2248 (1.3%)```

Which seems to indicate that your GPU is having some issues keeping up with the rendering of the scenes, or something just caused OBS to stop rendering the output.

Because of the sheer amount of complexity being relied on here from third party plugins (and indeed, the errors/warnings coming from them), I don't know if this is something we can realistically take action on. We've had scattered reports of this output freeze problem, but in every case that I have looked at so far, it's been a setup with a significant amount of third party plugins.

Without better reproduction steps and a reduced test case on OBS without third party plugins, this is going to be very difficult for us to take action on.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

At this time, we believe it is likely caused by a third party plugin, and as there aren't reliable reproduction steps, we'd prefer to troubleshoot with you in a more real-time medium.

Please use the [Discord server](https://obsproject.com/discord) to continue this conversation for now. For more info, check our [Help page](https://obsproject.com/help).
