### ISSUE TITLE
Browsersource refreshs on scene switching when streaming

### ISSUE THREAD

**Issue by Rockatweb** [obsproject/obs-studio#6066]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/MjM7pSqhUiXMW1jz

### Expected Behavior

When i switch a scene my browsersource with the streamlabs chat will **not** be cleared

### Current Behavior

if i switch scenes when i am streaming the browsersource with the chat will be cleared on switching

### Steps to Reproduce

1. add browsersource with streamlabs chatbox
2. go live for quite some time
3. switch scenes and the chat is empty (i havent activated "Refresh browser when scene becomes active")

### Anything else we should know?

- i already have fixed some issues after creating the log and digging through the warnings before i opened this ticket
- don't had this issue with the old version 27.1.3

**Comment by Fenrirthviti** [comment]
I cannot replicate this with a normal browser source pointed to an arbitrary URL (https://webglsamples.org/aquarium/aquarium.html).

I suspect this is an issue specifically with the Streamlabs Chatbox (they may have built-in visibility state checking or similar). Can you confirm if this issue happens with any other URL?

**Comment by Rockatweb** [comment]
but this issue isnt there in the old version 27.1.3
is there anything that was changed in the new version with the browser source?

so i tested a different browsersource, but there i cannot see this issue, but when streaming this will not happen directly. As i said it needs some time. And it will not happen when your not streaming

**Comment by Fenrirthviti** [comment]
Yes, the browser source was updated a significant number of versions (From Chromium 75 to 95). However, the behavior described sounds like an issue with the page itself, rather than OBS.

Can you please provide exact replication steps? I'm not sure what "some time" here means, I have had OBS open and active since my last post and it still changes scenes just fine on my test source.

I would also recommend in the meantime reaching out to Streamlabs to report the issue to see if there is any information they can provide on their end, since as mentioned it might be something with the page itself.

**Comment by CyBeRoni** [comment]
https://github.com/obsproject/obs-browser/issues/307

**Comment by Rockatweb** [comment]
> [obsproject/obs-browser#307](https://github.com/obsproject/obs-browser/issues/307) may be related. Does it happen if you use studio mode and keep the chat scene in the preview?

i will try this tomorrow when i stream again. But this sound exactly like my problem

**Comment by Fenrirthviti** [comment]
Going to close this in favor of keeping discussion on https://github.com/obsproject/obs-browser/issues/307

If this is determined to be separate, we can reopen.
