### ISSUE TITLE
Alert followers to link web not view stream

### ISSUE THREAD

**Issue by thebigwolfy** [obsproject/obs-studio#6095]
### Operating System Info

Windows 8.1

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/X5-BSYSXGPJXgz02

### Expected Behavior

That the alerts are displayed

### Current Behavior

Currently, only the sound works, the alert is not displayed (I'm talking about the navaigator option)

### Steps to Reproduce

*I am french, sorry for traduction ^^'

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Please turn off hardware acceleration for browser sources in Settings -> Advanced. If this doesn't work, please use the above support channels.

Thank you!

**Comment by energizerfellow** [comment]
You're on Intel GPU driver version 10.18.10.3379, which is from 2013. Please update to the latest Intel iGPU drivers for your 3rd-genteration Intel Core i3-3240T from here:
https://www.intel.com/content/www/us/en/support/products/81501/graphics/graphics-for-3rd-generation-intel-processors/intel-hd-graphics-2500.html

**Comment by thebigwolfy** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Please turn off hardware acceleration for browser sources in Settings -> Advanced. If this doesn't work, please use the above support channels.
> 
> Thank you!

Thank you very much, sorry I didn't know ^^' All works <3
