### ISSUE TITLE
OBS recording glitch (I think I've found the cause)

### ISSUE THREAD

**Issue by ApplicationCoding** [obsproject/obs-studio#6103]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/TK-HDYVUe2P-_h85

### Expected Behavior

OBS will record just fine. Original Post: [Videos recorded directly at OBS glitches #5915](https://github.com/obsproject/obs-studio/issues/5915)

### Current Behavior

I was recording a video on OBS. Everything seems to work just fine as the viewer doesn't show any kind of bug. But when I was to play the video recording itself, the video was glitching. If my term is wrong, please correct it. But I have a screenshot of the clip I have recorded as an example of this bug.
![152452307-33d5e63e-9024-4a24-bfa4-cd64a484df5e](https://user-images.githubusercontent.com/76902392/157141721-e702e09c-d842-4210-8800-7e5aca98914f.png)

### Steps to Reproduce

1. Open OBS
2. Start recording
3. Stop recording
4. Remux the clip to **".mp4"**

### Anything else we should know?

I noticed that when I checked the **.mkv** version of the clip, there were totally no glitches or anything. The recording is very clean. So I think it's better if I use **.mkv** from now on with everything I record on OBS Studio.

**Comment by Fenrirthviti** [comment]
In the future, please don't open a second issue when the original was closed. If you think you have more information to confirm something is a bug rather than a support request, you can comment on the original post after it was closed. It would be preferred if you used the support channels as requested first, as this is not really actionable as presented.
