### ISSUE TITLE
My OBS Pop! OS dosn't renognize NVENC and error of external library

### ISSUE THREAD

**Issue by admirw** [obsproject/obs-studio#6109]
### Operating System Info

Other

### Other OS

POP! OS

### OBS Studio Version

27.2.3

### OBS Studio Version (Other)

obs STUDIO

### OBS Studio Log URL

https://obsproject.com

### OBS Studio Crash Log URL

https://obsproject.com

### Expected Behavior

I'D LIKE TO USE THE NVIDIA GEFORCE TO RECORD MY VIDEOS IN OBS STUDIO POP! OS

### Current Behavior

MANY ERROR MESSAGES
external library
software atualization and now, the pc don't recognize the nvidia in obs ... only option x264

### Steps to Reproduce

1.
2.
3.
...
???

### Anything else we should know?

Help me please!

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a side note, we do not support the Pop! OS package, so you will probably need to reach out to them to ensure that it is built properly.

Thank you!
