### ISSUE TITLE
Pair of crashes during the stream

### ISSUE THREAD

**Issue by omexlu** [obsproject/obs-studio#6142]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/54ui-baIVicu-3iB

### Expected Behavior

No crashes...

### Current Behavior

Today there was a crash several times during the stream so that OBS completely froze and the closing had to be forced.

Thanks in advance.

### Steps to Reproduce

I don't know how to describe it, it only happens once in a while but then several times.

**Comment by notr1ch** [comment]
Hello, please use the forums or Discord for support. Github issues are only for confirmed bugs with reproducible steps.

**Comment by omexlu** [comment]
Yes... and its still somewhere a bug? Its even known? Other games work great and before the last updates it worked to.

**Comment by feetstv** [comment]
Just because you're having an issue doesn't mean you've found a bug. If you need help and support, you should visit the [OBS forums](https://obsproject.com/forum/) and/or the official OBS community support [Discord server](https://discord.com/invite/obsproject).

**Comment by omexlu** [comment]
> Just because you're having an issue doesn't mean you've found a bug. If you need help and support, you should visit the [OBS forums](https://obsproject.com/forum/) and/or the official OBS community support [Discord server](https://discord.com/invite/obsproject).

Already done, but it seems to be a bug because few weeks ago i dont havent this problem.

**Comment by dodgepong** [comment]
Visit one of the support centers and talk to someone there. If they confirm that it is a bug, then we will re-open this. Until then, this issue will remain closed.

**Comment by dodgepong** [comment]
> I assume some bug.

Right, you're _assuming_ it's a bug. For the last time, please go to the Discord or Forums and find a support volunteer to work with you to either resolve your issue or _confirm_ that there is a bug, _with reproduction steps_.

**Comment by omexlu** [comment]
Already done...

I have also done some tests and maybe indentified this programm as problem:
https://obsproject.com/forum/resources/obscurrentsong-spotify.658/

Maybe this .exe makes some trouble with some games in combination with OBS.

Also I have minimalized all my sources and scenes to check wheres the problem.

My last battlefield stream was successfully, maybe this problem in combination with other sources was the problem.

I need to investigate more 👍

**Comment by dodgepong** [comment]
You say "already done" but have provided no further information that somebody from one of the support channels ought to have provided you. Who did you talk to? What did they say? Did you assemble reproduction steps for your bug report?

**Comment by Fenrirthviti** [comment]
Given the type of crash, this is almost certainly the fault of a third party plugin. 

When posting an issue or bug report to a project, you are asking for people to take time to verify and investigate the cause of the reported issue. Providing full, complete, replication steps is *required* for anyone on the project to take a closer look. Crash logs are helpful, but not a silver bullet for us being able to find an issue. If there are no steps, we cannot look, and posting in issue is a waste of everyone's time.

When we ask you to follow our process by going through the support channels first, we are not dismissing the issue, we are trying to help you follow the process and get the information that we need in order to take action.

Thanks for your understanding. It looks like this issue should be resolved by removing the faulty plugin.
