### ISSUE TITLE
Linux | Option 'Start virtual camera'  missing

### ISSUE THREAD

**Issue by Ricky-Tigg** [obsproject/obs-studio#6148]
### Operating System Info

Other

### Other OS

Fedora (Linux)

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/w06BC94Sv0wOSl0e

### Expected Behavior

Complete UI.

### Current Behavior

- Windows' side

![windows_obs_studio_v 27 2 3](https://user-images.githubusercontent.com/26058215/158383677-da730d43-966f-4a66-b8d0-5693a96923c1.PNG)

Option _Start virtual camera_ here present is missing in Linux.

- Linux's side

![q](https://user-images.githubusercontent.com/26058215/158383892-45bc4ccb-8b40-40d3-9067-a5b634284643.png)

### Steps to Reproduce

Get application via Flathub. Tested on Wayland and X11.

### Anything else we should know?

Linux and Windows installed on same computer.

**Comment by feetstv** [comment]
I suggest you visit the official OBS community support [Discord server](https://discord.com/invite/obsproject) and ask in #linux-support, as this seems like a support query rather than a code issue.

**Comment by mihawk90** [comment]
1. This is a support request, not a bug.
2. `15:09:23.060: v4l2loopback not installed, virtual camera disabled`
3. You need `v4l2loopback` to be installed to get this button

**Comment by Ricky-Tigg** [comment]
At least that did  confirm my doubt – missing component in that flatpak build.

**Comment by tytan652** [comment]
> At least that did confirm my doubt – missing component in that flatpak build.

The flatpak is missing nothing to enable the virtual cam, but your kernel is missing a module.

**Comment by Ricky-Tigg** [comment]
No surprise. Missing instruction in OBS very own Install Instructions [page](https://obsproject.com/wiki/install-instructions#linux) for Fedora. At last, that was the source of the issue. `sudo dnf install obs-studio v4l2loopback` should have been mentioned instead of the current incomplete command.

**Comment by mihawk90** [comment]
Depends on your definition of incomplete.
The virtual cam is an optional functionality, so listing it in the same command is not necessarily the best idea (see also the Ubuntu install instructions).

If you want to add them, you can do so by editing the Wiki.

On a sidenote:
`sudo dnf install obs-studio` is not eh Flatpak version and will miss you some functionality that RPM Fusion cannot ship.
If you want those, use the Flatpak as you did before or use my builds here:
https://github.com/mihawk90/obs-studio.spec/releases

**Comment by Ricky-Tigg** [comment]
I had trouble to understand your purpose

- "Depends on your definition of incomplete." | Sentence without original context.  That is **your** sentence.
- "_The virtual cam is an optional functionality_" | Whose OS that does apply to? At least not Windows. Nothing requiring user intervention to be part of the UI.
- "_see also the Ubuntu install instructions_" | Installation instructions are for Fedora, Ubuntu among others. No section suggesting common instructions for those OSs. Would it make sense to follow your advice and read section of an OS that does not match yours?

at https://obsproject.com/

![obsproject com](https://user-images.githubusercontent.com/26058215/158566376-4e47b096-44eb-4607-845f-bb32813f78c2.png)

Builds compared to Windows' release version
- **the one exhibited** (unknown OS) |  one version older
- **RPM Fusion** | two versions older
- **you builds** | two versions older
- **Flathub** | up-to-date

You see by yourself the one up-to-date. That is most likely to be picked.

**Comment by Ricky-Tigg** [comment]
I had trouble to understand your purpose

- "Depends on your definition of incomplete." | Sentence without original context.  That is **your** sentence.
- "_The virtual cam is an optional functionality_" | Whose OS that does apply to? At least not Windows. Nothing requiring user intervention to be part of the UI.
- "_see also the Ubuntu install instructions_" | Installation instructions are for Fedora, Ubuntu among others. No section suggesting common instructions for those OSs. Would it make sense to follow your advice and read section of an OS that does not match yours?

at https://obsproject.com/

![obsproject com](https://user-images.githubusercontent.com/26058215/158566376-4e47b096-44eb-4607-845f-bb32813f78c2.png)

Linux builds compared to Windows' release version
- **the one exhibited** (unknown Linux OS) |  one version older
- **RPM Fusion** | two versions older
- **you builds** | two versions older
- **Flathub** | up-to-date

You see by yourself the one up-to-date. That is most likely to be picked.

**Comment by Ricky-Tigg** [comment]
I had trouble to understand your purpose

- "Depends on your definition of incomplete." | Sentence without original context.  That is **your** sentence.
- "_The virtual cam is an optional functionality_" | Whose OS that does apply to? At least not Windows. Nothing requiring user intervention to be part of the UI.
- "_see also the Ubuntu install instructions_" | Installation instructions are for Fedora, Ubuntu among others. No section suggesting common instructions for those OSs. Would it make sense to follow your advice and read section of an OS that does not match yours?

at https://obsproject.com/

![obsproject com](https://user-images.githubusercontent.com/26058215/158566376-4e47b096-44eb-4607-845f-bb32813f78c2.png)

Linux builds compared to Windows' release version
- **the one exhibited** (unknown Linux OS) |  one version older
- **RPM Fusion** | two versions older
- **your builds** | two versions older
- **Flathub** | up-to-date

You see by yourself the one up-to-date. That is most likely the one to be picked.

**Comment by mihawk90** [comment]
> * Sentence without original context.  That is **your** sentence.

I know that's my sentence... but the context was you saying

> the current incomplete command

> * Whose OS that does apply to? At least not Windows. Nothing requiring user intervention to be part of the UI.

Obviously it applies to Linux since we're talking about the Linux version?
While it's true that the Windows version doesn't require additional setup, you just can't compare Windows and Linux directly, that's not how it works.
Both Windows and Linux require an API that OBS can send the video feed to to register as a camera. On Windows that is already part of the OS, on Linux that is handled through `v4l2loopback`, which is in itself a kernel module.
Whether you see Virtual Cam as optional or not, that module is required if you want to use it.

> * Would it make sense to follow your advice and read section of an OS that does not match yours?

It doesn't hurt to do so, but not in the context of the installation, rather in the context of the entire sentence that parentheses belongs to.
I mentioned the Ubuntu instructions because that's how it's listed there:

> If you want virtual camera support you need v4l2loopback-dkms installed. You can install it with the following command :
> 
> ```
> sudo apt install v4l2loopback-dkms
> ```

I agree it should be on the Fedora instructions too (hence the suggestion to add them), but as a separate listing just like the Ubuntu instructions. I would add them but I don't use the virtual cam so I don't know what the correct package (as Fedora has multiple ones).

The reason it's listed separately is because it might require some setup and may not work right out of the box. The alternative would be showing the button and it not working, which doesn't make sense either. And that is exactly why the module being disabled is logged in the Log Files.

> * **the one exhibited** (unknown Linux OS) |  one version older

It's not "unknown", and also not "older". That is the latest release for Linux - no matter the distribution - if the package is up to date. As dodgepong mentioned the .3 release is Windows only, see also [the Release Notes](https://github.com/obsproject/obs-studio/releases/tag/27.2.3).

> * **RPM Fusion** | two versions older
> * **your builds** | two versions older

Technically one (see above), but yes my builds ~~are~~ were not up to date because I was waiting on RPM Fusion (since they are based on the RPM Fusion spec-file). But since that doesn't seem to be happening for whatever reason I just pushed the latest release. Thanks for the reminder.

**Comment by mihawk90** [comment]
> Pay attention; notihng yet has been related to Linux version which is the version of the Linux kernel.

Oh my god can you stop intentionally twisting words.

Obviously we're talking about the **_Linux version of OBS_**

> Strange is that you were unable to mention that Linux OS distribution that would have provided that version 27.2.2 at the time. It shall remain unknown.

??? I'm not sure why I'd have to, but fine.
All that are up to date.
The Ubuntu PPA for one, which in fact is the only official Linux package that is actually maintained by the OBS team. 
Arch had it, but they went ahead to update the package version to 27.2.3 as well (which as was mentioned before is unnecessary).
And newsflash: There's a million distros out there and I don't know every single package version of every package for every distro.

> That number should not represent an installation source whose version number is not the highest.

That is exactly dodgepong's point.
27.2.2 **is** the latest release for any Linux because the 27.2.3 release is Windows-only.
The only reason Flathub has 27.2.3 is because Flatpaks are built on GitHub automatically and pushed to Flathub automatically whenever there is a new release on GitHub. Speaking from a source code perspective it is identical to 27.2.2 though, *for Linux*.

And to be clear here: It is not "wrong" to build 27.2.3 on Linux, it's just pointless because it doesn't include anything for Linux compared to 27.2.2, therefore the latest version *for Linux* is.

This is not the first time the versions diverged due to a hotfix and it will surely not be the last.

**Comment by Fenrirthviti** [comment]
This is getting really off topic and heated, so I'm going to go ahead and lock it. This issue was already closed and the solution was provided. If someone wants to update the install directions, feel free to edit the wiki.
