### ISSUE TITLE
Running two USB cameras crashes OBS while internet browser is on

### ISSUE THREAD

**Issue by Kynimer** [obsproject/obs-studio#6179]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/pneF_H9yZNRNmodw

### Expected Behavior

To be able to browse the web and stream from two cameras simultaneously.

### Current Behavior

Crashing.  Took me a second to sus out how it was crashing, so the crash log is a couple days old, uploaded manually in "Anything else".  The one uploaded via OBS is of one that didn't crash for comparison, I suppose.

### Steps to Reproduce

1. Stream from OBS with browser open
2. Turn on camera A
3. Turn on camera B
4. Wait a few seconds...
...

### Anything else we should know?

[2022-03-18 10-55-20.txt](https://github.com/obsproject/obs-studio/files/8311978/2022-03-18.10-55-20.txt)

**Comment by Fenrirthviti** [comment]
The additional log provided is not a crash log, but a normal log file.

I'm confused exactly what is being said here, but if your browser itself is crashing, sounds like an issue with the camera devices or your PC, not with OBS.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

If you meant that OBS itself is crashing, please provide the crash log (Help -> Crash Reports) from that, and this can be reopened.

Thank you!

**Comment by Kynimer** [comment]
OBS crashes, not the browser.  But only when the browser is open with two cameras on.  Sorry that wasn't clear and sorry for the wrong log, but I didn't find a crash log, it just stopped.
