### ISSUE TITLE
HW Encoder from GTX 650ti shows now NVENC but did not have it

### ISSUE THREAD

**Issue by niceguy0815** [obsproject/obs-studio#6191]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/QfwzEMwUiUH5aAiQ

### Expected Behavior

I hade an olde GTX 650 TI as encoder in OBS 27.1.X end it was woking fine before the Update.

### Current Behavior

But after Twitch API changes I hade to update to a newer OBS Version 27.2.3 in order to stream on twitch.
But now my old NVIDIA encoder is gone and i see now an entry NVIDIA MVENC h264 (new)
And i cant unse it because my GTX 650 TI did not have an NVENC encoder NO CUDA CORES!!!!
Now i have set it to software x264 CPU encoderbut. But why is the old Hardware encoder for NVIDIA gone?
Bug?
And i cant downgrade OBS becaus than i cant stream on twitch.

![image](https://user-images.githubusercontent.com/43955022/159539139-a7752d59-8f9c-490c-8ca0-44ad96ba89f8.png)

### Steps to Reproduce

1.Update odl OBS to 27.2.3
2.
3.
...

**Comment by Fenrirthviti** [comment]
StreamFX modifies available encoders in OBS, please remove it and check again.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by niceguy0815** [comment]
Hav compleatly deinstalled StreamFX but same result:
![image](https://user-images.githubusercontent.com/43955022/159543656-24d9e024-7df0-4dfd-b361-2846df179f50.png)

**Comment by Fenrirthviti** [comment]
I'm confused what the problem here is then, NVENC is right in the screenshot you have. If you're having issues starting a stream/recording, please use the support channels so someone can take a closer look why it's failing to start. Usually this means your drivers are too outdated.

**Comment by RytoEX** [comment]
> my old NVIDIA encoder is gone and i see now an entry NVIDIA MVENC h264 (new)
And i cant unse it because my GTX 650 TI did not have an NVENC encoder NO CUDA CORES!!!!
Now i have set it to software x264 CPU encoderbut. But why is the old Hardware encoder for NVIDIA gone?
Bug?

We would need log files from you trying to use NVENC in OBS Studio 27.2.3 to actually look into this. The best way to get help for this is to use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

> NVENC Encoder oly exists on new NVIDIA Cards 20xxx and 30xx with Cuda Cores.

NVENC exists on Kepler GPUs (GTX 6xx) and newer. In OBS, "NVIDIA NVENC H.264 (new)" is still using NVENC. It just has newer code in it. It _should_ automatically fallback to the older code if your system cannot use the newer code.

Our forums or Discord are the best places to investigate further.
