### ISSUE TITLE
Display DXGI method shows black screen on newer versions

### ISSUE THREAD

**Issue by Kinuseka** [obsproject/obs-studio#6269]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://pastebin.com/pi0gUMf2

### Expected Behavior

on versions 27.2.4 DXGI capture method does not work and shows black screen instead. Windows 10 1904 UP capture method works however not viable as it shows yellow corners

### Current Behavior

It is displaying black screen

### Steps to Reproduce

1.Open obs version 27.2.4
2.Display capture
3.Watch
...

### Anything else we should know?

It works fine on versions 27.0.1. Newer versions are highly unstable

Running on admin doesnt fix it either

**Comment by RytoEX** [comment]
DXGI works fine here on 27.2.4 on Windows Version: 10.0 Build 19044 (release: 2009; revision: 1586; 64-bit). DXGI Display Capture _may_ blink off and on while switching into or out of games running in fullscreen mode. Running multiple Display Capture sources pointed at the same display _may_ cause unexpected capture issues, so we generally do not recommend that you do this. When adding another Display Capture source, use the "Add Existing" option to duplicate the Display Capture source in a way that uses less resources.

Regarding the yellow border for "Windows 10 (1903 and up)" (Windows Graphics Capture / WGC):
> When using a Display Capture or Window Capture source with the "Windows 10 (1903 and up)" method, you will have a yellow border surrounding the portion of the screen being captured. Unfortunately, this border cannot currently be removed, as the Windows SDK does not allow it.
> 
> You can try using another capture method in the source properties, but it's possible this will instead produce a black screen. Once Microsoft releases an update to the Windows SDK that allows us to disable the yellow border, we will be sure to let you turn off the border.
> 
> It is only visible to you, and it will not show up on stream or in recordings.

However, it can be toggled off in Windows 11.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance. Thank you for your understanding.

**Comment by Technetium1** [comment]
@RytoEX this bug is still affecting OBS 27.2.4 on Windows 10 (21H2), Build 19044 revision: 1826; 64 Bit.

**Comment by nkrad** [comment]
Adding on for interest, black screen. Same setup as @Technetium1 ^

**Comment by RytoEX** [comment]
@Technetium1 @nkrad Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance. Please be prepared with logs of OBS sessions where this behavior occurred. Thank you for your understanding.
