### ISSUE TITLE
OBS: Glitches in Windows (Panels)

### ISSUE THREAD

**Issue by pheiduck** [obsproject/obs-studio#6291]
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

27.2.1

### OBS Studio Version (Other)

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Cuhpbz2yupChC9kC

### Expected Behavior

No glitches in side windows (like in the Flatpak)

### Current Behavior

Option windows aren't usable, because they have a wired Behavior on XFCE.: (see image)
https://forum.manjaro.org/uploads/default/original/3X/7/7/777db6b8680abb10e356f850a6a6599013988ad0.png

### Steps to Reproduce

1. Install PKGBUILD (Arch Linux Package)
2. Select a Source
3. See behavior inside the Properties

### Anything else we should know?

Enviroment: Manjaro XFCE Kernel 5.15.28
Behavior is see on Version 27.2.1 and 27.2.3

**Comment by pheiduck** [comment]
Its only broken on the dark Theme / default is fine

**Comment by pheiduck** [comment]
@Fenrirthviti any News here?

**Comment by Fenrirthviti** [comment]
No news, but this is almost certainly going to be a problem with your environment, rather than anything in OBS specifically. I don't know what though, but any time we come across theme issues with Linux, it's a problem with global environment Qt/theme overrides that mess with our themes. Could also be related to UI scaling. Since this isn't using our package (we don't natively support or provide to Arch), and I've tested the themes are working fine on my Debian system which uses XFCE, there isn't enough information here to be actionable.

This is probably something that should be run through our normal support channels [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) first. If a bug or issue on the OBS side can be determined, we can reopen this.

**Comment by HerrCraziDev** [comment]
Aloha !

I have also experienced the same problem with the default dark theme. I'm on Arch with KDE. Changing themes did not help - it happens regardless of the theme used.

**Comment by pheiduck** [comment]
the flatpak resolves the issue for me. So I suggest not using the Arch PKGBUILD because its not official supportes by obs

**Comment by HerrCraziDev** [comment]
Thanks! Will try that
