### ISSUE TITLE
40.000+ page faults per second (No PageFile.sys possible cause: the OS denying illegal memory access. Second cause: OBS Growing memory access ?)

### ISSUE THREAD

**Issue by SkybuckFlying** [obsproject/obs-studio#6303]
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/vto5TRf-fCDyBXp6

### Expected Behavior

Be efficient and don't generate page faults.

### Current Behavior

Generating 40.000+ page faults per second.

Note: 

The operating system is Windows 7 Home Edition with PageFile.sys disabled.

### Steps to Reproduce

Open task manager on Microsoft Windows.

Enable Page Fault columns.

Watch the page fault difference counter/column.

### Anything else we should know?

Please fix it, this lags the system incredibly and it forces me to switch to another streaming software solution.

(This toshiba laptop does have a broken 3D graphics chip, not sure if that has anything to do with it, at least I believe this is the case, could also be a broken driver but I don't think so, I turn off hardware acceleration in all software, including webbrowser/firefox, but this should not effect streaming since OBS can be used even when firefox is not running).

Here you can see my youtube stream and you can see OBS is working on this laptop:

https://www.youtube.com/watch?v=zz167CxQZyQ

At 2:05 minutes approx you can see me right now and see the task manager in action and the page faults.

Most likely this is being caused by "the OS denying illegal memory access".

**Comment by Fenrirthviti** [comment]
OBS requires a properly functioning GPU to operate. Please fix your hardware as there's nothing on the OBS side for us to do.

**Comment by derrod** [comment]
(Also WIndows 7 is not supported anymore)

**Comment by SkybuckFlying** [comment]
There is  something to do for you, check if OBS is also producing page faults on your systems !

**Comment by RytoEX** [comment]
I have checked. While OBS does produce some page faults on my system, this is not, by itself, evidence of anything particularly wrong. As far as I know within my limited understanding, applications can generate page faults through normal operation. What _would_ be concerning are a large number of hard faults, which I am not seeing when checking Performance Monitor or Resource Monitor. At most, I've seen single/double digit numbers of those. I've certainly not seen 40,000+ per second of any type of page fault.

Additionally, given that your system only has 6GB of RAM, disabling PageFile.sys will only exacerbate the low availability of RAM by not allowing the system to allocate virtual memory when needed. This is most likely leading to the large number of page faults that you are seeing.

> This toshiba laptop does have a broken 3D graphics chip, not sure if that has anything to do with it

OBS relies heavily on graphics hardware to render its graphics. This may or may not contribute to the high count of page faults on your system.

These things together would lead me to conclude that the issue you are seeing is caused by your system configuration (RAM constraints, disabled PageFile, possible issue with GPU). As written, this Issue is not actionable. There is nothing further for us to investigate. Thank you for understanding.

**Comment by SkybuckFlying** [comment]
Windows divides the RAM into 4 kilobyte blocks called pages. These pages are stored in lists in Windows.

Windows pretends to be capable of doing more than it really can by sometimes writing these 4 kilobyte pages to disk for memory which is not recently accessed, or when there is a shortage of memory.

Once the user switches back to an inactive application this can cause freezes because now windows has to load these 4 kilobyte pages back into RAM from the disk.

These "missing' 4 kilobyte pages in RAM is what causes the page faults, it signals to the system that something is not there and should be loaded. It can also indicate an illegal memory access.

Disabling pagefile.sys will keep windows very fast, but will limit what it can do.
Disabling pagefile.sys forces the applications to stay in RAM at all times, and thus these kinds of page faults should be illiminated this you can try yourself.

OBS needs only 1 gigabyte of RAM so 6 gigabyte of RAM is fine.

So this only leaves the possibility of another kind of page fault being caused, most likely some kind of illegal memory access.

Perhaps it is calling some kind of API that is not available on windows 7 or something deep in the graphics driver.

So far OBS seems to be working fine, except it generates these page faults and that can take quite some CPU it seems though not entirely sure.

One thing you could do is try and run OBS studio on a windows 7 computer if you have one and see if the problem is there too.

**Comment by RytoEX** [comment]
> One thing you could do is try and run OBS studio on a windows 7 computer if you have one and see if the problem is there too.

I do not have one. We officially stopped supporting OBS on Windows 7 a year or two ago. Microsoft stopped supporting it completely on January 14, 2020. I don't think anyone on the dev team has a Windows 7 machine. We're unlikely to commit resources to investigating this further.

**Comment by alinsavix** [comment]
@SkybuckFlying:
> So this only leaves the possibility of another kind of page fault being caused, most likely some kind of illegal memory access.

This is not really an accurate description of how things work.

There are _lots_ of causes for page faults, of which you only mention a few, and you fail to differentiate between hard and soft page faults.

An example of the other things that _very_ commonly cause soft page faults, which is in no way an exhaustive list, include things like writing to a copy-on-write memory page (the page fault is used to copy the page and make the copy writable), the first use of allocated-but-not-mapped pages (the page fault is used to map a physical page into the appropriate place in the process, because generally allocating memory _does not actually allocate physical pages until they are used_), accessing a page on the standby list (the page fault is used to mark it as recently used). A huge number of things in modern systems use the page fault mechanism as a completely normal part of their memory management.

Invalid memory accesses, though they do generate page faults, use the fault handler to... crash the program. If OBS is accessing invalid memory, you will get exactly one page fault, an OBS crash, and ... that's it.

Hard page faults (and you never did differentiate what kind you were getting) are indeed used to page in memory that's been written to the page/swap file, but that's far from the only use there, either. Hard page faults are also how memory mapped files are brought into memory -- and that's a pretty common way to handle file processing of a lot of files.

So even there, going "I have 6GB and OBS only takes 1GB" in no way means you'll be free of page faults. Especially since all the memory OBS actually uses isn't strictly measured as OBS's RAM usage -- files cached in memory, for example, don't show as OBS memory, but still take memory from the system. And if at any point the system starts to think it's low on memory, it will start looking for memory that is not in active use, that it can discard to free up some working memory (and page back in later, via hard fault, if needed). There are all sorts of things like this always happening under the hood, which frequently make it difficult to even accurately answer simple questions like "how much memory is X _actually_ using", much less answer more complex questions about how memory (and other resources) are used in a given OS at a given time. The VM setups of modern operating systems are _extremely_ complex.

At any rate, you seem to have an incomplete understanding of how memory management on modern systems works, and because of that are jumping to conclusions that do not actually match the facts at hand.

The reality is that it's impossible to point to something that says "there are `n` page faults/s" and be able to declare it a problem, _regardless_ of the value of `n`, without additional information. In some situations 100 faults/sec might be indicative of a problem. In other situations, 1000000/sec might be indicative of a properly functioning system. You are seeing problems where there is none (or, at least, you haven't provided evidence of an actual problem).. There's nothing that describes something that can be fixed. Our princess is in another castle.

**Comment by SkybuckFlying** [comment]
I observed a lot of software during my life time, high ammount of page faults per second are quite rare, and is usually an indicator that something is wrong with the software.

I have taken a look with perfmon.exe.

From the looks of it it seems that these 40.000 page faults/seconde are caused by nil-pointer accessess.

So this means the applications is trying to access memory via a pointer which is set to nil which is equal the memory address 0, which is a reserve place in virtual memory per application. I believe the lower 64 KB of virtual memory are inaccessible/illegal to access, these are reserved for the OS.

Operating Windows 7 has the capability of observing illegal memory access attempts to address 0.

Not sure if this is address 0 per application process/virtual memory space, or if it's address 0 for the os/hardware itself.
