### ISSUE TITLE
Virtual cam doesn't work

### ISSUE THREAD

**Issue by MarkMHY** [obsproject/obs-studio#6340]
### Operating System Info

Other

### Other OS

macOS 12.3

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/X6ibi85tr2ZsNJJ8

### Expected Behavior

i hope the virtual camera can work correctly.

### Current Behavior

i tried to open virtual camera, but it didn't work, while in OBS app, it told me the virtual cam had been opened.

### Steps to Reproduce

1.open the virtual cam
2.try to use it in Photo Booth, but i can't find it in camera list
3.close the virtual cam, and try again
...

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by darknoon** [comment]
So I don't think this bug is very clear, but I think this is a valid issue…

To display the source in certain Apple apps like Safari, you need to use the new avextension system extension point, available since macOS 12.3

There are a few components to providing this:
- Create system extension
- Bundle within OBS app
- Use App Group to allow them to communicate
- Provide directions on how to activate (Open System Preferences, click Allow)

So, this is probably better regarded as a feature request, nonetheless it would be very nice to provide it [like Camo has](https://twitter.com/reincubate/status/1521794064538128386).
