### ISSUE TITLE
obs hangs when stoping recording and never stops it. wayland

### ISSUE THREAD

**Issue by jokbon** [obsproject/obs-studio#6473]
### Operating System Info

Other

### Other OS

Kubuntu based on ubuntu 20.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/mfHNVSshjsKo65UW

### Expected Behavior

obs stops recording properly

### Current Behavior

obs is no longer responsive when stoping recording

### Steps to Reproduce

1.start fulscreen recoding with settings below
2.stop recording
3.obs stoping recording hangs
...

### Anything else we should know?

![image](https://user-images.githubusercontent.com/29400409/168441857-c5d44f62-1c17-48ca-8932-7d4c95dafa10.png)

same system on windows can record

**Comment by Fenrirthviti** [comment]
Looks like your system cannot handle the AV1 encoder, which is experimental anyway. It's failing to stop because the encoder is lagging so far behind, it doesn't understand what to do anymore.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
