### ISSUE TITLE
OBS freezes when closing after recording

### ISSUE THREAD

**Issue by osfanbuff63** [obsproject/obs-studio#6504]
### Operating System Info

Windows 10

### Other OS

N/A

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

N/A

### OBS Studio Log URL

https://obsproject.com/logs/q0icgp7dQuav6b0t

### Expected Behavior

OBS wouldn't freeze 

### Current Behavior

OBS froze instead of closing

### Steps to Reproduce

1. Open OBS, and start recording (DO NOT perform any other action!)
2. Stop your recording
3. Attempt to close OBS

### Anything else we should know?

If you open OBS and perform no action, this also occurs. The only way to stop it, that I know of, is closing the OBS process from Task Manager.

Sorry if this has already been reported, I just couldn't find another report on it :P

**Comment by Fenrirthviti** [comment]
You are using a third-party plugin which is showing some odd messages in the log, as well as running in sRGB/Full mode which is not recommended and may not be fully or well supported on hardware that old. On top of that, you have several issues with your scenes/sources that fall outside of normal recommendations.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
