### ISSUE TITLE
Aborted TBar transition results in incorrect result from obs_frontend_get_current_scene

### ISSUE THREAD

**Issue by OldBaldGeek** [obsproject/obs-studio#6586]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/cMBbQ1HW4wVZns2S

### Expected Behavior

In studio mode, when the TBar is moved all the way to the right and released, a normal transition occurs.

If the TBar is moved part-way to the right, but then back to the left and released, the Program view appears unchanged. A call to obs_frontend_get_current_scene should return the scene shown in Program (as it did before the TBar was moved)

### Current Behavior

If the TBar is moved part-way to the right, but then back to the left and released, a call to obs_frontend_get_current_scene actually returns the scene shown in Preview

### Steps to Reproduce

1. Select Studio Mode
2. Load a Scene Collection with at least two scenes, A and B. Show A in Preview, and B in Program
3. Load the script TBarFun.lua, and open the Script Log
4. Press the "Show Scenes" Button in the TBarFun UI. Two lines appear in the log, showing A as Preview and B as Program.
5. Invoke a transition, then press "Show Scenes" again. As expected, new lines appear in the log showing B as Preview and A as Program
6. Move the TBar partway to the right, then back to the left and release it
7. Press "Show Scenes" and new lines appear in the log showing B as both Preview and Program, even though the Program view clearly shows scene A.
...
[TBarFun.lua.txt](https://github.com/obsproject/obs-studio/files/8836584/TBarFun.lua.txt)

**Comment by PatTheMav** [comment]
The issue looks like it stems from this source:

https://github.com/obsproject/obs-studio/blob/7396c211be75da3bce74cf8d2661a481a5c10fff/UI/window-basic-main-transitions.cpp#L315

When moving the T-Bar slider, `TransitionToScene` is called, which sets the `programScene` to the source scene. But as the transition is never completed, this never becomes the case. And stopping any movement on the slider doesn't reset this information.

The frontend-API call just returns the name of the current `programScene`, hence why the Lua script will yield the updated name.

I have no current idea how to fix it, but the bug is confirmed.
