### ISSUE TITLE
Linear alpha blending makes transparent images render incorrectly in browser sources

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#6659]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

25.0.8 (no issue), 27.2.3 (has this issue)

### OBS Studio Log URL

27.2.3: https://obsproject.com/logs/OSLWeBlPIqqEqPRv 25.0.8: https://obsproject.com/logs/8gusm9aJiX13dCb0

### Expected Behavior

Images with alpha should render correctly using Browser source.

### Current Behavior

Images with alpha render as if the alpha channel was replaced with 50% grey.

### Steps to Reproduce

Download this image file and add it as a Browser source.
[follower_bar_swirl_ALPHA.zip](https://github.com/obsproject/obs-studio/files/8987233/follower_bar_swirl_ALPHA.zip)
![follower_bar_swirl_ALPHA](https://user-images.githubusercontent.com/63289008/175828406-dec32db6-0b0c-4e94-b7b2-e940976abe41.png)

**Comment by jpark37** [comment]
This looks like a consequence of upgrading Chromium for the browser source in v27. The image we get from CEF has the gray baked in, so we can't reasonably adjust it from there. It looks like you can work around the new behavior by suppling an html file with an img tag, or just using an image source instead of browser source.

**Comment by thatpix3l** [comment]
For those that end up here through searching and absolutely _need_ the browser source (like custom WebApps), set the CSS for `html` and `body` elements to `background: none !important`
