### ISSUE TITLE
OBS not saving last path when browsing for LUT filter

### ISSUE THREAD

**Issue by flleeppyy** [obsproject/obs-studio#6777]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/qYRCAtNpCPG4fZOM

### Expected Behavior

I expect that OBS saves the last folder I was viewing when I selected the filter I want to use, so I can try out multiple filters

### Current Behavior

When selecting a LUT filter for a source, it does not save the last path you were browsing at that moment, but it saves when you click "Close" and open the window up again.

### Steps to Reproduce

1. Add source like a webcam or something
2. Open Filters
3. Apply LUT Filter
4. Browse for a filter, and go to a folder that is not the default obs-filters folder
5. Select one
6. Browse for a filter again
7. The last path you were in did not save.

Now do this again but instead of browsing for a filter again, close the filters window, open it again then browse for a filter, it will then have your last path saved, but this is not the wanted and convenient behavior.
...

**Comment by tuduweb** [comment]
This situation is caused by `obs_properties_add_path` arg5 `default_path`. 

When this argument is not `NULL` like in LUT, the path dialog will always show `default_path` or `s->file` after that property UI construction.

I think this is a bug. This path property dialog default path should be changed after user changing the path setting.

**Comment by RytoEX** [comment]
Looking into this and the linked PR to make sure I understand the scope. Leaving some notes here.

The Path property of the "Image Mask/Blend" filter does not have this issue, because it specifies NULL for `default_path` to `obs_properties_add_path`. The "Image File" property of the Image Source does not have this issue because its `path` used for `default_path` is initialized as NULL and has no default value. Every other case in the obs-studio code that I examined is similar to Image Source, and is not susceptible to this bug, so this appears to be unique to the LUT filter (at least in obs-studio code) because it always specifies a path for `default_path`.
