### ISSUE TITLE
27.2 -> post-CMake rewrite upgrade mixes both _obspython.pyd and obspython.pyd which are incompatible

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#6841]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3 and git

### OBS Studio Log URL

https://pastebin.com/raw/zuTcH0va

### OBS Studio Crash Log URL

1 https://obsproject.com/logs/GzmAUnSdZTvDDp1x 2 https://obsproject.com/logs/s1uNRpNs1MPwBb2B 

### Expected Behavior

I expected scripts to keep working after a manual update.

### Current Behavior

Looks like two different files end up in the data/obs-scripting/64bit folder, which breaks all Python scripts, and also causes a crash on exit. I tried to change Python runtime version between 3.6 and 3.8.5, every attempt also resulted in a crash. Also, it seems that the file structure is slightly different:
![image](https://user-images.githubusercontent.com/63289008/181522833-8210d154-af7c-458d-afd9-34089ab9b3ab.png)

### Steps to Reproduce

1.Install 27.2.3 
2.Install nightly (I used https://obsbot.rodney.io/artifacts/311851020)
3. Try to load any Python script, or change Python runtime folder

**Comment by WizardCM** [comment]
I noticed the same behaviour (two obspython.pyd files) while testing #6706. I can confirm it was not introduced by #6706 or #6696, but rather the Cmake rewrite in #5155.

It is likely this is simply a side effect of the rewrite, or could be intentional. Nothing stands out in the CMakeLists to explain why it's different.

I expect the official fix will be #6500, though we would need a similar check/fix for the installer. Manual copy-paste of versions will likely not be supported though.

**Comment by WizardCM** [comment]
Fixed by #6882
