### ISSUE TITLE
[28.0.0-beta1] Mouse wheel no longer scrolls drop-down menus

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#7011]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/0xyWe_UucX_rIPYT

### Expected Behavior

After hovering a drop-down menu or an editable combo box, the mouse wheel can be used to select the next or previous option.

### Current Behavior

After hovering a drop-down menu or an editable combo box, the mouse wheel doesn't do anything.

### Steps to Reproduce

1. In Settings>Advanced, hover the "Color Format" drop-down menu
2. Scroll down and up a few times

**Comment by notr1ch** [comment]
This was intentionally changed to prevent accidental changing of values.

https://github.com/obsproject/obs-studio/pull/6220

**Comment by matoi974** [comment]
Can this be made optional? I use the scroll wheel intentionally and this change is rather inconvenient.

**Comment by MattyFresh68** [comment]
I'm personally a fan of this change, however, I can see having this behavior as an option for a user to opt in to seems logical if at all possible.

**Comment by dodgepong** [comment]
Making this an option would be unnecessary complexity. Preventing accidental changing is much better behavior.

**Comment by MattyFresh68** [comment]
Is it complexity for those that have used it that way for an extended period of time? I get avoiding the accidental change. But I also dint get giving users a way to set how they interact as an option, given they are accustomed to how they interact.

**Comment by RytoEX** [comment]
The complexity mentioned is in terms of code written, maintainability, and user support for instances and variations of "my encode quality isn't what I expected for the options I picked" or "my audio sources aren't in my stream/recording the way I set them up" only to find that they'd unintentionally changed something by scrolling through the list of settings. We consider the capacity to unintentionally change settings resulting in a sub-par recording/stream to be close to data loss, and thus, it is something we want to avoid.

**Comment by dodgepong** [comment]
Any time you add an option for something, you increase the UX complexity of the program and make it harder for people to learn. It's how options screens balloon to huge pages of esoteric settings, because _someone_ out there wanted it to be an option. There's a very good reason that [XKCD 1172](https://xkcd.com/1172/) has become a meme among the OBS developer community.

There's a point at which we have to put our foot down and decide that the cost of adding yet another option does not outweigh the benefit the option confers. Given the fact that this option can easily turn into a footgun (allows users to shoot themselves in the foot by accidentally changing settings when they scroll a window), it's an easy choice to simply omit the option entirely.
