### ISSUE TITLE
[28.0 Beta 2, macOS] Application/Window Capture

### ISSUE THREAD

**Issue by Chromagram** [obsproject/obs-studio#7051]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/PMQu3gQVXt7dkohQ

### Expected Behavior

Expected behaviour is that on the macOS release, the Window and Application capture modes function the same as the one found already in OBS for Windows, as previously noted in an https://github.com/obsproject/obs-studio/issues/6299.

Window Capture should only capture the windows of actual applications, not things like icons on the menu bar, SpringBoard or background task items, etc.

Application Capture, no matter the state (windowed or in full screen), should again, only capture actual applications and not backend processes. Also expected of Application Capture, by selecting an open application like Google Chrome for example, it should actively capture everything Chrome is displaying, including all of its tabs and any changes. Finally, with both capture states, it is my explicit suggestion that OBS should not capture the scrolling animation when macOS swipes between full-screen Spaces ([example animation](http://kb.parallels.com/Attachments/kcs-12540/swipe.gif)).

### Current Behavior

Currently, Window capture displays non-application windows including things like [Control Center], [Spotlight], [Notification Center], and other background processes like "Focus Proxy", "Menubar", etc. These are very niche captures that either display nothing, or display a single asset like an icon from your menubar by itself. It is my strong opinion that if you wanted to capture a single small asset like that, you can crop either a display capture or window capture for a specific window.

Switching to Application Capture, currently it does display all the names for the open applications. No matter what application you add besides OBS itself, it seems to just capture a black overlay with OBS Studio's menubar above.

For example, I want to capture Google Chrome as an application because I want to have a scene where my stream and I can look at a couple tabs I saved beforehand. At the moment, if you use Window Capture, you can only select a single tab within Chrome, and if you switch to another tab within Chrome, the capture is lost. If you use Application Capture and select Chrome, you just get the aforementioned black screen with the OBS Studio menubar up top. You either have to preemptively predict every single tab you might want to share throughout your entire stream and add them as sources, or fiddle with the settings and possible resizing/crop constantly during a stream.

[Addendum 1] I have also discovered that with the currently testable Window Capture, it won't actually show an active capture of the selected window, but it will just grab a screencap of the current state and freeze there until you edit the source again to get a new screencap. For example, I added IINA (a media player on Mac) as a window capture, and it correctly showed the window. However, the progress slider, the scrolling metadata, and the change when the song turns over, none of that moves in the capture. It appears to just be a still screencap.

### Steps to Reproduce

- Add a new source for macOS Screen Capture.
- Select Window Capture, and tick on both Show Applications and Show Cursor boxes. (Mirroring cursor/unnecessary processes issues)
- Alternatively, select Application Capture and ensure the same tickboxes are checked. (Black capture/mirroring cursor issues)
- Also, select Window Capture, select an active window with any moving elements. (Frozen capture issue)

**Comment by PatTheMav** [comment]
> ### Current Behavior
> Currently, Window capture displays non-application windows including things like [Control Center], [Spotlight], [Notification Center], and other background processes like "Focus Proxy", "Menubar", etc. These are very niche captures that either display nothing, or display a single asset like an icon from your menubar by itself. It is my strong opinion that if you wanted to capture a single small asset like that, you can crop either a display capture or window capture for a specific window.

We didn't implement a global "exclusion" list yet, reasons include (but are not limited to):

1. Any app adding a menu bar item will have it appear as a separate "window" in the list, we cannot possibly maintain a list of all these window identifiers
2. We do not have a well maintained and tested list of window identifiers for default helper windows
3. We chose to have this feature out sooner rather than later for its massive improvements in capture performance and capability (i.e. direct audio capture on macOS 13).

We'd happily review a PR that implements such a list of default window identifiers that can be safely excluded, though be mindful that there will always be users that would go "but I _need_ to capture some of those", so it'd probably need to be an option that can be toggled.

> Switching to Application Capture, currently it does display all the names for the open applications. No matter what application you add besides OBS itself, it seems to just capture a black overlay with OBS Studio's menubar above.

Cannot reproduce, all my applications on the selected screen appear in the dropdown and are captured with all associated windows (as positioned on the given screen).

> For example, I want to capture Google Chrome as an application because I want to have a scene where my stream and I can look at a couple tabs I saved beforehand. At the moment, if you use Window Capture, you can only select a single tab within Chrome, and if you switch to another tab within Chrome, the capture is lost. 

Either I don't understand the issue correctly or that's an issue with Chrome. If I select a single Safari window with multiple tabs in it, I can switch tabs just fine and the capture shows the contents of the changed tab accordingly (because the tabs still exist within the same application window).

> If you use Application Capture and select Chrome, you just get the aforementioned black screen with the OBS Studio menubar up top. You either have to preemptively predict every single tab you might want to share throughout your entire stream and add them as sources, or fiddle with the settings and possible resizing/crop constantly during a stream.

As noted above, I cannot reproduce that behaviour.

> [Addendum 1] I have also discovered that with the currently testable Window Capture, it won't actually show an active capture of the selected window, but it will just grab a screencap of the current state and freeze there until you edit the source again to get a new screencap. For example, I added IINA (a media player on Mac) as a window capture, and it correctly showed the window. However, the progress slider, the scrolling metadata, and the change when the song turns over, none of that moves in the capture. It appears to just be a still screencap.

That is a limitation of macOS - if you put IINA or Quicktime into fullscreen, the WindowServer will not render every frame of the video as it's not visible (macOS prioritises system and energy efficiency) and will only continue audio playback. As such the capture will only get a single frame capture from the full screen source. The same applies when an application is minimised.

**Comment by HiroiSekai** [comment]
Thanks for the reply, I do want to mention a few things to it:

Regarding the exclusion list, that makes sense and I understand. I do like the idea of longer term that a general default list of exclusions with an optional tickbox, not honestly a big deal. It's just about digging through 10-20+ entries hunting for a specific window, especially during a stream.

I'm going to combine the replies for Application capture into one note, I definitely continue to have the problem through each of the existing beta and release candidate updates. Here's a couple videos: one showing that OBS Studio itself as an Application Capture works as intended, the other video shows how nothing else does.

https://user-images.githubusercontent.com/44986450/186536724-93b606e5-ea58-4b66-a148-3cb00bbc2169.mov
https://user-images.githubusercontent.com/44986450/186537143-0d9e3d95-87d3-41b8-b6c2-abda6e08f4bd.mov

As for the IINA example, I have tested the windows in full screen and windowed mode, but specifically for IINA, the issue was reported while testing in windowed mode. It does not enter full screen in any way, nor is it minimized, it stays up on the desktop the whole time.

**Comment by PatTheMav** [comment]
Unfortunately I cannot reproduce these issues, I can capture apps and windows just fine. Have you given OBS.app the necessary screen capture permission? If you already have an entry in your privacy settings and you ran the x86_64 version of OBS before, that permission won't apply to the M1 version.

**Comment by HiroiSekai** [comment]
That is strange for sure. Just to make sure, I closed OBS, went into my Mac's Security settings, removed OBS.app from Screen Recording, then added a new entry for the OBS.app that I have now, which is the Release Candidate 2 that was just released.

I unfortunately still have the problem. I can't describe why it's happening to just mine.

**Comment by RytoEX** [comment]
I cannot reproduce this on macOS 12.5. Are you trying to capture windows or applications that are minimized?

**Comment by HiroiSekai** [comment]
I am not, they are all open and either in Windowed mode on the desktop, or in macOS full screen mode.

**Comment by HiroiSekai** [comment]
I did a little bit more fiddling around as troubleshooting. The only thing I found is that _if_ I take OBS out of macOS full screen mode, Application Capture replicates how it always did on older versions of macOS OBS Studio- it will only successfully capture apps that are windowed as well and on the same desktop. Even this though is not acting correctly.

As previously mentioned, even with OBS in full screen mode, if you select OBS from the application capture list, it will display properly as expected. It shows the OBS menu bar at the top, with the application captured in full below. Pick anything else while OBS is full screen, and it captures a black screen. You can even kind of see that it's trying to capture the app's menu bar because just the little  button gets captured in the very top left.

At this point I've tried removing every instance of OBS from my security settings and adding it to every subsection I can, and it hasn't changed anything. I'm at a loss of what to try.

**Comment by PatTheMav** [comment]
This is expected behaviour - if you put OBS in full screen mode, it will be moved onto its own separate space. As no other window is visible, their contents will not be updated and as such the capture will also yield no frames.

The important thing to remember with SCK is that macOS will always prioritise energy efficiency, so content that does not need to be updated, will not be updated:

* Minimised windows
* Windows on other spaces but the current one

When running OBS on a different space, all windows on another space will be treated as "hidden" by macOS (which is also why you need to enable "show hidden windows") and visible updates are suspended.

Do note that OBS will record and stream contents of the Window Capture just fine, but the you need to ensure that you keep the space with the played content (game, application, video) active.

**Comment by HiroiSekai** [comment]
Sorry if I'm mistaken, but wasn't the whole point of updating the framework for macOS to allow for apps to be captured more like the style that Windows OBS does with less of the restrictions? This expected behaviour is no different to how I have been able to use OBS on Mac until now- keep it and apps in the same space and active.

The problem really is that I need OBS open and visible during streaming to see my chat, adjust scenes, view statistics, etc. If an alternate app needs to be active and visible, that means I basically have to overlay and obscure my OBS window to capture it. Is that correct?

If this is expected behaviour, that's really a shame, it won't be a feasible streaming option for me. On top of using an external capture card like the Elgato, I also need to capture a media player window for Now Playing view, LiveSplit to capture speedrunning times, Chrome to open up a reference tab, etc. If Chrome for instance has to overlap and be the screen focus, I can no longer interact/see chat, notice frame drops, see alerts, etc.

Well, thanks for laying it out. I guess I don't really have a need to follow the beta anymore, I may just have to swallow the cost and get a PC to stream from, as much as I can't stand Windows.

**Comment by PatTheMav** [comment]
> The problem really is that I need OBS open and visible during streaming to see my chat, adjust scenes, view statistics, etc. If an alternate app needs to be active and visible, that means I basically have to overlay and obscure my OBS window to capture it. Is that correct?

That is not correct - choosing a window or application to capture will only yield the visible area of that window/app regardless of where it is in the stack of your open windows. You can capture any window and still manage your stream in OBS without worrying about overlaps, you just need to ensure that both are on the same space to avoid macOS from "hiding" the windows on the non-active space.

You can keep OBS open and check your chat while capturing another window, the only limitation is that if you capture a game that runs in full screen (but uses macOS' native full-screen function) its output will be paused when you're back in OBS to manage your scenes (because the game runs on a different space and switching to the OBS window will "hide" the game window).

We've reached out to Apple for clarification as especially for the game use case this seems counterintuitive, but at least the status-quo follows an internal logic.

**Comment by HiroiSekai** [comment]
Thanks for expanding, that helps explain the intended behaviour a lot. I think I can find some way to string a use case out of it. Additionally, I did find that by using Apple's Sidecar feature, OBS can treat an extended iPad display's desktop as the "same space" as the desktop on my primary Mac's display. I can span out the apps I want to capture over the desktop on my iPad and have OBS open on my Mac.

I see it's really just a matter of remembering the certain extra limitations to work around on the Mac version. I can't keep a different app "full screen" open, I just have to maximize the window and stay active on the desktop itself. All games I capture go through an Elgato capture card which is external, so that's no problem. 

Thanks for reaching out to Apple for clarification as well. I'm safely considering that you've already been asking them about the full screen app limitation? Seems like a restriction Apple wouldn't budge on for sure. I just wonder if someday, they will allow it per app level if explicitly added by a user through security settings.

Thanks again.

**Comment by PatTheMav** [comment]
Keeping this open until we have received further insights into what macOS is doing here and whether this is a bug or indeed intended behaviour.

**Comment by HiroiSekai** [comment]
Could I just pop back in to check about one more thing?

So I'm currently using Application Capture for the apps I put into Windowed mode on the same space as OBS, which works. However, here and there I would like to swipe over to a different space to check something on Chrome or dig up a needed file in Finder, which I keep in full screen mode. When I swipe over to them, all the Application Capture scenes also just swipe over to show nothing.

Since I'm keeping all the apps and OBS windowed regardless, is there a way to request OBS to retain focus on the specified application even as I swipe away from the space OBS/the application is on? I would prefer not to have to clutter every single one of my apps into windowed mode just to use OBS.

There's also another issue with the current capture as is. Let's hypothetically say I did put all of my apps into windowed mode on the desktop with OBS to capture them. Whenever I have to leave OBS for a different app, I use a swipe gesture to fan out my apps to select another one. The animation of the apps panning out is also captured by OBS, making it pretty infeasible to create any custom overlays with precise capture windows that don't fly around or change size/shape.

**Comment by gxalpha** [comment]
> So I'm currently using Application Capture for the apps I put into Windowed mode on the same space as OBS, which works. However, here and there I would like to swipe over to a different space to check something on Chrome or dig up a needed file in Finder, which I keep in full screen mode. When I swipe over to them, all the Application Capture scenes also just swipe over to show nothing.

This is expected. Application capture really captures the display with only the one application shown. 

> Since I'm keeping all the apps and OBS windowed regardless, is there a way to request OBS to retain focus on the specified application even as I swipe away from the space OBS/the application is on?

No.



As noted earlier, most of the behavior is expected.
