### ISSUE TITLE
Audio Mixer skips over -20.0 dB mark when using the volume slider

### ISSUE THREAD

**Issue by yevheniiushtyk** [obsproject/obs-studio#7062]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/wElkSaLYyJlDU6O7

### Expected Behavior

When changing the volume of a Audio Mixer source by dragging the slider the values should change by the decrement of -0.1 dB

### Current Behavior

This works as intended except for when you slide over the -19.9 dB mark, the next value should be -20.0 dB but instead gets skipped over to -20.1 dB.

### Steps to Reproduce

1. Go to one of your Audio Mixer sources (happens on every source)
2. Click on the volume slider and go over to the -19.9 dB mark
3. Try to decrease the volume to -20.0 dB using the slider, but instead it skips over 1 tenth of dB to a value of -20.1 dB
...

### Anything else we should know?

This bug only occurs when dragging by the volume slider, you can still set the volume value to -20.0 dB using the Advanced Audio Properties dialog.

Same bug on macOS, haven't tested any other systems yet.

**Comment by tuduweb** [comment]
When you drag the slider to change volume, it's change the original value of volume(percentage), not dB.
It's covered by original value.

I think this feature maybe not obviously or user-friendly.

**Comment by yevheniiushtyk** [comment]
Hm, seems to be working fine on macOS as of now, I'll see if the problem persists on windows still.

**Comment by tuduweb** [comment]
the dB value is converted by percentage value.
You can find the value is not linear.

**Comment by PatTheMav** [comment]
The issue is independent of the actual value, e.g. I can set it to -20.0db just fine, but it skips to -19.8db for me then.

The slider itself is set to a precision of 4096, but the actual volume set by moving the slider is also dependent on the size of the slider on your screen:

* On a high density display (e.g. Retina screens on a Macbook or a 4k monitor) you will have a higher accuracy for discrete slider values than on a single density screen
* As such moving the slider by a single "notch" can either change the slider value by 30 or just 8 units
* These values are divided by the precision value (4096) and then further calculated into a deflection value

This entire process will introduce further accuracy issues, but here's an example where due to the accuracy of the slider itself (step value 8) you'll never be able to set -20.0db using the mouse:

```
Volume changed to 1979 (0.483154297)
dB changed to -19.9479752
Volume changed to 1972 (0.481445313)
dB changed to -20.0739174
Volume changed to 1964 (0.479492188)
dB changed to -20.2186031
Volume changed to 1956 (0.477539063)
dB changed to -20.3640881
```

We could increase the precision constant to reduce the effect somewhat, but given different display resolutions, different window sizes, and different pixel densities, there is no fix that would be effective, but also _efficient_. We can keep this in mind, but I don't see this as an immediate issue to fix - @RytoEX feel free to weigh in.

**Comment by RytoEX** [comment]
No extra feedback from me. I concur with @PatTheMav 's assessment.

**Comment by yevheniiushtyk** [comment]
I didn't expect this, I gotta thank @PatTheMav for the excellent explanation, I'm glad I got to learn what is happening behind the scenes of this "bug" that I spotted, really it just was my OCD that led me to making this haha, sorry for the trouble!
This was also my first issue on GitHub :)

In this case I have nothing to add and am closing the issue.
