### ISSUE TITLE
NVENC Error: CAnnot perform 10-bit encode on this encoder.

### ISSUE THREAD

**Issue by ElizabethZeta** [obsproject/obs-studio#7066]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/TRzI_ELvP9FR2_Yd

### Expected Behavior

I do the same  thing as usuall,  expoect this one HDR content could be display, and I want this feature for a long time.
though I met some trouble but I fix it,  but  seems the last barrier kept me out side.
It show me "NVENC Error: CAnnot perform 10-bit encode on this encoder."  I turn of all x264 and don't know how to do that.

### Current Behavior

the program cannot run probably.

### Steps to Reproduce

1.open OBS
2.setting obs as everyone dose
3.follow the instruction on the muanul page.
...

**Comment by gxalpha** [comment]
NVENC (and most other encoders) cannot encode 10-bit H264. Use another encoder like NVENC HEVC.

**Comment by ElizabethZeta** [comment]
How can I download and use this encoder, thanks.

**Comment by gxalpha** [comment]
@ElizabethZeta Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

**Comment by life777eternal** [comment]
Greetings, I have the same issue now.

![OBS Studio Failed to start streaming](https://user-images.githubusercontent.com/25623649/230682572-e0ecd8f7-f3c7-46ca-9463-7b2ee00001cb.png)

Would anyone have any idea of what could be causing this error?  Just noticed it today. I have set OBS with setting recommended by NVIDIA [here](https://nvidia.com/en-us/geforce/guides/broadcasting-guide/).

Also I posted the same issue on the OBS Forum [here](https://obsproject.com/forum/threads/nvenc-error-cannot-perform-10-bit-encode-on-this-encoder.165772/).

Have added an animated gif image that's 8 bits per pixel, but when I deleted that, the error still came up, and that's the only change I've made since I last streamed with OBS, other than the NVIDIA recommended settings. 

Thank you.

**Comment by Fenrirthviti** [comment]
Please do not cross-post support issues on our github. The first comment here explains the likely issue, past that please provide a log file on the forum post so someone can take a closer look.

**Comment by QcVibes** [comment]
-- AMD users --
![Advanced Output](https://github.com/obsproject/obs-studio/assets/157758923/c0d4e38b-0078-4b1c-aae5-f565e45b5185)
![Advanced](https://github.com/obsproject/obs-studio/assets/157758923/b7ff25d5-90f3-4837-bc99-74e0a00ae731)


For thoses who get ''cannot perform 10-bit encode on this encoder'' using this tutorial, I found a workaround. I'm using ''AMD HW AV1'' for my video encoder. CPU: 7950x3d and GPU: rx7900xtx, so I don't have that ''NVIDIA NVENC HEVC'' option for my encoder. AMD HW H.264(AVC) and AMD HW H.265(HEVC) didn't worked for me as I was getting this error.

To get a better quality, I'm using a CQP bitrate and a level of 16 CQ.

Note that if you are using Adobe Premiere Pro, AV1 files are not supported. I suggest you try Autokroma Influx 1.4.2 (or above). It's a little bit of a headache to set ip up, but it works as intendend!

DM me if you want some screenshots of my OBS parameters. This post won't let me include pictures in that response.
