### ISSUE TITLE
Build on Debian requires qt6-base-private-dev, not probed by cmake

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-studio#7075]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

Git

### OBS Studio Log URL

n/a

### Expected Behavior

During cmake's probing of the system, all required dependencies should be located, and errors thrown if not found.

### Current Behavior

CMake finished successfully, but the actual build process bombed:

```
[ 78%] Building CXX object UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-output-ui.dir/__/__/qt-wrappers.cpp.o
/home/rosuav/obs-studio/UI/qt-wrappers.cpp:39:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   39 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

### Steps to Reproduce

1. Don't have qt6-base-private-dev installed
2. Do have most of Qt6 dev files installed.
3. Attempt to bulid OBS.

### Anything else we should know?

Hopefully just a simple matter of adding another check to CMake :)

**Comment by tytan652** [comment]
If `Qt::Gui` is found, `Qt::GuiPrivate` is considered found by the CMake finder provided by Qt. `Qt::GuiPrivate` is almost only meant for linking not to show headers availability.

So, having those private headers split from the public one on the package level does not seem supported by Qt. Which lead to those issues.

But you are just missing a dev package that you shall install to build OBS on debian based distro.
Also build instructions in the wiki ask you to install this package.

**Comment by Rosuav** [comment]
Yes, I was missing a dev package; I know that. But every other dependency is probed at the configure stage, instead of waiting until the actual compilation. That's what those checks are for.

**Comment by tytan652** [comment]
And I explained to you that the check for `Qt::Gui` consider that `Qt::GuiPrivate` (private headers) exist even if no headers are present because Qt does not expect such a package split.

**Comment by Rosuav** [comment]
So which is correct - to expect what theoretically SHOULD happen, or to expect what actually DOES happen on a major distribution? :)

**Comment by tytan652** [comment]
1. Qt has chosen to put QPA has unstable API and private headers, which is not a good thing because it is a public API.
2. When building a software all dependencies headers should be installed.
3. Some distro split the headers package between private and public.
4. The OBS wiki indicate that the Qt private header package is required.

Theoretically, private headers should be installed because the build instructions were followed.

Reality, not all advanced users check the wiki and so does not install all the required packages.

**Comment by PatTheMav** [comment]
> Yes, I was missing a dev package; I know that. But every other dependency is probed at the configure stage, instead of waiting until the actual compilation. That's what those checks are for.

No such checks take place in the case of CMake packages, because a package exports its public headers and compile flags when its created (which also speeds up discovery of dependencies). Splitting the "private" components into a separate package by distributions for all intents and purposes breaks the CMake packages as generated by the Qt team.

This should be fixed by package managers in cooperation with Qt, because to me it sounds like the distro packages are created by package managers without considering their impact on the CMake packages:

* If the private components are removed, then the associated code should also be removed in `Qt6GuiTargets.cmake` (and instead added to a new package with `Qt6GuiPrivateTargets.cmake`).
* That way the CMake finder will complain if the the private header package is not installed

As such, this is an upstream issue for Linux distributions to fix IMO.

**Comment by Rosuav** [comment]
Ah, the CMake packages come from the Linux distribution? Sorry, I thought it was all part of the OBS cmake configs. My bad!

**Comment by PatTheMav** [comment]
> Ah, the CMake packages come from the Linux distribution? Sorry, I thought it was all part of the OBS cmake configs. My bad!

Yeah the CMake package files (that end up in `lib/cmake`) that CMake uses to discover dependencies are distributed with the distro packages. We only ship custom finders (that do indeed check for existence of specific header files as you correctly mentioned) for dependencies that do not ship proper package files.

**Comment by Rosuav** [comment]
Right, that makes sense. I was under the impression that (like with many build systems) it was much more under the control of the project.
