### ISSUE TITLE
Browser sources don't look good if Windows High Contrast is enabled

### ISSUE THREAD

**Issue by AxelTerizaki** [obsproject/obs-studio#7137]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/rN2u5vH71h751u7X

### Expected Behavior

Browser sources (and docked windows using browser) shouldn't obey Windows' high contrast setting

### Current Behavior

There are two items affected by this :

- Docked windows (like Twitch Chat or Twitch Stream Info) 
- Browser Sources.

When the Windows' high contrast theme is enabled (Windows 10/11) browser sources are affected by the setting and produce strange results. Example with a Twitch Chat widget as browser source (from Streamlabs) 👍 

![obs64_fqQ1Z47sES](https://user-images.githubusercontent.com/4531597/185625719-07281c89-b650-4a6b-b196-ada2136a00e6.png)

If you disable the high contrast theme, it looks normal : 

![obs64_C9chfo4njl](https://user-images.githubusercontent.com/4531597/185625778-32736e5a-5af2-4580-a353-f157273e73ca.png)

This affects all web sources you might want to use in a stream, and changes text background color to a solid black, as well as overriding its text color.

### Steps to Reproduce

1. Enable high contrast mode in Windows 10 (search High Contrast in control panel) or for Windows 11, enable a High Contrast theme.
2. Launch OBS, create a new browser source with any kind of online widget or webpage
3. Disable high contrast mode to see changes.

### Anything else we should know?

The main problem is that Windows' high contrast theme affects the browser OBS is using.

I tried to modify the CSS of my web sources by adding `forced-color-adjust: none;` to the `body` element, but it didn't cancel the high contrast mode for that web source.

I have had similar issues in other software using Electron (like Tweeten or Tabby) and to fix this, I had to modify their CSS to work around this and add that property like this :

```
@media screen and (forced-colors: active) {
  body {
	forced-color-adjust: none;	
  }
}
```

This workaround does work in the Twitch Chat widget by Streamlabs but doesn't seem to do anything for the Alert Box one for some reason I can't quite explain. So it's not a 100% working workaround and hence why I decide to open this issue.

Note : high-contrast mode isn't applied when creating a browser source with a local file, for some reason. It only does with web sources.

Thanks in advance for your help in this. As a nearly blind user trying to setup a stream, this is quite annoying as my web sources aren't looking like they should be simply because I'm using the Windows' high contrast mode (I'm easily blinded by light and not all apps have a dark theme like OBS does)

**Comment by RytoEX** [comment]
Warning: there are screenshots in this reply with High Contrast White, which are bright. I have placed them in spoiler sections to try to avoid them showing on screens by default when viewed on GitHub. Email notices will still likely render the screenshots without hiding them.

I believe that this is intended and by design of the High Contrast feature. Applications and websites _should_ respect that setting. OBS browser sources and browser docks are, essentially, Chromium browser tabs. If you have concerns about how certain websites change their appearance with High Contrast enabled, you should report it to the maintainers of those websites.

That said, if you want to forcibly disable this option for all browser sources and docks, you can set `--disable-features=ForcedColors` on your OBS shortcut to disable CEF from respecting High Contrast from the Operating System.

Warning: brightness. The following two screenshots have a default gray OBS color source (#D1D1D1) behind a browser source.

Here are some tests with a Streamlabs browser source Twitch chat dock.
<details>
<summary>Windows 10 High Contrast Black</summary>

![image](https://user-images.githubusercontent.com/624931/185705140-4c9b8a78-fe22-40e9-8e2f-f775c6f88f04.png)
</details>

<details>
<summary>Windows 10 High Contrast Black with --disable-features=ForcedColors</summary>

![image](https://user-images.githubusercontent.com/624931/185705252-0e9ea73e-db82-42af-82f6-2b2054e1def5.png)
</details>

----

Here are some tests with the official Twitch docks in OBS Studio 27.2.4 with Dark as the OBS theme.
<details>
<summary>Windows 10 dark theme (Settings -> Personalization -> Colors -> Choose your color -> Dark):</summary>

![image](https://user-images.githubusercontent.com/624931/185684692-942f3312-1900-43f4-ad0d-9ae23eb745a6.png)
</details>

<details>
<summary>Windows 10 High Contrast Black:</summary>

![image](https://user-images.githubusercontent.com/624931/185684864-960aeaa9-2889-45b5-9c40-dffe695091b1.png)
</details>

<details>
<summary>Windows 10 High Contrast White (warning: brightness):</summary>

![image](https://user-images.githubusercontent.com/624931/185684977-214e399f-3896-4a58-8c29-eaaa67730108.png)

</details>

----

Here are some tests with https://www.google.com/ in Google Chrome. The site contents change appearance when switching from a Windows 10 dark theme to High Contrast White, making the site almost unreadable.

<details>
<summary>Windows 10 dark theme:</summary>

![image](https://user-images.githubusercontent.com/624931/185683484-216f5004-29f5-4206-a053-f6589e15e5b4.png)
</details>

<details>
<summary>Windows 10 High Contrast Black:</summary>

![image](https://user-images.githubusercontent.com/624931/185683648-add0a229-007a-4b48-a632-d65f1c292ac3.png)
</details>

<details>
<summary>Windows 10 High Contrast White (warning: brightness):</summary>

![image](https://user-images.githubusercontent.com/624931/185683537-4fe88cbd-9c93-458e-820a-3b67ed29c7e9.png)

</details>

**Comment by AxelTerizaki** [comment]
Thank you for your reply (and the spoilered screenshots, but really you didn't have to :) )

I understand what you're saying but I still find it to be a bug if a user in my case (or simply because they prefer the high contrast theme) has to forcibly enable a command-line switch in their shortcut to OBS. I don't believe this is documented anywhere in this issue either.

Would it be possible to add this as a checkbox option somewhere in OBS options window at least ?

Thanks in advance for considering this (and for the quick reply too.)

**Comment by RytoEX** [comment]
> Thank you for your reply (and the spoilered screenshots, but really you didn't have to :) )
> 
> I understand what you're saying but I still find it to be a bug if a user in my case (or simply because they prefer the high contrast theme) has to forcibly enable a command-line switch in their shortcut to OBS. I don't believe this is documented anywhere in this issue either.
> 
> Would it be possible to add this as a checkbox option somewhere in OBS options window at least ?
> 
> Thanks in advance for considering this (and for the quick reply too.)
> 
> EDIT : Forgot to mention that's what Discord does to remedy this problem in their Accessibility menu in the user settings : theye ven detect that you're using the high contrast theme on launch and offer to disable it if you feel like it. I think this is neat and while OBS doesn't need to go that far, an option in the settings would be nice to have, UX-wise, I believe.

It's something that we could look into for a future update, though it would require quite a bit more work beyond just adding the user-facing option in the UI. However, I see this not as a bug, but as a feature request. The browser sources are respecting the OS setting, so they are working as intended.

**Comment by AxelTerizaki** [comment]
Should I open another issue and mark it as a feature request then, and reference this one?

**Comment by RytoEX** [comment]
No. We do not track feature requests on GitHub. Feature requests can be submitted to [our Ideas and Suggestions website](https://ideas.obsproject.com/).

**Comment by AxelTerizaki** [comment]
Alright, I will look into it tomorrow then, thank you for your help.
