### ISSUE TITLE
Typing anything on a keyboard within browser panel in focus causes OBS to close

### ISSUE THREAD

**Issue by ToRRent1812** [obsproject/obs-studio#7146]
### Operating System Info

Other

### Other OS

Nobara KDE (Based of Fedora 36)

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/N0b9VdqKxY7r2whY

### Expected Behavior

Being able to pass keystrokes to browser panel without obs closure.

### Current Behavior

Typing anything within browser panel (ex. logging in to Twitch dashboard) causes OBS to close without crash log.

### Steps to Reproduce

1. Launch latest OBS
2. Create custom browser panel
3. Try to type anything on a keyboard while panel is in focus

**Comment by WizardCM** [comment]
Alright, I've done some extensive testing today.

First, thanks for reporting this - I am unsure how I didn't catch this earlier.

The crash call stack we've managed to acquire can be summarised like so

```
#1-2 ../gtk/gtk/gtktextlayout.c
#3 ../gtk/gtk/gtktextbtree.c:5461
#4 ../gtk/gtk/gtktextbuffer.c:841
#5-7 ../gtk/gtk/gtktextview.c:4435
#8 ../gtk/gdk/gdk.c:769
#9-12 ../glib/glib/gmain.c
#13 /usr/src/debug/qtbase-everywhere-src-6.3.1/src/corelib/kernel/qeventdispatcher_glib.cpp:429
#14-15 /usr/src/debug/qtbase-everywhere-src-6.3.1/src/corelib/global/qflags.h
#16 /home/tytan652/Programming/OBS/obs-studio/UI/obs-app.cpp:2346
```

Long story short: GTK in CEF & Qt are fighting each other. Again. Reproduced by multiple users on both Qt5 and Qt6, so it's safe to say it's caused by the CEF update.

Launching with `QT_NO_GLIB=1` fixes the issue. This was previously added in #1759 and reverted in #4155 by @GeorgesStavracas.

I am unsure where to go from here. Will coordinate with others on the team.

**Comment by ToRRent1812** [comment]
I can confirm this argument fixes the issue however, browser panels are disappearing when obs is not in focus.

**Comment by WizardCM** [comment]
Interesting. Thanks for the follow-up. We're going to try an alternate solution in the next RC (requires rebuilding CEF), I'll post again once it's ready for testing to see if it solves the issue for you.

**Comment by WizardCM** [comment]
A fix has been pushed and should be available in the next Release Candidate. We ended up disabling GTK entirely in CEF so it should no longer conflict.

This does come with the downside of certain CEF-GTK features being disabled/missing, but I'd rather reimplement such features (such as `alert()` dialogs and file browsers) using Qt instead.
