### ISSUE TITLE
Can't use Preview Scaling (Canvas) actions when a Media source is selected on the Preview

### ISSUE THREAD

**Issue by admshao** [obsproject/obs-studio#7199]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

-

### OBS Studio Crash Log URL

-

### Expected Behavior

When a source is selected in the preview, if Preview Scaling is set to canvas, "Space" hotkey should be catch first for the control of the pan and zoom of the preview canvas and not by the Source Toolbar.

### Current Behavior

if a media source is selected, instead of triggering the scaling actions, holding "space" will make the Source Toolbar toggle the media playing state between pause and play.

### Steps to Reproduce

1. Start a Fresh OBS scene
2. Add any Media Source
3. Right Click preview and change Preview Scaling to "Canvas"
4. Click in the preview to select the media source
5. Try to use Space to adjust the canvas and observe media source pause and play in loop
...

### Anything else we should know?

I know if you click outside the preview to deselect any source this is not observed and a workaround for now but when zoomed in to check pixel alignments might be impossible to click outside instead of zooming out all the way.

**Comment by PatTheMav** [comment]
@GeorgesStavracas sounds to me this is an UX issue because we try to serve conflicting user expectations here: 

* Space key used as modifier to drag/change the preview like in Photoshop, vs. 
* Space key used as activator of currently selected button

Also the "currently selected button" is not visually made apparent in our current UI so it actually shouldn't trigger anything.

**Comment by WizardCM** [comment]
Not introduced in 28 (confirmed in 27.2.4), removing from the release bug tracker.
