### ISSUE TITLE
"Check File Integrity" and "Check for Updates" menu items do nothing

### ISSUE THREAD

**Issue by Leo40Git** [obsproject/obs-studio#7258]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/fzPj-zYb4RejNhyf

### Expected Behavior

When clicking the "Check File Integrity" or "Check for Versions" menu items, I expected something to happen.

### Current Behavior

Nothing happens when clicking on these menu items.

### Steps to Reproduce

1. Start OBS Studio
2. In the "Help" menu, click on "Check File Integrity" or "Check for Updates"
3. Behold, as absolutely nothing happens

### Anything else we should know?

Log is from me starting OBS, clicking on "Check File Integrity", then clicking on "Check for Updates".

**Comment by Mister36MN** [comment]
I can confirm that doing "Check File Integrity" seemingly did nothing.

**Comment by notr1ch** [comment]
This is due to the rollout of v28 via the auto updater. As not all users will receive the update at the same time, the updated files manifest to allow for auto updating (and file integrity checks) is not available. This will only occur during the 28 release - after the rollout is complete, OBS 28 will allow these functions to fetch the new version manifest even if they aren't part of the current update rollout group.
