### ISSUE TITLE
OBS crashes on start

### ISSUE THREAD

**Issue by CaptJRoger** [obsproject/obs-studio#7300]
### Operating System Info

Ubuntu 22.04

### Other OS

Pop!_OS 22.04 LTS

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://pastebin.com/71GeN2Nt

### Expected Behavior

The expected behavior would of course be for OBS to open, at all. 

### Current Behavior

OBS doesn't open. I can open obs as a different user in my terminal, but when it does open there is no audio inputs or outputs.

### Steps to Reproduce

1. Build according to instructions at https://obsproject.com/wiki/build-instructions-for-linux
2. Open from software menu, wait a few minutes, nothing
3. Open in Terminal, still doesn't work, but I get the log
4.  $ doas -u user2 obs, it opens, but no audio input or output
...

**Comment by norihiro** [comment]
> info: [tuna] Loading v1.7.0 build time 2022.06.10 11:08
> QWidget: Must construct a QApplication before a QWidget
> Aborted (core dumped)

This is because the 3rd party plugin is compiled against Qt5. Please remove or update the plugin. Maybe `tuna.so` is the plugin causing the error.

When using `sudo`, the user's configuration is read from different location. Maybe this is the reason the error does not happen. However, it is not recommended to use `sudo` to start obs.

Support question should be asked on [Forum](https://obsproject.com/forum/list/linux-support.34/) or [Discord](https://discord.com/invite/obsproject).

**Comment by kkartaltepe** [comment]
Never run OBS as root, it is not intended to be run as root. Running obs as root is unsupported.

As mentioned you ran obs as a user that didnt have your incompatible plugins installed. These incompatible plugins crashed. If you use a plugin on this list https://obsproject.com/kb/obs-studio-28-plugin-compatibility you must update it or remove it for obs to start on v28.
