### ISSUE TITLE
Unpausing a recording results in termination of the recording

### ISSUE THREAD

**Issue by cooperised** [obsproject/obs-studio#7313]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/BtkLzneQvpMxmZmk

### Expected Behavior

Pausing a recording, for any length of time, and subsequently unpausing, should resume the recording.

### Current Behavior

Pausing for any longer than 5 seconds results in the attached error dialog, and termination of the recording.  This is a regression, and did not happen prior to upgrade to 28.0.1.
![Screenshot from 2022-09-06 15-18-37](https://user-images.githubusercontent.com/7403302/188660128-821636b6-22df-4d1d-84cd-7adf55dc1a93.png)

### Steps to Reproduce

1. Open OBS and start recording
2. Pause the recording
3. Wait at least 5 seconds, then unpause

### Anything else we should know?

This does not seem to be Linux-specific - see the forum report [here](https://obsproject.com/forum/threads/so-when-are-all-the-28-vers-issues-fix.159261/) from a Windows user.  Not sure if it is confined to h.264.

**Comment by cooperised** [comment]
Update: pausing and unpausing multiple times also triggers the bug, as soon as the total pause duration exceeds 5s.  So two 3s pauses will do it.

**Comment by MattyFresh68** [comment]
It seems that this doesnt require lossless or i444 like I originally thought. In 28, setting color range to full while using h264 + ffmpeg scaling(doesnt occur on obs h264), a +5 second pause will trigger https://obsproject.com/logs/BAzphhhki_l8u9Wf

This seems to be a regression because on 27, using the same settings(full color range + ffmepg h264), a +5 second pause has no issue  https://obsproject.com/logs/NHFPHxs_x7wiKvcL

**Comment by xVince19** [comment]
In response to my findings that MattyFresh68 provided, I have yet to test whether this is the case on stream. If the stream stops due to the above error in the first post, color range would be irrelevant. If it doesn't persist, we know what caused this bug.

**Comment by xVince19** [comment]
> In response to my findings that MattyFresh68 provided, I have yet to test whether this is the case on stream. If the stream stops due to the above error in the first post, color range would be irrelevant. If it doesn't persist, we know what caused this bug.

The issue is either caused by FFmpeg or Full Color Range, although I believe it to be the color range as I am still using Rescaling under the Output tab in settings, which falls back to ffmpeg as far as I am aware.

**Comment by TheChrisD** [comment]
It's definitely a problem caused by using FFmpeg. I've had streams get cut off because of GPU stalls since upgrading to OBS 28, and I tested the same settings on a local recording just now and can replicate the issue with the pause recording function. Never been an issue in previous OBS versions.

I'm on Windows, 1440p canvas rescaled down to 720p stream. NV12 colour format, with limited colour range.

Full log from the test: https://obsproject.com/logs/K4z5HRTn7sJlCzjx

**Comment by PatTheMav** [comment]
FWIW this issue does not occur on macOS with either x264 or VideoToolbox encoding - I tried output with rescaling, limited/full colour ranges, both encoders, no issues in any case.

Does this occur on Windows/Linux with x264 or non-NVidia encoders as well?

**Comment by Fenrirthviti** [comment]
Just to confirm, what exactly was the last version this was not an issue? 27.2.4? Or was this introduced in 28.0 to 28.0.1? Knowing last known good version will help with a bisect to understand what might have changed.

**Comment by tertius1** [comment]
I can reproduce the error by:
- advanced output mode
- nvenc h.264
- force fallback to ffmpeg by setting "rescale output" to 1280x720 while having output resolution still at 1920x1080

Happens for me for all 28 versions. I tested them all starting with 28.0.0 beta 1, up to 28.0.1.
Doesn't happen with 27.2.4.

**Comment by MattyFresh68** [comment]
ALL HAIL!
