### ISSUE TITLE
OBS Studio crash when deleting video filter

### ISSUE THREAD

**Issue by snicolai** [obsproject/obs-studio#7325]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/5wenb2HhQXV5RWsS

### Expected Behavior

OBS Studio should not crash.
[OBS Remove Filter Crash.txt](https://github.com/obsproject/obs-studio/files/9531458/OBS.Remove.Filter.Crash.txt)

### Current Behavior

See crash log.

### Steps to Reproduce

1.  I'm using the mac arm NDI plugin from https://github.com/Palakis/obs-ndi/actions/runs/2977380826
2. Add a color correction filter to the NDI source
3.  Mess with the sliders a bit4. 
4.  Click the delete button, watch OBS crash

**Comment by gxalpha** [comment]
Does this only happen with NDI sources? If so, please report this to the plugin instead.

**Comment by snicolai** [comment]
The same crash also happens with a El Gato CamLink source, so NDI isn't needed.

It also happens with a sharpen filter.  You have to change the settings without saving the filter for the crash to happen.  If you've closed the filter dialog (saved the filter) then the crash doesn't happen.

**Comment by WizardCM** [comment]
I cannot reproduce this on Windows 28.0.1 with the Color Correction filter on a browser source and a video capture device source.

**Comment by PatTheMav** [comment]
Confirmed the crash, this is yet another bug probably introduced by Qt6 and the automatic focus switch trying to set input focus on a destroyed widget (see also https://github.com/obsproject/obs-studio/issues/7259).

Exact reproduction steps:
* Add video input source
* Add colour correction filter
* Change a value of the colour correction filter
* Do not close the property window or accept the change
* Instead, delete the colour correction filter
* Observe crash

The root cause seems to be the following order of events:

* Deleting the filter triggers `QListWidget::currentRowChanged` (the selected row was the colour correction filter which has now been deleted)
* This triggers `OBSBasicFilters::on_effectFilters_currentRowChanged`, which calls `UpdatePropertiesView`
* This triggers `ui->propertiesFrame->setVisible(false);`
* Now this `setVisible` call triggers `QWidget::focusNextPrevChild`, which attempts to find a new widget to give the keyboard focus to
* This recursive search yields `FocusList::FocusList` as the Widget to set the focus to (triggering `FocusList::focusInEvent`)
* This triggers `on_asyncFilters_GotFocus`, which calls `UpdatePropertiesView` yet again
* Here we set `view` to `nullptr`
* Once we return to the first call of `UpdatePropertiesView` (after we made the propertiesFrame invisible) calling `hide` on `view` will crash as we set it to a `nullptr` just before.

This is a bit annoying as we check if `view` is a valid pointer before, but apparently making the `propertiesFrame` invisible did not lead to another loop into the same function before.

**Comment by snicolai** [comment]
If you skip the "Change a value of the color correction filter" step and then delete it right away, it doesn't crash for me.

If you change the "Do not close the property ...." step to closing and re-opening the filter property window, then it doesn't crash for me either.  So this is a workaround until the problem is fixed.  Though if you are doing a live stream and crash OBS with this bug setting up a new scene, it will be noticeable.

I haven't looked at the code, but it seems the problem only happens when the the "dirty" flag is set, and it's not been saved (maybe there isn't something filled out in the record like an ID until it's saved?)

**Comment by PatTheMav** [comment]
Part of the issue is that we added a workaround to a perceived issue in Qt for lists (mainly that you can "unselect" in a list that should always have an item selected).

We enforce selection of the last remaining item in a list, which triggers this undefined/unexpected Qt behaviour.

**Comment by PatTheMav** [comment]
There are indeed a few conditions that need to be met:

* You need to have a property window with 2 lists (async filters, filters)
* The async filter list needs to be empty
* You need to have interacted with an input in the property view
* You need to click on the delete button to remove the filter without clicking anywhere else

The crash is triggered by Qt moving the focus away from the control you clicked on to another possible candidate - when the window has an (empty) async filter list, it will set focus to this list.

As the list is empty, it yields no filter source to show properties for, so we automatically hide the property view. This sets the pointer to `nullptr` and once we bubble all the way back up to our original focus change, we try to do the same (only this time on the normal filter list: No filter available, no source, hide the properties), but the properties are "gone" already. 

Hence, crash.
