### ISSUE TITLE
[OBS 28.0.1/Linux] Obspython not allowing access to classes.

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#7331]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/JAlp-8VBGI1eaYPO

### Expected Behavior

Calling a class defined in obspython.py within an obs script with `obs.NameOfClass()` should call the class. 

### Current Behavior

Instead, the scripts returns an error `AttributeError: module 'obspython' has no attribute 'NameOfClass'`

### Steps to Reproduce

1. Download this [demonstration script](https://cdn.discordapp.com/attachments/767069216011452450/1017810140092710972/vec_tester.py)
2. Add it as script in OBS
3. Notice error message `AttributeError: module 'obspython' has no attribute 'vec2'` even though vec2 is defined as a class in obspython.py

### Anything else we should know?

Not reproducible on windows.
Reproduced both on flatpak and ppa.

**Comment by PatTheMav** [comment]
`class vec2(object):` is defined in `obspython.py`, so on macOS this works fine as well.

My main hunch is that for legacy reasons, the target prefix for `obspython` is set to an empty string on Linux, which results in the generated binary module `obspython.so`, which will be loaded by Python before `obspython.py` (because the python wrapper actually loads the binary library as `_obspython.so` on the other platforms).

I haven't questioned this because the old CMake build scripts did this as well, but it could be that Linux just needs to use the same prefixes as the other platforms.

**Comment by Penwy** [comment]
To add to this, on v27, where the issue doesn't occur, obspython used `_obspython.so` too.
