### ISSUE TITLE
Push to talk is interrupted by pressing modifier keys

### ISSUE THREAD

**Issue by apple1417** [obsproject/obs-studio#7474]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/O7q5JqbwCibyDEZD

### Expected Behavior

After starting to hold my push to talk key, my mic should stay enabled until the moment I release it, with no interruptions.

### Current Behavior

After starting to hold my push to talk key, my mic correctly turns on. While still holding PTT, my mic turns off if I press ctrl, alt, or win, until I release those keys.

I find this is particularly a problem when trying to speak while recording gameplay including a lot of crouching/sliding (bound to ctrl).

### Steps to Reproduce

1. Set a push to talk key.
2. Press and hold PTT. The mic input turns on.
3. While still holding PTT, press and hold ctrl. The mic input turns off.
4. Release ctrl. The mic input turns on again.

### Anything else we should know?

This appears to have been introduced #5095. While that fix definitely makes sense for "instant" hotkeys, it causes these extra issues for "while held" ones, like push to talk.

As a workaround, you can set 8 push to talk hotkeys, for each combination of ctrl+alt+win+[key].

**Comment by Fenrirthviti** [comment]
The workaround of setting multiple hotkeys for the edge cases where it might have been desired functionality is the current correct solution, as it was discussed on #5095. Unfortunately, this isn't something we are likely to revert or add additional complexity to hotkeys for at this time.

**Comment by apple1417** [comment]
I can understand not wanting to add a bunch of extra complexity right now, but this just feels like horribly unintuitive default behavior - I've definitely never encountered another app which interrupts PTT like this. It's also not the easiest thing to work out, I was lucky to be running an input overlay and it still took me reading through the v28 patch notes to find the root cause. At the very least hopefully this thread will start appearing on google.

**Comment by Fenrirthviti** [comment]
I can understand where you're coming from, but keep in mind OBS is not intended to be used like a standard voice chat application, so those considerations aren't usually at the top of the design decisions, and would have ramifications for how other hotkeys would be processed. PTT, IMO, is really there for no-win situations where no other solution is viable. But as mentioned, we do understand and recognize this isn't ideal. Luckily, it should only be a single time setup.

Keeping in mind I'm just wildly speculating here as to your use case of PTT, I'd recommend looking in to things like a voice gate, compressor, or any of the noise suppression filters if background noise on the open mic is the concern.

**Comment by john-oldman** [comment]
I'd like to offer three considerations:

### Discoverability

Because it was introduced somewhat silently and because the subject of my recordings had me press modifiers sporadically without much correlation to what I was saying, I had no clue why the audio seemed to cut randomly even though other applications (e.g. voice chat) were picking it up. I had to perform many tests and inspect many (long) recordings in-depth before I figured out that I should even look at PTT, and then do further research to understand it was related to modifier keys. I don't particularly wish this on anyone else.

So, while it's very understandable why some specific refactoring for this scenario would be difficult to consider right now, especially since it looks like the current solution is quite consistent otherwise, I'd suggest adding some tooltips, log entries or use other UX tricks to increase the odds that PTT users don't get mistakenly put in the asylum before they figure out their issue ;) (or worse; stop using OBS!).

### Consistency

Many people using voice chat with PTT, for example Discord while gaming, rightly or wrongly expect that the rules for activation would be similar across their applications.

While I've only tested Discord for now and (hopefully correctly) remember other applications which also don't discriminate based on key modifiers, it's possible that a majority of other applications (or the majority of popular applications) would also differ from the new behavior of OBS in that same way.

If true, it would be likely many more people will be surprised and perplexed by this in the future, particularly if they use these applications concurrently (and probably many already are and simply haven't found this issue report yet).

### Privacy

PTM (Push-to-mute) is similarly impacted by the change. Although it's easy to tell users to be careful about this when they use this feature to say something private to someone off-broadcast in the context of a live stream, it's similarly easy to imagine that because of the nature of the issue the first time someone would discover that they have to be careful about it would be _after_ they do the "mistake" of leaking private information in the first place.

Furthermore, it still might not be immediately obvious why their PTM key sometimes works and sometimes "doesn't", leading to a sense of uncertainty and distrust in the application until they (hopefully) figure it out.

### About discouraging PTT/PTM

I understand PTT/PTM are not the most popular of features. Personally I think they have value: for example I vastly prefer PTT to editing after-the-fact for long recordings mostly intended for archival and for which I know in advance that I can decide what to capture and what not to capture as I'm recording.
