### ISSUE TITLE
macOS ScreenCapture (BETA) - doesn't respond if menu bar is hidden

### ISSUE THREAD

**Issue by dheg** [obsproject/obs-studio#7550]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/XZm_1HOvN7qkVsj6

### Expected Behavior

From the moment macOS ScreenCapture is added the entire screen should be visible in real time on the canvas. 

### Current Behavior

macOS ScreenCapture was added and only showed a black screen. 
When moving mu cursor up to reveal my hidden menu bar, the black screen became live and showed the entire display and cursor moving. 
When the menu bar is hidden again, the last image of the display is frozen in place. 
If I change the setting in System Preferences to always show menu bar, the ScreenCapture works at all times. Issue seems to be related to the hiding of the menu bar. 

### Steps to Reproduce

1. Enable hide menu bar in system preferences
2. Launch OBS and add macOS ScreenCapture (BETA)
3. The added source will be black with a red boarder when selected (optional, transform to resize the source to fit in canvas)
4. Move cursor up to reveal the menu bar
5. Source will be come active
6. Move the cursor away and the menu bar will automatically hide
7. Source becomes frozen on last image before the menu bar was hidden

### Anything else we should know?

You're doing amazing.

**Comment by gxalpha** [comment]
This is a known issue with a workaround we have to do on macOS 12.5 due to a macOS bug that would otherwise cause the capture to not start at all. This bug will not get fixed in any minor version of macOS 12, so this annoyance will stay.
On macOS 13, you'll see the issue magically disappear. For now, use Display Capture.

The only real solution to this issue (and similar ones) is for us to remove the `macOS Screen Capture` source from macOS 12.x entirely, which at this point we may just end up doing.

**Comment by PatTheMav** [comment]
I'd instead suggests hiding (thus disabling) Application Capture and Desktop Capture on macOS 12 (and only use SCK for Window Capture). We should retain the old Desktop Capture under a new name anyway, because it is _much_ more efficient than SCK (given that we just tap into the IOSurface for the entire screen).

**Comment by attaboyBrad** [comment]
> We should retain the old Desktop Capture under a new name anyway, because it is _much_ more efficient than SCK (given that we just tap into the IOSurface for the entire screen).

Any chance you could elaborate on this a bit? Give your general recommendations of best practices for capturing windows vs. apps vs. whole displays? Does this still apply with MacOS 13? 

What sort of performance/reliability disparity should I expect between SCK and Desktop Capture sources on MacOS 13 using Apple Silicon, and is that disparity likely to remain or be ameliorated over the coming year or so?

For my tutoring I usually use half a dozen captured desktop sources across several scenes--pdf app, whiteboard/sketching app, calculator app, browser, etc.--with a bunch of filters on some of them to produce an effect of "transparency" where it looks like I'm annotating on a transparent surface between my students and me.

For my use case SCK seems to be working fine for the most part outside of [this bug](https://github.com/obsproject/obs-studio/issues/7651) and my sources "forgetting" that they're supposed to be on my secondary display.

**Comment by PatTheMav** [comment]
Display Capture is a very "dumb" capture method - it takes the display stream from a single display without any additional processing and as such has very low overhead, but you're limited to only getting the full contents of what's visible on a display.

SCK is capable of much more, capturing the contents of the entire screen is just one aspect of it. We don't even expose the full capabilities of SCK because the UI required for that would be a bit of a support nightmare, but in theory you can tell SCK to "capture entire screen except App a, b, and c." or "capture desktop, and additionally apps x, y, and z.".

This obviously requires macOS to create a new composite of the desktop with the desired configuration on the fly, so a bit more processing is involved.

Recent Macs (especially Apple Silicon variants) have enough horse power for this, but my 7-year old iMac definitely shows higher resource usage when capturing desktop via SCK compared to the "legacy" desktop capture.

It should also be noted that on macOS 12 we had to use a workaround to make desktop capture work due to a bug that was fixed in macOS 13 and that workaround cost a bit of performance. In general we suggest using SCK exclusively on macOS 13 (also because of the audio capture you get for free).
