### ISSUE TITLE
Scene item border flickers

### ISSUE THREAD

**Issue by AlexRain** [obsproject/obs-studio#7569]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/M6eriAUkffZATzAY

### Expected Behavior

Scene item border should not flicker 

### Current Behavior

Scene item border flickers like this
![1665287040](https://user-images.githubusercontent.com/13672219/194736907-0d14b503-ba20-4d53-bb6a-cb33a93560d5.gif)

### Steps to Reproduce

1.Add a Game Capture source
2.Select 'Capture specific window' , select a valid window and capture normally
3.Select another invalid window and preview display black

**Comment by PatTheMav** [comment]
The flickering of the selection box is due to our injection system attempting to hook the selected application at a set interval:

* As no hook exists, `init_hook` is called, setting `gc->active = true`
* Before the preview is rendered, `update_item_transform` is executed to update the transformation matrix on the game capture source
* This function calls `obs_source_get_width` and `obs_source_get_height` which in turn end up in `game_capture_width` and `game_capture_height` respectively
* Either function returns the width and height of the last valid source or `0` if the source is not active
* Because `gc->active` was set to true, the "old" width and height are reported, and a valid transformation is set
* `OBSBasicPreview::DrawSelectedItem` (responsible for drawing that red border) considers an item visible if it has a valid transformation
* Because the source reported valid widths and heights, that check is true and a border is drawn
* Once our `inject-helper` signals that it was unsuccessful in hooking the target window, `stop_capture` is executed, setting `gc->active` to `false`
* `update_item_transform` then receives a width and height of `0`
* `OBSBasicPreview::DrawSelectedItem` thus deems the source not visible and no box is drawn
* After a few seconds the game capture source will attempt to hook the process again, the entire process begins anew

A possible fix might be to guard the calls to `game_capture_width` and `game_capture_height` to check not only for an active, but also capturing, source via `(gc->active && gc->capturing)`.
