### ISSUE TITLE
OBS stores Youtube API client_secret in client

### ISSUE THREAD

**Issue by CommanderRoot** [obsproject/obs-studio#7572]
### Operating System Info

Other

### OBS Studio Version

28.0.3

### OBS Studio Log URL

not relevant

### Expected Behavior

The Youtube account connection should be handled by a server (at least partly) and not fully locally. This way the client wouldn't need the client_secret from the OBS Youtube API client.

### Current Behavior

As per [Googles OAuth 2.0 Policies](https://developers.google.com/identity/protocols/oauth2/policies#secure-credentials) the `client_secret` shouldn't be stored publicly. Shipping it with every OBS installation is therefore probably not the right move.

### Steps to Reproduce

1. Try to link your Youtube account with OBS while having a mitm proxy setup
2. See request with `client_secret`
[Maintainer Edit: Screenshot removed]

**Comment by derrod** [comment]
The policies only state
> You must never commit client credentials into publicly available code repositories. We highly recommend that you avoid committing them to any code repository.
Which we aren't doing. Storing the secrets in the binary is somewhat unavoidable for this flow, and I do not believe that the OAuth 2.0 specification includes a flow that could avoid storing the secret in the client (at least not for long-lived refresh tokens). Our Twitch/Restream implementation is very much non-standard.

If you look at their reference for native apps they do make note of certain limitations due to the fact that native apps are assumed to be unable to keep secrets: https://developers.google.com/identity/protocols/oauth2/native-app

At the end of the day this is not a huge issue, aside from the fact that YouTube has that stupid quota system and doesn't allow us to restrict the use of certain methods.

**Comment by Marenthyu** [comment]
I would like to support @CommanderRoot 's Viewpoint in this case and add a few further comments on the issue.

I am no expert in security, but have dealt with OAuth on Twitch's side multiple times and explained usecases there as well, so I think I have sufficient credentials to explain my thought process.

* The secret being embedded in the Binary (yes, in obfuscated form, but it's still there and obtainable as Root has shown) allows anyone to freely abuse it and ruin whatever quota may be acquired by youtube/google, effectively impersonating "OBS" as the service in this case. This would make a limit/quota increase ineffective, and we are already seeing the quota being an issue recently, even assuming this has not yet been abused.
* "any code repository" - By uploading builds of OBS with the secret embedded to GitHub, OBS is, in my understanding, uploading the secret to a public repository. Yes, not in code form, but in binary form. (I am not a lawyer, but even then, it doesn't change the _reasoning_ for the wording, which is that it shouldn't be shared publicly - which the secret currently is, effectively.)
* `Our Twitch/Restream implementation is very much non-standard.` it is, indeed, nonstandard. For Restream, I see that they only offer the Authorization Code Flow, thus this "workaround" is required to avoid putting the Secret into the binary. On the other side with Twitch, I can see that it is "nonstandard" due to the "wrong" flow having been selected. Refer to the below Flow Chart that sums up the Twitch case quite nicely. In the end, for Twitch _and YouTube_, an Implicit Flow (`grant_type=token`) is available. YouTube/Google lists this as [OAuth 2.0 for Client-side Web Applications](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow) to more immediately show what it is meant for, but in effect, this allows Applications to _not_ store a secret, but still generate a Token for _local_ usage, which is _exactly_ what OBS requires. In addition, I would highly recommend this approach for Twitch as well, considering they have recently added security to their Login Flow, meaning "nonstandard" or "unsupported" Browsers can cause issues. (Like CEF) Instead, opening the OS-default Web Browser and then sharing the token as passed in the `document.location.hash` object to OBS, for example via obs-websocket or similar. This would avoid both the secrets issue as well as Twitch's Integrity requirements. ![Flowchart of Suggested Twitch OAuth Flows to utilize](https://shared.meme.stream/i.3v.fi/choosing-oidc-oauth-flow-dark.svg?s)
* Yes, OBS is an "installed Application", but this does not fit in YouTube/Google's definition, as it expects an Android, iOS or UWP App to allow for additional verification during the authentication procedure, making it non-viable.

I would be more than happy to assist with the implementation of the Twitch-specific authorization procedure, assuming there are no additional Discussions already ongoing that I may have missed.

As for YouTube, I _hgihestly_ recommend taking the security of the secret more serious, as I doubt that it would pass Google's Application review when requesting a higher quota - at minimum, I would suggest using the infrastructure that is already in place for Twitch and Restream to remove the secret from OBS' build process and avoid sharing it in obfuscated binary form.

**Comment by iXyles** [comment]
I'd still argue that it is against standards to include a client_secret in an application the user installs on their device. As it opens the possibility of using the client_id & client_secret to identify themself as the OBS application (opens up an attack vector of bad actors)

From the link provided in OP: [policies#secure-credentials](https://developers.google.com/identity/protocols/oauth2/policies#secure-credentials)
`Treat your OAuth client credentials with extreme care, as they allow anyone who has them to use your app's identity to gain access to user information. Store your OAuth client information in a secure place and protect it, especially your client secret, just as you would a password.`

Along with the second link you posted: [oauth2#installed](https://developers.google.com/identity/protocols/oauth2#installed)
`The process results in a client ID and, in some cases, a client secret, which you embed in the source code of your application. (In this context, the client secret is obviously not treated as a secret.)`

I do understand in this case that it is not a committed "secret" to the code base, but it is still included in the binary which is almost practically the same thing. It is just complicating the way how a person with bad intentions gets it in the first place.

Additional link to the "OAuth 2.0 Threat Model and Security Considerations"
- [RFC-6819 - Section 4.1.1 (Attack: Obtain Secret From Source Code or Binary)](https://www.rfc-editor.org/rfc/rfc6819#section-4.1.1)

Regarding `At the end of the day this is not a huge issue, aside from the fact that YouTube has that stupid quota system`:
As of today, it might not be an issue except for the things already written above & mentioned by @Marenthyu ; But also for the fact that we could take the client_id & client_secret to generate a client_credential and hammer the API to hit the quota which would disrupt the usage of OBS implementation.
But also, what about the future? What if youtube opens up endpoints to query information on behalf of the user of the "apps" they have permitted? This is as of today used by Twitch in how event sub subscription works.

**Comment by derrod** [comment]
> This would make a limit/quota increase ineffective

Only if the increase is too low and people increasingly abuse it. Increasing the quota is not an issue though, just takes some time for them to get to it. And to be honest we just didn't check often enough to see how close to the limit we are.

> "any code repository" - By uploading builds of OBS with the secret embedded to GitHub, OBS is, in my understanding, uploading the secret to a public repository.

Binaries are not code. GitHub releases are not a code repository.

> [OAuth 2.0 for Client-side Web Applications](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow)

This flow does not provide a refresh token, meaning that every time the access token expires the user would have to go through the authentication flow again (not sure how long tokens last for Google/Twitch, but usually access tokens only last a few hours to a day). This is not viable for our use.

>  I doubt that it would pass Google's Application review when requesting a higher quota

It does and has.

> As it opens the possibility of using the client_id & client_secret to identify themself as the OBS application (opens up an attack vector of bad actors)

Only if they can use the localhost redirect URL, i.e. already have code executing on the user's machine. At that point the OBS applications being impersonated is really the least of our worries. Given the limited scope of the OBS OAuth credentials, this is also not a huge problem in general.

> But also, what about the future? What if youtube opens up endpoints to query information on behalf of the user of the "apps" they have permitted? This is as of today used by Twitch in how event sub subscription works.

That seems extremely dangerous and not something that Google would do, or at least not without any sort of required migration.

---

Again I'd urge everyone to consider that even with a proxy in the middle as we are currently using for Twitch and Restream this is still vulnerable to nearly all the same problems as with the secret in the client application itself. As a bad actor can simply query the OBS OAuth proxy to authenticate their app anyway. Right now that proxy is very dumb and cannot block anything, and that seems like more trouble than its worth.

**Comment by derrod** [comment]
(Also probably worth noting that the YouTube implementation in OBS came from YouTube themselves)

**Comment by iXyles** [comment]
> That seems extremely dangerous and not something that Google would do, or at least not without any sort of required migration
For reference regarding this comment [Event sub docs](https://dev.twitch.tv/docs/eventsub/manage-subscriptions) under `Authorization` section. How ever as it says in the docs, some additional scopes would be required for some of the subscriptions.

> Only if they can use the localhost redirect URL, i.e. already have code executing on the user's machine. At that point the OBS applications being impersonated is really the least of our worries. Given the limited scope of the OBS OAuth credentials, this is also not a huge problem in general.

Sure if it is limited to "localhost" the attack surface is reduced, but it is still there. It could potentially open up the possibility for a person to make an application and say it is being done by "OBS" as it'd actually authenticate as the OBS application towards google.

> (Also probably worth noting that the YouTube implementation in OBS came from YouTube themselves)
I am unsure if I should feel some comfort about this, or be a bit worried (honestly speaking).

**Comment by derrod** [comment]
> It could potentially open up the possibility for a person to make an application and say it is being done by "OBS" as it'd actually authenticate as the OBS application towards google.

That would still be possible even with a proxy since it doesn't know what initiated the request or where it'll redirect to at the end.

> For reference regarding this comment [Event sub docs](https://dev.twitch.tv/docs/eventsub/manage-subscriptions) under Authorization section. How ever as it says in the docs, some additional scopes would be required for some of the subscriptions.

Those would still require an "app access token", which is separate from the OAuth client secret.

**Comment by Marenthyu** [comment]
> Those would still require an "app access token", which is separate from the OAuth client secret.
An App Access Token is generated by combining the `Client Secret` (which should be kept secret) and `Client ID`, which is public.

So if the Secret is leaked, effective Access is granted to the user that acquired the Secret.

**Comment by iXyles** [comment]
> That would still be possible even with a proxy since it doesn't know what initiated the request or where it'll redirect to at the end.

Yes it'd be possible show up as "OBS Studio" but it'd not be able to complete the authentication as you are required to use the client_secret to get the actual access token.

> Those would still require an "app access token", which is separate from the OAuth client secret.

A app access token is generated by "client_id" and "client_secret" also known as "client_credential"

**Comment by derrod** [comment]
> > That would still be possible even with a proxy since it doesn't know what initiated the request or where it'll redirect to at the end.
> 
> Yes it'd be possible show up as "OBS Studio" but it'd not be able to complete the authentication as you are required to use the client_secret to get the actual access token.

Yes, and you can just use the proxy for that, since - again - it cannot differentiate what initated the request.

> > Those would still require an "app access token", which is separate from the OAuth client secret.
> 
> A app access token is generated by "client_id" and "client_secret" also known as "client_credential"

Ah great. Well that is irrelevant here anyway since we're not doing that for Twitch.

**Comment by derrod** [comment]
Honestly this issue is just retreading conversations we've had internally for literally years at this point. Unfortunately OAuth 2.0 does not include a solution for this problem, and this issue is neither unique to OBS, nor really fixable within the current framework.

There are approaches to mitigate some of these problems, such as relying entirely on us running a proxy or API endpoint that handles YouTube/Twitch/etc. interactions rather than doing it on the client directly, but that's cumbersome and ultimately a defence against a threat that is insignificant in potential impact.

We may do *something* in the future should this become an issue, but at this time it is a minor inconvenience at most that can be solved with a nicely worded email to our YouTube contacts.

**Comment by Marenthyu** [comment]
Thanks for the additional insight!

Are there public documentations of said discussions? I would love to be able to follow the arguments and thought process that went into this, as it does not match what I would argue for.

Obviously, there will be discussions going on that can't be shared publicly, but understanding the reasoning for security-focused elements of an Open Source Project is in the general interest of the public (in my opinion).

As far as changes go, I hope that whatever discussion is happening that both sides (YouTube and the OBS Maintainers) can find a fitting solution that avoids leaking the secret. For the Twitch side of things, I assume something may be in the works already as well, but will keep my eye on changes in the area and maybe create a Pull Request if I can find the necessary free time - If nothing else, having more options should be a decent approach. (And the current Solution is one supported by Twitch currently.)

Again, thank you for addressing the topic, despite our differing opinions!

**Comment by derrod** [comment]
>Are there public documentations of said discussions? I would love to be able to follow the arguments and thought process that went into this, as it does not match what I would argue for.

Unfortunately no, those discussions largely happened somewhere on Discord. It's mostly the same of what has been said here; with the conclusion of "yes it's not optimal, but it's also not really an issue".

> For the Twitch side of things, I assume something may be in the works already as well

Nothing has been done as of yet.

Twitch's future restrictions impact the OBS implementation far more than just requiring OAuth with a local webserver, it also means not being able to use the login cookies for our docks.

While the former is fairly easy to fix (copy-paste YT code + some changes to the proxy), as of now we do not have a solution for the latter.
