### ISSUE TITLE
Proposal: Fix cursor scaling when using DXGI capture

### ISSUE THREAD

**Issue by caesay** [obsproject/obs-studio#7607]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### Expected Behavior

OBS will record cursors that look to be the same size as the cursor that windows renders.

### Current Behavior

OBS records a cursor that is scaled for the primary display DPI without any cursor scaling. 

### Steps to Reproduce

1. Change the cursor size to > 1 using the new Ease of Access -> Mouse pointer settings.
2. Record screen using DXGI.
3. Note that OBS records a tiny cursor.

### Anything else we should know?

This would fix https://github.com/obsproject/obs-studio/issues/2604 (which has recently been closed as wontfix). Feel free to also close this issue if there is no interest in this being fixed. If there is interest, I would be willing to have a look at doing a PR as I've just recently done this in another app.

The problem is the windows API OBS uses to retrieve the current cursor icon (`GetCursorInfo` and `GetIconInfo`) does not work with scaling properly. These API's will return a cursor bitmap which is scaled to the primary display DPI (eg. `GetSystemMetrics(SM_CXCURSOR)`) and without the cursor scaling settings applied. This is _extra_ wrong, because it means if the cursor is on a secondary display with a smaller DPI than the main display, the cursor will actually appear larger than it should be. Furthermore, the icon bitmap you get has no reference to the underlying icon file containing the other cursor sizes - so doing a naïve scaling will produce a correctly sized but blurry cursor.

The best way (that I know of) to produce a correctly sized cursor is:
 - Calculate the correct cursor size for the current monitor dpi using a combination of the registry `CursorBaseSize` setting and `GetSystemMetricsForDpi(SM_CXCURSOR, monitorDpiX)`. 
 - Retrieve the cursor file path from the registry `HKEY_CURRENT_USER\\Control Panel\\Cursors`
 - Load the cursor icon from file with `LoadIconWithScaleDown`, using the requested cursor size. This will find the cursor bitmap in the file which is one step larger than the requested size and scale it down to the correct size.

It works 99% of the time, but it's not completely fool-proof. Some windows cursor schemes don't actually set the cursor file path in the registry. In the case where the cursor file path is empty, the default cursors are loaded by Windows from user32.dll embedded resources, and the best you can do is the blurry naïve bitmap up-scaling to the correct cursor size.

**Comment by gxalpha** [comment]
If you have a fix, feel free to submit a PR for it.

The issue was closed mainly because it became clear that no one on the team would try to fix it (since the issue doesn't happen in WGC which we recommend using anyways), however contributions are always welcome. Personally I can't judge whether your solution would be the correct fix for the issue, that would require someone with knowledge of the capture API and likely only happen once a PR exists.

**Comment by caesay** [comment]
@gxalpha Why is WGC recommended? If you made me pick I'd choose DXGI every time to avoid that yellow border while recording. 

I'm happy to submit a PR but it would be good to get a tentative green light on the approach before I do the work.

**Comment by gxalpha** [comment]
WGC is the more modern API. I believe that on Windows 11 we can disable the yellow border.

Regarding a green light, I can't give that as it's outside of my area of expertise.

**Comment by RytoEX** [comment]
> Why is WGC recommended? If you made me pick I'd choose DXGI every time to avoid that yellow border while recording.

WGC works seamlessly across GPUs in multiGPU setups (such as laptops) where DXGI does not. It is largely for this reason that we recommend WGC over DXGI.

For the record, the yellow border does not show up in Windows 11, as the APIs and settings to allow apps to turn off the yellow border exist on that version of Windows.
![image](https://user-images.githubusercontent.com/624931/196761638-bbb95721-421c-4e51-9a0b-a3e7233f1ab3.png)

It's not clear if these settings will ever be added to Windows 10.

If you want to discuss potential approaches to PRs before opening one, asking on [our Discord's](https://obsproject.com/discord/) #development channel would be a better place than here. Otherwise, simply open a PR, and feedback can be provided there as time permits for those who are able to provide feedback. Our GitHub Issues are only for bug reports.

Thank you for your understanding.
