### ISSUE TITLE
OBS doesn't follow Qt6's system theme

### ISSUE THREAD

**Issue by MiliAxe** [obsproject/obs-studio#7689]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/72TFTmwJcddygisf

### Expected Behavior

Prior to the new update, OBS followed Qt5's system theme wonderfully (I use qt5-styleplugins to set my qt5 theme to be like my gtk theme). System theme should follow the style of the Qt6's theme (I have qt6gtk2).

### Current Behavior

System theme is just a white theme that does not follow system's Qt6 theme. 

Screenshot: 
![image](https://user-images.githubusercontent.com/55515322/198943341-5041f650-9867-4dfc-9858-1951997671df.png)

### Steps to Reproduce

1. Install any version of OBS above 28
2. Set Theme from Settings > Theme to "System"
3. OBS's theme now does not follow Qt6's theme.

### Anything else we should know?

There is no problem with this on versions prior to 28 that had Qt5. I have tried the new versions including 28.1 and 28.03 and it still has the same issue. Any other software using Qt6's theme work without any issues.

**Comment by WizardCM** [comment]
This is intentional to bypass KDE Breeze overriding our styling for custom themes without any method of being disabled.

Additional information can be found here https://github.com/obsproject/obs-studio/pull/6664

**Comment by tytan652** [comment]
Too late but I still post it.

Qt5 or Qt6, it doesn't matter. 

We just enforce Fusion as base Qt style because common Qt Style like Breeze or QGnome break every OBS theme. (https://github.com/obsproject/obs-studio/pull/6664)
So "System" only applies Fusion.

But you can try to set the environment variable `QT_STYLE_OVERRIDE` to avoid Fusion it is at your own risk.

**Comment by 71GA** [comment]
Sorry, but I have never heard something so ignorant from a developers _(to enforce something like this is plain stupid)_.

**Comment by derrod** [comment]
> Sorry, but I have never heard something so ignorant from a developers _(to enforce something like this is plain stupid)_.

Not having broken UI is stupid? News to me.

**Comment by 71GA** [comment]
> > Sorry, but I have never heard something so ignorant from a developers _(to enforce something like this is plain stupid)_.
> 
> Not having broken UI is stupid? News to me.

Well you do have a broken UI. It fails to follow system theme hehehe.

**Comment by Fenrirthviti** [comment]
> Sorry, but I have never heard something so ignorant from a developers _(to enforce something like this is plain stupid)_.

> Well you do have a broken UI. It fails to follow system theme hehehe.

If you actually want this to be looked at, showing up on our repo with hostile, passive aggressive bullshit is probably the worst way to get us to take your concerns seriously. I would suggest starting by taking the time to read our [code of conduct](https://github.com/obsproject/obs-studio/blob/master/COC.rst) that informs how not to act towards developers and other members of our community.

As for this specific issue, if you have a better solution, we are open to entertaining suggestions, but we've weighed the options and this is the least bad solution we settled on. It allows OBS to continue to have a functional UI for the majority of users, with a very simple and basic workaround (the mentioned `QT_STYLE_OVERRIDE` environment variable) for those that want to live with the caveats otherwise. If you have the knowledge and capability of fixing all the issues allowing Qt to inherit the system theme, PRs are very welcome to that end. In our experience and testing, it was not worth the effort and disruption to the project to invest time in to at the time, which is why this is closed.

**Comment by Fenrirthviti** [comment]
Thank you for your input, it sounds like you found the solution we provided that works for you.

**Comment by 71GA** [comment]
> Thank you for your input, it sounds like you found the solution we provided that works for you.

This is not a solution... Commit should be reverted.

**Comment by Kommynct** [comment]
on nixos QT_STYLE_OVERRIDE=qt5ct seems to do absolutely nothing. Has this been made worse?

**Comment by Naxdy** [comment]
@Kommynct `QT_STYLE_OVERRIDE` is now completely ignored following this commit: https://github.com/tytan652/obs-studio/commit/34d577d74873168025c63736bf5783fe24ef6e85

**Comment by Kommynct** [comment]
So, there's no way to override this and pick the system theme now at all? it worked perfectly with my system theme, darn.
