### ISSUE TITLE
Windows: Logs still show deprecated release ID

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#7726]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/Vtn5hXtjQ-vn0W60

### Expected Behavior

Mine should show "Windows Version: 10.0 Build 19043 (release: **21H1**; revision: 2130; 64-bit)"

### Current Behavior

shows "Windows Version: 10.0 Build 19043 (release: **2009**; revision: 2130; 64-bit)"

### Steps to Reproduce

1. Check the log and crash log

### Anything else we should know?

https://techcommunity.microsoft.com/t5/windows-management/windows-10-21h2-and-windows-11-21h2-both-show-up-as-quot-2009/m-p/2994441

`ReleaseId` key is deprecated; use `DisplayVersion` for windows 10 (or see the "documented" way in the link in the article link in the link (sorry!))

**Comment by PatTheMav** [comment]
According to the Microsoft product manager who responded to the issue on Twitter it sounds like not even `DisplayVersion` should be used, because both are for internal use only and can break at any given time:

https://twitter.com/bytenerd/status/1395071115072966656

Instead CurrentBuild or CurrentBuildNumber should be used.

**Comment by WizardCM** [comment]
https://github.com/obsproject/obs-studio/blob/5658bf6732c58e6a8b59d78729e7acd0f4907585/libobs/util/platform-windows.c#L1186-L1192

**Comment by PatTheMav** [comment]
So just remove the ReleaseId?

**Comment by WizardCM** [comment]
We could. I wouldn't be against keeping it as an easier at-a-glance for older Windows 10 versions though.

**Comment by CodeYan01** [comment]
Why not use the DisplayVersion if it's available, then fall back to ReleaseId? It's not a very critical piece of code, and it would require more maintenance to keep a table of build numbers and their respective display name. If DisplayVersion gets re-deprecated for newer versions, we could remove that. But my guess is that it won't be deprecated soon. ReleaseId was only deprecated because Windows added letters to the version. It's not like ReleaseId was ever documented from the response in the tweet.

**Comment by derrod** [comment]
Yeah we already rely on a number of undocumented things in OBS because MS never made this available via any APIs (e.g. game bar detection). So I don't think there's much of an issue with reading another string from the registry. Could be a simple `ReleaseId` if `ver->build <= 2009_BUILD_ID` otherwise use `DisplayVersion`.

**Comment by RytoEX** [comment]
Without actually checking what the log analyzer actually looks for, and what patterns it expects around the version components, and actually testing it to make sure a change doesn't break it, I'm not inclined to change logged strings for OS versions on a whim. In any case, this is not a bug. This is working exactly as we designed it.

**Comment by derrod** [comment]
The analzer doesn't parse the release in OBS logs, probably precisely because it is wrong: https://github.com/obsproject/loganalyzer/blob/3429f257c2f610684d3408de5cd326afc8a951ed/checks/windows.py#L235

Changing this should not impact the analyzer.

**Comment by RytoEX** [comment]
> The analzer doesn't parse the release in OBS logs, probably precisely because it is wrong: https://github.com/obsproject/loganalyzer/blob/3429f257c2f610684d3408de5cd326afc8a951ed/checks/windows.py#L235
> 
> Changing this should not impact the analyzer.

The regex to build the individual components does.
https://github.com/obsproject/loganalyzer/blob/3bbe8442b8dba2d3119e860b202ac36d7b64fef5/checks/utils/windowsversions.py#L5-L17

**Comment by derrod** [comment]
> The regex to build the individual components does. Though it appears that part is deemed "optional", so one might be in luck there. It should still actually be tested, which is simple enough for someone with time to do.

The regex is written to accept both numeric and alphanumeric release names so it works as expected.

> Also worth noting that the win10versions and win11versions objects use ReleaseId and CurrentBuildNumber, which are later used in version checks, IIRC (I cannot recall which of the two are actually used).

The release number in those lists is used for some checks, but it's never read from the regex result. Those checks could be migrated to use the actual build number instead.

> This is still, in my opinion, not a bug.

The function is supposed to log the windows version and release name, it no longer fulfills that function due to a change in Windows. That is a bug.
