### ISSUE TITLE
OBS studio doesn't work with Pipewire Desktop capture but gives no error. 

### ISSUE THREAD

**Issue by jhaand** [obsproject/obs-studio#7931]
### Operating System Info

Other

### Other OS

Debian Bookworm (X11)

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.01.11-3

### OBS Studio Log URL

https://obsproject.com/logs/-PJxRg1rGUq5Q71r

### Expected Behavior

When selecting desktop capture using Pipewire under a Xorg desktop, provide an error.
The Pipewire option only works under Wayland and users should use the Xshm Screen Capture. 

### Current Behavior

OBS studio only gives a warning that Pipewire doesnt't work but gives no suggestions. \ 
`warning: [pipewire] Failed to create session, denied or cancelled by user`

### Steps to Reproduce

1. Start a desktop session under Linux with KDE and Xorg display server.
2. Start OBS Studio. 
3. Add 'Screen Capture (Pipewire)' 
4. Try to record and see the desktop capture. 
5. See the logging in the Terminal. 

### Anything else we should know?

Trying to get this working has costed me 5 hours to figure out.

**Comment by tytan652** [comment]
KDE Plasma did not implement X11 capture with PipeWire. Only GNOME seems to have done it.

**Comment by jhaand** [comment]
Ok. Thank you for elaborating. 
I hope some other people will find it sooner than I did.

**Comment by woshishabii** [comment]
> KDE Plasma did not implement X11 capture with PipeWire in their portal. Only GNOME seems to have done it.
> 
> Edit: Use Xcomposite and Xshm for Plasma X11.

well on arch linux plasma x11, xshm just produce some weird videos

**Comment by iam-TJ** [comment]
I've just encountered this with Debian 12 (Bookworm) amd64 and KDE Plasma desktop. It's a UX regression since Debian 11 (but I'm not attributing the cause to OBS; just making it known) - I hadn't used OBS since upgrading to Debian 12 and was confused when the several Xcomposite based window captures all failed, so went digging deeper.

As well as Pipewire window captures failing as described here, in my case the existing (or indeed a new) Xcomposite window capture also fails with:
```
error: xcb_composite_name_window_pixmap failed
```
as others have detailed in

https://obsproject.com/forum/threads/error-xcb_composite_name_window_pixmap-failed-and-window-capture-xcomposite-doesnt-work.164861/

Unfortunately I do not have Xorg logs from Debian 11 to see if this is some way related to the Xorg **Xcomposite** extension not being loaded. It isn't reported in `/var/log/Xorg.0.log` but I don't know if it was in Debian 11.

Plasma is set to do compositing as it was for Debian 11 so I'm currently stumped!

Screen Capture (XSHM) does work but is no good since it is capturing the entire screen not the application window.
