### ISSUE TITLE
Logs do not detect/track if something is plugged into the wrong GPU

### ISSUE THREAD

**Issue by VtuberTalk** [obsproject/obs-studio#7947]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ey-GDIJpLZVBYdk_

### Expected Behavior

OBS logs should say that HDMI is plugged into wrong GPU.

### Current Behavior

When generating a log where an HDMI is plugged into the wrong GPU, there is no mention of it in the log, making it difficult to impossible for people to realize that it is an issue while troubleshooting.

### Steps to Reproduce

1. Have monitor plugged into wrong GPU.
2. Install OBS fresh.
3. Launch with no scenes/assets.
4. Attempt to close OBS.
5. OBS will hang and not appear in Task Manager, but if you attempt to reopen, OBS will say an instance is already running.
6. Generate log. Log will not say that an HDMI is plugged into the wrong GPU.
...

### Anything else we should know?

Had to work with a lot of people before someone suggested checking the HDMI plug placement. Spent 10 hours troubleshooting only for the answer to be a plug. The person I spoke with said they would have expected this to be noted in the log. I hope that my case can help make things easier for someone else down the line!

**Comment by Fenrirthviti** [comment]
There is no such thing as "wrong GPU" in the context of OBS, as we cannot determine intent of the user when launching. Logs will already show what displays are connected to what GPUs right at the top, as the log you have provided shows.

Since this information is already logged, I'm a bit unclear what exactly would need to be changed. We poll the OS (Windows in this case) for this information in the first place, so if it's reporting incorrectly (given the context of the Discord conversation, this is likely the case), there is unfortunately not much we can do.

**Comment by Fenrirthviti** [comment]
As an additional note, this only seems to affect Intel/AMD mixed systems for some reason. This would need to be reported to either AMD or Microsoft, however, as we use the standard APIs.
