### ISSUE TITLE
Check for updates proposes earlier version

### ISSUE THREAD

**Issue by iemejia** [obsproject/obs-studio#7952]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/OayNI11SDgo0WW0L

### Expected Behavior

When I click on `Check for Updates` while using version `29.0.0-beta3` I expect the update to tell me that there are not updates or propose me a newer version.

### Current Behavior

The installer proposes the earlier version `28.1.2`.
I assume the current behavior is because it is a beta, and not a stable version but the correct behavior should probably a newer beta, rc or stable release.

### Steps to Reproduce

1. Open OBS 29.0.0-beta3
2. Click the menu option Check for Updates
...
![Screenshot 2022-12-21 at 16 08 10](https://user-images.githubusercontent.com/79476/208938828-1547bece-9192-4f95-a70d-cd45bdacfcaf.png)

**Comment by Fenrirthviti** [comment]
This is currently expected, as we haven't fully rolled out the new beta channels for the updater. Release is the "newest" version as far as the updater is concerned, even if betas are technically newer. This is something we're working on rolling out as part of the new beta channels feature, but there is still some work that needs to be completed before it is ready.

**Comment by alinsavix** [comment]
It seems weird that the client would just go "oh, 28.1.2 is what the site says is newest and that's not me, so I need to update" rather than doing something like "oh, 28.1.2 is what the site says is newest, but I'm 29.0.0 and 29.0.0 > 28.1.2, so I'm not going to do anything". That seems like the right thing to do on the client, regardless of what the server side of things is doing, or even what update channels there are (e.g. if someone is set to the 'stable' update channel, but installs a beta version by hand, I wouldn't expect it to try to roll back to the stable version the next time the user checks for updates)

(or, at least, it sounds like the server side is the main thing that still needs updating, so seemed worth pointing out the weird client behavior)

**Comment by Fenrirthviti** [comment]
The current logic has no real concept of versions, beta, or release. It's a pretty "dumb" check, which is part of what the new update channels feature is supposed to fix. It's definitely weird right now, but it's working as we expect it to even if it's unintuitive, and should hopefully not be that way for much longer.
