### ISSUE TITLE
Encode not running on correct GPU

### ISSUE THREAD

**Issue by lavavex** [obsproject/obs-studio#7975]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29 beta 3

### OBS Studio Log URL

https://obsproject.com/logs/7YU1N4BZoY1gzHCB

### Expected Behavior

when running AMD Encoder, It should be using my AMD GPU, not my Nvidia GPU

### Current Behavior

With AMD Encode selected in settings, it still runs encode on Nvidia GPU

### Steps to Reproduce

1. Have AMD iGPU and Nvidia dGPU
2. Open OBS
3. Open Settings
4. Set Encoder to AMD Hardware
5. Start Stream
6. Runs on Nvidia
...

### Anything else we should know?

AMD Encode did not show up until this beta, but still does not work properly

**Comment by Fenrirthviti** [comment]
The encoder is not running on your NVIDIA GPU, that's impossible, and reflected in the log.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
