### ISSUE TITLE
pipewire format negotiation can fail to fallback to shared memory

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-studio#7985]
### Operating System Info

Fedora 37

### OBS Studio Version

29.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/GJUwf1iqZLQRDfBv

### Expected Behavior

Fallback to shared memory should always work, and the negotiation should eventually succeed (or fail)

### Current Behavior

We enter an infinite loop attempting to negotiate format. We also attempt to bmalloc 0 bytes which we shouldnt do.

### Steps to Reproduce

1. Run your compositor on a driver that supports modifiers
2. Run obs on a software renderer, or possibly older mesa versions with different modifier support than native.
3. Observe negotiation continues infinitely.
...

**Comment by kkartaltepe** [comment]
cc @GeorgesStavracas if you have any thoughts

**Comment by columbarius** [comment]
On software rendering (eg. `LIBGL_ALWAYS_SOFTWARE=true`) [init_format_info](https://github.com/obsproject/obs-studio/blob/master/plugins/linux-pipewire/pipewire.c#L346) won't contain any format.

**Comment by mcoffin** [comment]
This *might* be related to what I just tracked down while working out kinks with new hardware.

With the number of supported modifiers on formats growing, (11 on all relevant formats for me at the time of writing), we actually out-grow the 2048-byte buffer we were using to construct the SPA version of the format params. This *seems* a bit excessive, but I don't know how the internals of `spa_pod_builder` work, so once I confirmed this I didn't look too much farther to see if we're leaking something temporarily there.

This results in the "changes" we think we're making to the relevant formats (removal of incompatible modifier) not taking effect, so we push either identical, or null changes through to pipewire, which realizes there's no change, and never triggers a change event on either end.

It wouldn't be a bad idea to add some defensive coding to prevent the "trying the same params twice" case to prevent an actual logic issue in the future, but in the immediate time frame, simply increasing the buffer size from 2048->4096 resolves it (at least with my hardware). IMO, these buffers should either be dynamically resizable or *far* larger than that to cover future use cases like more metadata. While there's a time for the assumption around a max buffer size, this negotiation is hopefully seldom. I'm not yet any kind of decent at SPA, so I didn't take a crack at it yet, but I can :)

If you want an easy way to confirm this overflow, just break at the end of `build_format_params`, and if any element of `params` is NULL that doesn't correspond to a `format_type` that has already exhausted its list of qualifiers, then the builder has overflowed.

I'm not familiar with what the *expected* behavior of passing `NULL` values to `pw_stream_update_params` within the `[0,n_params)` range is either, so regardless of the infinite loop this wasn't likely terrific behavior :rofl: 

```patch
diff --git a/plugins/linux-pipewire/pipewire.c b/plugins/linux-pipewire/pipewire.c
index b269344a9..d8acd1c82 100644
--- a/plugins/linux-pipewire/pipewire.c
+++ b/plugins/linux-pipewire/pipewire.c
@@ -33,6 +33,7 @@
 #include <spa/param/video/format-utils.h>
 #include <spa/debug/format.h>
 #include <spa/debug/types.h>
+#include <spa/debug/pod.h>
 #include <spa/param/video/type-info.h>
 #include <spa/utils/result.h>
 
@@ -327,6 +328,12 @@ build_shm:
 			pod_builder, &obs_pw->video_info,
 			obs_pw->format_info.array[i].spa_format, NULL, 0);
 	}
+	// blog(LOG_DEBUG, "[pipewire] Built format params [%u]", params_count);
+	// for (unsigned int i = 0; i < params_count; i++) {
+	// 	if (params[i] == NULL)
+	// 		continue;
+	// 	spa_debug_pod(0, NULL, params[i]);
+	// }
 	*param_list = params;
 	*n_params = params_count;
 	return true;
@@ -434,7 +441,7 @@ static void renegotiate_format(void *data, uint64_t expirations)
 
 	pw_thread_loop_lock(obs_pw->thread_loop);
 
-	uint8_t params_buffer[2048];
+	uint8_t params_buffer[4096];
 	struct spa_pod_builder pod_builder =
 		SPA_POD_BUILDER_INIT(params_buffer, sizeof(params_buffer));
 	uint32_t n_params;
@@ -759,7 +766,7 @@ static void play_pipewire_stream(obs_pipewire_data *obs_pw)
 	struct spa_pod_builder pod_builder;
 	const struct spa_pod **params = NULL;
 	uint32_t n_params;
-	uint8_t params_buffer[2048];
+	uint8_t params_buffer[4096];
 
 	obs_pw->thread_loop = pw_thread_loop_new("PipeWire thread loop", NULL);
 	obs_pw->context = pw_context_new(
```

**Comment by GeorgesStavracas** [comment]
I'm afraid I'd have to fix this to actually provide more feedback on what's going on

**Comment by kkartaltepe** [comment]
> This might be related to what I just tracked down while working out kinks with new hardware.

I could not replicate this i with i915/nvidia-drm drivers, I just set an assert on build_format's return value, and it seems they do not report as many modifiers as whatever system you are on. e.g. https://drmdb.emersion.fr/snapshots/d8f2db7b84d5 or https://drmdb.emersion.fr/snapshots/bb72f61358be 

The most popular amdgpu cards also dont report so many modifiers (or any): 580 series https://drmdb.emersion.fr/snapshots/bff76074682d,  5xxx series:https://drmdb.emersion.fr/snapshots/5e48acec4633 but looking at the 7xxx series it seems they have kept adding more: https://drmdb.emersion.fr/snapshots/d5dc1c516b42

if there is a way to compute the required size of our builder sending a patch for sizing would be good.

**Comment by columbarius** [comment]
> With the number of supported modifiers on formats growing, (11 on all relevant formats for me at the time of writing), we actually out-grow the 2048-byte buffer we were using to construct the SPA version of the format params. This _seems_ a bit excessive, but I don't know how the internals of `spa_pod_builder` work, so once I confirmed this I didn't look too much farther to see if we're leaking something temporarily there.

This is independent from this issue. But yeah, we need to calculate the required size for all EnumFormats.

> It wouldn't be a bad idea to add some defensive coding to prevent the "trying the same params twice" case to prevent an actual logic issue in the future, but in the immediate time frame, simply increasing the buffer size from 2048->4096 resolves it (at least with my hardware). 

We don't try the same params twice. A modifier is always dependent on the used format. If a modifier don't work for a given format we drop it, but the same modifier value might work with another format. Also if we update our EnumFormats, we have to announce everything we support. Otherwise the producer might have issues with our selected subset and can't choose a valid pair.

**Comment by mcoffin** [comment]
> We don't try the same params twice

100% agreed with all the logic, but... I think what I failed to say since I'm new to this ecosystem is that that's the behavior that is triggered by encountering the aforementioned overflow. Despite the call to `pw_update_stream_params` being initiated (observed w/ debugger), the presence of null values in `params` triggers (likely undefined) downstream behavior, that I observed to be pipewire taking *no action whatsoever* in terms of actual updates in response to the call. This means we print "Renegotiating format", but never actually get that far, and repeatedly fail to use the DMA-BUF in our rendering API (exactly as is in the logs in the OP).

I realize this is *very likely* only tangentially related if there are logic failures that cause circumstances other than this to trigger similar symptoms. I think we're all on the same page there; That said, the desktop hardware support stack(s) are a a painfully broad, and oft lonely experience to independently learn on one's own, so after spending far too long ramping up to track down what ended up being a simple lack of buffer space, I'll take whatever good discussion for learning I can get out of it, and hopefully save some poor google'ing sap some time in the process.

> If a modifier don't work for a given format we drop it, but the same modifier value might work with another format

This was my assumption too based on my limited understanding, but at least for my current version of `firefox` (`100.0.1`), it's webrtc implementation of pipewire dma-buf sharing *does* remove a given modifier from *all* formats during each round of attempted negotiation. Thanks for confirming my suspicion that the OBS implementation was more correct despite my experienced issues! I spent far too long chasing that red herring while getting my bearings yesterday
