### ISSUE TITLE
Cannot stream to YouTube via HLS with a bitrate over 8Mbps

### ISSUE THREAD

**Issue by snnacks** [obsproject/obs-studio#8065]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/P5Wi672qBqSKfCvh

### Expected Behavior

To be able to stream at the same bitrate I can stream with RTMPS (up to 51Mbps)

### Current Behavior

Drop frames if exceed a total bitrate (audio + video) of 8Mbps

### Steps to Reproduce

1. Stream to YouTube via HLS
2. Set combined (audio and video) bitrate to a value greater than 8Mbps (the higher the bitrate the more dropped frames)

### Anything else we should know?

Myself and others have noticed that when streaming over 8Mbps the bitrate will actually dip to 0Mbps for a second or two and then return to the set bitrate

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by snnacks** [comment]
I have reason to believe there is an issue with OBS Studio/YouTube as a few others have reported the same issue in the OBS Discord...

**Comment by Dongree-976** [comment]
I have Same issue.
The capture card I have is an OBS certified Avermedia GC573, Asus CU4K30.

The system is Windows 11 Pro for Workstation.
Internet is 1Gb Internet

1)
CPU : Threadripper 3960X
GPU: Rtx3090
RAM: 128GB

2)
Intel I9 13900K
RTX 4080

3)
Ryzen 5950X
RTX 3070

The same test was performed on the three systems above.

In RTMPS, even 100000 Kbps could be processed without difficulty.
However, HDR transmission using HLS does not last 4 seconds and causes frame drops.
Network transfer rates momentarily and frequently hit 0Kbps.

I made a rather odd discovery. Recently, the Apple Silicon Mac version of OBS was able to transmit 100,000 Kbps HLS HDR even while on Wi-Fi.
The same HDR transmission was possible with the M2 and M1 MAX.
Unfortunately, with the capture card I had, I could only set the device to Rec 709 and NV12. (GC573, CU4K30, Ultrastudio 4K mini, 4K Web Presenter)

The point is that the HLS transmission on Windows is the problem rather than the system problem.
This is the data obtained by live streaming 102 times through a YouTube private link.
