### ISSUE TITLE
Max Headroom effect on OBC Virtual Camera to Google Meet

### ISSUE THREAD

**Issue by RayHollister** [obsproject/obs-studio#8078]
### Operating System Info

macOS 12

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/v7fDoOOUMGVZ5ZgF

### Expected Behavior

Normal OBS Virtual Camera preview

### Current Behavior

The preview on Google Meet when I am using OBS Virtual Camera is CRAZY. I couldn't figure out a better way to describe it, but it makes me look like Max Headroom. Here's a video showing it: 

https://user-images.githubusercontent.com/369131/212933665-0af34f9c-0cae-4e96-b401-585d4ea08636.mp4

It looks completely normal to the other users though. 

### Steps to Reproduce

1. Open OBS
2. Click Start Virtual Camera
3. Open a Google Meeting
4. Change camera to OBS Virtual Camera

**Comment by RayHollister** [comment]
I tried rolling back to 28.1.2 and it stopped happening. Then, just for giggles, I tried reinstalling 29.0 one more time, and now it has stopped. 🤷🏻‍♂️

**Comment by gxalpha** [comment]
Hi, could you try [this build](https://github.com/obsproject/obs-studio/suites/10399560756/artifacts/513599820) (the current nightly build of OBS)? Install it, then start the virtual camera once (make sure to grant it permissions at start). Then restart Chrome and try again.
During installation, it might say that it cannot be opened as our nightlies aren't signed. In that case, right click it and select "Open", it should give you the option to continue anyways.

There have been issues with the virtual camera in 29.0.0, and although they're not completely the same as what your video is showing, I suspect there's a chance that it's the same cause.

**Comment by Fenrirthviti** [comment]
Possibly related to https://github.com/obsproject/obs-studio/issues/8039?

**Comment by risacher** [comment]
@gxalpha I had the same issues as @RayHollister.  (Red flickers on MacOS 12 OBS virtual camera into Chrome browser) I tried the  nightly build that you suggested and it fixed the problem.  

For reference, it was tricky to test because not only is OBS unsigned, but the camera plugin is also unsigned.  As you note, on MacOS you can run an unsigned application by right-click & open, but to use the plugin, I needed to also do this: `sudo xattr -rd com.apple.quarantine /Volumes/Untitled/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/`

**Comment by risacher** [comment]
Also, I second the suggestion of  @Fenrirthviti that this is the same issue as #8039 and conclude that it was fixed by #8044.

**Comment by RytoEX** [comment]
Closing as fixed by #8044.
