### ISSUE TITLE
Havin multiple media sources with "Restart playback when the source becomes active" makes OBS mini freeze on scene changes

### ISSUE THREAD

**Issue by TheRealDadbeard** [obsproject/obs-studio#8143]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/hOqcAHHSqK6f7mxm

### Expected Behavior

No small freezes

### Current Behavior

Small freezes on the end of the transition of scenes mostly from the Scene that has multiple media sources.

### Steps to Reproduce

1. Have multiple media sources with those settings 
![grafik](https://user-images.githubusercontent.com/23340600/214515421-0afc883f-2609-4202-a278-c79e83fd4c21.png)
2. Use a stinger or a fade to transition
3. Transiton multiple times
4. I would move in the camera to see the stutter but it's globally, keep an eye out when the sources from the other scene disappear from the audio mixer. Right in that moment the freeze happens

### Anything else we should know?

I have already tested this with a clean version and the same happens. Logs from my OBS install with all my plugins. All files are on an NVME drive.

If I disable "Restart playback when the source becomes active" there is still VERY minimal freezing but with it on it's worse. Funny enough it mostly only happens when I transition FROM the scene that has multiple media sources and I have to use it as otherwise OBS will not unload the files and hog 1.2GB of RAM even in my slimmed down game scene.

Sometimes it's less but sometimes it freezes noticeably. I try to get some videos of that in the next days.

**Comment by gxalpha** [comment]
I think what you're describing looks more or less expected with the settings you're using.
In particular, three of the settings may have an effect on this:
- "Restart playback when source becomes active": The file has to be reloaded from the beginning, using up performance
- "Use hardware decoding when available": You may see increased CPU load here due to the CPU having to decode multiple files at once, in real time (instead of the dedicated cores on the GPU doing that)
- "Close file when inactive": As the tooltip explains, this results in delay when having to re-open the files every time (and additionally having to decode them again)

I'm closing this issue as this is going into support territory. Please consult the support channels on our [Discord](https://obsproject.com/discord) or [Forums](https://obsproject.com/forum) for further questions.

**Comment by TheRealDadbeard** [comment]
I see you didn't read my issue.

This mini freeze happens when OBS UNLOADS the sources, not when loading them.

I have a 5800x3D and all the files are on an NVME. 

This is kinda annoying having all my issues always closed then suddenly there is a bug in the code. Please open this again, this has nothing to do with support.

Why does it freeze on unload and not loading? Makes no sense. It is a little bit better when I keep the files loaded but thats all.

**Comment by RytoEX** [comment]
> Why does it freeze on unload and not loading? Makes no sense. It is a little bit better when I keep the files loaded but thats all.

The option "Restart playback when source becomes active" also affects deactivation/unload. When this option is enabled, the source and the backing media object are stopped. See:
https://github.com/obsproject/obs-studio/blob/29.0.2/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L673-L685
https://github.com/obsproject/obs-studio/blob/29.0.2/deps/media-playback/media-playback/media.c#L993-L1004

This forces a call to `mp_media_reset` in the media thread, which results in additional cleanup and prep for restarting the source. Thus, unloading has a cost when this option is enabled as the source must be spun down. Disabling the option keeps the source running while not visible/active, which requires constant CPU and RAM utilization (the source is not spun down, but continues playing/decoding in the background, even if not rendered). You can observe this by checking resource utilization in Task Manager with the options enabled or disabled.

The option "Show nothing when playback ends" also results in additional calls in this scenario when the above option is enabled and the source is deactivated.

The option "Close file when inactive" requires a full teardown of the backing `mp_media` object when the source becomes inactive.

These options are generally recommended for systems that cannot be constantly running all media sources in the background because they reduce overall resource utilization. However, there are non-zero costs associated with spinning media sources up or down, and enabling these options changes what occurs when a source activates or deactivates.

**Comment by TheRealDadbeard** [comment]
What does this mean? That the code is unoptimized or that this is just how it is and can't be fixed?

Why is the mp_media_reset call creating such a massive freeze? I didn't time it but looks like around 500ms.

I have the last option now disabled as I have 32gb of ram now and it makes a big difference. I created this when I had 16 and optimized everything. It still occurs but is very small. First one really is needed or I would have many files running in the bg.

**Comment by TheRealDadbeard** [comment]
Wow so this will be just closed right? OBS should not freeze on unloading sources at all, not on my system.

That is not a support question when the code is the issue.

**Comment by Fenrirthviti** [comment]
While this is not technically a bug, everything is working as expected and as implemented. It's a bit nuanced, but "user doesn't expect" can muddy what constitutes an actual bug or issue. Currently, there isn't much information in this issue we aren't already aware of, so opening the issue doesn't really change anything.

It is our opinion that this can't easily be fixed in the current implementation, and the effort is better spent on an eventual rewrite.  A fix was attempted here: https://github.com/obsproject/obs-studio/pull/8634 but as per the comment, effort was better spent on a full rewrite rather than trying to change things in the current implemention. There is no ETA on when that work will be completed, but tracking for that will happen on a PR when it is ready.
