### ISSUE TITLE
Destiny 2 Dimmed Display

### ISSUE THREAD

**Issue by AyresIV** [obsproject/obs-studio#8164]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

*

### OBS Studio Crash Log URL

*

### Expected Behavior

During Stream, I moved between games. I was playing Apex Legends Using Game Capture to stream it, Later I went to play Destiny, But because Destiny 2 does NOT support Game Capture I am obligated to use Either Display Capture or Window capture while playing the Game on Windowed. For the past few years that I have been playing and Streaming Destiny 2, I've always done it using Display Capture while Playing Destiny 2 on Full Screen. Meaning this issue never occurred before, to me at least. With OBS 29.0.0 When I went to Destiny 2 The screen went Dim, on Display in OBS. I researched with no Luck until I tried downgrading back to 27.2.4 which eliminated the issue. My Guess it's an issue with HDR On version above 27.2.4

### Current Behavior

The Game works fine, OBS Captures fine after rolling the version back

### Steps to Reproduce

1.Use any OBS Version that is above 28.0 in my case it was 29.0
2.Use Display capture while playing Destiny 2 on **FULL SCREEN**
The Display capture should show the game **VERY DIMMED**
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

In the future, a log file is required for any bug report to be actionable. Do not ignore the template.

Thank you!
