### ISSUE TITLE
"one full screen projector per display" background show for a split second

### ISSUE THREAD

**Issue by TECHNICKER** [obsproject/obs-studio#8165]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/9o9bTKvXTqaI3AT2

### Expected Behavior

when the "only one fullscreen projector per display" option is enabled, it should seamlessly switch from one projector to another when a full screen projector is sent to a display already displaying a fullscreen projector.

### Current Behavior

the option "only one fullscreen projector per display" however behaves in a way that before the new projector is displayed the first one is closed and it shows the background, or whatever app is below it for a split second. this is disctracting and makes the feature pretty much useless.

### Steps to Reproduce

1. enable "only one fullscreen projector per display"
2. display a fullscreen projector on another display (using the projector hotkeys script)
3. send a different scene as a fullscreen projector on the same display (using the script hotkey)
4. observe the bug
...

### Anything else we should know?

I use the projector hotkeys script (https://obsproject.com/forum/resources/projector-hotkeys.1197/), not sure which version, but it behaves as expected.

**Comment by gxalpha** [comment]
The feature works as intended. Before a new projector is opened, the old one gets closed. Otherwise, you'd be having multiple projectors open at the same time for a few milliseconds (unless you'd want to modify the existing projector instead of opening a new one).
Seeing that you're describing them as useless in this state, projectors may not be the right solution to the problem you're trying to solve. I'd recommend checking out our [Discord server](https://obsproject.com/discord) or [forums](https://obsproject.com/forum) if you want to look for alternative solutions that might better fit your use case.
