### ISSUE TITLE
Streaming flapping after update to 29.0.0

### ISSUE THREAD

**Issue by trinityradioclub** [obsproject/obs-studio#8173]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/8Gej2BYGgGoMo2Aa

### Expected Behavior

We connect to Boxcast streaming.  We have a 1GB ethernet card direct connected to our internet router (MetroNet in MN).  Network card is Realtek Gaming GbE Family Controller with driver 1.0.0.14. 

Since updating to version 29, our streaming connection is up and down constantly.  It worked fine in the last version of 28. 

We upgraded to 29 on 1/22 and saw this same issue.  Thought it was our internet on 1/22.  Turned out not to be the case.

### Current Behavior

Streaming connection to Boxcast is up and down.  Connects for a couple of seconds then drops again. Recording works just fine. Internet is up and working as I have another VoIP system sending audio to our local radio station.  Never had a problem with both streams going at the same time (we have 1GB down and 1GB up for internet connection).

Stats show:
CPU Usage - 0%
Memory Usage - 1597.1 MB
FPS - 30.00
Average time to render frame - .9 ms
Frames missed due to rendering lag - 67/80888
Skipped frames due to encoding lag - 0/81385

Output - Status live
Dropped frames (network) 5744/10080 (59%)

### Steps to Reproduce

1. Basically we just start streaming
2. Connection is made to Boxcast.  Then a few seconds later it starts to drop frames on the live stream.
3.
...

### Anything else we should know?

Will be uninstalling 29 and reinstalling final version of 28 again to see if the issue resolves.  My guess it will.  I will update this case after this is completed (can't do it now as I"m trying to stream/record).

**Comment by Mister36MN** [comment]
It is highly unlikely that using v29 would cause this:

08:16:27.818: Output 'adv_stream': Total frames output: 2028 (7200 attempted)
08:16:27.818: Output 'adv_stream': Total drawn frames: 7391
08:16:27.818: Output 'adv_stream': Number of dropped frames due to insufficient bandwidth/connection stalls: 5172 (71.8%)

Unless it was some sort of weird symptom of something else that changed - 

08:38:36.067: [AMF] <Id: 16> Initial Frame Latency is 264325500 nanoseconds. (About a quarter of a second but I'm not sure I've seen that message before)

**Comment by trinityradioclub** [comment]
Going to close the issue.  Downgraded to 28.x and it is still happening.  Now thinking we have a network card issue.  Thanks!

**Comment by trinityradioclub** [comment]
Closed as I don't believe this is a problem with OBS.  Sorry for the "crying wolf".
