### ISSUE TITLE
Rec. 601 (but not 709) lossless recording with FFMPEG (FFV1) has horizontal chroma subsampling even if set to I444

### ISSUE THREAD

**Issue by JonasCz** [obsproject/obs-studio#8196]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iEdMkMw1eZ9ahzeB

### Expected Behavior

Expected behavior would be no unexpected chroma subsampling, or a warning about it when using Rec. 601 if it's unavoidable. 

### Current Behavior

The output video has horizontal chroma subsampling, i.e. colors are horizontally blended together. For reference, here's the top left corner of the test PNG, as it should look (and does, with Rec. 709):

![vlcsnap-2023-02-02-17h25m11s630](https://user-images.githubusercontent.com/10514959/216383201-f1bfb07a-fdb1-4786-9534-476e2618120e.png)

...And what it actually looks like, with Rec. 601, note the blended colors:

![vlcsnap-2023-02-02-17h25m17s944](https://user-images.githubusercontent.com/10514959/216383233-72918abf-cb54-457f-9e0b-c4bc0c93af7d.png)

The Rec. 601 file does still report 4:4:4 in Mediainfo, so it seems it is being encoded as such. Codecs other than FFV1 also show this problem, however simple output mode + NVENC H264 does not (even with Rec. 601). I've also tested players other than VLC.

### Steps to Reproduce

1. Create new profile & scene collection
2. Advanced -> Colour Format: I444, Colour Space: Rec. 601, Range: Full (note: this only occurs with Rec. 601, 709 is fine)
3. Video -> Canvas & scaled resolution: 720x480, FPS: 29.97
4. Output: Advanced, Recording: custom FFMPEG, Container: matroska, Encoder: ffv1.
5. Drag the following PNG image file onto the preview, make sure it's the same size as the preview so no scaling is happening: 
![test-colors](https://user-images.githubusercontent.com/10514959/216373399-9d90e639-e990-49eb-84ad-005f223c4484.png)
7. Hit "start recording".

### Anything else we should know?

This also happens with sources other than a PNG image, which was how I encountered this originally.

**Comment by ValZapod** [comment]
The fact that Nvidia uses BT.601 matrix in their Shadowplay with NVfbc does not mean you (or anyone, really) should use it. BT.601 matrix coefficients are derived from white point that is not D65, but C and primaires that were used back when System M was there. BT.709 is derived from BT.709 primaries that are also used in sRGB. BT.601 thus is not compatible with modern sRGB displays.

In fact all sRGB JPEGs are wrong in that sense.

**Comment by ValZapod** [comment]
>lossless recording

YCbCr 8 bit cannot preserve RGB 8 bit anyway. Use x264 lossless with RGB coding, see: https://github.com/obsproject/obs-studio/issues/7345

**Comment by energizerfellow** [comment]
Not only is full-range export via FFmpeg currently broken in OBS as of this writing (see #8199), but using full-range YUV will cause color clipping due to illegal values in the color cube. Limited range historically wasn't just because of ADC/DAC overshoot and analog circuit characteristics, but from the math of color cubes to prevent clipping (more info [here](https://www.intel.com/content/www/us/en/develop/documentation/ipp-dev-reference/top/volume-2-image-processing/image-color-conversion/color-models.html) and [here](https://techpubs.jurassic.nl/manuals/0650/developer/DIVO_OG/sgi_html/apd.html#:~:text=Range%20Issues%20For%20Color%20Conversions%20Done%20by%20Any%20Means)).

OBS also doesn't currently differentiate between the primaries of EBU 3213 / ITU-R BT.470/601 (B/G) and SMPTE 170M "C", which causes accuracy issues. This is before getting into the differing white points of C (x = 0.310, y = 0.316) vs D65 (x = 0.313, y = 0.329) vs Japanese D93 (x = 0.28314, y = 0.29711). There's also the issue of PAL/SECAM historically having a 2.8 gamma EOTF (ITU-R BT.470/H.373) vs some more modern PAL/SECAM being 2.2 (ITU-R BT.1700), which is further muddied by many historical CRT displays being closer to 2.4 gamma and the ITU-R BT.1886 situation on modern displays.

**Comment by mufunyo** [comment]
Limited range historically wasn't just because of ADC/DAC overshoot and analog circuit characteristics, but from the math of color cubes to prevent clipping (more info [here](https://www.intel.com/content/www/us/en/develop/documentation/ipp-dev-reference/top/volume-2-image-processing/image-color-conversion/color-models.html#color-models_YUVCOLORMODEL) and [here](https://techpubs.jurassic.nl/manuals/0650/developer/DIVO_OG/sgi_html/apd.html#:~:text=Range%20Issues%20For%20Color%20Conversions%20Done%20by%20Any%20Means)).

I feel that's a little misleading. If you use limited range conversion matrices for full range conversion, you're obviously going to get out-of-range values. There's no inherent clipping in YUV that is magically corrected by offsetting the input by 16 and limiting it to 235. If that were the case all JPEG images on earth would have invalid colours. But you do have to use matching matrices for conversion both to and from full range YUV. See also, ITU-T T.871 section 7, "Conversion to and from RGB".

**Comment by energizerfellow** [comment]
Core of that issue is that in the video world YCbCr is a scaled and offset version of the YUV color space. Full range quantization isn't defined in BT.601 and technically violates BT.601 (along with BT.709, for that matter).

**Comment by ValZapod** [comment]
>Japanese D93 (x = 0.28314, y = 0.29711)

That is an ambient. It is not the same as primaries, that is still D65. iPhones already have ambient SEI in HEVC: https://github.com/FFmpeg/FFmpeg/search?q=ambient&type=commits

>If you use limited range conversion matrices for full range conversion

In float those are the same matrices... The scaling changes, that is all.

>corrected by offsetting the input by 16 and limiting it to 235

Try encoding anything lossy with libx264, it will produce some gamut warning with mpv.

>were the case all JPEG images on earth would have invalid colours

They are no invalid per se, they are just not optimal.

>But you do have to use matching matrices for conversion both to and from full range YUV. 

Well, the conversion is indeed symmetric.

**Comment by ValZapod** [comment]
>Core of that issue is that in the video world YCbCr is a scaled and offset version of the YUV color space.

YCbCr uses 1/2 instead of 0.436 and 0.615 for Umax and Vmax in YUV used in analog TVs back in 1958 when Eisenhower pressed the button: https://www.youtube.com/watch?v=4vBEMGTdDYc

**Comment by energizerfellow** [comment]
> That is an ambient. It is not the same as primaries, that is still D65. iPhones already have ambient SEI in HEVC: https://github.com/FFmpeg/FFmpeg/search?q=ambient&type=commits

While ambient SEI metadata is a nice to have, ITU-T H.274 wasn't even approved until 2020 and only recently showed up as a patch in FFmpeg, per your link.

The use of D93 (9300K) was very much a thing during the SD era in Japan and many, many older PVM/BVM pro monitors had a config option for switching between D65/D93, even well into the post-CRT flat panel area. You'll notice things like a NES or SNES game console looks more accurate on D93, for instance.

Per ITU-R BT.470-6, page 16, footnote 3:
"In Japan, the chromaticity of studio monitors is adjusted to a D-white at 9 300 K"

**Comment by RytoEX** [comment]
While I'm sure this conversation is fascinating, it is of little consequence to my core concerns on this GitHub Issue.

1. Is this a real bug in OBS?
2. Is this something we can fix?
3. Is this something we want to fix?
4. Is there already a patch or PR to fix it?

**Comment by SuslikV** [comment]
Cannot confirm this.

As soon as this is 8-bit per component recording I have better (easier to understand) test images/videos to check the behavior of the player/display/recording_software_hardware:
https://obsproject.com/forum/resources/obs-studio-color-space-color-format-color-range-settings-guide-test-charts.442/

High chance that this is "display" issue. Please, take a look at other media players, like mpv for example (mpv-x86_64-20200329-git-bca917f or similar builds).

**Comment by JonasCz** [comment]
> Cannot confirm this.

I retested it with compile latest git and it looks like this is fixed. Possibly by this PR: : https://github.com/obsproject/obs-studio/pull/8374
