### ISSUE TITLE
MacOS Ventura 13.1 OBS 29.0.1 In Full screen, Application/Display/Windows Capture

### ISSUE THREAD

**Issue by bvitl** [obsproject/obs-studio#8210]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.1

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/bE7sX53r01ZIOhLv

### Expected Behavior

OBS Studio in Full Screen mode view working windows in Application/Display/Windows Capture as OBS Studio in windows mode

### Current Behavior

OBS Studio in Full Screen mode not view working windows in Application/Display/Windows Capture

https://user-images.githubusercontent.com/28355819/216764551-93b05716-c7f4-4e0a-a7a5-5cb33e1fb12d.mp4

### Steps to Reproduce

1. Add Source capture macOS screen
2. Select capture window
3. Select Window 
4. If OBS in Full Screen then not all windows view
5. if OBS as window then OK

**Comment by gxalpha** [comment]
OBS can only capture windows that are currently in an active space because of macOS limitations. Putting OBS into fullscreen puts it into its own space, so any other windows are on your normal Desktop space which will be inactive if you're in OBS, hence you can't capture it. There is nothing we can do about that.
