### ISSUE TITLE
Significant frame drops when using Custom Output (FFmpeg) but "Standard" recording works fine

### ISSUE THREAD

**Issue by BoxcartCoronet** [obsproject/obs-studio#8226]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/duMxok8xyEnuQet9

### Expected Behavior

Smooth recording

### Current Behavior

Output file has intact audio but video has significant frame loss and stuttering

### Steps to Reproduce

1. See full explanation below
2.
3.

### Anything else we should know?

Full explanation with screenshots: https://obsproject.com/forum/threads/cannot-get-advanced-outputs-to-work.164076/

I also tried following the steps identified in a separate thread on a similar issue (https://github.com/obsproject/obs-studio/issues/6062) but changing to P5 in the file and modifying it as described by the OP in https://github.com/obsproject/obs-studio/issues/6062 to what fixed it for them did not work for me.

Changing to NV12 all else being equal produces a smooth recording but horribly burned/washed out colors.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a note, it appears your encoder is overloaded, and custom FFmpeg output mode is effectively "no warranty" and unsupported for issues like this.

Thank you!
