### ISSUE TITLE
Problems with HLS live streaming on Windows.

### ISSUE THREAD

**Issue by Dongree-976** [obsproject/obs-studio#8318]
I have Same issue.
The capture card I have is an OBS certified Avermedia GC573, Asus CU4K30.

The system is Windows 11 Pro for Workstation.
Internet is 1Gb Internet

1)
CPU : Threadripper 3960X
GPU: Rtx3090
RAM: 128GB

2)
Intel I9 13900K
RTX 4080

3)
Ryzen 5950X
RTX 3070

The same test was performed on the three systems above.

In RTMPS, even 100000 Kbps could be processed without difficulty.
However, HDR transmission using HLS does not last 4 seconds and causes frame drops.
Network transfer rates momentarily and frequently hit 0Kbps.

I made a rather odd discovery. Recently, the Apple Silicon Mac version of OBS was able to transmit 100,000 Kbps HLS HDR even while on Wi-Fi.
The same HDR transmission was possible with the M2 and M1 MAX.
Unfortunately, with the capture card I had, I could only set the device to Rec 709 and NV12. (GC573, CU4K30, Ultrastudio 4K mini, 4K Web Presenter)

The point is that there are problems with HLS live streaming on Windows.
This is the data obtained by live streaming 102 times through a YouTube private link.

_Originally posted by @Dongree-976 in https://github.com/obsproject/obs-studio/issues/8065#issuecomment-1438934491_

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

In the future, please do not delete the issue template when submitting a new issue.

Thank you!
