### ISSUE TITLE
macOS window capture loses track of Keynote or Powerpoint presentation windows

### ISSUE THREAD

**Issue by mishakim** [obsproject/obs-studio#8379]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

logs are failing to upload

### Expected Behavior

When OBS is capturing the editor window of Keynote or PowerPoint, and the presentation is started in a window (which replaces the editor window), OBS should show the presentation. And vice-versa -- when switching back from presentation mode to the editor, OBS should show the editor window. 

Ideally, OBS would seamlessly switch back and forth between showing whichever window the app is showing, editor or presentation. At a minimum, when whichever one it was told to capture returns to existence after being in the other mode, OBS should resume capturing that window.  (note: application capture is not a good substitute, as that would also capture the presenter control window)

### Current Behavior

When switching between editor and presentation view (in a window), the original window is replaced with a new window, with the same title. Whenever this happens, OBS loses track of the window, and freezes the source at the last thing shown before the mode switch. When switching back, OBS continues to show the prior screen, that is, it doesn't recognize that the window it was originally capturing has returned. Only solution is to enter Properties and re-select the correct window after every mode change.

Log upload is not working, but the following appears:
```
16:16:44.764: [ mac-screencapture ]: destroy_screen_stream: Failed to stop stream with error (null)
16:16:44.764: 
```

### Steps to Reproduce

1. Create a new macOS Screen Capture source, select Window Capture, select Keynote (or Powerpoint)
2. In Keynote, switch to Presentation mode, with the presentation in a window
3. OBS still shows the presentation editor, not the windowed presentation
4. In Keynote, exit the presentation, going back to the editor
5.  OBS still shows the editor as it existed before, no longer capturing the live window
...

**Comment by PatTheMav** [comment]
This is a known limitation of how macOS and ScreenCaptureKit work:

* Keynote spawns new windows for the presentation and director's view
* From OBS' point of view they are entirely different windows
* There is nothing we can use to "detect" which of Keynote's windows would represent the actual presentation

Once you got a presentation running, you _can_ go back to OBS and manually select the new window as the capture source. Be sure to enable app switching in presentation mode (it is _not_ enabled by default in Keynote) and enable the capture of full screen/hidden windows in OBS' capture source.

If on a single screen, the original Keynote window will be gone and instead a new one will have appeared - you select this one, then switch to the presentation and back to OBS. The source will now have actual dimensions (because macOS doesn't render the window if it's not active), so you can position and scale the source as needed.

Following these steps you can capture the presentation.

Please file feedback with Apple regarding this, as it's obvious neither Keynote nor ScreenCaptureKit's interaction have taken this use case into account.

**Comment by mishakim** [comment]
Thanks for the explanation - and I do know how to get it working, it's just that it makes automation impossible and increases the number of steps I have to teach to the other people that might run my stream (using it for church services). I'll provide feedback to Apple as suggested.

It does seem, though, like OBS could figure out which window to use, because its name within the UI doesn't change. I assume that there's some unique window name which OBS is really using to talk to ScreenCaptureKit, but since OBS is able to render the human-facing name in the pick list, and that doesn't change, it should also be able to remember which name was selected and re-select it automatically whenever its real identity changes. Maybe that would require an additional option, like "persist selection across window sessions"

**Comment by PatTheMav** [comment]
We cannot make the assumption that it is indeed the presentation window or what the user intends us to do. The risk of making something appear "automatically" in a recording or stream that the user never intended to present to the world is too great and runs counter to macOS' permission model.

It is my opinion that we should never automatically change what screen contents a capture source taps into because we're making up user intent where there might not be any.

**Comment by Developer-Ecosystem-Engineering** [comment]
If you perform an Application Capture instead of a Window Capture, the behavior should match your expectations.

**Comment by mishakim** [comment]
The problem with application capture in this context s that it also captures the presenter control window. Additionally, the source rendered in OBS is the size of the entire desktop, though only the selected app's windows are shown within that (that actually seems like a bug, I can report it separately if it is), so it has to be cropped, and any change in window position disrupts that.
