### ISSUE TITLE
100% repeatable - scene/group layout breaks down, absolute weirdness

### ISSUE THREAD

**Issue by desirepl** [obsproject/obs-studio#8400]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

-

### Expected Behavior

Positions/dimensions/sizes/anchor points must be stable, predictable and as specified.

### Current Behavior

Totally unpredictable/weird behavior.
More group elements - more weirdness and (almost) unfixable.

### Steps to Reproduce

1. Start new project.
2. Add a scene.
3. Add text layer (for example, "Text (Pango)" element), write something, Press "Ok".
4. Press Ctrl-E, left position/rotate as is, change size (for ex) to 918x33, alignment - as is. Close.
5. Move this text layer to the group.
6. Add "Background color" element > dimensions 1600x39. Press "Ok".
7. Move this bg layer to the group.
8. Check sizes/positions of Text and BG with Ctrl-E. Currently they are probably Ok.
9. Now select a group and press Ctrl-E. Change alignment position from Top-Left to Center. At this point we see strange behavior (*element* center is moved to Top-Left of the scene (?)), ok, maybe it is as it must be. Supposably.
10. For example, we have a 1920x1080 monitor where OBS is opened. We need to move group to the center, ok, divide monitor dimensions by 2 and write "960" and "540" as position of our group. Visually it is almost Ok, moved to center [but margins are wrong - left/right is 160px, but top/bottom 521/519 - *NOT EQUAL*]. Press Close.
11. Now select our Text element and press Ctrl-E. Now all is Ok, as we think - positions are 0/0, size 918x33, Top-Left. Let's change alignment position to *Center*.
12. Text element center is moved to Top-Left corner of our group. Same behavior as in step 9.
13. But look at POSITION - 459/16. What??? And Look at margin markers - total trash - 730x271, 532/514, lines painted *somewhere*. Hmm. Not the last.
14. Now... TRY to change position. For example, to 0/0. Can you do this? TRY AGAIN. No? Element is jumping but numbers are left as it is - 459/16.
15. Ok, Let's try enter number "9" (we want to enter 960, but stop after first number - cursor is moved to second position, but number "9" is not written).
16. Now press "6".... what numbers in position now? It is totally unpredictable - each pressing moves element somewhere and entering any numbers will lead to something.
17. Press "Close".
18. Now select group and press Ctrl-E. What do you see in position/size inputs?
19. Select "background color" element inside our group.
20. Change alignment position to *Center*. Play with positions number like before. Close.
21. Repeat step 18.
22. Let's try to fix it. Enter position 960/540 (we are editing group options, remember?). Fix the size: enter 1600x39.
23. Look at the composition. Where we see and how we see text/bg layers?.
24. Select any of the group elements, press Ctrl-E and look at numbers.
25. Want more maidness? Add more elements and repeat.
26. Try to move any element a few pixels lower/right when alignment position at default Top-Left. For example, move to position 2/2. 2 pixels right, 2 pixels bottom. Play with center alignment at other elements and change size/position of them.
27. There will be a total madness. Numbers will change to thousands, minus, any number after the comma etc. And changing parameters of one element in group will lead to changing parameters of all elements inside a group and a group at one time.
28. Finally, let's try to... UNDO this with Ctrl-Z.

https://user-images.githubusercontent.com/18093731/222780498-a892d750-8cdd-4bd4-bf80-fbf117447529.mp4

**Comment by RytoEX** [comment]
Please only report a single issue in a GitHub Issue.

Step 9 is expected. You have changed the origin point of the group from its top left to its center. The group moves to respect its new origin point accordingly.

Step 10 is expected. You have attempted to center a 1600x39 element (the group) in a 1920x1080 canvas at coordinates (960, 540). The width of the element is 1600px. Centered at an X coordinate of 960, it must take up 800px to either side.
| 160px | 1600px | 160px | = 1920px

The height of the element (the group) is 39px due to the height of the color source (39px). Centered at Y coordinate 540, the element does not have an even distribution of pixels to either side due to its odd number of pixels in height.
---
521px
---
39px
---
520px
---
This sums to 1080px, exactly the height of the canvas.

With an odd number of pixels for height, one of the margins between the canvas edges _must_ be odd.

Step 13, while unexpected, I think is by design. I suspect this is because groups try to automatically resize to contain all of its elements. When you ask the text source to change its alignment to "Center", it moves accordingly to honor its new origin point (as with Step 9). However, _then_ the group resizes itself to fully contain the whole text source, which is why the coordinates for the text source are now (459, 16). This is to accommodate the text source's size of 918x33 (918/2 = 459; 33/2 ~= 16). The position/spacing helpers (the graphical lines with pixel margin numbers) are incorrect here, and I suspect that is because of the combination of the item being inside a group (which has its own coordinate plane) and using a Center origin instead of Top Left. This last part could be considered a bug, but everything else up to this point is by design or expected.

Step 14, again, while unexpected, is by design. You are trying to move an item with a Center origin to the (0, 0) coordinate of a group, which will try to expand to accommodate all of its child items, which will change the coordinate of the child item's origin because you have asked to place it outside of the groups original bounding box.

Steps 15 and 16 is the same as Steps 13 and 14.

Step 18:
Position: (506, 533)
Size: 2509x55
This is caused by the group resizing behavior I mentioned above.

Steps 19-21 are going to exhibit the same behavior I mentioned above.

At this point, I'll admit that I skipped Steps 22-27, because they appear to be describing more of the same: moving group child items in such a way that places them outside the current boundaries of the group results in the group resizing itself to accommodate the new position, which subsequently changes the coordinates of the child item according to the group's coordinate plane.

Step 28, I was able to undo back to Step 8.

The video and the Steps To Reproduce do not match, which was very confusing for me until I realized that they were not identical.

Finally, please always provide a log file when opening GitHub Issues.

**Comment by desirepl** [comment]
@RytoEX, video is for example that ANY actions will lead to something wrong.
If you think that when I'm trying to enter (0, 0) is wrong - try to enter ANY number you think will be correct. You will fail.

**Comment by RytoEX** [comment]
> If you think that when I'm trying to enter (0, 0) is wrong - try to enter ANY number you think will be correct. You will fail.

That is because OBS automatically tries to update the position as you type it. So a single digit will make it think that you are trying to reposition the element to, for example, X coordinate 9, which will result in the group resizing behavior that I described above.

You can see this occur if you move an item _slightly_ outside of the group bounding box, and then try to move it back in one pixel at a time. The group size will shrink to accommodate until the item is back inside the group's bounding box, and then the position coordinates will change as normal.

> PS: How to really lock group dimensions? I didn't see any chance of this. Tried a lot of things.

You can lock the scene items by activating the lock icon in the Sources Dock. However, this will not lock changes in the Transform dialog. It is only to lock changes in the UI to prevent users from accidentally making changes by clicking on the OBS UI.

> PPS: Why the "origin point" is the element point but not parent?

As mentioned earlier, groups have their own coordinate planes, with their own (0, 0) origin, and all child items are positioned relative to _that_ origin. At their core, groups are scenes, and scenes have their own (0, 0) origin.

The best way to handle positioning items in groups is to ungroup them, reposition the items, and then group them.

**Comment by desirepl** [comment]
And you think all this is Ok? Really?
My last questions still unanswered. Your answers is equivalent to no answers. All this I tried and it's totally unusable current way.
How to enter needed numbers? No ways.
How to lock group dimensions? No ways.
How to position elements relative to parent? Ungroup-group etc? No way. It will break at any step if user change anything step away from "happy path" (easy speaking - there is no happy path).

**Comment by Fenrirthviti** [comment]
While I agree that there is room for improvement in how groups function, everything is currently working as designed. Unfortunately, a misunderstanding on how something is designed does not make this a bug.

Since this is not a bug, please use the [ideas page](https://ideas.obsproject.com) for suggestions on how it may be improved, or our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further support assistance.

Thanks!
