### ISSUE TITLE
fedora 37 wayland error when record 4k 60fps

### ISSUE THREAD

**Issue by hawk0w1** [obsproject/obs-studio#8416]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/vatGbt4mx1cUfn2h

### Expected Behavior

Record 4k 60fps video

### Current Behavior

error with windows : Nvidia nvenc h.264(ffmpeg) take too long time 
then the recording is stop

### Steps to Reproduce

1. set  video record cofig to high quality 
2. set video config to 3840x2160 and 60fps
3.recording
...

### Anything else we should know?

CPU: AMD Ryzen 9 5950X 16-Core @ 32x 3.4GHz
GPU: NVIDIA GeForce RTX 3090/PCIe/SSE2

NVIDIA driver version : 525.89.02 
OBS version : 28.1.2

OS : fedora 37 with wayland

other: when set to 30fps , it works well

**Comment by hawk0w1** [comment]
and the screen display fps is 144

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a note, you are on an old version of OBS. I would recommend upgrading first.

Thank you!

**Comment by hawk0w1** [comment]
@Fenrirthviti it seems to be a bug ,not a support ,because the window have provide 60 fps option .
and you close the issue in 2min, have you read the log totally?

**Comment by hawk0w1** [comment]
@Fenrirthviti and i would to say that , please tell me how to upgrade to new version with fedora ? there is no document and package download link
