### ISSUE TITLE
Push-To-Talk with mouse4 or 5 not working again under Archlinux

### ISSUE THREAD

**Issue by egrain** [obsproject/obs-studio#8517]
### Operating System Info

Other

### Other OS

Archlinux (freshly updated and rebooted)

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

29.0.2-2

### OBS Studio Log URL

https://obsproject.com/logs/ECM5rJnYiWzs7r0F

### Expected Behavior

Push to talk with mouse4 and 5 to work.

### Current Behavior

Same behavior that quickishfm described it here:  Push-to-talk no longer functions correctly #4843
Looking at the sound bar when I press the PTT button, it goes high for almost a tenth of a second then quickly fades to zero, even when still pressed.

### Steps to Reproduce

1. Enable push to talk for your recording device in settings/audio/hotkeys (at the bottom)
2. Bind mouse4 to push to talk in settings/hotkeys under Mic/Aux
3. (press + on the right next to where you put in mouse4 so you can set mouse5 as a ptt hotkey has well)
4. In the main windows where you can see the mic gauge press mouse 4 (or 5). 
...

### Anything else we should know?

Archlinux, Xorg, Pipewire.
I had this issue with 27 I think as well, everything worked fine in 28. Then I updated to 29.0.2-2 (arch package) and now push to talk on mouse4 and 5 buttons stopped working.
If I set keyboard hotkey it works fine. Mouse4 and 5 are recognized when I set up the hotkeys.
Both mouse buttons work fine in Mumble.

**Comment by kkartaltepe** [comment]
It still works for me on multiple surfaces, on X11 it seems it does not work outside the window or when the mouse is over certain qt elements like a source/scene. Which iirc is how it was previously "broken".

**Comment by egrain** [comment]
Tried it on all kinds of windows. Background, foreground, obs window, browser, panel, desktop even. Switched scene where I only have camera and no desktop elements, also nothing.

**Comment by kaythomas0** [comment]
This same bug is happening to me on Gentoo

**Comment by egrain** [comment]
Bug persists. I'm now on Arch extra/obs-studio 31.0.0-4.

**Comment by SeanRamey** [comment]
This is still a problem. EXACT same thing is happening to me. EndeavourOS obs-studio 31.0.3-1 arch linux extra repo. @jp9000 Can we re-open this? It's definitely not fixed. I think it's important to note that something DOES work to recognize mouse inputs, but the push to talk only turns on for a fraction of a second. The issue seems to be that the input is thrown away practically immediately or something similar.

Another interesting issue is that mouse buttons 4 and 5 aren't recognizing my presses when I use them for toggling on/off a source visibility. However, mouse button 3 works just fine.

EDIT: Just did some testing, and this bug becomes an issue on obs-studio 27.0.0, but works perfectly on obs-studio 26.1.2

Also, just a note: This is also an issue with the official Flatpak build.
