### ISSUE TITLE
How does the 'IAudioRenderClient render' work without calling 'Start()' in 'plugins/win-wasapi/win-wasapi.cpp#L843'

### ISSUE THREAD

**Issue by ffiirree** [obsproject/obs-studio#8525]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/blob/master/plugins/win-wasapi/win-wasapi.cpp#L843

### Expected Behavior

What the ClearBuffer function does is:

> Silent loopback fix. Prevents audio stream from stopping and  messing up timestamps and other weird glitches during silence by playing a silent sample all over again.

and it should play a silent sample all over again.

### Current Behavior

Without calling `client->Start()` , it does not play a silent sample.
But if I have called the `client->Start()`, it has the expected behavior.

### Steps to Reproduce

I tested this module separately

### Anything else we should know?

If I'm missing something, please let me know.

**Comment by gxalpha** [comment]
If you have code changes for OBS, please open a Pull Request instead of an issue. Make sure to describe the bug it's fixing there.
Feel free to join our [discord server](https://obsproject.com/discord) and ask in the `#development` channel if you have further questions on how to contribute to OBS, how to create PRs, etc.
