### ISSUE TITLE
29.1 Beta - Bundled libraries missing versioned symlink

### ISSUE THREAD

**Issue by aramg** [obsproject/obs-studio#8698]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.0-beta3

### OBS Studio Log URL

n/a

### Expected Behavior

The app bundle contains the versioned names of all libraries, for example:
```
$ pwd
/Volumes/OBS-28.1.2-macOS-Intel/OBS.app/Contents/Frameworks

$ ls -l libavcodec.* 
 libavcodec.59.18.100.dylib
 libavcodec.59.dylib -> libavcodec.59.18.100.dylib
 libavcodec.dylib -> libavcodec.59.18.100.dylib

$ ls -l libobs.0.dylib
 libobs.0.dylib -> libobs.framework/Versions/Current/libobs
```

### Current Behavior

The versioned names are missing, breaking dependencies for plugins.

```
$ pwd
/Volumes/obs-studio-29.1.0-beta3-macos-x86_64/OBS.app/Contents/Frameworks

$ ls -l libavcodec*
  libavcodec.dylib

$ ls -l libobs.0.dylib
ls: libobs.0.dylib: No such file or directory
```

### Steps to Reproduce

1. Mount the dmg file and list the OBS.app/Contents/Frameworks directory

**Comment by PatTheMav** [comment]
That is intended - plugins should not link to `libobs` dynamic library version but use the Framework instead - we introduced the Framework several versions ago and we need to cut the cord (any plugin supporting Apple Silicon needs to use the Framework anyway).

Linking against other libraries in the application bundle besides Qt is also not officially supported, so it's up to plugin authors to keep up with changes to them.

Especially FFmpeg would have broken with the new version regardless, as we've updated to FFmpeg 6 and the named library versions would have changed to `libavcodec.60.dylib`.

**Comment by aramg** [comment]
The Framework approach adds overhead (I am not even sure what they are, and how they work), whereas linking against the libs is straightforward and consistent with *nix systems. It's been working just fine so far, including on Apple Silicone.

Supporting newer libavcodec.X is less of an issue, and is just a matter of re-building against new OBS releases. 
It's the same e.g. on Windows where avcodec-60.dll is shipped in the latest update, and requires users to also update plugins that may depend on it.

Just my 2 cents, keeping the versioned libs in the bundle makes it easier to support macOS for plugin devs (less restrictive), imo; rather than forcing them to dive into Apple-specific Frameworks.  
Are there any technical/security/etc reasons for removing these? Because obs-deps still include all the versioned symlinks as before.

**Comment by PatTheMav** [comment]
The main reason is consistency with the macOS platform - macOS is not Linux and while POSIX/Linux things kinda work, the environment has actually different standards and requirements (e.g. version information is contained within Framework/library metadata, so named filenames are not needed).

Frameworks are the canonical way to package libraries with their headers and additional data, as are bundles. CMake will work with frameworks just like with libraries on macOS and the linker supports the as well.

Moving forward we want the macOS version to be more compliant with the OS, as we need and want to implement more macOS functionality.

**Comment by aramg** [comment]
Fair enough, but as things are the ffmpeg libs are neither versioned nor frameworked. 

Unless I'm missing something, this opens the door for potential crashes in the future if any plugins are linking against the generic `libavcodec.dylib`, or?  Does the major version number in the rpath get respected, eg:
`@rpath/libavcodec.dylib (compatibility version 60.0.0, current version 60.3.100)`

**Comment by PatTheMav** [comment]
If your plugin links against an incompatible version of `libavcodec` it will just abort loading your plugin. Plugins are not linked at compile time but loaded at runtime, so the dynamic library loader will log an error about not being able to resolve the requested library, but OBS will just skip your plugin then.

The compat version is ignored by `dyld` for any library targeting Mac OSX 10.14 or newer, so only the "current version" in the MACHO headers is compared. The version number in the file name has no bearing on this (`dyld` doesn't do any version checks on the file name) - the version number in the MACHO header of the _provided_ library needs to be greater or equal to the version number in the MACHO header of the library you used for linking.

The very first line of `otool -L` output shows the `id` of a library that contains that version information:

```
build_arm64/UI/Debug/OBS.app/Contents/Frameworks/libavcodec.dylib:
	@rpath/libavcodec.dylib (compatibility version 60.0.0, current version 60.3.100)
```

With the binary requesting `@rpath/libavcodec.dylib (compatibility version 60.0.0, current version 60.3.100)`, `dyld` will find a matching library version.

---

Do note that we make no guarantees about library compatibility apart from `libobs` and `obs-frontend-api`. If you use any of the other libraries shipped with the App, you're in unsupported territory and responsible for ensuring that your plugin doesn't crash OBS. The libraries are not available "for public use" - the only reason FFmpeg's libraries are retained as dynamic libraries is because they're actually shared between OBS modules, otherwise we'd prefer static linking (we've switched several other libraries to be statically linked already).

**Comment by aramg** [comment]
> With the binary requesting @rpath/libavcodec.dylib (compatibility version 60.0.0, current version 60.3.100), dyld will find a matching library version.

Sure, and the question and the potential issue here is that if libavcodec goes up to version 61.x.x, the plugin will still get loaded, no?
Which would eventually cause instability because that's a major version bump.

```
build/foo.so:
	@rpath/libavcodec.dylib (compatibility version 60.0.0, current version 60.3.100)
``` 

 versus 
```
build/foo.so:
	@rpath/libavcodec.60.dylib (compatibility ... )
```

In the second case, then the plugin will not get loaded, as you described, and simply be ignored by OBS.
And in the first case version 61+ is still compatible? Let me know if I'm mistaken here, but that's what it looks like on surface.

---

> Do note that we make no guarantees about library compatibility apart from libobs and obs-frontend-api. If you use any of the other libraries shipped with the App, you're in unsupported territory and responsible for ensuring that your plugin doesn't crash OBS.

If this is the official OBS Project stance, I would argue the whole plugins ecosystem is then under question.
* The majority of plugins link against Qt, are you also not guaranteeing Qt compatibility / not available for public use?
* Considering OBS is all about audio & video processing, making FFmpeg not available for public use also doesn't make sense. I don't see why plugins should not be allowed to extend functionality by leveraging libavcodec.

In practice, this list is already libobs, obs-frontend-api, Qt, libav*.

---
I would also note that everything has worked just fine up until now, simply by having the version name/symlink to all libs.
Everything still works just fine on other OSs.

I understand that the .framework structure on macOS includes version information inside, but again since libavcodec is not frameworked, as things stand it looks prone to failure.

**Comment by PatTheMav** [comment]
If OBS ships with `libavcodec` version 61 and your plugin requires version 60, it will be loaded (because required version is lower than available version). It's common in macOS to deprecate old APIs and introduce new ones instead of breaking the old ones (before they get removed entirely). If FFmpeg breaks this contract, we have to update our own code and plugin authors relying on it have to do the same.

So _if_ you use a 3rd party library shipped with OBS, you have to put in the same amount of care and maintenance to keep your plugin working with these libraries as we do for the main application. And as we're not in control of what Qt or FFmpeg do, we can't guarantee that plugins using them will continue to do so if we upgrade our libraries. It's by no means prohibited, but it's your responsibility to keep up with our internal changes then.

It should also be noted that macOS evolves quicker and more regularly than either Windows or Linux: New APIs are introduced as regularly as old APIs are deprecated or removed, with new APIs often requiring apps to be more compliant with Apples rules to work, and a new version of macOS releases every autumn.

This specific change was required to make our app more compatible with how Xcode works, which was required to make use of a Camera Extension (which we need to provide virtual camera functionality in macOS 14 and beyond). 

It's my hope that we're about to reach the point where the internal bundle design is stabilised (e.g. the names of the shipped libraries _should_ not change for the most part), but then again it's "internal" for a reason.

**Comment by RytoEX** [comment]
> The majority of plugins link against Qt, are you also not guaranteeing Qt compatibility / not available for public use?

This is not my understanding from the last time I surveyed plugins, and many that did link against Qt had no reason to do so (they didn't actually call Qt code). I would strongly recommend that any plugin authors who do link against Qt re-examine why they are doing so and avoid it if at all possible.

We make no specific guarantees about Qt compatibility. Qt (generally) makes compatibility guarantees between minor releases but not major releases. Plugin authors who want to link against Qt must abide by those constraints, such as when we updated from Qt 5 to Qt 6 for OBS Studio 28.

> Considering OBS is all about audio & video processing, making FFmpeg not available for public use also doesn't make sense. I don't see why plugins should not be allowed to extend functionality by leveraging libavcodec.

Plugins leveraging any shared libraries we happen to ship do so at their own risk. We make no guarantees that those versions will not change or that we will continue to ship them in perpetuity.

----

As @PatTheMav has said, these changes to our application bundle and dependencies were done in pursuit of continuing to provide virtual camera functionality on macOS. With macOS 14 (expected out this year), the current virtual camera implementation (a DAL plugin) will be blocked by macOS from working and we *must* use a Camera Extension (Core Media IO Camera Extension / CMIO Camera Extension) or we lose virtual camera functionality.

**Comment by aramg** [comment]
OK, closing this as wont fix from the sounds of it. 
If this change was required for the virtual cam, then yes, I don't see how we can work around it.

>So if you use a 3rd party library shipped with OBS, you have to put in the same amount of care and maintenance to keep your plugin working with these libraries as we do for the main application. And as we're not in control of what Qt or FFmpeg do, we can't guarantee that plugins using them will continue to do so if we upgrade our libraries. It's by no means prohibited, but it's your responsibility to keep up with our internal changes then.

100% this, and I personally am happy to do so. But since there isn't yet a plugin manager, this path forward may lead to some crashes. I suppose a runtime version check, if possible, would be another way to guard against breakage.
