### ISSUE TITLE
obs recording -> outputting rawvideo to udp:// , cannot set colour space.

### ISSUE THREAD

**Issue by nixinator** [obsproject/obs-studio#8848]
### Operating System Info

Other

### Other OS

Nixos

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/69WOMBVUCG2kUBKf

### Expected Behavior

trying to get rawvideo output via recording.

*This however may not be support*

I'm having trouble setting the pixel format.

 I've searched and not found any clues and how to properly set it, so quite possible it's me!! 

### Current Behavior

![image](https://user-images.githubusercontent.com/66913205/235964071-83121d90-1155-4f42-9969-17c03e286cb9.png)

### Steps to Reproduce

1. set up recording for rawvideo to a url udp://127.0.0.1:6969 
2. ffplay -f rawvideo -videosize 1280x1080 -i udp://127.0.0.1:6969

i've tried a specifying the pixel format in ffplay, but not luck. I've also tried to set the pixel format in recording tab of obs, but i'm not sure i'm doing that correctly.
...

This seems to happen a few version of obs. 

### Anything else we should know?

OBS is great! 

I have a workaround where i can just use v42loopback, which i've compiled from source and is work well.

But rawvideo to a local udp port would be very useful!

**Comment by RytoEX** [comment]
I'm fairly certain we fixed this in #8374. Please test against OBS Studio 29.1.0 (or newer). We do not accept bug reports for older versions of OBS.

**Comment by derrod** [comment]
This isn't really supported, FFmpeg output is basically "you're on your own territory", and we generally do not accept issues for it.

Since you're trying to send raw video over UDP, without any signaling that would describe to the receiver what format it is as far as I can tell, you'd have to manually set the correct one. But we can't really help you with that. There may be better options for whatever you're trying to do here (e.g. virtualcam or various plugins), though I can't make any direct recommendation for Linux.

**Comment by nixinator** [comment]
Yep , I ended up v4l2loopback driver, and using that as a source to encode from. Raw video is not supported... that the great thing about OBS, it's lets you choose all sorts of combinations of transports and encoders that have no possible way of working with each other... FTW!.
