### ISSUE TITLE
SRT Streaming not working like (Ip/Domain)

### ISSUE THREAD

**Issue by PanterSoft** [obsproject/obs-studio#8876]
### Operating System Info

Other

### Other OS

Works on kind of on macOS but not on Ubuntu

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/MSzUTxWG1bcgbKBc

### Expected Behavior

When click streaming stream should connect and start streaming. => Image displayed on other side of Connection

### Current Behavior

When click streaming => bottom right corner green stream indicator and after 2 Seconds there is an popup saying Connection Lost try reconnecting. => No Image displayed on other side of Connection

### Steps to Reproduce

srt://GLOBAL_IP_ADRESS:9999?streamid=srt%3A%2F%2FMY_DOMAIN%3A9999%2Fapp%2Fstream => Works on MacOS but not on Ubuntu 20.04

srt://MY_DOMAIN:9999?streamid=srt%3A%2F%2FMY_DOMAIN%3A9999%2Fapp%2Fstream => Works neither on MacOS or on Ubuntu 20.04

1. OvenMediaEngine (Tested works fine)
2. Domain which resolves to OvenMediaEngine

**Comment by tytan652** [comment]
SRT is not available on Ubuntu 20.04.

**Comment by PanterSoft** [comment]
But Why is it not possible to use a Domain on macOS either ?

**Comment by tytan652** [comment]
For the macOS part, this sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

And in future, don't create one issue for two issues.

Thank you!
