### ISSUE TITLE
macOS Screen Capture stops working after waking from sleep

### ISSUE THREAD

**Issue by JacksonChen666** [obsproject/obs-studio#8928]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/6rGLVnQlA1EhExs7

### Expected Behavior

macOS Screen Capture continues to work (capture) after waking from sleep.

### Current Behavior

macOS Screen Capture freezes after waking from sleep.

### Steps to Reproduce

1. Open OBS
2. Have a macOS Screen Capture source (Add if necessary)
3. (Optional) Start recording
4. Close lid (or go to sleep)
5. Open lid (wake from sleep)
6. Experience the issue

### Anything else we should know?

- 100% reproduction chance
- *Only* macOS Screen Capture seems to stop working (freeze).
- This issue can be fixed by the end-user by restarting OBS Studio, or by switching to another scene collection and back (likely restarting the macOS Screen Capture source).

**Comment by gxalpha** [comment]
We added a "Restart Capture" button to the properties of the source in OBS 30.0 that should be enabled when certain stoppages of capture (computer goes to sleep, user stops capture via menu bar in macOS 14) are detected. Could you try if that button is enabled when the computer wakes up again, and if pressing it fixes the problem?

**Comment by mattymatty** [comment]
same issues happens to me

**Comment by RytoEX** [comment]
The Apple sample app does the same thing as OBS here, so this seems like intended behavior for ScreenCaptureKit. Closing as such.

**Comment by baardbi** [comment]
This has happened to me several times now. If I do some recording of webcam and macOS screen capture for a little while, it works fine. Then I stop the recording and go to lunch (leaving the OBS application open). Then I come back and start recording again, and when I'm done I see that (in the recorded video) only the webcam recording is shown in front of my desktop wallpaper. None of the applications (or mouse pointer, app windows etc.) I use during the recording is shown in the finished video. Just me in front of the desktop wallpaper. If I close the OBS recording before going to lunch and open it when I come back and start recording, it work just fine. The problem is that I sometimes forget to do that, and it's super frustrating when I have recorded an hour of a tutorial video for something.

**Comment by thefrostypixel** [comment]
I don't understand why this has been closed. It's really annoying to have to manually go to OBS, right click the screen recording, select properties and press Restart Capture every time my mac wakes back up, and I don't see any reason for it being that way. Just because an Apple app does it this way that doesn't mean it's convenient or logical in any way.

**Comment by rafalsk** [comment]
also I do not understand, we are using OBS like a lot (gridnet.org) and this behaviour of OBS is real pain the ass on mac OS.

Basically all our scripts get broken after single session. Mac OS goes to sleep - everything broken all over again.

**Comment by lauhub** [comment]
I have the same problem and it is really a pain...

If it is possible to put a button to "Restart capture", why OBS couldn't be able to restart it automatically, without human action ?

At least an option should be available to allow this. And capture should be restarted automatically when resuming recording or streaming, or starting a new one.

Should we create a new issue for this ?

**Comment by RytoEX** [comment]
> Should we create a new issue for this ?

No. GitHub Issues are not feature requests, they are for bug reports. A request to add an option or to change OBS behavior from in the manner described above is a feature request.

> If it is possible to put a button to "Restart capture", why OBS couldn't be able to restart it automatically, without human action ?

See [this comment](https://github.com/obsproject/obs-studio/pull/9107#issuecomment-1597390076) on the PR that introduced the button:
> > Is there anything that prevents us from just restarting the capture without the user having to manually do it?
> Yes, the fact that the user explicitly chose to stop the capture.
> I guess for the other failures (sleep etc) that could be an option.

The challenge then becomes how to make sure we never accidentally re-enable capture when the user has explicitly chosen to stop the capture. I do not know if there is even a way to tell the difference programmatically. We had, and still have, little to no interest in trying to be "smart" when consent/permissions were involved in this case.

The fact that the Apple sample app does the same thing as OBS here indicates to us that ScreenCaptureKit does not by itself support resuming an active capture session that is interrupted by system sleep, so our implementation is "working as designed". Generally speaking, we consider the system changing power states while OBS is running to be disruptive and not something we're super interested in working around. Quitting OBS before putting your system to sleep is the best way to avoid unexpected behavior.

**Comment by TUTOUNITYFR** [comment]
This issue is still relevant, happened to me today.

macOS 15.1.0
CPU Architecture: arm64

**Comment by yayuanli** [comment]
I wrote a script to detect the frozen resource and restart capture automatically: https://github.com/yayuanli/OBS_Restart_Capture_Stuck_Source

Hope it helps :)

**Comment by huevos-y-bacon** [comment]
> I wrote a script to detect the frozen resource and restart capture automatically: https://github.com/yayuanli/OBS_Restart_Capture_Stuck_Source
> 
> Hope it helps :)

I've taken yayuanli's and rejigged it to suit my purposes - in case it's useful to someone else.  https://github.com/huevos-y-bacon/obs_capture_freeze_monitor

**Comment by filipedeschamps** [comment]
> The challenge then becomes how to make sure we never accidentally re-enable capture when the user has explicitly chosen to stop the capture. I do not know if there is even a way to tell the difference programmatically. We had, and still have, little to no interest in trying to be "smart" when consent/permissions were involved in this case.

First of all, thank you for clarifying the details of this behavior.

But instead of adding a button, wouldn’t it make more sense to add a toggle that enables or disables the _"smart"_ behavior of restarting screen capture, with a clear warning about the potential risks?

Given the **huge number of complaints** across the internet about this behavior, it really feels like a bug or at least a poor default, one that prioritizes covering edge cases.

I’d suggest implementing the toggle and revisiting the decision only if people start complaining that the current behavior is gone.

**Comment by Apethesis** [comment]
> > I wrote a script to detect the frozen resource and restart capture automatically: https://github.com/yayuanli/OBS_Restart_Capture_Stuck_Source
> > Hope it helps :)
> 
> I've taken yayuanli's and rejigged it to suit my purposes - in case it's useful to someone else. https://github.com/huevos-y-bacon/obs_capture_freeze_monitor

How is yours different from theirs? I can barely tell-

**Comment by LucaL1fe** [comment]
Made a obs lua script fixing this: https://github.com/LucaL1fe/obs-capture-restarter
