### ISSUE TITLE
Choppy playback when remuxed

### ISSUE THREAD

**Issue by alexgillon** [obsproject/obs-studio#8970]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/OFBtJY0dxtwOl2cp

### Expected Behavior

I've been using OBS Studio for some time to stream, record and remux with.

### Current Behavior

Since updating to OBS Studio 29.1.1, my remuxed MP4s have resulted in a lower fps than the original MKV, leading to choppy playback. I've tried remuxing with different software and gotten the same results, leading me to believe there's an issue with the original MKV.

To cut a long story with lots of bug hunting, I believe that Lavf60 has some sort of issue when recording to MKV and playing a Webm at the same time. The reason is, my steps to recreate the issue work every single time in OBS Studio 29.1.1, but never in 29.0.2. According to MediaInfo, the ONLY difference between these files is the use of Lavf60.

You can find both of the files, one working and one broken, here: https://drive.google.com/drive/folders/1-C0AStGVwQmWl8SPhSkJ_5NJTiB-DGIq?usp=sharing

### Steps to Reproduce

1. Start with a scene with a looping webm file in it
2. Start recording
3. Switch to a blank scene
4. Stop recording
5. The resulting file will remux to lower than 60fps

**Comment by RytoEX** [comment]
Please try to reproduce this in 29.1.2 (or newer) with a simple, nearly empty scene collection. Please create a new scene collection and add just the webm file as a Media Source (or some other single test source) to the scene.

How are you checking that the FPS is lower? Where is playback of the remuxed file choppy (in a media player, media editor)?

What tool did you use to remux these files? Was it remuxed in an older version of OBS? The Lavf version of "file with fps issues when remuxed.mp4" does not match "file with fps issues when remuxed.mkv".

Can you also try to reproduce this with x264 instead of NVENC?

**Comment by flaeri** [comment]
Interesting. I spent some time trying to work this out, and have some additional pieces of information.

* Its exclusive to ffmpeg nvenc (does not happen with zeroCopy)
* I believe its related to b_adapt (adaptive b-frame insertion)

The reason I believe this is because it does not happen when using:
Preset p5, p5 + lookahead enabled, p6 with b-frames 0
Happens on preset p6 (lookahead and b-adapt is enabled by default).

I've tried really hard to reproduce the issue with p5+lookahead (and its quite easy to reproduce), but I cannot.

When Inspecting the output of the source mkv + the remuxed mp4, I can see several missing b-frames in the mp4 output (hence the low framerate/stuttering output). There are fewer frames in the mp4.

Example of where this happen (time/pts is refenced in stream/coded order, not display) :

MKV: PBPBPBP, all is well, until frame 56, where we go `BPBBP` (b-adapt changes the amount of b-frames):
Frame 57 (P) will display as 59
Frame 58 (B) will display as 58
Frame 59 (B) will display as 57
Frame 60 (P) will display as 60

Remuxed MP4: PBPBPBP, all is well, until frame 56, which is now changed, we go `BPBPP`:
Frame 57 (P) will display as 58 (this frame as twice the normal duration)
Frame 58 (B) will display as 57
Frame 59 (P) will display as 59
Frame 60 (P) will display as 61

The original B frame (59) from the mkv, has been dropped.

When b-adapt is enabled with ffmpeg nvenc, I suspect the timestamps may become unexpected and handeled incorrectly, resulting in the dropped/missing frames.

OBS log when remuxing a file which has this issue: `media_remux: Error muxing packet: Invalid argument`

I've tried remuxing the same file which has the problems with an old verison of OBS (27.2.4), and the same error message is in the log, and the resulting mp4 has the exact same problem. I don't think this is a new issue with the remux function. I think its more likely that ffmpeg nvenc now works differently, producing this unexpected output.

**Comment by alexgillon** [comment]
Thank you so much for the incredibly detailed reply, I thought I was going insane when I was the only one having issues!! It sounds like a super niche and hard to trace issue, so awesome job figuring all that out.

The one thing I don't understand is why wasn't I getting the issue when I was recording a blank screen, only when there was WebM's in the scene? Did you find the same, or were you able to replicate the issue with a blank scene?

It sounds like you've got a similar conclusion to me though, although I think that's more luck than judgement on my part! The recorded file has the issues, it's not an issue with remuxing itself. Do we know what the solution is? Is it more an issue for the guys at ffmpeg?

**Comment by flaeri** [comment]
There is nothing inherently wrong with your webm file. I did dig at that. I've re-encoded the file 6 different ways, in different resolutions, codecs etc. It does not matter. 

What matters is what it is showing/displaying, and it just so happens that it does the job perfectly of triggering b_adapt to change the number of b-frames (my personal belief/conclusion, not very fact based).

I think I could reproduce this without your file, but it would take a lot of time and guesswork to create the right content to replicate.

**Comment by alexgillon** [comment]
Whatever this incredibly niche issue was seems to be resolved now!

I've just tried both the latest release of OBS and the version that first caused this issue and neither seem to trigger it. I assume this was fixed in a Nvidia driver update.

Are you able to confirm @flaeri so that this ticket can be closed?

**Comment by flaeri** [comment]
Yep, seems fine to me :) Can no longer reproduce
