### ISSUE TITLE
window record returns black screen on hyprland-nvidia after 29.0.2-6

### ISSUE THREAD

**Issue by User10987654321** [obsproject/obs-studio#9084]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2-6(in title)

### OBS Studio Log URL

https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406

### OBS Studio Crash Log URL

https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406

### Expected Behavior

obs recording selected window

### Current Behavior

in 29.1.1-2, because of https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406, the window was recorded as black

### Steps to Reproduce

1.install xdg-desktop-portal-hyprland, hyprland-nvidia-git, and obs-studio on archlinux
2.run obs-studio 29.1.1-2(or any after 29.0.2-6, according to https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406)
3.
...

### Anything else we should know?

https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406

**Comment by Fenrirthviti** [comment]
In the future, please don't just paste the same external issue instead of providing the information directly. Log files from affected session are useful, and just posting the link to an external issue makes it difficult to parse what the current status is.

For anyone looking in to this on our side, speculation from the hyprland issue is that https://github.com/obsproject/obs-studio/commit/584de6b2646320ea46b600b56b01965a87136810 is a possible cause of this.

**Comment by kkartaltepe** [comment]
If the compositor rejects all requests that contain video transform parameters instead of ignoring them, that sounds like a compositor bug to me. Someone from hyprland would need to explain why they reject such requests.

**Comment by gxalpha** [comment]
Closing per the comment above.
Please follow up if you have reasons to believe that this is an OBS bug instead of a compositor bug.
