### ISSUE TITLE
Audio volume should not increase if audio monitoring is on

### ISSUE THREAD

**Issue by GregTonoski** [obsproject/obs-studio#9086]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/OGmVeMP1drxJ2sTb

### Expected Behavior

Volume to remain constant.

### Current Behavior

Volume increases indefinitely (ears can't stand it).

### Steps to Reproduce

1. Plug-in 3.5mm jack from headset to laptop.
2. Set Jack Mic Properties levels to 100% (the issue doesn't occur if the value is different).
3. Open OBS -> Advanced audio properties -> monitor only (or "Monitor and Output").

Listen to the recording (the issue starts around the 11th second when mic. level is changed from 99% to 100% ).

https://github.com/obsproject/obs-studio/assets/111286121/c42ba60e-a758-4403-b472-92d10fb7c43d

**Comment by Penwy** [comment]
Does it also happen if you use a microphone that isn't physically connected to your headset?
What this sounds like is the microphone picking up the audio outputted by the headphones, which naturally creates a feedback loop.

**Comment by prgmitchell** [comment]
This sounds more like a support issue as it is specific to you, I cannot reproduce and am not seeing other report this. Looking at the log, it may just be because you are monitoring to a device you are also recording (your headphones). If you set Desktop Audio to "disabled" and do a test recording, I would guess this may not happen anymore. If that doesn't help you, please head over to the community support [discord](https://discord.com/invite/obsproject) or [forums](https://obsproject.com/forum/) for support.
