### ISSUE TITLE
First User interface is not dispayed.

### ISSUE THREAD

**Issue by bijubjs** [obsproject/obs-studio#9154]
### Operating System Info

macOS 13

### Other OS

Mac OS 13.4.1 ventura

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

obs-studio-29.1.3-macos-x86_64.dmg

### OBS Studio Log URL

N/A

### Expected Behavior

I am expecting to OBS to show user interface after installing and opening the software for the first time.

### Current Behavior

I am not seeing the user interface. Instead, I am seeing screen as attached in the image:
[
<img width="1680" alt="Screenshot 2023-06-25 at 19 20 36" src="https://github.com/obsproject/obs-studio/assets/11329730/97b97b8c-668d-41ad-bc59-eea1e64c2028">
](url)

### Steps to Reproduce

1. Download obs-studio-29.1.3-macos-x86_64.dmg
2. Install in Mac
3. Open installed OBS Studio app.
...

**Comment by Fenrirthviti** [comment]
It looks like you might have had OBS installed previously, and enabled the stats window to show up on launch.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by bijubjs** [comment]
So, how can I solve this problem?
I could not access Discord. and I did not find answer that can solve the problem when I typed "c" and "disable stats window".

**Comment by Fenrirthviti** [comment]
I'd recommend just deleting the cached OBS settings from the previous install of OBS:

In Finder, press Shift-Cmd-G  → `~/Library/Application Support/obs-studio`

And clear everything out of that folder, or just delete it entirely.
