### ISSUE TITLE
Latest update extremely unstable

### ISSUE THREAD

**Issue by Kobi-Blade** [obsproject/obs-studio#9202]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FvJdpiaWY5vWMWElY#logURL

### Expected Behavior

Stable long sessions of streaming like previous versions of OBS.

### Current Behavior

Ever since OBS 29.1.3 after streaming for long periods of time, OBS randomly freezes and crashes with no crash logs.

The behaviour is extremely random, I been able to trigger it while changing sources/scenes.

Sometimes OBS reports no issues at all, yet the preview screen is frozen and the stream itself on Twitch is OFFLINE, making it hard to diagnose.

### Steps to Reproduce

1. Stream for +4h
2. Change between scenes, sources
3. Stream goes offline without warning (while OBS reports is still streaming), or OBS freezes entirely.

### Anything else we should know?

Using OBS 29.1.1 I can stream for over 12h straight with no issues, already rollback as a temporary fix.

**Comment by prgmitchell** [comment]
This sounds more likely to be a support issue, please head over to the [community discord](https://discord.com/invite/obsproject) or the [forums](https://obsproject.com/forum/) if you would like to troubleshoot this problem.

**Comment by prgmitchell** [comment]
> > This sounds more likely to be a support issue, please head over to the [community discord](https://discord.com/invite/obsproject) or the [forums](https://obsproject.com/forum/) if you would like to troubleshoot this problem.
> 
> I'm sorry, but is not a support issue, since I made sure to ask multiple streamers in my community about this, and there more people facing the issue.
> 
> So unless OBS Team is interested in supporting each and everyone one of us (cause I'll link them to support if that is the case), we would really appreciate this bug solved.
> 
> Some streamers have had this issue since the first 29 release and been generally fine since 29.1.3, others like me only started having issue with 29.1.3.
> 
> As stated only happens after long sessions, so is not something small time streamers will run into it.

It does sound like a support issue. There are a lot of different troubleshooting steps to go through and the issues section is not a place where we do this sort of troubleshooting. Feel free to ping me in the discord server and direct any others you know with these kind of issues there as well. My name is Mitchell | Yolo and you will see me listed in the user list sidebar.

**Comment by Fenrirthviti** [comment]
This report doesn't really contain anything actionable for us. The steps to reproduce are basically "hope it happens". Without being able to reliably reproduce the issue, there isn't much for us to look in to. If OBS itself is locking up and not actually crashing, that's usually an indication that there's something external to OBS causing issues or a lock of some kind.

Most commonly, HAGS has been causing a host of issues, including what you're reporting here, and disabling it solves almost all of them. If the issue is with HAGS, there isn't anything we can do as the issue happens inside the GPU driver.

If OBS is frozen, what would help most is a [memory dump of the OBS process](https://obsproject.com/forum/resources/how-to-create-a-dmp-file-for-debugging.598/), provided to one of our support team either on the forums or Discord. Make sure to be careful sharing a memory dump publicly, as it could contain sensitive information about your stream (but only information from OBS)

**Comment by Fenrirthviti** [comment]
As a note, several members of the team have offered to assist with and look at this issue. We don't provide support over github issues, and they are reserved for confirmed, reproducible reports.

If you chose not to follow our processes as we have outlined here, that is very different from us being "not interested". That's on you.

**Comment by Lain-B** [comment]
Hi there, I'm the author. You know, these kind of situations are frustrating, because I know quite well what it's like to be in your position, to where I feel so certain of something that I don't want to go through the typical "go through support first" stuff, and it just brings me frustration. It's like having an issue with your internet connection, and you feel like you're pretty certain what the issue is, but you call your ISP, and they give you the run-around of support, forcing you to check the most basic things and it just drives you up the wall. I completely understand that and sympathize with that.

However, they do make you go through low-level support and have you go through the basic checks for a very good reason. The reason why they do that is because if every single person who had an issue comes around and wants to get the direct attention of an engineer to fix their specific issue, that engineer would never have a single moment of peace because almost everyone wants that same thing: to make sure their issue is taken seriously, and taken care of as soon as possible. But it's just not realistic because all of us, engineers included, only have so much time and are merely human beings.

Having written this program, I now realize fully why that situation occurs, and it's made me come to have a bit of humility for the process of having to go through the lower levels of support when I call my ISP in order to get elevated to the higher levels of support. That's something that I simply wouldn't have understood quite as acutely before I wrote this program.

I would kindly ask you to have patience, and to try to go through whatever processes our support people recommend, because chances are if you have a legitimate issue and you display that to them clearly, they will bring it directly to our attention.

All I would ask is that in the future, you think about these things, and remember that.

Another thing I would like you to keep in mind is that we don't really operate like a company. We're not selling you a product; we're all volunteers. We don't have some service staff operating the phone lines or something. We're a bunch of friends interested in the same thing, trying to make good open source software, working together. I don't know about other projects, but at least with us, if you try to work with us the best you can, we will also do the best to listen to you.

I wish you the best, and hope you have more patience with us in the future.
