### ISSUE TITLE
Dropped frames on recordings in random moments, nothing which could cause it is happening

### ISSUE THREAD

**Issue by Linkyop** [obsproject/obs-studio#9285]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/7lEilXGwNBXhTgU6

### Expected Behavior

Not choppy recording.

### Current Behavior

Since one of OBS update no matter of settings I use, my videos are always in random moments having dropped frames to ~30 despite not having overloaded either CPU or GPU or having lags in game. Sometimes it's entire videos, sometimes it happens in random moments of video just to stay or return to normal just to happen again later.

### Steps to Reproduce

1. Start recording.
2. Stop recording.

### Anything else we should know?

Creating issue here because tips on forum didn't helped at all, and my friends says they are having similiar issues with dropped frames on recording and even streams despite normal FPS of working programs.

Link to thread: https://obsproject.com/forum/threads/random-fps-drops-on-recorded-videos-despite-games-and-programs-running-smoothly.167443/

**Comment by prgmitchell** [comment]
The log you posted shows no frames being lost. Github issues are used to track bugs while this is more likely to be a support issue. If you need help, please continue the discussion on your forum post or join the community [discord](https://discord.com/invite/obsproject) for support.

**Comment by Linkyop** [comment]
@prgmitchell 
> Github issues are used to track bugs while this is more likely to be a support issue.

It is a bug because rolling back to previous version of OBS with same recording setup resolves issue.

**Comment by prgmitchell** [comment]
> @prgmitchell
> 
> > Github issues are used to track bugs while this is more likely to be a support issue.
> 
> It is a bug because rolling back to previous version of OBS with same recording setup resolves issue.

That would be an important detail to include, you didn't mention that in your post here or on the forums. What version specifically?

I looked at the log and see no issues there. I also looked at the video and couldn't notice what you were talking about. Your steps to reproduce are not detailed or specific, if I follow the same steps there is no issue and others are not reporting issues which would point to it being something specific about your setup. That would require troubleshooting which as I mentioned, is not something done on Github issues.

**Comment by Linkyop** [comment]
Problem is gone on version 29.0.2. Steps to reproduce are the exact ones I wrote, there is no errors, no drops in game, no log issues, what I should provide if I'm not doing anything weird while recording? Nothing is overloading, no game affected, tried disabling every Windows Game settings even. Fighting with this a month by now.
Also I'm on laptop, my friend has a PC with completely different setup, settings and we tried same OBS settings and different ones with same result.

It's clearly OBS issue and not setup issue, but alright, will search help somewhere else.

**Comment by prgmitchell** [comment]
> Problem is gone on version 29.0.2. Steps to reproduce are the exact ones I wrote, there is no errors, no drops in game, no log issues, what I should provide if I'm not doing anything weird while recording? Nothing is overloading, no game affected, tried disabling every Windows Game settings even. Fighting with this a month by now. Also I'm on laptop, my friend has a PC with completely different setup, settings and we tried same OBS settings and different ones with same result.
> 
> It's clearly OBS issue and not setup issue, but alright, will search help somewhere else.

I am not saying whether or not there is something that can be looked at within OBS but I am saying that this is not the spot for that type of troubleshooting. That is why I linked you to the appropriate places in my original reply.

**Comment by gxalpha** [comment]
This appears to have been resolved off-thread.

**Comment by Linkyop** [comment]
@gxalpha 
It wasn't resolved at all but whatever. At least I know there is no bug reporting support for OBS.
Downgraded version until someone will actually fix it in future updates.

**Comment by Fenrirthviti** [comment]
I've reviewed the support interaction, and in our analysis we found the results to be exactly the same between the samples provided. This is just how compositing works, and expecting an exact, frame-perfect result every time with any compositing software is going to be virtually impossible. I understand that it is frustrating, and that you feel that there is something that can be fixed, but there really isn't. Unless every single source, game, application, display, etc. is all running at *exactly* to the microsecond 60fps, there will inevitably be SOME desync that happens, and a skipped or missed frame will occur to keep everything from drifting apart.

If you feel that the an older version works better for you, you are welcome to continue to use that version.

**Comment by JoLiKMC** [comment]
> This appears to have been resolved off-thread.

Can you clarify this statement, please?  I would like to see the resolution.  Unless the resolution is "try downgrading", which is not… really a "going forward" kind of fix, or the kind of "fix" a company really should suggest unless they've stopped updating their product altogether.

> This is just how compositing works, and expecting an exact, frame-perfect result every time with any compositing software is going to be virtually impossible.

That… that's not a solution, either.  That's an excuse, no offense.

Yes, I understand that, unless the software you're recording has a built-in video dump feature, there will _always_ be occasional inconsistencies such as dropped frames and the like.  A lot of recording and streaming software will let the user know when something has gone wrong and _OBS Studio_ is no exception.  It has an entire _dock panel_ dedicated to this which _does_ let the user know about dropped frames and the like.  The problem here is that _OBS_ *isn't seeing any dropped frames.*  Instead, it's just going about it's day, acting like these dips go 45 or even 30 frames per second aren't happening, whether streaming or recording.

Now, correct me if I'm wrong, but you're implying that… it's somehow not _OBS_ that's to blame?  You're saying that _OBS_ is working perfectly and that it's the games, many of which are capped at 30 or 60 FPS through some means and run unaffected by _OBS_?  You're honestly telling us that whether it be on high-end computers or budget laptops, it's *absolutely normal* that _OBS_ isn't noticing anything gone wrong since it's 29.1 incarnation, and that with certain programs, it's "perfectly normal" to have these completely unnoticed and unreported drops to 45 or even 30 FPS for periods of time?  Well, that's simply not ideal.  I would be more upset, but rolling back to 29.0.2 does vastly improve the problem.  It's just… you know… not very helpful going forward.

Not to be pushy, especially since this is a free and open source program available to all users across multiple platforms, but this seems like something that should really be looked into and taken seriously.

Thank you,
J

**Comment by Fenrirthviti** [comment]
Feel free to join our Discord if you want to discuss in further detail, there's an entire #encoding-talk channel devoted to this kind of thing.

**Comment by Linkyop** [comment]
@JoLiKMC Thank you for backing this thread up. Something weird ks going on and people are trying to forcefully make us thing this bug is "normal behaviour" where we both are reporting this started with 29.1.

I have never saw a bug being covered up so harshly, even being an open project, and I never saw people trying to tell me that I am wrong.

Will say one more time and will not continue this topic here, because I learnt asking for help here has no sense:

**Issue exists on version 29.1.x. Problem is gone on 29.0.2 and below.**

And if someone reports the same issue and they are being shut down like I am, that's a yellow flag for me.

**Comment by JoLiKMC** [comment]
To be fair, I wasn't exactly "shut down" like you ended up being, but I certainly wasn't getting any kind of useful answers or advice… but as someone affected by this issue, and someone who has _seen_ others affected by this issue, I'm absolutely going to toss my beret in with you on this one.

It's confusing that this bug isn't being addressed on the forums or here on the bug tracker as it should be.  It's affecting who knows how many people, and some of have even provided raw renders as proof of this happening.  Honestly, if someone had said "your hardware's too weak for modern _OBS_" or something similar, I would have been unhappy, but been more accepting of that than the current "rendering is a fickle mistress" reasoning given in this thread.  And unfortunately, that post seems to be the "fallback" answer for lack of better ones, right now.

> Feel free to join our Discord if you want to discuss in further detail, there's an entire #encoding-talk channel devoted to this kind of thing.

@Fenrirthviti Why?  All of the details are in my posts, including my computer specs and render settings.  What's there to discuss…?

**Comment by Fenrirthviti** [comment]
I'm going to reply to a few specific comments, but it is, again, just how the rendering pipeline works. No amount of "I don't like your answer" will change it. This affects any application that is trying to do real-time rendering and compositing, and is an expected result that a small amount of frames are dropped/duplicated.

> I have never saw a bug being covered up so harshly, even being an open project, and I never saw people trying to tell me that I am wrong.

Nobody is "covering up" this. We acknowledge that it's happening. It's been happening since OBS Classic, because it's normal and expected.
 
> Will say one more time and will not continue this topic here, because I learnt asking for help here has no sense:
> 
> **Issue exists on version 29.1.x. Problem is gone on 29.0.2 and below.**

No, it's not. You brough the supposed "good" video to our discord support team, who analyzed it, and found the exact same results in that video. You dismissed them, and said we were mistaken after being provided the evidence. Any version of OBS will show these kinds of inconsistencies, and expecting a frame-perfect reproduction of your captures in the output is an exercise in madness. There were no changes in any of the related areas of OBS that would have any impact on this. If 29.0.2 feels better to you, then by all means continue to use that version. We will never force an update.

> And if someone reports the same issue and they are being shut down like I am, that's a yellow flag for me.

Again, nobody is being "shut down" or ignored here, we all agree the resulting file is not perfect. It is, again, expected, and there isn't really anything anyone can do about it. All sources, from all locations outside OBS, would need to be synced down to the microsecond in terms of framerate in order to avoid this. So, it is practically impossible.

> To be fair, I wasn't exactly "shut down" like you ended up being, but I certainly wasn't getting any kind of useful answers or advice… but as someone affected by this issue, and someone who has _seen_ others affected by this issue, I'm absolutely going to toss my beret in with you on this one.
> 
> It's confusing that this bug isn't being addressed on the forums or here on the bug tracker as it should be. It's affecting who knows how many people, and some of have even provided raw renders as proof of this happening. Honestly, if someone had said "your hardware's too weak for modern _OBS_" or something similar, I would have been unhappy, but been more accepting of that than the current "rendering is a fickle mistress" reasoning given in this thread. And unfortunately, that post seems to be the "fallback" answer for lack of better ones, right now.


"I don't like the answer" is not the same as "not being addressed". Please show us where we have stated that this isn't happening. We acknowledge that it is, and have been trying to explain that it's normal and there's not really anything we can do about it. If you feel that you have a better solution on how to avoid what is ultimate caused by the lack of sync between source inputs being composited, we welcome PRs.

> @Fenrirthviti Why? All of the details are in my posts, including my computer specs and render settings. What's left to discuss…?

Because I have explained this a hundred thousand times over the years, and "I don't like the answer" is, frankly, getting to be a bit annoying. Maybe someone else explaining the same thing will help you understand that there isn't really anything we can do. GitHub issues isn't really the right place to have an in-depth technical discussion on how compositing works.

The rendering pipeline is an *incredibly complex* mechanism, and there's thousands, if not more, of potential points where this kind of thing can be introduced, many of which would be expected. It's a fallacy to assume everything "frame drop" is related, and just because someone got a few frame drops, doesn't mean the issue would be related, which makes separating the *actual* issues from expected outcomes very time consuming, and difficult. In this case, for the *original post* our analysis says that it's not something in OBS or something we can fix. I have no idea if your issue is the same, or if it's unrelated, which is why you should always go through the support channels first so someone can take a look. Unconfirmed or "me too" posts on GitHub are unhelpful at best, and harmful at worst as they muddy the report to what is actually going on.

What do we, as the project, gain by "covering up" this issue and not addressing it? We are an open source project, none of our users are paying to use us, so we gain nothing from leaving issues like this unaddressed. If there was something we could do, we would have already done it.

I will ask, again, that this discussion be moved either to the forums or discord where further in-depth technical analysis (much of which was already provided, and dismissed outright for some reason) can be provided.

**Comment by Linkyop** [comment]
I wanted to answer this, but deleted my entire wall of text now, because I just realized people here cannot be reasoned with.
What a waste of time and nerves.
