### ISSUE TITLE
AMD HW AV1 recorded video cannot be played

### ISSUE THREAD

**Issue by txs1234** [obsproject/obs-studio#9382]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/T9iBiS47Zr5CS3N2

### Expected Behavior

Record video with amd hw av1

### Current Behavior

The video was recorded using amd hw av1, but the recorded video was corrupted and could not be played

### Steps to Reproduce

1.Set encoder to  amd hw av1
2.recording

**Comment by flaeri** [comment]
Could you please upload a sample file that does not work? It only needs to be a few seconds. Should be small enough to be able to upload on github (drag the file in).

**Comment by txs1234** [comment]
https://github.com/obsproject/obs-studio/assets/90123607/2f7d97c8-91d0-42f6-a01b-3db29c66fefc

**Comment by flaeri** [comment]
This is most likely because of the Opus audio codec you've selected. The built in window video players do not like it very much. I would suggest getting a more capable media player (like VLC: https://www.videolan.org/), or changing the audio to aac.

I believe this can be closed, and you can seek further help/assistance on the forums or in the discord like I suggested in the previous message :)
