### ISSUE TITLE
How to debug "Encoding overloaded"?

### ISSUE THREAD

**Issue by tari3x** [obsproject/obs-studio#9395]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/mP6ZBzFIxBGu0uKA

### Expected Behavior

When I see "Encoded overloaded" I would love if there was a way for me to gain some visibility into what is contributing. 

### Current Behavior

There used to be profiler output in version 27-something, but this seems to be gone? 

I asked in [How to debug Encoding overloaded?
](https://obsproject.com/forum/threads/how-to-debug-encoding-overloaded.168625/) but there seems to be some amount of confusion about how to read the profiler output. 

### Steps to Reproduce

None - I don't know how to debug an issue.

**Comment by YorVeX** [comment]
`GPU conversion not available for format: 7`

IIRC this means color space conversions are done by the CPU instead, because you selected BGRA, and your CPU is probably not up for the task (i.e. the extra load from it is too much in total).

The profiler output is still there, but you need to exit OBS first to have it written to the log.

You should really ask these things on Discord, it's easier to discuss it there.

**Comment by Fenrirthviti** [comment]
Please stop opening new issues for support.

**Comment by tari3x** [comment]
@YorVeX : Oh, good point, thanks a lot (would be cool if it said that 7 is RGBA)!

**Comment by tari3x** [comment]
For reference, I made https://github.com/obsproject/obs-studio/issues/9396 which got instantly closed.

**Comment by The1Hound** [comment]
i have the same issue brand new gpu
