### ISSUE TITLE
commit b6b8f5b broke build with -DENABLE_WAYLAND=OFF

### ISSUE THREAD

**Issue by hrzhu** [obsproject/obs-studio#9454]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Git

### OBS Studio Log URL

Compile issue. No log recorded.

### Expected Behavior

Obs successfully compiled.

### Current Behavior

Commit b6b8f5b breaks build with `-DENABLE_WAYLAND=OFF`. Have to enable wayland to make compile succeed after this change.

```
/home/h/src/obs-studio/plugins/obs-qsv11/common_utils_linux.cpp: In function ‘mfxStatus Initialize(mfxVersion, _mfxSession**, mfxFrameAllocator*, void**, bool, bool)’:
/home/h/src/obs-studio/plugins/obs-qsv11/common_utils_linux.cpp:114:46: error: ‘OBS_NIX_PLATFORM_WAYLAND’ was not declared in this scope; did you mean ‘OBS_NIX_PLATFORM_X11_GLX’?
  114 |         } else if (obs_get_nix_platform() == OBS_NIX_PLATFORM_WAYLAND) {
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                              OBS_NIX_PLATFORM_X11_GLX
[ 61%] Building C object libobs-opengl/CMakeFiles/libobs-opengl.dir/gl-zstencil.c.o
make[2]: *** [plugins/obs-qsv11/CMakeFiles/obs-qsv11.dir/build.make:146: plugins/obs-qsv11/CMakeFiles/obs-qsv11.dir/common_utils_linux.cpp.o] Error 1
```

### Steps to Reproduce

1. pull the latest git master
2. compile obs with -DENABLE_WAYLAND=OFF

**Comment by Chiitoo** [comment]
I don't see 867938cd9d5 [1] fixing this, since 'LIBVA_WAYLAND_LIB' is still being searched for in 'cmake/Modules/FindLibva.cmake' [2].

1. https://github.com/obsproject/obs-studio/commit/867938cd9d51e2d790d8ec4f11a523b0294b7562
2. https://github.com/obsproject/obs-studio/commit/b6b8f5b80afc37208485c831bb6cb7928e76de02#diff-a735c4428a3a9eeb5bee39d648e92abb8b210c1d02614b1d103dce96929b6319R53

**Comment by RytoEX** [comment]
See also: #9510
