### ISSUE TITLE
AMF AV1 Does Not Align Video Stream To Container

### ISSUE THREAD

**Issue by Bopler** [obsproject/obs-studio#9515]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/YPBv8Atu14qbDhBT

### Expected Behavior

The video file should match the output canvas resoloution. 

### Current Behavior

Padding is added to match a 64x16 resoloution. Video bitstream remains correct, but container resoloution is mismatched. For example, I record my canvas at 2560x1080, but the output is 2560*1082 with 2 extra lines of padding added at the bottom.

This is the intended behavior when no Align proptery is assigned, as descirbed at https://trac.ffmpeg.org/wiki/Encode/AV1#Align

### Steps to Reproduce

1. Set OBS to record using AMD HW AV1
2. Set canvas resoloution to anything that doesnt align to 64*16
3. Observe that video bitstream reloution does not match container resoloution when viewing properties in a player such as MPV.
...

### Anything else we should know?

Please either automatically populate the align parameter to match the output canvas, or expose the align propety in the encoder settings. This has been an issue since the AMF AV1 encoder was implemented, I just presumed someone else would report it to be honest

**Comment by Fenrirthviti** [comment]
As far as I understand it, this is an issue with the AMD AV1 encoder and there's not much we can do about it.

**Comment by derrod** [comment]
As the documentation you link to explains, there isn't really any way to solve this. AMD's encoder either has to pad the video to the next resolution divisible by 64x16, or to 1082p in the special case of 1080p. The only thing we could do is restrict resolutions to those strictly divisible by 64x16 but that would prevent people from recording 1080p at all.

**Comment by caniko** [comment]
@derrod 

I agree with the hardware part of this explanation. `VCN4` must encode an aligned frame, and preventing `1080p` recording would be worse than accepting the two padded rows. I’m not proposing either of those changes.

What seems to have changed since this was closed in 2023 is the available muxing mitigation. With `FFmpeg 8.1.2`, direct `av1_vaapi` still produces a raw AV1 sequence header with the aligned `1082` height, but the resulting MP4 is reported as the requested `1080` height. The hardware gets its aligned frame while the container preserves the intended dimensions.

`OBS 32.2.1` loses that distinction. On the same system, both `Hybrid MP4` and `Matroska` recordings are reported as `2560×1082`, even though OBS requests and logs `2560×1080`. OBS appears to derive its AV1 metadata from the first encoded hardware packet, which contains the aligned height.

Could this issue track preserving the requested dimensions through container crop/display metadata rather than changing the hardware encoding dimensions? That would avoid rejecting `1080p` while hiding the two implementation-specific padding rows where the container and player support it.
