### ISSUE TITLE
obs_frontend_add_scene_collection not working in lua

### ISSUE THREAD

**Issue by afastication** [obsproject/obs-studio#9561]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/3hSDDODNBvGMUeOd

### Expected Behavior

running this script:

obslua.obs_frontend_add_scene_collection("script-scene-collection")

should create a new scene collection

### Current Behavior

The scene collection is not created, and the script's log prompts:

[scene-collection-creator.lua] Error running file: ...regia/Documents/obs-scripts/scene-collection-creator.lua:1: attempt to call field 'obs_frontend_add_scene_collection' (a nil value)

### Steps to Reproduce

1.create a script containing just the line obslua.obs_frontend_add_scene_collection("script-scene-collection")
2.add the script to obs
3.run the script and check the log
...

### Anything else we should know?

I also tried on 29.1.3 on windows 11. the behaviour does not change.

**Comment by Penwy** [comment]
That function is not included in the scripting API.

I'm not sure how it's not present because looking at the obslua.i, as far as I can see it _should_ be included, but very clearly it isn't.
That being said, it probably shouldn't be used in a script, because scripts are tied to scene collections, meaning the moment you use that function, you'll unload your script too.
Still I'll try to have a look to see why it's not included in the API.

**Comment by gxalpha** [comment]
`obs_frontend_add_scene_collection` is among the functions intentionally not included in scripting, see 66f993d. As noted above, using it would be destructive to the script anyways.
