### ISSUE TITLE
Media sources start playing on OBS startup despite "Restart playback when source becomes active" checkbox being unticked

### ISSUE THREAD

**Issue by Destroy666x** [obsproject/obs-studio#9589]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/H7NbjLvK5PfrjQKO

### Expected Behavior

Media should not play at OBS startup when `Restart playback when source becomes active` is not ticked

### Current Behavior

Media is played at OBS startup.

### Steps to Reproduce

1. Add media source
2. Uncheck `Restart playback when source becomes active`  in properties
3. Restart OBS
4. Media will be playing

### Anything else we should know?

There's also a suggestion here https://ideas.obsproject.com/posts/1957/prevent-media-sources-from-starting-on-obs-startup but it's a bug IMO as the checkbox doesn't do 100% what it says - source wasn't playing when OBS closed and it starts playing when source becomes active again at startup.

It's especially annoying if you have a bunch of media in a scene included in almost all scenes. You can in theory work around it b putting them into a group and then changing visibility  of the group, but it's not a great workaround since you can forget it (unless you automate it with Advanced Scene Switcher) and I'm using groups on these sounds for other purpose.

**Comment by Fenrirthviti** [comment]
This is currently working as expected. The option is doing exactly what it is supposed to, which is provide an option to restart playback (rather than resume) when the source becomes active. It makes no promises that playback does not start.

While I agree that this is probably something we should have a solution for, this is not a bug and the Ideas post is already present for tracking for a new feature request/update.
