### ISSUE TITLE
Screen recording colors are wrong on Wayland (every second screen in preview)

### ISSUE THREAD

**Issue by mylinux4work** [obsproject/obs-studio#9627]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/wJyf2zGdqY2EKh5W

### Expected Behavior

Colors in the screen recording should be the same as the real screen colors.

### Current Behavior

When I record my screen, the colors are wrong. It looks like orange not blueish. But every second screen on the preview looks right. Please see the screenshot attached.
![1695578485_grim](https://github.com/obsproject/obs-studio/assets/145253254/405d9d35-439c-4ac1-b40c-470340bcd709)

### Steps to Reproduce

1. Open OBS
2. Select Pipewire screenrecording
3. Select Fill screen
...

**Comment by kkartaltepe** [comment]
This looks like a bug in your compositor/xdg-desktop-portal-xyz implementation, they are advertising the wrong color format so when we use it the red/blue colors are swapped. If I can find the old script to dump pipewire nodes we can maybe investigate a little bit more, but you are probably better raising this with your compositor.

**Comment by mylinux4work** [comment]
Yes. You were right. Switched from xdg-desktop-portal-hyprland to xdg-desktop-portal-wlr Everything is working again. Thank you.

**Comment by vaxerski** [comment]
@kkartaltepe xdph dev here, the logs from the affected user indicate OBS chooses not to use dmabuf and falls back to SHM, even though dma is advertised. Any reason as to why?

**Comment by kkartaltepe** [comment]
In my limited understanding of pipewire the client is responsible for advertising first, and the server is responsible for picking. We advertise modifiers in https://github.com/obsproject/obs-studio/blob/master/plugins/linux-pipewire/pipewire.c#L1263, and if the server finds a usable format and responds back during negotiations we use it in https://github.com/obsproject/obs-studio/blob/master/plugins/linux-pipewire/pipewire.c#L1041

If not we use shm. Since this didnt renegotiate I assume the server didnt send any modifiers, maybe you filtered all of the formats that OBS supports.
