### ISSUE TITLE
Terminal error - add-apt-repository - command not found

### ISSUE THREAD

**Issue by nicitaacom** [obsproject/obs-studio#9660]
### Operating System Info

Other

### Other OS

kali linux

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

?

### Expected Behavior

No error

### Current Behavior

I'm here - https://obsproject.com/kb/linux-installation

entered this command
```bash
https://obsproject.com/kb/linux-installation
```

And got this error
sudo: add-apt-repository: command not found

### Steps to Reproduce

1. go here - https://obsproject.com/kb/linux-installation
2.ctrl+c ctrl+shift+v in terminal - sudo add-apt-repository ppa:obsproject/obs-studio
3.Got this - sudo: add-apt-repository: command not found

**Comment by tytan652** [comment]
Kali is Debian-based, not Ubuntu-based.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.  

Thank you!
