### ISSUE TITLE
Upcoming changes to publishing to Flathub

### ISSUE THREAD

**Issue by barthalion** [obsproject/obs-studio#9722]
Flathub will be enabling server-side build validation on a tentative date of November 6th. This will require some changes to your pipeline for publishing new builds:

- the validation part can be replicated by using `docker pull ghcr.io/flathub/flatpak-builder-lint:latest` on the ostree repo produced by flatpak/flatpak-builder. Example usage: `flatpak-builder-lint --exceptions repo /path/to/ostree/repo`
- `flat-manager-client create` needs to include `--build-log-url $URL`, where $URL points to a pipeline building the flatpak. This is also exposed by the latest release of the flatpak/flatpak-github-actions/flat-manager GitHub Action.

**Comment by tytan652** [comment]
It is kind of you to signal to us (OBS Studio) such changes, but issues in this repo are meant for bug reports.

**Comment by PatTheMav** [comment]
It is definitely not a bug report, if you had the courtesy to fill out the issue template instead, it has the chance to be one.

Please edit your OP using the template, otherwise this issue will be closed.

**Comment by Fenrirthviti** [comment]
For future reference, it's consider bad etiquette (and in some cases, can be read as disrespectful) to completely delete an issue template when submitting an issue to a repo. It sends a message, intentional or not, that following our processes aren't worth your time. I'm reasonably sure we're already aware of this, but keep this in mind for any future interactions, both with our project and others.
