### ISSUE TITLE
How to fix audio n Dazzle DVC100

### ISSUE THREAD

**Issue by markosjal** [obsproject/obs-studio#9732]
### Operating System Info

Other

### Other OS

Linux Mint 20.2 based on Ubuntu 20.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

25.0.3+dfsg1-2 64bit

### OBS Studio Log URL

https://obsproject.com/logs/BcEIZHygagQxlXEf

### Expected Behavior

I expect that the Dazzle DVC100 sound device would be initialized on launch of OBS. Apparently this is not happening. It will get initialized in the necessary manner when I click on "Dazzle DVC Video" properties cog in the sources box. Note this is NOT a typo nor error . Clicking on video properties suddenly causes the Dazzle DVC 100 Audio to work, at least under my configuration. This is a 100% reproducible error. and clicking on this cog after a reboot and re-launch of OBS has caused the audio to work again 100% of the time counting many reboots. Whatever gets initialized or reset  when going into these video properties needs to get initialized or reset at start-up

### Current Behavior

By default there is no audio from Dazzle DVC 100 Rev 1.1 to OBS. I spent a week looking for solutions online and many solutions for older software versions , or that simply did not work. In some cases youtube videos claiming to fix it but never show it working! (clickbait)

### Steps to Reproduce

1. Reboot Machine
2.Launch OBS and confirm no audio from Dazzle
3.Click the cog wheel and open Dazzle DVC properties in sources menu and audio starts up

This assumes your configuration is similar to mine. I can provide settings screenshots. Audio is sure to fail again at next reboot. I have ALL audio devices disabled in File > Settings > Audio  and only the custom audio device for the Dazzle DVC100 (ALSA) in sources.

...

### Anything else we should know?

if needed I have detailed screenshots to reproduce this exactly. I tried to post this fix to forums and moderator deleted it with no explanation given

So I made a new post here:
https://obsproject.com/forum/threads/making-an-improvement-for-some-hardware.170400/

I know it is old hardware (Dazzle DVC100) but the video quality is excellent. There are a lot of people still digitizing old analog material. I will be installing a Linux Mint (latest LTS) to my older Mac Mini and test this again with latest version of Linux Mint, once my new SSD arrives. I will then know if the same fix applies to newer versions of Kernel driver, Linux Mint and OBS.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by markosjal** [comment]
As I stated! I wrote a VERY lengthy post on the forums that was DELETED by a moderator. 

I have made a POST nobody cares it seems. Passing the buck! Besides. it is a BUG why is the audio not initialized at launch of the program the same way it is when I click on Dazzle DVC Video Properties?

**Comment by Fenrirthviti** [comment]
Your post was not deleted, but rather caught by spam filters and was pending approval. I've since approved it.

Assuming this is the same Dazzle DVC100 I'm remembering, that device is absolutely ancient, and extremely buggy/unreliable. It's unlikely we're doing anything wrong, and clicking on the "Video Properties" button opens the driver config outside OBS, which we don't directly manage. Those devices have a long history of being, frankly, awful. We haven't had any reports of this happening with other capture devices, and is not likely something we would even be able to fix in the first place.

If you know what code needs to change in OBS to allow this to work, however, we're happy to review that as a PR.

**Comment by Fenrirthviti** [comment]
There is also a chance this is related to something with ALSA, which going through our support channels would shake out, which is why the recommendation to go through support first for someone to take a look is recommended.

**Comment by markosjal** [comment]
Let me be clear ....,.

My post originally appeared
Some hours later I went to username > your content and it showed in strikethough
Then after some more hours it was completely gone from username > Your content . That is when I made the post asking why it was deleted.

Regardless of you calling the Dazzle DVC 100 "ancient" which clearly is an exaggeration It is used by many still and many need a solution other than the bundled software . It is one of the few cards that actually handles Interlaced SD content properly, and there is still plenty of SD content in the world to be digitized.

The chance that this relates to ALSA may or may not be correct, but why would clicking on Sources > Dazzle DVC Video  > Cog wheel then initialize the card in a way that seemingly should have been done when OBS was started? I trhink we both know that there is not going to be some other user that has the magic solution to the problem. I am handing the solution to you here and you refuse it? You have no idea how many devices may be affected by the same issue.  There is no harm in initializing the card at start up.

I have in no way asked for any support. I am asking for a modification to the code so that this initialization that happens when one clicks on Sources > Dazzle DVC Video > Cog Wheel also occurs automatically when the program is started. 

I have taken a long time to figure this out and I will not give up so quickly . The problem is I want it to be more natural and that can only be done with a modification to the code so that this device (and others) are initialized at start up.

**Comment by Fenrirthviti** [comment]
You are making wild assumptions that there isn't already some "initialization" that is happening.

I'm going to be blunt here, your understanding of the problem and the solution is very flawed with how things actually work in OBS. Going through the support channels so someone can take a look at the setup, and verify the issue, is what is required for this to progress because what you're asking us to "change" does not make any sense, and is not how OBS works. I am not being negative, I am asking you to follow our established processes so that *we can take a closer look and figure out what's actually going on.* 

Thank you for your understanding.

**Comment by markosjal** [comment]
then explain to me one simple thing....

What is it that is happening when that cog is clicked that suddenly and reliably causes the audio to work?

**Comment by Fenrirthviti** [comment]
Because the cog opens the device driver configuration, which is likely where the actual bug/issue is, not in OBS.
