### ISSUE TITLE
Screen sharing notification remains in macOS menu bar after quitting OBS 30.0.0 RC2

### ISSUE THREAD

**Issue by Iritscen** [obsproject/obs-studio#9796]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/iajBVDgolAIpEOiA

### Expected Behavior

I expected that the notification in the menu bar that shows the screen is being captured would go away when streaming/capturing stops and the app is quit.

### Current Behavior

After streaming or recording with OBS, the blue notification remains lodged in the menu bar until I log out of macOS.

### Steps to Reproduce

1. Simply open OBS and begin streaming anything from any video source – a window, etc.
2. Stop streaming.
3. Quit OBS.  The menu item will remain.

### Anything else we should know?

This also happened in the version of OBS which I was previously using, v29.1.3, so it's not a brand-new bug.  Visual of menu item attached below.

![Screenshot 2023-11-03 at 8 16 08 PM](https://github.com/obsproject/obs-studio/assets/1541542/0f0d609e-402f-43cd-a8f2-33d0497984a3)

**Comment by gxalpha** [comment]
This is very likely a macOS bug. Please file a feedback to Apple.

**Comment by Iritscen** [comment]
To be clear, other screen-capturing apps such as ScreenFlow do not leave the screen recording annunciator (if that's the correct term) visible in the menu bar after they're done capturing the screen.  I've also just noticed that simply opening OBS triggers the screen sharing annunciator.  I can quit OBS without ever having told the app to record or stream, and it remains in the menu bar.

**Comment by soheilpro** [comment]
I also have the same problem on macOS 14.2 (23C64).

**Comment by remyhunt** [comment]
Also having this issue on version 28.1.2 (64 bit), updated to 29.1.3 and the issue still persisted

M1 chip, Mac OS 14.1

<img width="349" alt="Screenshot 2024-01-11 at 4 40 21 PM" src="https://github.com/obsproject/obs-studio/assets/5217127/5d9b63de-935e-4ead-8a85-97e58598e8f9">

**Comment by gxalpha** [comment]
*Copy-pasting my reply from https://github.com/obsproject/obs-studio/issues/9850#issuecomment-1891098202:*

Contrary to what we believed before this is not fixed in macOS 14.2, but as stated earlier it is already worked around on the current OBS master branch (see https://github.com/obsproject/obs-studio/pull/9803), so if this highly important to you you're welcome to test a nightly build (and, if using that nightly build the issue still persists please open a new issue).

Though again the underlying bug is in macOS. OBS can't be sharing anything at this point because, you know, it's not running anymore.

**Comment by filipef101** [comment]
Anyone know if/where this is being tracked on apple side? MacOS 14.4.1 (23E224) and still get this. Also with other apps like chrome and safari when sharing screen during meetings

**Comment by VityaSchel** [comment]
Still appears to be present
