### ISSUE TITLE
[DXGI] OBS hooking seems to take a reference to IDXGISwapChain object which prevents application from recreating swapchain during runtime.

### ISSUE THREAD

**Issue by hsiversson** [obsproject/obs-studio#9863]
### Operating System Info

Windows 10

### Other OS

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

Most of them, we've tried with a lot of versions, all are facing the same issue.

### OBS Studio Log URL

no log, crash happens in external application being hooked into

### Expected Behavior

I expect OBS hooking to properly handle that the external application can destruct and create a new swapchain object in runtime.

### Current Behavior

Currently OBS seems to keep a reference to the IDXGISwapChain object internally.
This was tested in external application being hooked into.

The external application needs to be able to destruct existing IDXGISwapChain object and create a new one in runtime.
When OBS is hooked in, this is does not work because of the lingering reference kept by OBS internally.

To provide more detail:
In Windows 10 or later you are only allowed to have a _single_ IDXGISwapChain object referencing a particular window handle (HWND) using a DXGI_SWAP_EFFECT_FLIP_* setup. The proper way to reconstruct a swapchain with this setup is to first release the initial swapchain object, make sure that the D3D* backend have properly released the object, and then create the new one.
However, because of the lingering reference in OBS, the swapchain object never gets destructed, and thus prevents the application from ever creating a new swapchain.

### Steps to Reproduce

1. Launch an external application that initializes a IDXGISwapChain object.
2. Hook OBS to said application.
3. Have the application try to destruct and create a new IDXGISwapChain object in runtime.
4. Observe that the initial swapchain object never gets properly released, and thus creation of new swapchain objects results in E_ACCESSDENIED with the following message:

> DXGI ERROR: IDXGIFactory::CreateSwapChain: Only one flip model swap chain can be associate with an HWND, IWindow, or composition surface at a time. ClearState() and Flush() may need to be called on the D3D11 device context to trigger deferred destruction of old swapchains. [ MISCELLANEOUS ERROR #297: ]

See [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgifactory2-createswapchainforhwnd) for more info.

**Comment by jpark37** [comment]
I've looked at this in the past, and I wasn't able to figure out a good way to be notified when the application is done with a swap chain to reset the OBS D3D objects around the swap chain. Even hooking the Release method and Inspecting the reference count is of limited help because the ref count can be inflated for reasons that aren't documented. If you have a better approach in mind, I'm wide open to suggestions.
One of the saving graces is that the OBS game capture hook is not implicit for D3D applications (unlike Vulkan), so it doesn't break incompatible applications without consent. Users can use window/display capture instead. Microsoft themselves have said they don't want to go out of their way to make it easier for applications to hook and to use one of their approved capture methods.

**Comment by jpark37** [comment]
> What about hooking the create function (CreateSwapChainForHwnd)

Haven't completely thought it through, but I suspect this will break some use cases and do nothing for others.

> You can use ID3DDestructionNotifier::RegisterDestructionCallback

I might be missing something here, but OBS is probably going to prevent that from happening because it's holding references to the swap chain textures and that keeps the swap chain alive. And the number of refs that adds to the swap chain ref count isn't reliable either.

**Comment by jenatali** [comment]
Can you not hold references to the swapchain buffers, and just retrieve them on-demand from the swapchain?

**Comment by jpark37** [comment]
With 11on12, that's probably a lot of churn each frame. We don't hold for straight 11 capture although I forget if this is still a problem there. D3D12 capture had this issue for sure.

**Comment by jenatali** [comment]
Eh, I don't think it'd be that much churn. I imagine that's how Steam does it for their overlay.

**Comment by jamespark-unreal** [comment]
Ok, I'll try and measure tonight then. Thanks!

**Comment by jpark37** [comment]
Ok, I'll try and measure tonight. Thanks!

**Comment by jpark37** [comment]
Also, the fix is sitting here if OP wants to give it a try.
https://github.com/jpark37/obs-studio/tree/dxgi-leak
