### ISSUE TITLE
Fail to capture from v4l2 Elgato device

### ISSUE THREAD

**Issue by dov** [obsproject/obs-studio#9958]
### Operating System Info

Other

### Other OS

Linux fedora 38

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ycZsEJNqD8BqlyKS

### Expected Behavior

I have a scene that contain a video capture source connected to /dev/video1 which is connected to Elgato HD60x box.

### Current Behavior

The scene is black, i.e. no capturing is occuring. Further the following lines are written in the log:
```
info: v4l2-input: Start capture from /dev/video1
error: v4l2-input: Unable to set input 0
error: v4l2-input: Initialization failed, errno: Device or resource busy
```
If I run the command `fuser /dev/video1` I see get the process id that belongs to obs. I.e. no other process is accessing the device.

### Steps to Reproduce

1. Connect elgato 60x to the computer
2. Run obs
3. Add a video source pointing to the device of the elgato 60x
...

### Anything else we should know?

The capture works perfectly e.g. with guvcview with the following command:
```
guvcview -d /dev/video1
```
However the following command fails to run
```
gst-launch-1.0 v4l2src device="/dev/video1" \! jpegdec \! decodebin \! video/x-raw \! xvimagesink
```
which fails with the error "Can't typefind stream"
```
on the other hand if I connect the above command to my web cam on /dev/video3 it does work.

Perhaps this gives a clue.

**Comment by dov** [comment]
@Fenrirthviti How can it be a support request? I'm getting a black screen trying to access an existing video device which works perfectly in another application (gucview).

Note also the obs error message:
```
error: v4l2-input: Initialization failed, errno: Device or resource busy
```
I.e. obs believes the device to be busy, but using `fuser` shows that it is obs that is the owner of the device. This certainly looks like a bug to me.

I'll be happy to help debug this, but I need guidance. Is there a command line that corresponds to the capture that obs is doing?

**Comment by danir-de** [comment]
@Fenrirthviti @jp9000  This is certainly not a support request - it's a bug with the V4L2 camera/video capture device implementation that makes it very hard to work with certain Elgato cameras (such as the [Game Capture HD60 X](https://www.elgato.com/de/de/p/game-capture-hd60-x), or _my_ [Facecam Pro](https://www.elgato.com/de/de/p/facecam-pro)).

Initially loading an existing camera source with it's previously used settings works alright and you can use the video source in OBS. 

The problem occurs when freshly adding an Elgato camera or when changing **any** setting in the Source properties.

![image](https://github.com/obsproject/obs-studio/assets/4672840/bf793bc9-d979-4e7f-b47f-bed058b2b8cc)
> Screenshot of the camera source properties.

Changing any setting here, freezes the camera input and doesn't recover it, even when "Autoreset on Timeout" is checked.

The error output is identical to the one @dov described:
```log
info: v4l2-input: /dev/video0: Stopped capture after 758 frames
info: v4l2-input: Start capture from /dev/video0
error: v4l2-input: Unable to set input 0
error: v4l2-input: Initialization failed, errno: Device or resource busy
```

#### One important thing here:
The (changed) settings itself aren't the problem and not invalid, it's OBS failing to acquire a picture after changing anything in its settings. **That's why this not a support - but a bug request!**
To prove that any changes are correct, you simply have to restart OBS. The camera then gets initialized and perfectly works with the previously selected settings, without throwing any errors.
You can also test changing all setting-options with other applications giving you camera controls, such as Camerctrls, which works flawlessly with on-the-fly changes without disconnects, timeouts or restarts.
