### ISSUE TITLE
"Failed to create xdg-screensaver: 2" error in log

### ISSUE THREAD

**Issue by superclarkk** [obsproject/obs-studio#9968]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

30.0.0 64-bit

### OBS Studio Log URL

https://obsproject.com/logs/2QYKBCszHhmN1lAF

### OBS Studio Crash Log URL

https://obsproject.com/logs/8z3SRmi03uSgFK7N

### Expected Behavior

"Failed to create xdg-screensaver: 2", and any other errors, should not occur.

### Current Behavior

Errors in the log

### Steps to Reproduce

OBS mostly works fine. However, intermittently, and without warning, I'm logged out of the user session, which closes OBS and loses the file it was recording. I haven't got to the bottom of it, and it may well not be due to OBS. However, OBS has always been running when this has happened. Thus, if it's possible to resolve any errors in OBS, it would be useful, to help eliminate it from the root cause.

### Anything else we should know?

It's running on a standard system, not in a docker container, or anything like that.

**Comment by gxalpha** [comment]
> which closes OBS and loses the file it was recording

are you sure about the "loses the file it was recording" part? Since you're recording to mkv, the file should work until the point where OBS closes.


Besides this, it doesn't look like there are any OBS issues here. OBS should not be able to log you out. It might be that you're running out of system memory or something else.

**Comment by Dhizaes** [comment]
I have this same problem in OBS 30.0.2, Fedora 39. It spams the system log and when I check log size it reaches 1GB. It is horrible thing to see. I suspected from NVIDIA GPU because I was using NVENC for streams. Changed it to x264 but same thing happens. I'm not sure what causes it.

**Comment by RytoEX** [comment]
As far as I know, the warning is what it says: the screensaver could not be created. This is, in fact, intentional:
https://github.com/obsproject/obs-studio/blob/30.0.2/libobs/util/platform-nix.c#L787

This is part of a series of functions to prevent the system from sleeping while OBS is open.

It has nothing to do with any crashes you may be experiencing.

**Comment by akvadrako** [comment]
Even if this warning doesn't cause a crash, it would be nice to not fill the log with it.

BTW, this was reported years ago in #5479.
