### ISSUE TITLE
A770 QSV AV1 encoder doesn't work when RTX4090 installed at the same PC

### ISSUE THREAD

**Issue by DP-Huanhuan** [obsproject/obs-studio#9982]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/VxNFhER0pOkkr7d8

### Expected Behavior

The setup:
GPU 0: UHD 770 in 13900K
GPU 1: RTX 4090
GPU 2: Intel A770

Expected Behavior: When QSV encoders selected, tasks runs on GPU 2.  Access to Intel Hyper Encoding which allows to share task between iGPU and dGPU and the option to choose which GPU to use would be even better.

### Current Behavior

QSV H264&H265 runs on GPU 0. Zero activity on GPU 2. 
QSV AV1 fails because it is only supported by GPU 2. If all QSV encoder runs on GPU 0, it will certainly fail when it comes to AV1.

### Steps to Reproduce

1. Select QSV AV1 encoder in recording tab
2. Hit record button.
3. Error window pops up. It says "Starting the output failed"

### Anything else we should know?

Driver/OS/OBS everything is the latest.
There are two GPU from different vendors installed, which might be the cause.
Tried to disable the hardware accelerated GPU scheduling. Nothing changed.

**Comment by jadenquinn** [comment]
I can't even get the QSV AV1 option to show up at all. Consider yourself lucky.

**Comment by tphakala** [comment]
According to logs OBS selects RTX4090 as GPU to use

    Adapter 0: NVIDIA GeForce RTX 4090
    ....
    >>> app not on intel GPU, fall back to old qsv encoder

Have you followed these steps to select ARC 770 as GPU to use with OBS?
https://obsproject.com/kb/gpu-selection-guide

What comes to hyper encoding, is does not work with OBS. I have 12th gen CPU id HD730 iGPU and ARC 750 and AV1 runs on ARC adapter but it does not share load with iGPU.

**Comment by RytoEX** [comment]
I can confirm this behavior occurs even on an Intel+Intel (iGPU+dGPU; Iris Xe + Arc A770M) system if OBS is running on the iGPU. The key factor here is that the GPU OBS is running on does not have QSV AV1 capabilities, and the non-texture sharing fallback is failing. This has been reported to Intel.

**Comment by Selexo** [comment]
I have a MultiGPU setup in a AMD based Single PC setup 6700xt and a Arc 380 for the hardware encoder and OBS doesn't know how to deal with MultiGPU systems on a SinglePC MultiGPU Windows PC. 

One thing that got me concerned and what ultimately brought this bug to my attention was the fact that when I was trying to use "FULL SCREEN PROJECTOR (Preview)" kept selecting the wrong display even when I clearly selected my other display connected to the other GPU. Then reviewing the log I found it wasn't even using the GPU encoder to its full potential, the the intel QSV encoder does use the GPU but obviously a lesser quality because it's not as up to date. 

21:34:20.708: 	Adapter 0: AMD Radeon RX 6700 XT
21:34:20.708: 	  Dedicated VRAM: 12836904960 (12.0 GiB)
.
.
21:34:20.708: 	Adapter 1: Intel(R) Arc(TM) A380 Graphics
21:34:20.708: 	  Dedicated VRAM: 6350176256 (5.9 GiB)
.
.
21:38:22.276: >>> app not on intel GPU, fall back to old qsv encoder

So I found a workaround as today, you basically have to tell windows what GPU you want OBS to open up on. 
In the windows search start typing "Graphics" till you see "Graphics Setting" or if you turned off you search, look for Graphics Setting under you "Display Settings" Scroll down till you find  -> "Graphics" under "Related Settings"

Because OBS doesn't have full screen exclusive mode you will need to add OBS manually so under "Add and app" ass "Desktop App" by selecting browse, and find your obs64.exe.

On this "Graphics Preference" Window you have to tell it Last option "Specific GPU" and from the drop down select the GPU you want to use. "Intel ARC A380" in my case. 

Close the app if its already running, and relaunch it. 

This solved a few OBS bugs or how it interacts with windows, 

First thing you will notice it the app will actually OPEN on the other display, A know bug reported on another thread where the app doesn't remember what display to open up on even if your drag it there. Mainly Multi GPU version of this bug, as it still doesn't fix single GPU issue. 

Second thing this fixed is that I can "Fullscreen Projector Preview" on the any correct Display. if I have OBS open on the intel arc GPU it can still project to my Main display or the second display. Selecting the different displays actually works.

In the LOG you will now see....

18:52:50.931: >>> new qsv encoder

So win win. Hope this helps a few of you fix a few issues if you can manually select your GPU in windows.

**Comment by Selexo** [comment]
This doesn't actually fix anything, but some things I noticed.. 

I have a MultiGPU setup in a AMD based Single PC setup 6700xt and a Arc 380 for the hardware encoder and OBS doesn't know how to deal with MultiGPU systems on a SinglePC MultiGPU Windows PC. 

One thing that got me concerned and what ultimately brought this bug to my attention was the fact that when I was trying to use "FULL SCREEN PROJECTOR (Preview)" kept selecting the wrong display even when I clearly selected my other display connected to the other GPU. Then reviewing the log I found it wasn't even using the GPU encoder to its full potential, the the intel QSV encoder does use the GPU but obviously a lesser quality because it's not as up to date. 

21:34:20.708: 	Adapter 0: AMD Radeon RX 6700 XT
21:34:20.708: 	  Dedicated VRAM: 12836904960 (12.0 GiB)
.
.
21:34:20.708: 	Adapter 1: Intel(R) Arc(TM) A380 Graphics
21:34:20.708: 	  Dedicated VRAM: 6350176256 (5.9 GiB)
.
.
21:38:22.276: >>> app not on intel GPU, fall back to old qsv encoder

So I found a workaround as today, you basically have to tell windows what GPU you want OBS to open up on. 
In the windows search start typing "Graphics" till you see "Graphics Setting" or if you turned off you search, look for Graphics Setting under you "Display Settings" Scroll down till you find  -> "Graphics" under "Related Settings"

Because OBS doesn't have full screen exclusive mode you will need to add OBS manually so under "Add and app" ass "Desktop App" by selecting browse, and find your obs64.exe.

On this "Graphics Preference" Window you have to tell it Last option "Specific GPU" and from the drop down select the GPU you want to use. "Intel ARC A380" in my case. 

Close the app if its already running, and relaunch it. 

This solved a few OBS bugs or how it interacts with windows, but doesn't actu
ally fix anything

First thing you will notice it the app will actually OPEN on the other display, A know bug reported on another thread where the app doesn't remember what display to open up on even if your drag it there. Mainly Multi GPU version of this bug, as it still doesn't fix single GPU issue. 

Second thing this fixed is that I can "Fullscreen Projector Preview" on the any correct Display. if I have OBS open on the intel arc GPU it can still project to my Main display or the second display. Selecting the different displays actually works.

In the LOG you will now see....

18:52:50.931: >>> new qsv encoder

New problem is I can't capture outside the GPU. lol.. as reported by RytuEX

20:09:53.445: gs_texture_open_shared (D3D11): Failed to open shared 2D texture (80070057)
20:09:53.445: [game-capture: 'Game Capture'] init_shtex_capture: failed to open shared handle

**Comment by RytoEX** [comment]
This should be resolved as of OBS Studio 30.2.0 Beta 1 with #10170 and #10740.
